# Makefile for RISC-V specification for CHERI extensions

# Directories and files
BUILD_DIR := build
# Output files
PDF_RESULT    := $(BUILD_DIR)/riscv-cheri.pdf
HTML_RESULT   := $(BUILD_DIR)/riscv-cheri.html

# Convenience targets
pdf: $(PDF_RESULT)
$(PDF_RESULT):
	$(MAKE) -f Makefile $(PDF_RESULT)
html: $(HTML_RESULT)
$(HTML_RESULT):
	$(MAKE) -f Makefile $(HTML_RESULT)
all: pdf html

clean:
	$(MAKE) -f Makefile clean

.PHONY: all generate clean
