= RISC-V Specification for CHERI Extensions

:gh_org: riscv
:gh_repo: riscv-cheri

This repository contains the CHERI extension specification, adding hardware capabilities to the RISC-V ISA to enable fine-grained memory protection and scalable compartmentalization.

The latest draft HTML version can be accessed at https://{gh_org}.github.io/{gh_repo} and the latest PDF snapshot can be downloaded from https://github.com/{gh_org}/{gh_repo}/releases.

* *Draft HTML snapshots of the latest commit* integrated in to the main ISA documents can be viewed at the following locations:
** https://{gh_org}.github.io/{gh_repo}/snapshot/unprivileged/
** https://{gh_org}.github.io/{gh_repo}/snapshot/privileged/

== License

This work is licensed under a Creative Commons Attribution 4.0 International License (CC-BY-4.0). For details, see the link:LICENSE[LICENSE] file.

== Contributors

The list of contributors to this specification is maintained in the link:src/contributors.adoc[contributors] file.

For guidelines on how to contribute, refer to the link:CONTRIBUTING.md[CONTRIBUTING] file.

== Building the Document

=== Prerequisites

To build the document, you'll need the following tools installed on your system:

* Make
* Docker

If you want to build outside of Docker, you'll need some more tools:
* Python3
* asciiDoctor-pdf, asciidoctor-bibtex, asciidoctor-diagram, asciidoctor-mathematical and asciidoctor-sail
* bytefield-svg
* wavedrom-cli

=== Cloning the Repository

```shell
git clone --recurse-submodules https://github.com/riscv/riscv-cheri.git
```

=== Building the Documentation

To start the build process, run:

```shell
# build just the standalone spec
cd ./riscv-cheri && make build/riscv-cheri.pdf
# Build the privileged/unprivileged/cheri documents
cd ./riscv-cheri && make build-pdf -j4
```

The link:Makefile[] script will check the availability of Docker on your system:

* If Docker is available, the documentation will be built inside a Docker container using the image riscvintl/riscv-docs-base-container-image:latest. This ensures a consistent build environment across different systems.
* If Docker is not available, the documentation will be built directly on your system using the installed tools.

The documentation is generated from the AsciiDoctor source files in your project. The primary source file is specified by the `HEADER_SOURCE` variable in the Makefile.

The build process utilizes several options, including theming and font settings, and generates a PDF document as output.

=== Cleaning up

To clean up the generated files, run:

```shell
make clean
```

This will remove the generated PDF file.

== Enabling pre-commit checks locally
The repository has some basic commit checks set up with https://pre-commit.com/[pre-commit] that will be enforced by the GitHub CI.
To ensure these checks are also run in the local repository while making changes the following command can be run:
[source,shell]
----
pip3 install pre-commit && pre-commit install
----

When enabling additional checks https://pre-commit.com/#plugins[by editing .pre-commit-config.yaml], it is recommended to run to newly added check on all files in the repository. This can be done with the following command:
[source,shell]
----
pre-commit run --all-files
----
