[appendix]
[#app_cheri_instructions]
== RISC-V Instructions with different behavior for {cheri_base_ext_name}

ifdef::cheri_standalone_spec[]
WARNING: This chapter needs to be refactored. It will appear as an appendix in the unpriv specification.
endif::[]

These instruction pages are for the new CHERI instructions, and some existing RISC-V
instructions where the effect of CHERI needs specific details.

For existing RISC-V instructions, note that:

. In {cheri_int_mode_name}, every byte of each memory access is bounds checked against <<ddc>>

NOTE: Not all RISC-V extensions have been checked against CHERI. Compatible
extensions will eventually be listed in a CHERI profile.

// NOTE: these are technically unnecessary as they just follow the stated rules
<<<
=== RV32I/E and RV64I/E Base Integer Instruction Sets

There are a number of load and store instructions that are already in RISC-V that have modified behavior when CHERI is included (see <<section_existing_riscv_insns>>).

include::insns/load_32bit.adoc[]

include::insns/store_32bit.adoc[]

ifdef::cheri_standalone_spec[]
// FIXME: needs to be in privileged chapter
<<<
=== RV32I/E and RV64I/E Privileged Instruction Sets

There are a number of instructions that are already in RISC-V that have modified behavior when CHERI is included.

include::insns/mret_sret.adoc[]

include::insns/dret.adoc[]

endif::[]

<<<
=== "A" Standard Extension for Atomic Instructions

Atomic instructions and their interactions with CHERI.
// NOTE: these are technically unnecessary since they just follow the default rules

include::insns/amo_32bit.adoc[]

include::insns/load_res_32bit.adoc[]

include::insns/store_cond_32bit.adoc[]

ifdef::cheri_standalone_spec[]
// Already in A chapter for non-standalone

include::insns/load_res_cap_32bit.adoc[]

include::insns/amoswap_32bit_cap.adoc[]

include::insns/store_cond_cap_32bit.adoc[]
endif::[]

<<<
=== "Zfh", "Zfhmin", "F" and "D" Standard Extension for Floating-Point
// NOTE: these are technically  unnecessary as they just follow the stated rules
Floating point instructions and how CHERI affects them.

include::insns/load_32bit_fp.adoc[]

include::insns/store_32bit_fp.adoc[]

<<<
=== "C" Standard Extension for Compressed Instructions

One group of 16-bit encodings are remapped to different instructions dependent
upon the CHERI execution mode, MXLEN and which extensions are supported.

The following tables summarize the mappings.

NOTE: Zcf and Zclsd are incompatible

NOTE: Zcd and <<Zcmp,Zcmp>>/<<Zcmt,Zcmt>> are incompatible

//this has all been integrated into the relevant chapter
ifdef::cheri_standalone_spec[]
==== RV32 / {cheri_base32_ext_name}

include::rv32c_mapping_table.adoc[]

<<<
==== RV64 / {cheri_base64_ext_name}

include::rv64c_mapping_table.adoc[]

endif::[]

// No longer different now that we no longer fault on branch
// include::insns/condbr_16bit.adoc[]

include::insns/cmv_16bit.adoc[]

include::insns/addi16sp_16bit.adoc[]

include::insns/addi4spn_16bit.adoc[]

include::insns/jalr_16bit.adoc[]

include::insns/jr_16bit.adoc[]

include::insns/jal_16bit.adoc[]

include::insns/j_16bit.adoc[]

include::insns/load_16bit.adoc[]

include::insns/load_16bit_sprel.adoc[]

include::insns/load_16bit_fp_sp.adoc[]

include::insns/load_16bit_fp_dp.adoc[]

include::insns/load_16bit_cap_sprel.adoc[]

include::insns/store_16bit.adoc[]

include::insns/store_16bit_sprel.adoc[]

include::insns/store_16bit_fp_sp.adoc[]

include::insns/store_16bit_fp_dp.adoc[]

include::insns/store_16bit_cap_sprel.adoc[]

// NOTE: integrated into the CBO chapter
<<<
=== "Zicbom", "Zicbop", "Zicboz" Standard Extensions for Base Cache Management Operations

Cache-related instructions and how CHERI affects them.

include::insns/cbo.clean.adoc[]

include::insns/cbo.flush.adoc[]

include::insns/cbo.inval.adoc[]

include::insns/cbo.zero.adoc[]

include::insns/prefetch.i.adoc[]

include::insns/prefetch.r.adoc[]

include::insns/prefetch.w.adoc[]

//this has all been integrated into the relevant chapter
ifdef::cheri_standalone_spec[]
<<<
=== "Zba" Extension for Bit Manipulation Instructions

Bit manipulation instruction reference.

include::insns/adduw_32bit.adoc[]

include::insns/sh123add_32bit.adoc[]

include::insns/sh123adduw_32bit.adoc[]
endif::[]

<<<
[#sh4add_extension]
=== "{sh4add_ext_name}" Extension

include::insns/sh4add_32bit.adoc[]

include::insns/sh4adduw_32bit.adoc[]

// NOTE: these all follow the standard rules
<<<
[#Zcb,reftext="Zcb"]
=== "Zcb" Standard Extension For Code-Size Reduction

Code-size reduction instructions and how they interact with CHERI.

include::insns/load_16bit_Zcb.adoc[]

include::insns/store_16bit_Zcb.adoc[]

<<<
[#Zcmp_CHERI,reftext="Zcmp ({cheri_base32_ext_name})"]
=== "Zcmp" Standard Extension For Code-Size Reduction

The push (<<CM_PUSH_CHERI>>) and pop (<<CM_POP_CHERI>>, <<CM_POPRET_CHERI>>, <<CM_POPRETZ_CHERI>>) instructions are redefined in {cheri_cap_mode_name} to save/restore capability data.

The double move instructions (<<CM_MVSA01_CHERI>>, <<CM_MVA01S_CHERI>>) are redefined in {cheri_cap_mode_name} to move capability data between registers. The saved register mapping is as shown in <<saved_register_mapping>>.

.saved register mapping for Zcmp
[#saved_register_mapping]
[width="100%",options=header, align="center"]
|====================================
| saved register specifier | xreg | integer ABI | CHERI ABI
| 0                       | x8  | s0 | {abi_creg}s0
| 1                       | x9  | s1 | {abi_creg}s1
| 2                       | x18 | s2 | {abi_creg}s2
| 3                       | x19 | s3 | {abi_creg}s3
| 4                       | x20 | s4 | {abi_creg}s4
| 5                       | x21 | s5 | {abi_creg}s5
| 6                       | x22 | s6 | {abi_creg}s6
| 7                       | x23 | s7 | {abi_creg}s7
|====================================

include::insns/zcmp_cmpush.adoc[]

include::insns/zcmp_cmpop.adoc[]

include::insns/zcmp_cmpopret.adoc[]

include::insns/zcmp_cmpopretz.adoc[]

include::insns/zcmp_cmvsa01.adoc[]

include::insns/zcmp_cmva01s.adoc[]


<<<
[#Zcmt_CHERI,reftext="Zcmt ({cheri_base32_ext_name})"]
=== "Zcmt" Standard Extension For Code-Size Reduction

The table jump instructions (<<CM_JT_CHERI>>, <<CM_JALT_CHERI>>) are _not_ redefined in {cheri_cap_mode_name} to have capabilities in the jump table. This is to prevent the code-size growth caused by doubling the size of the jump table.

In the future, new jump table modes or new encodings can be added to have capabilities in the jump table.

The jump vector table CSR <<jvt_y>> is a full capability so that it can only be configured to point to accessible memory.
All accesses to the jump table are checked against <<jvt_y>> in {cheri_cap_mode_name}, and against <<pcc>> bounds in {cheri_int_mode_name}.
This allows the jump table to be accessed when the <<pcc>> bounds are set narrowly to the local function only in {cheri_cap_mode_name}.

NOTE: In {cheri_cap_mode_name} the instruction fetch bounds check is authorized by two different capabilities - <<jvt_y>> for the table access and <<pcc>> for the <<CM_JALT_CHERI>>/<<CM_JT_CHERI>> instruction, and target instruction.

NOTE: In {cheri_cap_mode_name} the implementation doesn't need to expand and bounds check against <<jvt_y>> on every access, it is sufficient to decode the valid accessible range of entries after every write to <<jvt_y>>, and then check that the accessed entry is in that range.

[#jvt_y,reftext="jvt ({cheri_base_ext_name})"]
==== Jump Vector Table CSR (jvt)

The Zcmt <<jvt>> CSR is extended to be a full capability.

.Jump Vector Table Capability register
include::img/jvtcreg.edn[]

All instruction fetches from the jump vector table are checked against <<jvt_y>> in {cheri_cap_mode_name}.
In {cheri_int_mode_name} the address field gives the base address of the table, and the access is checked against <<pcc>> bounds.

See <<CM_JALT_CHERI>>, <<CM_JT_CHERI>>.

If the access to the jump table succeeds, then the instructions execute as follows:

** <<CM_JT_CHERI>>   executes as <<JAL_CHERI,J>>   or <<AUIPC_CHERI,AUIPC>>+<<JALR_CHERI,JR>>
** <<CM_JALT_CHERI>> executes as <<JAL_CHERI,JAL>> or <<AUIPC_CHERI,AUIPC>>+<<JALR_CHERI,JALR>>

As a result the capability metadata is retained in <<pcc>> during execution.

include::insns/zcmt_cmjalt.adoc[]

include::insns/zcmt_cmjt.adoc[]

<<<

=== "H" Extension for Hypervisor Support

Hypervisor load and store instructions and the {cheri_base_ext_name} extensions.

While HLVX.* only requires execute permission in the PTE, the authorizing CHERI capability must grant <<r_perm>>.

include::insns/hypv-virt-load-cap.adoc[]
include::insns/hypv-virt-store-cap.adoc[]
