[appendix]
[#app_cheri_instructions]
== RISC-V Instructions with different behavior for {cheri_base_ext_name}

ifdef::cheri_standalone_spec[]
WARNING: This chapter needs to be refactored. It will appear as an appendix in the unpriv specification.
endif::[]

These instruction pages are for the new CHERI instructions, and some existing RISC-V
instructions where the effect of CHERI needs specific details.

For existing RISC-V instructions, note that:

. In {cheri_int_mode_name}, every byte of each memory access is bounds
checked against <<ddc>>
. In {cheri_int_mode_name}, a minimum length instruction at the target of all indirect
jumps is bounds checked against <<pcc>>
. In {cheri_cap_mode_name} a minimum length instruction at the target of all indirect
jumps is bounds checked against `cs1` (e.g. <<JALR_CHERI>>)
. A minimum length instruction at the taken target of all direct
jumps and conditional branches is bounds checked against <<pcc>> regardless of
CHERI execution mode

NOTE: Not all RISC-V extensions have been checked against CHERI. Compatible
extensions will eventually be listed in a CHERI profile.

<<<
=== RV32I/E and RV64I/E Privileged Instruction Sets

There are a number of instructions that are already in RISC-V that have modified behavior when CHERI is included.

include::insns/mret_sret.adoc[]

include::insns/dret.adoc[]

<<<
=== "Zicsr", Control and Status Register (CSR) Instructions

{cheri_base_ext_name} requires that RISC-V CSRs intended to hold addresses, are now able to hold capabilities.
Therefore, such registers are
extended to CLEN+1 bits in {cheri_base_ext_name} and a `c` suffix is added (e.g. <<mtvec>> is extended to <<mtvecc>>).

Reading or writing any part of a capability CSR may cause
side effects. For example, the CSR's tag bit may be cleared if a new address
is outside the <<section_cap_representable_check>> of a CSR capability being written.

This section describes how the CSR instructions operate on these CSRs in
{cheri_base_ext_name}.

The capability CSRs are summarized in xref:clen_csr_summary[xrefstyle=short].

[#zicsr-section-purecap]
==== CSR Instructions

ifdef::cheri_v9_annotations[]
NOTE: *CHERI v9 Note:* CSpecialRW is removed. Its role is assumed by
<<CSRRW>>.
endif::[]

All CSR instructions atomically read-modify-write a single CSR. If the CSR
accessed is of capability size then the
capability's tag, metadata and address are all accessed atomically.

When the <<CSRRW>> instruction is accessing a capability width CSR, then the source
and destination operands are *c* registers and it atomically swaps the values in the
whole CSR with the CLEN width register operand.

There are special rules for updating specific capability CSRs as shown in <<extended_CSR_writing>>.

When <<CSRRS>> and <<CSRRC>> instructions are accessing a capability width CSR,
such as <<mtvecc>>, then the destination operand is a *c* register and the
source operand is an *x* register. Therefore, the instructions atomically read
CLEN bits from the CSR, calculate the final address using standard RISC-V
behavior (set bits, clear bits, etc.), and that final address is written to the
CSR capability's address field. The update typically uses the semantics of a
<<SCADDR>> instruction which clears the validity tag if the capability is sealed, or
if the updated address is not representable. <<extended_CSR_writing>> shows the
exact action taken for each capability width CSR.

The <<CSRRWI>>, <<CSRRSI>> and <<CSRRCI>> variants are similar to <<CSRRW>>,
<<CSRRS>>, and <<CSRRC>> respectively, when accessing a capability width CSR
except that they update the capability's address only using an XLEN-bit value
obtained by zero-extending a 5-bit unsigned immediate field.

All CSR instructions cause CHERI exceptions if the <<pcc>> does not grant
<<asr_perm>> and the CSR accessed is privileged.

include::insns/csrrw_32bit.adoc[]

include::insns/csrr_32bit.adoc[]

<<<
=== "A" Standard Extension for Atomic Instructions

Atomic instructions and their interactions with CHERI.

include::insns/amo_32bit.adoc[]

include::insns/amoswap_32bit_cap.adoc[]

include::insns/load_res_32bit.adoc[]

include::insns/load_res_cap_32bit.adoc[]

include::insns/store_cond_32bit.adoc[]

include::insns/store_cond_cap_32bit.adoc[]

<<<
=== "Zfh", "Zfhmin", "F" and "D" Standard Extension for Floating-Point

Floating point instructions and how CHERI affects them.

include::insns/load_32bit_fp.adoc[]

include::insns/store_32bit_fp.adoc[]

<<<
=== "C" Standard Extension for Compressed Instructions

One group of 16-bit encodings are remapped to different instructions dependent
upon the CHERI execution mode, MXLEN and which extensions are supported.

NOTE: Zcf and Zclsd are incompatible

NOTE: Zcd and <<Zcmp>>/<<Zcmt>> incompatible


==== RV32

.16-bit instruction remapping in {cheri_int_mode_name}
[#insn_remapping_16bit_rv32_a]
[width="100%",options=header]
|==============================================================================
2+|Encoding    5+| Supported Extensions
|[15:13]|[1:0]   | Zca    | Zcf     | Zcd | Zcmp/ Zcmt | Zclsd
|111    |00      | N/A    | <<C.FSW>>   | N/A | N/A        | <<C.SD>>
|011    |00      | N/A    | <<C.FLW>>   | N/A | N/A        | <<C.LD>>
|111    |10      | N/A    | <<C.FSWSP>> | N/A | N/A        | <<C.SDSP>>
|011    |10      | N/A    | <<C.FLWSP>> | N/A | N/A        | <<C.LDSP>>

|101    |00      | N/A    | N/A     | <<C.FSD>>    | reserved^1^       | N/A
|001    |00      | N/A    | N/A     | <<C.FLD>>    | reserved^1^       | N/A
|101    |10      | N/A    | N/A     | <<C.FSDSP>>  | <<Zcmp>>/<<Zcmt>> | N/A
|001    |10      | N/A    | N/A     | <<C.FLDSP>>  | reserved^1^       | N/A
|==============================================================================

^1^ reserved for future standard Zcm extensions

.16-bit instruction remapping in {cheri_cap_mode_name}
[#insn_remapping_16bit_rv32_b]
[width="100%",options=header]
|==============================================================================
2+|Encoding    5+| Supported Extensions
|[15:13]|[1:0]   | Zca    | Zcf     | Zcd | Zcmp/ Zcmt | Zclsd
|111    |00    5+| <<C.SC>>
|011    |00    5+| <<C.LC>>
|111    |10    5+| <<C.SCSP>>
|011    |10    5+| <<C.LCSP>>

|101    |00      | N/A    | N/A     | C.FSD    | reserved^1^       | N/A
|001    |00      | N/A    | N/A     | C.FLD    | reserved^1^       | N/A
|101    |10      | N/A    | N/A     | C.FSDSP  | <<Zcmp>>/<<Zcmt>> | N/A
|001    |10      | N/A    | N/A     | C.FLDSP  | reserved^1^       | N/A
|==============================================================================

^1^ reserved for future standard Zcm extensions

<<<
==== RV64

.16-bit instruction remapping in {cheri_int_mode_name}
[#insn_remapping_16bit_rv64_a]
[width="100%",options=header]
|==============================================================================
2+|Encoding    5+| Supported Extensions
|[15:13]|[1:0]   | Zca    | Zcf     | Zcd | Zcmp/ Zcmt | Zclsd
|111    |00      | <<C.SD>>   | N/A     | N/A | N/A        | N/A
|011    |00      | <<C.LD>>   | N/A     | N/A | N/A        | N/A
|111    |10      | <<C.SDSP>> | N/A     | N/A | N/A        | N/A
|011    |10      | <<C.LDSP>> | N/A     | N/A | N/A        | N/A

|101    |00      | N/A    | N/A     | <<C.FSD>>    | reserved^1^       | N/A
|001    |00      | N/A    | N/A     | <<C.FLD>>    | reserved^1^       | N/A
|101    |10      | N/A    | N/A     | <<C.FSDSP>>  | <<Zcmp>>/<<Zcmt>> | N/A
|001    |10      | N/A    | N/A     | <<C.FLDSP>>  | reserved^1^       | N/A
|==============================================================================

.16-bit instruction remapping in {cheri_cap_mode_name}
[#insn_remapping_16bit_rv64_b]
[width="100%",options=header]
|==============================================================================
2+|Encoding    5+| Supported Extensions
|[15:13]|[1:0]   | Zca    | Zcf     | Zcd | Zcmp/ Zcmt | Zclsd
|111    |00      | <<C.SD>>   | N/A     | N/A | N/A        | N/A
|011    |00      | <<C.LD>>   | N/A     | N/A | N/A        | N/A
|111    |10      | <<C.SDSP>> | N/A     | N/A | N/A        | N/A
|011    |10      | <<C.LDSP>> | N/A     | N/A | N/A        | N/A

|101    |00    5+| <<C.SC>>
|001    |00    5+| <<C.LC>>
|101    |10    5+| <<C.SCSP>>
|001    |10    5+| <<C.LCSP>>
|==============================================================================

include::insns/condbr_16bit.adoc[]

include::insns/cmv_16bit.adoc[]

include::insns/addi16sp_16bit.adoc[]

include::insns/addi4spn_16bit.adoc[]

include::insns/jalr_16bit.adoc[]

include::insns/jr_16bit.adoc[]

include::insns/jal_16bit.adoc[]

include::insns/j_16bit.adoc[]

include::insns/load_16bit.adoc[]

include::insns/load_16bit_sprel.adoc[]

include::insns/load_16bit_fp_sp.adoc[]

include::insns/load_16bit_fp_dp.adoc[]

include::insns/load_16bit_cap_sprel.adoc[]

include::insns/store_16bit.adoc[]

include::insns/store_16bit_sprel.adoc[]

include::insns/store_16bit_fp_sp.adoc[]

include::insns/store_16bit_fp_dp.adoc[]

include::insns/store_16bit_cap_sprel.adoc[]

<<<
=== "Zicbom", "Zicbop", "Zicboz" Standard Extensions for Base Cache Management Operations

Cache-related instructions and how CHERI affects them.

include::insns/cbo.clean.adoc[]

include::insns/cbo.flush.adoc[]

include::insns/cbo.inval.adoc[]

include::insns/cbo.zero.adoc[]

include::insns/prefetch.i.adoc[]

include::insns/prefetch.r.adoc[]

include::insns/prefetch.w.adoc[]

<<<
=== "Zba" Extension for Bit Manipulation Instructions

Bit manipulation instruction reference.

include::insns/adduw_32bit.adoc[]

include::insns/sh123add_32bit.adoc[]

include::insns/sh123adduw_32bit.adoc[]

include::insns/sh4add_32bit.adoc[]

include::insns/sh4adduw_32bit.adoc[]

<<<
[#Zcb,reftext="Zcb"]
=== "Zcb" Standard Extension For Code-Size Reduction

Code-size reduction instructions and how they interact with CHERI.

include::insns/load_16bit_Zcb.adoc[]

include::insns/store_16bit_Zcb.adoc[]

<<<
[#Zcmp,reftext="Zcmp"]
=== "Zcmp" Standard Extension For Code-Size Reduction

The push (<<CM.PUSH>>) and pop (<<CM.POP>>, <<CM.POPRET>>, <<CM.POPRETZ>>) instructions are redefined in {cheri_cap_mode_name} to save/restore full capabilities.

The double move instructions (<<CM.MVSA01>>, <<CM.MVA01S>>) are redefined in {cheri_cap_mode_name} to move full capabilities between registers. The saved register mapping is as shown in

.saved register mapping for Zcmp
[#saved_register_mapping]
[width="100%",options=header, align="center"]
|====================================
| saved register specifier | xreg | integer ABI | CHERI ABI
| 0                       | x8  | s0 | cs0
| 1                       | x9  | s1 | cs1
| 2                       | x18 | s2 | cs2
| 3                       | x19 | s3 | cs3
| 4                       | x20 | s4 | cs4
| 5                       | x21 | s5 | cs5
| 6                       | x22 | s6 | cs6
| 7                       | x23 | s7 | cs7
|====================================


All instructions are defined in cite:[riscv-code-size-spec].

include::insns/zcmp_cmpush.adoc[]

include::insns/zcmp_cmpop.adoc[]

include::insns/zcmp_cmpopret.adoc[]

include::insns/zcmp_cmpopretz.adoc[]

include::insns/zcmp_cmvsa01.adoc[]

include::insns/zcmp_cmva01s.adoc[]


<<<
[#Zcmt,reftext="Zcmt"]
=== "Zcmt" Standard Extension For Code-Size Reduction

The table jump instructions (<<CM.JT>>, <<CM.JALT>>) defined in cite:[riscv-code-size-spec] are _not_ redefined in {cheri_cap_mode_name} to have capabilities in the jump table. This is to prevent the code-size growth caused by doubling the size of the jump table.

In the future, new jump table modes or new encodings can be added to have capabilities in the jump table.

The jump vector table CSR <<jvt>> has a capability alias <<jvtc>> so that it can only be configured to point to accessible memory. All accesses to the jump table are checked against <<jvtc>> in {cheri_cap_mode_name}, and against <<pcc>> bounds in {cheri_int_mode_name}. This allows the jump table to be accessed
when the <<pcc>> bounds are set narrowly to the local function only in {cheri_cap_mode_name}.

NOTE: Zcmt defines that the fetch from the jump table is from instruction memory.
 The overall instruction executed is effectively 48-bit, with 16-bits from <<CM.JALT>>/<<CM.JT>>, the other 32-bits (for RV32) from the table.
 Therefore <<pcc>> is used to authorize the fetch in {cheri_int_mode_name}, as the fetch is designated to be from instruction memory in cite:[riscv-unpriv-spec].

NOTE: In {cheri_cap_mode_name} the implementation doesn't need to expand and bounds check against <<jvtc>> on every access, it is sufficient to decode the valid accessible range of entries after every write to <<jvtc>>, and then check that the accessed entry is in that range.

[#jvt,reftext="jvt"]
==== Jump Vector Table CSR (jvt)

The JVT CSR is exactly as defined by cite:[riscv-code-size-spec]. It is renamed to <<jvtc>>.

[#jvtc,reftext="jvtc"]
==== Jump Vector Table CSR (jvtc)

<<jvtc>> extends <<jvt>> to be a capability width CSR, as shown in xref:ucsrnames-renamed[xrefstyle=short].

.Jump Vector Table Capability register
include::img/jvtcreg.edn[]

All instruction fetches from the jump vector table are checked against <<jvtc>> in {cheri_cap_mode_name}.
In {cheri_int_mode_name} the address field gives the base address of the table, and the access is
checked against <<pcc>> bounds.

See <<CM_JALT>>, <<CM_JT>>.

If the access to the jump table succeeds, then the instructions execute as follows:

** <<CM_JT>> executes as <<JAL_CHERI,J>> or <<AUIPC_CHERI>>+<<JALR_CHERI,JR>>
** <<CM_JALT>> executes as <<JAL_CHERI>> or <<AUIPC_CHERI>>+<<JALR_CHERI>>

As a result the capability metadata is retained in <<pcc>> during execution.

include::insns/zcmt_cmjalt.adoc[]

include::insns/zcmt_cmjt.adoc[]

<<<

=== "H" Extension for Hypervisor Support

Hypervisor instructions and the CHERI extensions.

include::insns/hypv-virt-load.adoc[]

include::insns/hypv-virt-load-cap.adoc[]

include::insns/hypv-virt-store.adoc[]

include::insns/hypv-virt-store-cap.adoc[]

include::insns/hypv-virt-loadx.adoc[]
