[appendix]
== Placeholder references to unprivileged spec

ifdef::cheri_standalone_spec[]
WARNING: This chapter only exists for the standalone document to allow references to resolve.
endif::[]

[#mstatus,reftext="mstatus"]
Machine Status Registers (mstatus and mstatush)::
[[xlen-control]]Base ISA Control in `mstatus` Register::
[[endianness-control]]Endianness Control in `mstatus` and `mstatush` Registers::
See `mtatus` in Chapter _Machine-Level ISA, Version 1.13_ in cite:[riscv-priv-spec].

[#mscratch, reftext="mscratch"]
Machine Scratch Register (mscratch)::
See `mscratch` in Chapter _Machine-Level ISA, Version 1.13_ in cite:[riscv-priv-spec].

.Machine-mode scratch register
include::img/mscratchreg.edn[]

[#mcause,reftext="mcause"]
Machine Cause (`mcause`) Register::
[[exception-priority]]Synchronous exception priority in decreasing priority order::
[[mcauses]]Machine cause (`mcause`) register values after trap::
See `mcause` in Chapter _Machine-Level ISA, Version 1.13_ in cite:[riscv-priv-spec].

.Machine Cause (`mcause`) register.
include::img/mcausereg.edn[]

[#mtvec,reftext="mtvec"]
Machine Trap-Vector Base-Address (`mtvec`) Register::
See `mtvec` in Chapter _Machine-Level ISA, Version 1.13_ in cite:[riscv-priv-spec].

.Machine-mode trap-vector base-address register
include::img/mtvecreg.edn[]

[#mepc,reftext="mepc"]
Machine Exception Program Counter (mepc)::
See `mepc` in Chapter _Machine-Level ISA, Version 1.13_ in cite:[riscv-priv-spec].

.Machine exception program counter register
include::img/mepcreg.edn[]

[#medeleg,reftext="medeleg"]
Machine Trap Delegation Register (medeleg)::
See `medeleg` in Chapter _Machine-Level ISA, Version 1.13_ in cite:[riscv-priv-spec].

[#mtval,reftext="mtval"]
Machine Trap Value Register (mtval)::
See `mtval` in Chapter _Machine-Level ISA, Version 1.13_ in cite:[riscv-priv-spec].

.Machine trap value register
include::img/mtvalreg.edn[]


[#stvec,reftext="stvec"]
Supervisor Trap Vector Base Address (`stvec`) Register::
See `stvec` in Chapter _Supervisor-Level ISA, Version 1.13_ in cite:[riscv-priv-spec].

.Supervisor trap vector base address (`stvec`) register.
include::img/stvecreg.edn[]

[#sscratch, reftext="sscratch"]
Supervisor Scratch (`sscratch`) Register::
See `sscratch` in Chapter _Supervisor-Level ISA, Version 1.13_ in cite:[riscv-priv-spec].

.Supervisor-mode scratch register
include::img/sscratchreg.edn[]

[#sepc,reftext="sepc"]
Supervisor Exception Program Counter (`sepc`) Register::
See `sepc` in Chapter _Supervisor-Level ISA, Version 1.13_ in cite:[riscv-priv-spec].

.Supervisor exception program counter register
include::img/sepcreg.edn[]

[#stval,reftext="stval"]
Supervisor Trap Value (`stval`) Register::
See `stval` in Chapter _Supervisor-Level ISA, Version 1.13_ in cite:[riscv-priv-spec].

.Supervisor trap value register
[#stval-format]
include::img/stvalreg.edn[]

[#scause,reftext="scause"]
Supervisor Cause (`scause`) Register::
[[scauses]].Supervisor cause (`scause`) register values after trap::
See `scause` in Chapter _Supervisor-Level ISA, Version 1.13_ in cite:[riscv-priv-spec].

.Supervisor Cause (`scause`) register.
include::img/scausereg.edn[]
