[appendix]
== Placeholder references to unprivileged spec

ifdef::cheri_standalone_spec[]
WARNING: This chapter only exists for the standalone document to allow references to resolve.
endif::[]

[#mstatus,reftext="mstatus"]
Machine Status Registers (mstatus and mstatush)::
[[xlen-control]]Base ISA Control in `mstatus` Register::
[[endianness-control]]Endianness Control in `mstatus` and `mstatush` Registers::
See `mtatus` in Chapter _Machine-Level ISA, Version 1.13_ in cite:[riscv-priv-spec].

[#mscratch, reftext="mscratch"]
Machine Scratch Register (mscratch)::
See `mscratch` in Chapter _Machine-Level ISA, Version 1.13_ in cite:[riscv-priv-spec].

.Machine-mode scratch register
include::img/mscratchreg.edn[]

[#mcause,reftext="mcause"]
Machine Cause (`mcause`) Register::
[[exception-priority]]Synchronous exception priority in decreasing priority order::
[[mcauses]]Machine cause (`mcause`) register values after trap::
See `mcause` in Chapter _Machine-Level ISA, Version 1.13_ in cite:[riscv-priv-spec].

.Machine Cause (`mcause`) register.
include::img/mcausereg.edn[]

[#mtvec,reftext="mtvec"]
Machine Trap-Vector Base-Address (`mtvec`) Register::
See `mtvec` in Chapter _Machine-Level ISA, Version 1.13_ in cite:[riscv-priv-spec].

.Machine-mode trap-vector base-address register
include::img/mtvecreg.edn[]

[#mepc,reftext="mepc"]
Machine Exception Program Counter (mepc)::
See `mepc` in Chapter _Machine-Level ISA, Version 1.13_ in cite:[riscv-priv-spec].

.Machine exception program counter register
include::img/mepcreg.edn[]

[#medeleg,reftext="medeleg"]
Machine Trap Delegation Register (medeleg)::
See `medeleg` in Chapter _Machine-Level ISA, Version 1.13_ in cite:[riscv-priv-spec].

[#mtval,reftext="mtval"]
Machine Trap Value Register (mtval)::
See `mtval` in Chapter _Machine-Level ISA, Version 1.13_ in cite:[riscv-priv-spec].

.Machine trap value register
include::img/mtvalreg.edn[]
