[appendix]
== Placeholder references to privileged spec

ifdef::cheri_standalone_spec[]
WARNING: This chapter only exists for the standalone document to allow references to resolve.
endif::[]

[[priv-csrs]]
Control and Status Registers (CSRs) overview::
See Chapter _Control and Status Registers (CSRs)_ in cite:[riscv-priv-spec].

[#mstatus,reftext="mstatus"]
Machine Status Registers (mstatus and mstatush)::
[[xlen-control]]Base ISA Control in `mstatus` Register::
[[endianness-control]]Endianness Control in `mstatus` and `mstatush` Registers::
See `mtatus` in Chapter _Machine-Level ISA, Version 1.13_ in cite:[riscv-priv-spec].

[#mscratch, reftext="mscratch"]
Machine Scratch Register (mscratch)::
See `mscratch` in Chapter _Machine-Level ISA, Version 1.13_ in cite:[riscv-priv-spec].

.Machine-mode scratch register
include::img/mscratchreg.edn[]

[#mcause,reftext="mcause"]
Machine Cause (`mcause`) Register::
[[exception-priority]]Synchronous exception priority in decreasing priority order::
[[mcauses]]Machine cause (`mcause`) register values after trap::
See `mcause` in Chapter _Machine-Level ISA, Version 1.13_ in cite:[riscv-priv-spec].

.Machine Cause (`mcause`) register.
include::img/mcausereg.edn[]

[#mtvec,reftext="mtvec"]
Machine Trap-Vector Base-Address (`mtvec`) Register::
See `mtvec` in Chapter _Machine-Level ISA, Version 1.13_ in cite:[riscv-priv-spec].

.Machine-mode trap-vector base-address register
include::img/mtvecreg.edn[]

[#mepc,reftext="mepc"]
Machine Exception Program Counter (mepc)::
See `mepc` in Chapter _Machine-Level ISA, Version 1.13_ in cite:[riscv-priv-spec].

.Machine exception program counter register
include::img/mepcreg.edn[]

[#medeleg,reftext="medeleg"]
Machine Trap Delegation Register (medeleg)::
See `medeleg` in Chapter _Machine-Level ISA, Version 1.13_ in cite:[riscv-priv-spec].

[#mtval,reftext="mtval"]
Machine Trap Value Register (mtval)::
See `mtval` in Chapter _Machine-Level ISA, Version 1.13_ in cite:[riscv-priv-spec].

.Machine trap value register
include::img/mtvalreg.edn[]

[#mseccfg,reftext="mseccfg"]
Machine Security Configuration (`mseccfg`) Register::
See `mseccfg` in Chapter _Machine-Level ISA, Version 1.13_ in cite:[riscv-priv-spec].
{cheri_priv_m_ext} adds a new CRE bit.

.Machine security configuration register (*mseccfg*)
[#mseccfgmodereg]
include::img/mseccfgreg.edn[]

[#menvcfg,reftext="menvcfg"]
Machine Environment Configuration (`menvcfg`) Register::
See `menvcfg` in Chapter _Machine-Level ISA, Version 1.13_ in cite:[riscv-priv-spec].
{cheri_priv_m_ext} adds a new CRE bit.

.Machine environment configuration register (*menvcfg*)
[#menvcfgmodereg]
include::img/menvcfgmodereg.edn[]


[#stvec,reftext="stvec"]
Supervisor Trap Vector Base Address (`stvec`) Register::
See `stvec` in Chapter _Supervisor-Level ISA, Version 1.13_ in cite:[riscv-priv-spec].

.Supervisor trap vector base address (`stvec`) register.
include::img/stvecreg.edn[]

[#sscratch, reftext="sscratch"]
Supervisor Scratch (`sscratch`) Register::
See `sscratch` in Chapter _Supervisor-Level ISA, Version 1.13_ in cite:[riscv-priv-spec].

.Supervisor-mode scratch register
include::img/sscratchreg.edn[]

[#sepc,reftext="sepc"]
Supervisor Exception Program Counter (`sepc`) Register::
See `sepc` in Chapter _Supervisor-Level ISA, Version 1.13_ in cite:[riscv-priv-spec].

.Supervisor exception program counter register
include::img/sepcreg.edn[]

[#stval,reftext="stval"]
Supervisor Trap Value (`stval`) Register::
See `stval` in Chapter _Supervisor-Level ISA, Version 1.13_ in cite:[riscv-priv-spec].

.Supervisor trap value register
[#stval-format]
include::img/stvalreg.edn[]

[#scause,reftext="scause"]
Supervisor Cause (`scause`) Register::
[[scauses]].Supervisor cause (`scause`) register values after trap::
See `scause` in Chapter _Supervisor-Level ISA, Version 1.13_ in cite:[riscv-priv-spec].

.Supervisor Cause (`scause`) register.
include::img/scausereg.edn[]

[#senvcfg,reftext="senvcfg"]
Supervisor Environment Configuration (`senvcfg`) Register::
See `senvcfg` in Chapter _Supervisor-Level ISA, Version 1.13_ in cite:[riscv-priv-spec]. {cheri_priv_s_ext} adds a new CRE bit.

.Supervisor environment configuration register (*senvcfg*)
[#senvcfgreg]
include::img/senvcfgreg.edn[]

[#sstatus,reftext="sstatus"]
Supervisor Status (`sstatus`) Register::
See `sstatus` in Chapter _Supervisor-Level ISA, Version 1.13_ in cite:[riscv-priv-spec].


[#vstvec,reftext="vstvec"]
Virtual Supervisor Trap Vector Base Address (`vstvec`) Register::
See `vstvec` in Chapter _"H" Extension for Hypervisor Support_ in cite:[riscv-priv-spec].
include::../images/bytefield/vstvecreg.edn[]

[#vsscratch, reftext="vsscratch"]
Virtual Supervisor Scratch (`vsscratch`) Register::
See `vsscratch` in Chapter _"H" Extension for Hypervisor Support_ in cite:[riscv-priv-spec].

.Virtual Supervisor-mode scratch register
include::../images/bytefield/vsscratchreg.edn[]

[#vsepc,reftext="vsepc"]
Virtual Supervisor Exception Program Counter (`sepc`) Register::
See `vsepc` in Chapter _"H" Extension for Hypervisor Support_ in cite:[riscv-priv-spec].

.Virtual Supervisor exception program counter register
include::../images/bytefield/vsepcreg.edn[]
