ifdef::cheri_standalone_spec[]

[appendix]
== Placeholder references to unprivileged spec
To allow building this document both as an extension to the RISC-V ISA documents and standalone, the following references point to the appropriate chapter in the (un)privileged specification:

[[rv32]]RV32I::
See Chapter _RV32I Base Integer Instruction Set_ in cite:[riscv-unpriv-spec].
[[rv32e]]RV32E and RV64E::
See Chapter _RV32E and RV64E Base Integer Instruction Sets_ in
[[gprs]]General purpose registers::
See Chapter _RV32I Base Integer Instruction Set_ in cite:[riscv-unpriv-spec].
[[ldst]]Load and Store Instructions::
See Chapter _RV32I Base Integer Instruction Set_ in cite:[riscv-unpriv-spec].
[[int-comp-lui-aiupc]]Integer Register-Immediate Instructions::
See Chapter _RV32I Base Integer Instruction Set_ in cite:[riscv-unpriv-spec].
[[ct-insns]]Control Transfer Instructions::
See Chapter _RV32I Base Integer Instruction Set_ in cite:[riscv-unpriv-spec].
[[atomics]]Atomics::
See Chapter _"A" Extension for Atomic Instructions_ in cite:[riscv-unpriv-spec].
[[zba]]Zba::
See Chapter _"B" Extension for Bit Manipulation_ in cite:[riscv-unpriv-spec].
[[zba]]Zicbom::
See Chapter _"CMO" Extensions for Base Cache Management Operation ISA_ in cite:[riscv-unpriv-spec].
[[zaamo_cheri]]Zaamo::
See Chapter _"A" Extension for Atomic Instructions_ in cite:[riscv-unpriv-spec].

endif::[]
