[appendix]
[#clen_csr_summary]
== {cheri_base_ext_name} YLEN CSR Summary

#this section includes debug CSRs#

.CSRs extended to YLEN
[#aliased_CSRs]
[width="100%",options=header,cols="1,1"]
|==============================================================================
include::generated/csr_aliases_table_body.adoc[]
|==============================================================================

.Action taken on writing to extended CSRs
[#extended_CSR_writing]
[width="100%",options=header,cols="1,2,2"]
|==============================================================================
include::generated/csr_alias_action_table_body.adoc[]
|==============================================================================

^*^ The vector range check is to ensure that vectored entry to the handler is within bounds of the capability written to `__x__tvec`.
  The check on writing must include the lowest (0 offset) and highest possible offset (e.g., 64 * MXLEN bits where HICAUSE=16).

XLEN bits of extended YLEN-wide CSRs are written when executing
<<CSRRWI_CHERI>>, <<CSRRC_CHERI>>, <<CSRRS_CHERI>>, <<CSRRCI_CHERI>> or <<CSRRSI_CHERI>> regardless of the
CHERI execution mode. When using <<CSRRW_CHERI>>, YLEN bits are written when the
CHERI execution mode is {cheri_cap_mode_name} and XLEN bits are written when
the mode is {cheri_int_mode_name}; therefore, writing XLEN bits with <<CSRRW_CHERI>>
is only possible when {cheri_default_ext_name} is implemented.

.Action taken on writing to YLEN-wide CSRs
[#new_cap_CSR_writing]
[width="100%",options=header,cols="1,2,2"]
|==============================================================================
include::generated/new_csr_write_action_table_body.adoc[]
|==============================================================================

XLEN bits of YLEN-wide CSRs added in {cheri_default_ext_name} are
written when executing <<CSRRWI_CHERI>>, <<CSRRC_CHERI>>, <<CSRRS_CHERI>>, <<CSRRCI_CHERI>> or
<<CSRRSI_CHERI>> regardless of the CHERI execution mode. YLEN bits are always written
when using <<CSRRW_CHERI>> regardless of the CHERI execution mode.

NOTE: Implementations which allow misa.C to be writable need to legalize `__x__epc`
 on _reading_ if the misa.C value has changed since the value was written as this
 can cause the read value of bit [1] to change state.

.YLEN-wide CSRs storing code pointers or data pointers
[#CSR_exevectors]
[width="100%",options=header,cols="1,1,1,1"]
|==============================================================================
include::generated/csr_exevectors_table_body.adoc[]
|==============================================================================

Some CSRs store code pointers or data pointers as shown in xref:CSR_exevectors[xrefstyle=short].
These are WARL CSRs that do not need to store full 64-bit addresses on RV64, and so need not be capable
of holding all possible invalid addresses. Prior to writing an invalid address to these CSRs,
the address must be converted to another invalid address that the CSR is capable of holding.
CSRs that store fewer address bits are also subject to the invalid address
check in <<section_invalid_addr_conv>> on writing.

The tables below show all YLEN-wide CSRs.

//the separate tables below are more useful
//.All YLEN-wide CSRs.
//[#all_capability_CSRs]
//[width="100%",options=header,cols="2,1,1,2,2,4"]
//|==============================================================================
//include::generated/csr_permission_table_body.adoc[]
//|==============================================================================

{cheri_priv_m_ext} and {cheri_priv_s_ext} extend the CSRs listed in
xref:dcsrnames-renamed[xrefstyle=short],
xref:mcsrnames-renamed[xrefstyle=short],
xref:scsrnames-renamed[xrefstyle=short],
xref:vscsrnames-renamed[xrefstyle=short] and
xref:ucsrnames-renamed[xrefstyle=short] from the base RISC-V ISA and its
extensions.

NOTE: If {cheri_default_ext_name} is supported then the <<cheri_execution_mode>> determines whether YLEN or XLEN bits are returned (see <<CSRRW_CHERI>>).

[[dcsrnames-renamed]]
.Extended debug-mode CSRs in {cheri_base_ext_name}
[%autowidth,float="center",align="center",cols="<,<,<,<,<",options="header"]
|===
include::generated/csr_renamed_purecap_mode_d_table_body.adoc[]
|===

[[mcsrnames-renamed]]
.Extended machine-mode CSRs in {cheri_base_ext_name}
[%autowidth,float="center",align="center",cols="<,<,<,<,<",options="header"]
|===
include::generated/csr_renamed_purecap_mode_m_table_body.adoc[]
|===

[NOTE]
=====
`mconfigptr` is not extended, despite representing an address,
as it is solely for use by _low-level system software_
and is not interpreted by hardware.
Such software can be expected to hold suitable <<root-cap>> capabilities
from which it can derive a capability to the address in this register.
=====

[[scsrnames-renamed]]
.Extended supervisor-mode CSRs in {cheri_base_ext_name}
[%autowidth,float="center",align="center",cols="<,<,<,<,<",options="header"]
|===
include::generated/csr_renamed_purecap_mode_s_table_body.adoc[]
|===

[[vscsrnames-renamed]]
.Extended virtual supervisor-mode CSRs in {cheri_base_ext_name}
[%autowidth,float="center",align="center",cols="<,<,<,<,<",options="header"]
|===
include::generated/csr_renamed_purecap_mode_vs_table_body.adoc[]
|===

[[ucsrnames-renamed]]
.Extended user-mode CSRs in {cheri_base_ext_name}
[%autowidth,float="center",align="center",cols="<,<,<,<,<",options="header"]
|===
include::generated/csr_renamed_purecap_mode_u_table_body.adoc[]
|===

ifndef::cheri_standalone_spec[]

[#CSRRWI_CHERI, reftext=CSRRWI ({cheri_base_ext_name})]
CSRRWI ({cheri_base_ext_name})::
  See the unprivileged manual for the definition of CSRRWI ({cheri_base_ext_name}).

[#CSRRCI_CHERI, reftext=CSRRCI ({cheri_base_ext_name})]
CSRRCI ({cheri_base_ext_name})::
  See the unprivileged manual for the definition of CSRRCI ({cheri_base_ext_name}).

[#CSRRSI_CHERI, reftext=CSRRSI ({cheri_base_ext_name})]
CSRRSI ({cheri_base_ext_name})::
  See the unprivileged manual for the definition of CSRRSI ({cheri_base_ext_name}).

[#CSRRC_CHERI, reftext=CSRRC ({cheri_base_ext_name})]
CSRRC ({cheri_base_ext_name})::
  See the unprivileged manual for the definition of CSRRC ({cheri_base_ext_name}).

[#CSRRS_CHERI, reftext=CSRRS ({cheri_base_ext_name})]
CSRRS ({cheri_base_ext_name})::
  See the unprivileged manual for the definition of CSRRS ({cheri_base_ext_name}).

[#jvt, reftext=jvt]
CSRRS ({cheri_base_ext_name})::
  See the unprivileged manual for the definition of the JVT CSR.

[#jvt_y, reftext=jvt ({cheri_base_ext_name})]
CSRRS ({cheri_base_ext_name})::
  See the unprivileged manual for the definition of the JVT ({cheri_base_ext_name}) CSR.

endif::[]
