[#section_cheri_priv_crg_ext]
== "{cheri_priv_crg_ext}" Extension, Version 1.0 for {cheri_base64_ext_name}

ifdef::cheri_standalone_spec[]
WARNING: This chapter will appear in the priv spec. Exact location TBD.
endif::[]

CAUTION: #This chapter needs additional updates before it is ready for ARC review#

NOTE: _Sv32_ (for RV32) does not have any spare PTE bits, and so no features from this chapter can be implemented.

The {cheri_priv_crg_ext} extension adds the ability to perform capability revocation of user mode pages (see <<cap_revocation>>) by adding the PTE.CRG bit, and <<sstatusreg_pte,sstatus>>.UCRG as described below.

NOTE: {cheri_priv_crg_ext} depends on {cheri_priv_vmem_ext} also being supported.

NOTE: {cheri_priv_crg_ext} is strongly recommended but not mandatory as a future version of this specification may specify an improved method.

NOTE: There is no explicit mechanism for enabling or disabling {cheri_priv_crg_ext}.

NOTE: If software ignores the new PTE bits then there is no change in functionality unless capabilities are accessed.

NOTE: A future version of this specification may include kernel revocation which may require an <<sstatusreg_pte,sstatus>>.SCRG bit.

The minimum level of PTE support is to set CW to 1 in all PTEs intended for storing capabilities (i.e., private anonymous mappings) and leave <<sstatusreg_pte,sstatus>>.UCRG and CRG in all PTEs set to 0, which will allow capabilities with their tags set to be loaded and stored successfully.

NOTE: Hardware initiated memory accesses from the page-table walker are not checked by a capability.

[#cap_revocation]
=== Capability Revocation

Page table enforcement can accelerate concurrent capability revocation
for temporal safety.
Without page table capability protection, a concurrent capability revocation
sweep must begin by visiting all PTEs to mark them unreadable, henceforth trapping on any
read to a new page to sweep it clean before proceeding.
With a page-granularity generational capability read permission, we can
eliminate the initial permission change of all PTEs.
In addition, a page-granularity capability write control can eliminate many pages
from the sweep that are known to not contain capabilities.


[#section_extending_pte]
=== Extending the Page Table Entry Format

ifdef::cheri_v9_annotations[]
NOTE: *CHERI v9 Note:* The current proposal is provisional and only includes
support for load-side revocation when compared to CHERI v9.
endif::[]

One new bit, Capability Read Generation (CRG), is added to leaf PTEs in Sv39, Sv48 and Sv57 as shown in
xref:sv39pte_crg[xrefstyle=short], xref:sv48pte_crg[xrefstyle=short] and
xref:sv57pte_crg[xrefstyle=short] respectively. For non-leaf PTEs these bits
remain reserved and must be cleared by software for forward compatibility,
or else a page-fault exception is raised. Additionally, if the hypervisor
extension is enabled these bits remain reserved for leaf and non-leaf PTEs
used in guest address translation.

.Sv39 page table entry
[#sv39pte_crg]
include::img/sv39pte_crg.edn[]

.Sv48 page table entry
[#sv48pte_crg]
include::img/sv48pte_crg.edn[]

.Sv57 page table entry
[#sv57pte_crg]
include::img/sv57pte_crg.edn[]

NOTE: The behavior in this section isn't relevant if:

. The authorizing capability doesn't have <<c_perm>>, for loads, stores and AMOs.
. Any extension-specific mediation has already cleared the stored tag, for stores and AMOs.

The CW bit (defined by {cheri_priv_vmem_ext}) indicates whether reading or writing capabilities with the {ctag} set to
the virtual page is permitted. When the CW bit is set, capabilities are written
as usual, and capability reads are controlled by the CRG bit.

NOTE: The {ctag} bit of the stored capability is checked _after_ it is potentially
cleared due to lack of <<c_perm>>.

If the CW bit is clear then:

* When a capability load or AMO instruction is executed, the implementation
 clears the {ctag} bit of the capability read from the virtual page.
* When CRG is clear, the "no capability state", a {cheri_excep_name_pte_st}
 is raised when a capability store or AMO instruction is executed and the {ctag} bit
 of the capability being written is set.
* When CRG is set, the "pre-CW state", two schemes are permitted (also see <<section_hardware_pte_updates>>):
** The same behavior as when CRG is clear, allowing software interpretation
of this state.
** When a capability store or AMO instruction is executed
and the {ctag} bit of the capability being written is set, the
implementation sets the CW bit and assigns the CRG bit equal to <<sstatusreg_pte,sstatus>>.UCRG.
+
The PTE update must be
atomic with respect to other accesses to the PTE, and must atomically check
that the PTE is valid and grants sufficient permissions. Updates to the CW bit
and CRG bit
must be exact (i.e., not speculative), and observed in program order by the
local hart. Furthermore, the PTE update must appear in the global memory order
no later than the explicit memory access, or any subsequent explicit memory
access to that virtual page by the local hart.  The ordering on loads and
stores provided by FENCE instructions and the acquire/release bits on atomic
instructions also orders the PTE updates associated with those loads and
stores as observed by remote harts.
+
The PTE update is not required to be atomic with respect to the explicit memory
access that caused the update, and the sequence is interruptible. However, the
hart must not perform explicit memory access before the PTE update is globally
visible.

When CW is set, the CRG bit indicates the current generation of the virtual memory page with
regards to the ongoing capability revocation cycle. Two schemes are permitted:

* A {cheri_excep_name_pte_ld} is raised when a capability load or AMO instruction is executed
with <<c_perm>> granted and the virtual page's CRG bit does not equal <<sstatusreg_pte,sstatus>>.UCRG and PTE.U is set.
* A {cheri_excep_name_pte_ld} is raised when a capability load or AMO instruction is executed
with <<c_perm>> granted and the virtual page's CRG bit does not equal <<sstatusreg_pte,sstatus>>.UCRG and PTE.U is set
and the capability read from memory has its tag set.

[[pte_cw_crg_load_summary]]
.Summary of Load CW and CRG behavior in the PTEs
[%autowidth,float="center",align="center",cols="<,<,<,<",options="header"]
|===
|PTE.CW |PTE.U|PTE.CRG                                    |Load/AMO
| 0     | X   | X                                         | Clear loaded tag
| 1     | 1   |&#8800; <<sstatusreg_pte,sstatus>>.UCRG    | {cheri_excep_name_pte_ld}, or {cheri_excep_name_pte_ld} if tag is set for _{cheri_priv_crg_load_tag_ext}_^1^
| 1     | 1   |=       <<sstatusreg_pte,sstatus>>.UCRG^1^ | Normal operation
| 1     | 0   | X                                         | Normal operation^2^
|===

^1^ The choice here is whether to take data dependent exceptions on load data for loads or atomic operations.
 The default is to take the trap without checking the value of the loaded {ctag}.
 Taking a trap when the {ctag} is not set will introduce additional traps during revocation sweeps.
 If _{cheri_priv_crg_load_tag_ext}_ is implemented then the trap is only taken if the loaded {ctag} is set, to reduce software overhead from revocation sweeps.
 Checking the loaded tag affects the exception priority, see <<exception-priority>>.

NOTE: _{cheri_priv_crg_load_tag_ext}_ is an optimization for software, and as such implementations are allowed to conservatively fault under certain conditions even if the {ctag} is not set.

_{cheri_priv_crg_load_tag_ext}_ implies _{cheri_priv_crg_ext}_.

^2^ A future version of this specification may check an SCRG bit in <<sstatusreg_pte,sstatus>> for kernel revocation.

[[pte_cw_crg_store_summary]]
.Summary of Store CW and CRG behavior in the PTEs
[%autowidth,float="center",align="center",cols="<,<,<",options="header"]
|===
|PTE.CW |PTE.CRG|Store/AMO
| 0     | 0     | {cheri_excep_name_pte_st} if stored tag is set
| 0     | 1     | {cheri_excep_name_pte_st} if stored tag is set, or <<section_hardware_pte_updates, hardware CW and CRG update>>
| 1     | X     | Normal operation
|===

[#section_hardware_pte_updates]
=== Enabling Software or Hardware PTE updates

The decision about whether to take exceptions on capability stores with the {ctag} set to a page with PTE.CW=0 and PTE.CRG=1 is determined by whether the _Svade_ and _Svadu_ extensions are enabled.
These cause PTE Accessed and Dirty updates to be done in software, via the exception handler, or by a hardware mechanism respectively.

* If only _Svade_ is implemented, or enabled through henvcfg.ADUE or menvcfg.ADUE, then take a {cheri_excep_name_pte_st}.
* If only _Svadu_ is implemented, or enabled through henvcfg.ADUE or menvcfg.ADUE, then do the hardware update of setting PTE.CW=1 and setting PTE.CRG=<<sstatusreg_pte,sstatus>>.UCRG as described in <<section_extending_pte>>.

[#xstatus_pte]
=== Extending the Supervisor (sstatus) and Virtual Supervisor (vsstatus) Status Registers

The <<sstatusreg_pte,sstatus>> and <<vsstatusreg_pte,vsstatus>> CSRs are extended to include the new Capability Read Generation (CRG) bit as shown.

When V=1 <<vsstatusreg_pte,vsstatus>>.UCRG is in effect.

<<mstatusreg_pte,mstatus>>.UCRG also exists. Reading or writing it is equivalent to reading or writing <<sstatusreg_pte,sstatus>>.UCRG.


[#mstatusreg_pte]
.Machine-mode status (*mstatus*) register when MXLEN=64
[wavedrom, ,svg]
....
{reg: [
  {bits:  1, name: 'WPRI'},
  {bits:  1, name: 'SIE'},
  {bits:  1, name: 'WPRI'},
  {bits:  1, name: 'MIE'},
  {bits:  1, name: 'WPRI'},
  {bits:  1, name: 'SPIE'},
  {bits:  1, name: 'UBE'},
  {bits:  1, name: 'MPIE'},
  {bits:  1, name: 'SPP'},
  {bits:  2, name: 'VS[1:0]'},
  {bits:  2, name: 'MPP[1:0]'},
  {bits:  2, name: 'FS[1:0]'},
  {bits:  2, name: 'XS[1:0]'},
  {bits:  1, name: 'MPRV'},
  {bits:  1, name: 'SUM'},
  {bits:  1, name: 'MXR'},
  {bits:  1, name: 'TVM'},
  {bits:  1, name: 'TW'},
  {bits:  1, name: 'TSR'},
  {bits:  1, name: 'SPELP'},
  {bits:  1, name: 'SDT'},
  {bits:  7, name: 'WPRI'},
  {bits:  2, name: 'UXL[1:0]'},
  {bits:  2, name: 'SXL[1:0]'},
  {bits:  1, name: 'SBE'},
  {bits:  1, name: 'MBE'},
  {bits:  1, name: 'GVA'},
  {bits:  1, name: 'MPV'},
  {bits:  1, name: 'WPRI'},
  {bits:  1, name: 'MPELP'},
  {bits:  1, name: 'MDT'},
  {bits: 18, name: 'WPRI'},
  {bits:  1, name: 'UCRG'},
  {bits:  1, name: 'WPRI'},
  {bits:  1, name: 'SD'},
], config:{lanes: 4, hspace:1024}}
....

[#sstatusreg_pte]
.Supervisor-mode status (*sstatus*) register when SXLEN=64
[wavedrom, ,svg]
....
{reg: [
  {bits:  1, name: 'WPRI'},
  {bits:  1, name: 'SIE'},
  {bits:  3, name: 'WPRI'},
  {bits:  1, name: 'SPIE'},
  {bits:  1, name: 'UBE'},
  {bits:  1, name: 'WPRI'},
  {bits:  1, name: 'SPP'},
  {bits:  2, name: 'VS[1:0]'},
  {bits:  2, name: 'WPRI'},
  {bits:  2, name: 'FS[1:0]'},
  {bits:  2, name: 'XS[1:0]'},
  {bits:  1, name: 'WPRI'},
  {bits:  1, name: 'SUM'},
  {bits:  1, name: 'MXR'},
  {bits:  3, name: 'WPRI'},
  {bits:  1, name: 'SPELP'},
  {bits:  1, name: 'SDT'},
  {bits:  7, name: 'WPRI'},
  {bits:  2, name: 'UXL[1:0]'},
  {bits: 27, name: 'WPRI'},
  {bits:  1, name: 'UCRG'},
  {bits:  1, name: 'WPRI'},
  {bits:  1, name: 'SD'},
], config:{lanes: 4, hspace:1024}}
....

[#vsstatusreg_pte]
.Virtual Supervisor-mode status (*vsstatus*) register when VSXLEN=64
[wavedrom, ,svg]
....
{reg: [
  {bits:  1, name: 'WPRI'},
  {bits:  1, name: 'SIE'},
  {bits:  3, name: 'WPRI'},
  {bits:  1, name: 'SPIE'},
  {bits:  1, name: 'UBE'},
  {bits:  1, name: 'WPRI'},
  {bits:  1, name: 'SPP'},
  {bits:  2, name: 'VS[1:0]'},
  {bits:  2, name: 'WPRI'},
  {bits:  2, name: 'FS[1:0]'},
  {bits:  2, name: 'XS[1:0]'},
  {bits:  1, name: 'WPRI'},
  {bits:  1, name: 'MXR'},
  {bits:  1, name: 'SUM'},
  {bits: 12, name: 'WPRI'},
  {bits:  2, name: 'UXL[1:0]'},
  {bits: 27, name: 'WPRI'},
  {bits:  1, name: 'UCRG'},
  {bits:  1, name: 'WPRI'},
  {bits:  1, name: 'SD'}
], config:{lanes: 4, hspace:1024}}
....
