[#section_debug_integration]
=== "{cheri_priv_debug_ext}", Integrating {cheri_base_ext_name} with Sdext

ifdef::cheri_standalone_spec[]
WARNING: This chapter will appear in the priv spec. Exact location TBD.
endif::[]

This section describes changes to integrate the Sdext ISA and
{cheri_base_ext_name}. It must be implemented to make external debug compatible
with {cheri_base_ext_name}. Modifications to Sdext are kept to a minimum.

The following features, which are optional in Sdext, must be implemented for
use with {cheri_base_ext_name}:

* The `hartinfo` register must be implemented.
* All harts which support {cheri_base_ext_name} must provide
  `hartinfo.nscratch` of at least 1 and implement the <<dscratch0c>> register.
* All harts which support {cheri_base_ext_name} must provide
  `hartinfo.datasize` of at least 1 and `hartinfo.dataaccess` of 0.
* The program buffer must be implemented, with `abstractcs.progbufsize` of at
  least 4 if `dmstatus.impebreak` is 1, or at least 5 if `dmstatus.impebreak`
  is 0.

[NOTE]
====
These requirements allow a debugger to read and write capabilities in integer
registers without disturbing other registers.  These requirements may be
relaxed if some other means of accessing capabilities in integer registers,
such as an extension of the Access Register abstract command, is added.  The
following sequences demonstrate how a debugger can read and write a capability
in `c1` if `MXLEN` is 64, `hartinfo.dataaccess` is 0, `hartinfo.dataaddr` is
0xBF0, `hartinfo.datasize` is 1, `dmstatus.impebreak` is 0, and
`abstractcs.progbufsize` is 5:

----
# Read the high MXLEN bits into data0-data1
csrrw  c2, dscratch0c, c2
gchi   x2, c1
csrw   0xBF0, x2
csrrw  c2, dscratch0c, c2
ebreak

# Read the valid tag into data0
csrrw  c2, dscratch0c, c2
gctag  x2, c1
csrw   0xBF0, x2
csrrw  c2, dscratch0c, c2
ebreak

# Write the high MXLEN bits from data0-data1
csrrw  c2, dscratch0c, c2
csrr   x2, 0xBF0
schi   c1, c1, x2
csrrw  c2, dscratch0c, c2
ebreak

# Write the valid tag (if nonzero)
csrrw   c2, dscratch0c, c2
csrr    c2, dinfc
cbld    c1, c2, c1
csrrw   c2, dscratch0c, c2
ebreak
----

The low `MXLEN` bits of a capability are read and written using normal Access
Register abstract commands.  If <<dscratch0c>> were known to be preserved
between abstract commands, it would be possible to remove the requirements on
`hartinfo.datasize`, `hartinfo.dataaccess`, and `abstractcs.progbufsize`,
however there is no way to discover the former property.
====

==== Debug Mode

When executing code due to an abstract command, the hart stays in debug mode
and the rules outlined in Section 4.1 of the _RISC-V Debug Specification_
apply.

==== Core Debug Registers

{cheri_base_ext_name} renames and extends debug CSRs that are designated to
hold addresses to be able to hold capabilities. The renamed debug CSRs are
listed in xref:dcsrnames-renamed[xrefstyle=short].

The <<pcc>> must grant <<asr_perm>> to access debug CSRs. This permission is
automatically provided when the hart enters debug mode as described
in the <<dpcc>> section. The <<pcc>> metadata can only be changed if the
implementation supports executing control transfer instructions from the
program buffer -- this is an optional feature according to
the _RISC-V Debug Specification_.

[#dpc,reftext="dpc"]
==== Debug Program Counter (dpc)

The <<dpc>> register is as defined in the _RISC-V Debug Specification_. It is a
DXLEN-bit register used as the PC saved when entering debug mode. <<dpc>> is
extended into <<dpcc>>.

.Debug program counter
include::img/dpcreg.edn[]

[#dpcc,reftext="dpcc"]
==== Debug Program Counter Capability (dpcc)

The <<dpcc>> register extends <<dpc>> to hold a capability.

{TAG_RESET_DCSR}

.Debug program counter capability
include::img/dpccreg.edn[]

Upon entry to debug mode, the _RISC-V Debug Specification_, does not specify how to
update the PC, and says PC relative instructions may be illegal. This concept
is extended to include any instruction which reads or updates <<pcc>>, which refers to
all jumps, conditional branches and <<AUIPC_CHERI>>. The exceptions are <<MODESW_CAP>> and <<MODESW_INT>>
which _are_ supported if {cheri_default_ext_name} is implemented, see <<dinfc>>
for details.

As a result, the value of <<pcc>> is UNSPECIFIED in debug mode according
to this specification. The <<pcc>> metadata has no architectural effect in debug
mode. Therefore <<asr_perm>> is implicitly granted for access to all CSRs and
no _{cheri_excep_name_pc}_ is possible.

On debug mode entry <<dpcc>> (and consequently <<dpc>>) are updated with the
capability in <<pcc>> whose address field is set to the address of the next
instruction to be executed upon debug mode exit as described in the _RISC-V Debug Specification_.

When leaving debug mode, the capability in <<dpcc>> is unsealed and written
into <<pcc>>.  A debugger may write <<dpcc>> to change where the hart resumes
and its mode, permissions, sealing or bounds.

The legalization of <<dpcc>> follows the same rules described for <<mepcc>>.

[#dscratch0,reftext="dscratch0"]
==== Debug Scratch Register 0 (dscratch0)

The <<dscratch0>> register is as defined in the _RISC-V Debug Specification_. It is an
optional DXLEN-bit scratch register that can be used by implementations which
need it. <<dscratch0>> is extended into <<dscratch0c>>.

.Debug scratch 0 register
include::img/dscratch0reg.edn[]

[#dscratch0c,reftext="dscratch0c"]
==== Debug Scratch Register 0 Capability (dscratch0c)

The <<dscratch0c>> register extends <<dscratch0>> to hold a capability.

{TAG_RESET_DCSR}

.Debug scratch 0 capability register
include::img/dscratch0creg.edn[]

[#dscratch1,reftext="dscratch1"]
==== Debug Scratch Register 1 (dscratch1)

The <<dscratch1>> register is as defined in the _RISC-V Debug Specification_. It is an
optional DXLEN-bit scratch register that can be used by implementations which
need it. <<dscratch1>> is extended into <<dscratch1c>>.

.Debug scratch 1 register
include::img/dscratch1reg.edn[]

[#dscratch1c,reftext="dscratch1c"]
==== Debug Scratch Register 1 Capability (dscratch1c)

The <<dscratch1c>> register extends <<dscratch1>> to hold a capability.

{TAG_RESET_DCSR}

.Debug scratch 1 capability register
include::img/dscratch1creg.edn[]

[#dinfc,reftext="dinfc"]
==== Debug Infinite Capability Register (dinfc)

<<dinfc>> is a debug mode accessible capability CSR. The address and access details are shown in
xref:default-csrnames-added[xrefstyle=short].

The reset value is the <<infinite-cap>> capability.

If {cheri_default_ext_name} is implemented:

* The <<m_bit>> is reset to {cheri_int_mode_name} ({INT_MODE_VALUE}).
* The debugger can set the <<m_bit>> to {cheri_cap_mode_name} ({CAP_MODE_VALUE}) by executing <<MODESW_CAP>> from the program buffer.
** Executing <<MODESW_CAP>> causes subsequent instructions execution from the program buffer, starting from the next instruction, to be executed in {cheri_cap_mode_name}. It also sets the CHERI execution mode to {cheri_cap_mode_name} on future entry into debug mode.
** Therefore to enable use of a CHERI debugger, a single <<MODESW_CAP>> only needs to be executed once from the program buffer after resetting the core.
** The debugger can also execute <<MODESW_INT>> to change the mode back to {cheri_int_mode_name}, which also affects the execution of the next instruction in the program buffer, updates the <<m_bit>> of <<dinfc>> and controls which CHERI execution mode to enter on the next entry into debug mode.

The <<m_bit>> of <<dinfc>> is _only_ updated by executing <<MODESW_CAP>> or <<MODESW_INT>> from the program buffer.

NOTE: A future version of this specification may add writeable fields to allow creation
 of other capabilities, if, for example, a future extension requires multiple formats for
 the <<infinite-cap>> capability.

.Debug infinite capability register
include::img/dinfcreg.edn[]

[#section_hybrid_debug_integration]
=== Integrating {cheri_default_ext_name} with Sdext

A new debug default data capability (<<dddc>>) CSR is added at the CSR number
shown in xref:default-csrnames-added[xrefstyle=short].

{cheri_default_ext_name} allows <<MODESW_CAP>> and <<MODESW_INT>> to execute in debug mode.

When entering debug mode, whether the core enters {cheri_int_mode_name} or
{cheri_cap_mode_name} is controlled by the <<m_bit>> in <<dinfc>>.

The current mode can be read from <<dinfc>>.

The following sequence executed from the program buffer will write {CAP_MODE_VALUE} for {cheri_cap_mode_name} and {INT_MODE_VALUE} for {cheri_int_mode_name} to `x1`:

[source]
----
csrr   c1, dinfc
gcmode x1, c1
----

ifdef::cheri_v9_annotations[]
NOTE: *CHERI v9 Note:* The mode change instructions <<MODESW_CAP>> and <<MODESW_INT>> are new
and the requirement to support them in debug mode is also new.
endif::[]

[#dddc,reftext="dddc"]
==== Debug Default Data Capability CSR (dddc)

<<dddc>> is a debug mode accessible capability CSR. The address is shown in
xref:default-csrnames-added[xrefstyle=short].

{TAG_RESET_DCSR}

{REQUIRE_HYBRID_CSR}

.Debug default data capability
include::img/dddcreg.edn[]

Upon entry to debug mode, <<ddc>> is saved in <<dddc>>. <<ddc>>'s metadata is
set to the <<infinite-cap>> capability's metadata (with tag set) and <<ddc>>'s
address remains unchanged.

When debug mode is exited by executing <<DRET_CHERI>>, the hart's <<ddc>> is updated to
the capability stored in <<dddc>>. A debugger may write <<dddc>> to change the
hart's context.

As shown in xref:CSR_exevectors[xrefstyle=short], <<dddc>> is a data pointer,
so it does not need to be able to hold all possible invalid addresses (see <<section_invalid_addr_conv>>).
