include::attributes.adoc[]
include::../symbols.adoc[]

[#section_debug_integration_ext]
== Integrating {cheri_base_ext_name} with Debug

include::trigger-integration.adoc[]

=== Integrating {cheri_base_ext_name} with Sdext

{cheri_base_ext_name} harts must provide a means for accessing capabilities in registers and in memory via the external debugger.

This is achieved by supporting at least one of:

. Implementing a program buffer configured as specified below.
. Supporting full capability access for both Access Register and Access Memory abstract commands (`aarsize=7` and `aamsize=7`).

==== Program Buffer

If a Program Buffer is implemented, this section shows how it can be configured and used to access capabilities.

* `hartinfo` must be implemented.
* `hartinfo.nscratch` is at least 1 and the <<dscratch0_y>> register is implemented.
* `hartinfo.datasize` is at least 1 and `hartinfo.dataaccess` is 0.
* `abstractcs.progbufsize` is at least 4 if `dmstatus.impebreak` is 1, or at least 5 if `dmstatus.impebreak` is 0.

[NOTE]
====
These requirements allow a debugger to read and write capabilities in integer registers without disturbing other registers.
These requirements may be relaxed if abstract commands support full capability access.

The sequences below demonstrate how a debugger can read and write a capability in `{creg}1` using the program buffer if:

* `MXLEN` is 64, and
* `hartinfo.dataaccess` is 0, and
* `hartinfo.dataaddr` is 0xBF0, and
* `hartinfo.datasize` is 1, and
* `hartinfo.nscratch` is at least 1, and
* `dmstatus.impebreak` is 0, and
* `abstractcs.progbufsize` is 5.

[source,subs=attributes+]
----
# Read the high MXLEN bits into data0-data1
csrrw  {creg}2, dscratch0, {creg}2
{gchi_lc}   x2, {creg}1
csrw   0xBF0, x2
csrrw  {creg}2, dscratch0, {creg}2
ebreak

# Read the {ctag} into data0
csrrw  {creg}2, dscratch0, {creg}2
{gctag_lc}  x2, {creg}1
csrw   0xBF0, x2
csrrw  {creg}2, dscratch0, {creg}2
ebreak

# Write the high MXLEN bits from data0-data1
csrrw  {creg}2, dscratch0, {creg}2
csrr   x2, 0xBF0
{schi_lc}   {creg}1, {creg}1, x2
csrrw  {creg}2, dscratch0, {creg}2
ebreak

# Write the {ctag} (if nonzero)
csrrw   {creg}2, dscratch0, {creg}2
csrr    {creg}2, drootc
{cbld_lc}    {creg}1, {creg}2, {creg}1
csrrw   {creg}2, dscratch0, {creg}2
ebreak
----

The low `MXLEN` bits of a capability are read and written using normal Access
Register abstract commands.

The above instruction sequences utilize these guarantees provided by
the _RISC-V Debug Specification_:

* When `hartinfo.nscratch` is greater than 0, the <<dscratch0_y>> register
  is guaranteed to retain its value within a single abstract command.

+
If <<dscratch0_y>> were known to be preserved between abstract commands,
it would be possible to remove the requirements on `hartinfo.datasize`,
`hartinfo.dataaccess`, and `abstractcs.progbufsize`, however, there is
no way to discover the former property.

* Execution of Access Register abstract commands does not alter the values of `data`
  debug module registers (unless read of a register is explicitly requested by
  setting `transfer` to 1 and `write` to 0).
====

==== Abstract Commands

Abstract commands are optionally extended to access full capabilities.

`aarsize/aarmsize=7` represent full capability access.

The `data<n>` register mapping for full capability accesses is as shown in <<debug_data_aarsize_7>>.

.Data register mapping when `aarsize/aamsize=7`
[#debug_data_aarsize_7]
[width="100%",options=header,cols="1,1,1,1,1"]
|=====
|ISA                    | arg0/return value| arg1^1^     | arg2        | {ctag}
|{cheri_base32_ext_name}| data0,data1      | data2       | data3,data4 | data5
|{cheri_base64_ext_name}| data0-data3      | data4,data5 | data6-data9 | data10
|=====

^1^ arg1 represents an address so never needs to exceed DXLEN.
 Each `data<n>` register is 32-bit so a maximum of 2 are required.

^2^ arg2 is not used for abstract commands, and is included for consistency with the equivalent table in the _RISC-V Debug Specification_

Bit 0 of `data5` or `data10` contain the {ctag} which is either written to, or read from, the target register.
All other bits in that `data` register are UNSPECIFIED.

==== Access Register Command

When a YLEN-wide register is accessible via an _Access Register_ abstract command, then:

- Reads of YLEN bits or any smaller amounts of bits must be supported.
- Writes of YLEN bits must be supported.
- Writes of smaller amounts of bits than YLEN may optionally be supported but it is UNSPECIFIED what happens to the higher bits.

NOTE: The debugger can change the low XLEN bits of a YLEN wide register by performing a read-modify-write sequence.

The requirement to support YLEN-wide access mandates that enough `data<n>` registers are implemented to cover the entire YLEN bit-width (at least 2 for {cheri_base32_ext_name} or at least 4 for {cheri_base64_ext_name}).

Implementations can choose to also support accessing {ctag}s as part of the access register command by supporting `aarsize=7`.

When a capability is written it must be derivable from the set of root capabilities available in <<drootc>>.
If not then the destination {ctag} is set to zero.

NOTE: If there is only a single root capability, then the derivable check is a capability subset check of the written capability against the capability in <<drootc>>.
 If there are multiple root capabilities then checks against multiple root capabilities may be required, as defined by the capability encoding format.

If `aarsize{ne}7` then {ctag}s are always read and written as zero.

NOTE: For the capability subset: `cap2` is the capability being written and `cap1` is the value of <<drootc>>.

NOTE: It is valid for root capabilities not to cover the entire possible address space.
 In this case the debugger cannot claim access to more memory than is permitted by the current value of <<drootc>>.

==== Access Memory Command

Implementations can choose to support accessing full capabilities, including the {ctag}s, via the _Access Memory_ abstract command. Full capability access is denoted by `aamsize=7` and uses the `data<n>` register assignments specified in <<debug_data_aarsize_7>>.

If `aamsize{ne}7` then {ctag}s are always read and written as zero.

==== Core Debug Registers

{cheri_base_ext_name} widens debug CSRs that are designated to hold addresses so that they can hold capabilities.

[#dpc_y,reftext="dpc ({cheri_base_ext_name})"]
===== Debug Program Counter Capability (dpc)

The `dpc` register is widened to a capability.

{TAG_RESET_DCSR}

.Debug program counter capability
include::img/dpccreg.edn[]

When the hart is in debug mode, the _RISC-V Debug Specification_ does not specify
how the `pc` is updated, and says that PC-relative instructions may be illegal. This concept
is extended to include any instruction which reads or updates PC, which refers to
all jumps, conditional branches and `AUIPC`. The exceptions are `{MODESW_CAP}` and `{MODESW_INT}`,
which _are_ supported if {cheri_default_ext_name} is implemented, see <<drootc>>
for details.

As a result, the value of the `pc` is UNSPECIFIED in debug mode according
to this specification. The `pc` metadata has no architectural effect in debug
mode. Therefore, `ASR-permission` is implicitly granted for access to all CSRs for
instruction execution.

On debug mode entry, <<dpc_y>> is updated with the
capability in the `pc`, whose address field equals to the address of the next
instruction to be executed upon debug mode exit as described in the _RISC-V Debug Specification_.

When leaving debug mode, the value in <<dpc_y>> is unsealed if it is a {sentry_cap_uc} and is written to PC.

NOTE: A debugger may write <<dpc_y>> to change where the hart resumes and its mode, permissions, sealing or bounds.
 The value saved from the `pc` on debug mode entry cannot be sealed.

The legalization of <<dpc_y>> follows the same rules described for `mepc`.

One possible implementation choice for debug mode exit is DRET.

[#dscratch0_y,reftext="dscratch0 ({cheri_base_ext_name})"]
===== Debug Scratch Register 0 (dscratch0)

The `dscratch0` register is widened to a capability.

{TAG_RESET_DCSR}

.Debug scratch 0 capability register
include::img/dscratch0creg.edn[]

[#dscratch1_y,reftext="dscratch1 ({cheri_base_ext_name})"]
===== Debug Scratch Register 1 (dscratch1)

The `dscratch1` register is widened to a capability.

{TAG_RESET_DCSR}

.Debug scratch 1 capability register
include::img/dscratch1creg.edn[]

[#drootcsel,reftext="drootcsel"]
===== Debug Root Capability Selector (drootcsel)

<<drootcsel>> is a DXLEN-bit debug mode accessible integer CSR.  The address and access details are shown in
xref:all_capability_CSRs_d[xrefstyle=short].

It selects which Root capability is exposed through <<drootc>>.
The reset value is `0`, which must cause <<drootc>> to expose a
Root Executable capability.

Other capability values may be defined for exposure through <<drootc>>
by the capability encoding,
and may be selected by having the debugger write to this register.
Writes are WARL, so the debugger may confirm that its selection has been applied.

.Debug root capability register
include::img/drootcselreg.edn[]

[#drootc,reftext="drootc"]
===== Debug Root Capability Register (drootc)

<<drootc>> is a debug mode accessible capability CSR. The address and access details are shown in
xref:all_capability_CSRs_d[xrefstyle=short].
It exposes the capability selected by <<drootcsel>>.

If {cheri_default_ext_name} is implemented,
the Root Executable exposed when <<drootcsel>> is `0` is further specified as follows:

* The `P-bit` is reset to {cheri_int_mode_name} ({INT_MODE_VALUE}).
* The debugger can set the `P-bit` to {cheri_cap_mode_name} ({CAP_MODE_VALUE}) by executing `{MODESW_CAP}` from the program buffer.
** Executing `{MODESW_CAP}` causes execution of subsequent instructions from the program buffer, starting from the next instruction, to be executed in {cheri_cap_mode_name}.
   It also sets the {cheri_mode_name} to {cheri_cap_mode_name} on future entry into debug mode.
** Therefore, to enable use of a CHERI debugger, only a single `{MODESW_CAP}` needs to be executed once from the program buffer after resetting the core.
** The debugger can also execute `{MODESW_INT}` to change the {cheri_mode_name} back to {cheri_int_mode_name}.
   This affects the execution of the next instruction in the program buffer, updates the `P-bit` of <<drootc>>, and thereby controls which {cheri_mode_name} to use on the next entry into debug mode.

The `P-bit` of this capability is _only_ updated by executing `{MODESW_CAP}` or `{MODESW_INT}` from the program buffer.

.Debug root capability register
include::img/drootcreg.edn[]

include::insns/dret.adoc[leveloffset=+1]

[#section_hybrid_debug_integration]
=== Integrating {cheri_default_ext_name} with Sdext

A new debug default data capability (<<dddc>>) CSR is added at the CSR number
shown in xref:all_capability_CSRs_d[xrefstyle=short].

{cheri_default_ext_name} allows `{MODESW_CAP}` and `{MODESW_INT}` to execute in debug mode.

When entering debug mode, whether the core enters {cheri_int_mode_name} or
{cheri_cap_mode_name} is controlled by the `P-bit` in the <<drootc>> capability selected by <<drootcsel>> value 0.

The current mode can be read by setting <<drootcsel>> to `0` and then reading <<drootc>>.

The following sequence executed from the program buffer will write {CAP_MODE_VALUE} for {cheri_cap_mode_name} and {INT_MODE_VALUE} for {cheri_int_mode_name} to `x1`:

[source,subs=attributes+]
----
csrr   {creg}1, drootc
{gcmode_lc} x1, {creg}1
----

NOTE: There is no CHERI enable/disable bit for debug mode, so CHERI register and instruction access is always permitted.

ifdef::cheri_v9_annotations[]
NOTE: *CHERI v9 Note:* The mode change instructions `{MODESW_CAP}` and `{MODESW_INT}` are new
and the requirement to support them in debug mode is also new.
endif::[]

[#dddc,reftext="dddc"]
==== Debug Default Data Capability CSR (dddc)

<<dddc>> is a debug mode accessible capability CSR. The address is shown in
xref:all_capability_CSRs_d[xrefstyle=short].

{TAG_RESET_DCSR}

{REQUIRE_HYBRID_CSR}

.Debug default data capability
include::img/dddcreg.edn[]

Upon entry to debug mode, `ddc` is saved in <<dddc>>. `ddc` is set to a
Root Data capability with an unchanged address.

NOTE: If the Root Data capability does not cover all of memory then `ddc` must be updated using the semantics of `{SCADDR}`.

When debug mode is exited by executing <<DRET_CHERI>>, the hart's `ddc` is updated to the capability stored in <<dddc>>.
When debug mode is exited the hart's `ddc` is updated to the capability stored in <<dddc>>, which may have been updated by the debugger.
A debugger may write <<dddc>> to change the hart's context.

As shown in xref:CSR_exevectors_d[xrefstyle=short], <<dddc>> is a data pointer,
so it does not need to be able to hold all possible invalid addresses.

=== Debug Mode YLEN CSR Summary

The tables below show all debug mode CSRs added or modified by {cheri_base_ext_name}.

.Action taken on writing to extended debug mode CSRs
[#extended_CSR_writing_d]
[width="100%",options=header,cols="1,1,1,2,2"]
|==============================================================================
include::{generated_dir}/csr_alias_action_d_table_body.adoc[]
|==============================================================================

Code pointers and data pointers in <<CSR_exevectors_d>> are WARL CSRs that do not need to store full 64-bit addresses on RV64, and so may be subject to invalid address conversion on writing.

.YLEN-wide Debug-Mode CSRs storing code pointers or data pointers
[#CSR_exevectors_d]
[width="100%",options=header,cols="1,1,1,1,1"]
|==============================================================================
include::{generated_dir}/csr_exevectors_d_table_body.adoc[]
|==============================================================================

<<all_capability_CSRs_d>> shows all debug-mode CSRs added or modified by {cheri_base_ext_name}.

.All {cheri_base_ext_name} debug mode CSRs.
[#all_capability_CSRs_d]
[width="100%",options=header,cols="2,1,1,1,1,2,2,4"]
|==============================================================================
include::{generated_dir}/csr_permission_d_table_body.adoc[]
|==============================================================================

NOTE: Where reset values are specified as a Root Executable or Root Data Capability they are a maximum possible value.
The platform may reset those CSRs to a smaller memory range, or to have fewer permissions.
