
[#section_cheri_hypervisor_integration, reftext="Hypervisor \"H\" ({cheri_base_ext_name})"]
== Hypervisor "H" Extension ({cheri_base_ext_name})

IMPORTANT: {not_v1_ratification_package_experimental}

{cheri_base_ext_name} affects the Hypervisor "H" extension as follows:

* Some CSRs are updated, either by widening to YLEN or by adding additional fields.
* The <<HLV_CAP>> and <<HSV_CAP>> encodings are added.

[#hstatus_y,reftext="hstatus ({cheri_base_ext_name})"]

NOTE: The {cheri_base_ext_name} field is not currently defined in G-stage PTEs and so remains reserved.
 A future extension may define this field.

VSXL and VSBE follow the same restrictions as <<mstatus_y>>.SXL and <<mstatus_y>>.SBE respectively.

[#henvcfg_y,reftext="henvcfg ({cheri_base_ext_name})"]
=== Hypervisor Environment Configuration Register (henvcfg)

The {CRE} bit is added to <<henvcfg_y>> as shown in xref:henvcfgreg[xrefstyle=short].

.Hypervisor environment configuration register (*henvcfg*)
[#henvcfgreg]
include::img/henvcfgreg.edn[]

The {CRE} bit controls whether explicit access to CHERI registers is permitted when V=1.

If {cheri_default_ext_name} is implemented then {CRE} becomes writeable, otherwise it is read-only one.

When <<henvcfg_y>>.{CRE}=1 and <<menvcfg_y>>.{CRE}=1 and <<misa_y>>.{CRE}=1, CHERI can be enabled by VS-mode and VU-mode.

When <<henvcfg_y>>.{CRE}=0, CHERI is disabled in VS-mode and VU-mode as described in xref:section_cheri_disable[xrefstyle=short].

NOTE: To allow RV32[IE]/RV64[IE] based guest OSs to run unmodified, the {CRE} bit should be initialized to zero.

[#hedeleg_y,reftext="hedeleg ({cheri_base_ext_name})"]
=== Hypervisor Exception Delegation Register (hedeleg)

Bits {cheri_excep_cause_list} of <<hedeleg_y>> refer to valid CHERI exceptions and so can be used to
delegate CHERI exceptions to a VS-mode guest OS.

[#vsstatus_y,reftext="vsstatus ({cheri_base_ext_name})"]
=== Virtual Supervisor Status Register (vsstatus)

[#vsstatusreg_pte]
.Virtual Supervisor-mode status (*vsstatus*) register when VSXLEN=64
[wavedrom, ,svg,subs=attributes+]
....
{reg: [
  {bits:  1, name: 'WPRI'},
  {bits:  1, name: 'SIE'},
  {bits:  3, name: 'WPRI'},
  {bits:  1, name: 'SPIE'},
  {bits:  1, name: 'UBE'},
  {bits:  1, name: 'WPRI'},
  {bits:  1, name: 'SPP'},
  {bits:  2, name: 'VS[1:0]'},
  {bits:  2, name: 'WPRI'},
  {bits:  2, name: 'FS[1:0]'},
  {bits:  2, name: 'XS[1:0]'},
  {bits:  1, name: 'WPRI'},
  {bits:  1, name: 'SUM'},
  {bits:  1, name: 'MXR'},
  {bits: 12, name: 'WPRI'},
  {bits:  2, name: 'UXL[1:0]'},
  {bits: 25, name: 'WPRI'},
  {bits:  1, name: '{pte_cap_fc_enable}'},
  {bits:  1, name: 'S{pte_cap_crg_pte_name}'},
  {bits:  1, name: 'U{pte_cap_crg_pte_name}'},
  {bits:  1, name: 'WPRI'},
  {bits:  1, name: 'SD'}
], config:{lanes: 4, hspace:1024}}
....

When VSXLEN=64 only:

* UXL and UBE follow the same restrictions as <<mstatus_y>>.UXL and <<mstatus_y>>.UBE respectively.
* The {pte_cap_fc_enable}, S{pte_cap_crg_pte_name} and U{pte_cap_crg_pte_name} fields are defined by <<mstatus_y>>.

[#vstvec_y,reftext="vstvec ({cheri_base_ext_name})"]
=== Virtual Supervisor Trap Vector Base Address Capability Register (vstvec)

The `vstvec` register is widened to a capability.

.Virtual supervisor trap vector base address capability register
include::img/vstveccreg.edn[]

The handling of <<vstvec_y>> is otherwise identical to <<mtvec_y>>, but in VS-mode.

[#vsscratch_y,reftext="vsscratch ({cheri_base_ext_name})"]
=== Virtual Supervisor Scratch Register (vsscratch)

The `vsscratch` register is widened to a capability.

.Virtual supervisor scratch capability register
include::img/vsscratchcreg.edn[]

[#vsepc_y,reftext="vsepc ({cheri_base_ext_name})"]
=== Virtual Supervisor Exception Program Counter Capability (vsepc)

The `vsepc` register is widened to a capability.

The handling of <<vsepc_y>> is identical to <<sepc_y>>, but is in use when V=1 (i.e. applying to <<SRET_CHERI>>).

.Virtual supervisor exception program counter capability
include::img/vsepccreg.edn[]

[#vstidc,reftext="vstidc"]
=== Virtual Supervisor Thread Identifier Capability (vstidc)

The <<vstidc>> register is used to identify the current software thread in VS-mode.
When V=1, <<vstidc>> substitutes for the usual <<stidc>>, so instructions that normally read or modify <<stidc>> actually access <<vstidc>>instead. The contents of <<vstidc>>never directly affect the behavior of the machine.

.Virtual supervisor thread identifier capability register
include::img/vstidcreg.edn[]

ifdef::cheri_xycfg_csr[]

[#vsycfg,reftext="vsycfg"]
=== Virtual Supervisor CHERI Capability Encoding (vsycfg)
The <<vsycfg>> register is used to identify which CHERI capability encoding is used by the platform.
The capability encoding both determines the in-memory representation of a CHERI capability
and entails a set of extensions present atop {cheri_base_ext_name}.
The CSR exists in the _writable_ namespace and all bits are defined to be WARL,
but, absent any future extensions, it is expected that each implementation has exactly one legal value.
For the meaning of the individual fields, refer to the <<uycfg>> register in the unprivileged specification.

.Virtual Supervisor CHERI capability encoding CSR (`vsycfg`) format
[#vsycfg_csr_structure]
include::img/ycfgreg.edn[]

endif::[]

=== "Smstateen/Ssstateen" Integration
The TIDC bit controls access to the <<stidc>> (really <<vstidc>>) CSR.

.Hypervisor State Enable 0 Register (`hstateen0`)
[wavedrom, ,svg,subs=attributes+]
....
{reg: [
{bits: 1, name: 'C'},
{bits: 1, name: 'FCSR'},
{bits: 1, name: 'JVT'},
{bits: 1, name: 'TIDC'},
{bits: 53, name: 'WPRI'},
{bits: 1, name: 'CONTEXT'},
{bits: 1, name: 'IMSIC'},
{bits: 1, name: 'AIA'},
{bits: 1, name: 'CSRIND'},
{bits: 1, name: 'WPRI'},
{bits: 1, name: 'ENVCFG'},
{bits: 1, name: 'SE0'},
], config: {bits: 64, lanes: 4, hspace:1024}}
....

=== Hypervisor Load and Store Instructions For Capability Data

Hypervisor virtual-machine load (<<HLV_CAP>>) and store (<<HSV_CAP>>) are added.
They are analogous to HLV.W and HSV.W but access capability data.

include::insns/hypv-virt-load-cap.adoc[]
include::insns/hypv-virt-store-cap.adoc[]
