[#section_hypervisor_integration]
== Integrating {cheri_base_ext_name} and {cheri_default_ext_name} with the "H" Extension

ifdef::cheri_standalone_spec[]
WARNING: This chapter will appear in the priv spec. Exact location TBD.

The RISC-V hypervisor (H) extension virtualizes the supervisor-level
architecture to support the efficient hosting of guest operating systems atop a
type-1 or type-2 hypervisor cite:[riscv-priv-spec].
endif::[]

The hypervisor extension is
generally orthogonal to CHERI; the main requirements, when integrating with
{cheri_base_ext_name} and {cheri_default_ext_name}, is that address CSRs added
for hypervisors are extended to YLEN size.
The remainder of this chapter describes these changes in detail.

[#hstatus,reftext="hstatus"]
=== Hypervisor Status Register (hstatus)

The <<hstatus>> register operates as described above except
for the VSXL field that controls the value of XLEN for VS-mode (known as
VSXLEN).

The encoding of the VSXL field is the same as the MXL field of **misa**. Only 1
and 2 are supported values for VSXL. When the implementation supports
{cheri_base_ext_name} (but not {cheri_default_ext_name}), then <<hstatus>>'s
VSXL must be read-only as described in xref:mstatus[xrefstyle=short] for
<<mstatus>>.SXL. When the implementation supports both {cheri_base_ext_name}
and {cheri_default_ext_name}, then VSXL behaves as described in
xref:mstatus_y[xrefstyle=short] for mstatus.SXL.

The VSBE field determines controls the endianness of explicit memory accesses
from VS-mode and implicit memory accesses to VS-level memory management data
structures. VSBE=0 indicates little endian and VSBE=1 is big endian. VSBE must
be read-only and equal to MBE when the implementation only supports
{cheri_base_ext_name}.

[#henvcfg_cheri,reftext="henvcfg({cheri_base_ext_name})"]
=== Hypervisor Environment Configuration Register (henvcfg)

The <<henvcfg_cheri>> register operates as described in the RISC-V Privileged
Specification. A new enable bit is added to <<henvcfg_cheri>> when the implementation
supports {cheri_default_ext_name} as shown in xref:henvcfgreg[xrefstyle=short].

.Hypervisor environment configuration register (*henvcfg*)
[#henvcfgreg]
include::img/henvcfgreg.edn[]

The {CRE} bit controls whether explicit access to CHERI
registers is permitted when V=1. When <<henvcfg_cheri>>.{CRE}=1 and <<menvcfg>>.{CRE}=1
and <<misa>>.{CRE}=1, CHERI can be enabled by VS-mode and
VU-mode. When <<henvcfg_cheri>>.{CRE}=0, CHERI is disabled in VS-mode and
VU-mode as described in xref:section_cheri_disable[xrefstyle=short].

The reset value is 0.

[#hedeleg,reftext="hedeleg"]
=== Hypervisor Exception Delegation Register (hedeleg)

Bits {cheri_excep_cause_list} of <<hedeleg>> refer to a valid CHERI exceptions and so can be used to
delegate CHERI exceptions to supervisor mode.

[#vsstatus_y,reftext="vsstatus"]
=== Virtual Supervisor Status Register (vsstatus)

The <<vsstatus_y>> register operates as described above
except for the UXL field that controls the value of XLEN for VU-mode.

The encoding of the UXL field is the same as the MXL field of **misa**. Only 1
and 2 are supported values for UXL. When the implementation supports
{cheri_base_ext_name} (but not {cheri_default_ext_name}), then <<vsstatus_y>>.UXL
must be read-only as described in xref:mstatus[xrefstyle=short] for
<<mstatus>>.UXL. When the implementation supports both {cheri_base_ext_name}
and {cheri_default_ext_name}, then UXL behaves as described in
xref:mstatus_y[xrefstyle=short] for mstatus.UXL.

[#vstvec_y,reftext="vstvec ({cheri_base_ext_name})"]
=== Virtual Supervisor Trap Vector Base Address Capability Register (vstvec)

The `vstvec` register is extended to hold a capability.
Its reset value is a <<root-rx-cap>> capability.

.Virtual supervisor trap vector base address capability register
include::img/vstveccreg.edn[]

The handling of <<vstvec_y>> is otherwise identical to <<mtvec_y>>, but in
virtual supervisor mode.

[#vsscratch_y,reftext="vsscratch ({cheri_base_ext_name})"]
=== Virtual Supervisor Scratch Register (vsscratch)

The `vsscratch` register is extended to hold a capability.

{TAG_RESET_SCSR}

It is not WARL, all capability fields must be implemented.

.Virtual supervisor scratch capability register
include::img/vsscratchcreg.edn[]

[#vsepc_y,reftext="vsepc ({cheri_base_ext_name})"]
=== Virtual Supervisor Exception Program Counter Capability (vsepc)

The `vsepc` register is extended to hold a capability.
Its reset value is a <<root-rx-cap>> capability.

As shown in xref:CSR_exevectors[xrefstyle=short], <<vsepc_y>> is a code capability, so it does not need to be able to hold all possible invalid addresses (see <<section_invalid_addr_conv>>).
Additionally, the capability in <<vsepc_y>> is unsealed when it is written to <<pcc>> on execution of an <<SRET_CHERI>> instruction when V=1.
The handling of <<vsepc_y>> is otherwise identical to <<mepc_y>>, but in VS-mode.

.Virtual supervisor exception program counter capability
include::img/vsepccreg.edn[]

[#vstval,reftext="vstval"]
=== Virtual Supervisor Trap Value Register (vstval)

The <<vstval>> register is a VSXLEN-bit read-write register.

<<vstval>> is updated following the same rules as <<mtval>> for CHERI exceptions
and <<cheri_pte_fault,CHERI page faults>> which are delegated to VS-mode.

.Virtual supervisor trap value register
[#vstval-format]
include::img/vstvalreg.edn[]

[#vstidc,reftext="vstidc"]
=== Virtual Supervisor Thread Identifier Capability (vstidc)

The <<vstidc>> register is used to identify the current software thread in virtual supervisor mode.
It is used to identify the current software thread in
As other Virtual Supervisor registers when V=1, <<vstidc>> substitutes
for <<stidc>>, so that instructions that normally read or modify
<<stidc>> actually access <<vstidc>> instead.
When V=0, <<vstidc>> does not directly affect the
behavior of the machine.
On reset the {ctag} of <<vstidc>> will be set to 0 and the remainder
of the data is UNSPECIFIED.

.Virtual supervisor thread identifier capability register
include::img/vstidcreg.edn[]

[#vsycfg,reftext="vsycfg"]
=== Virtual Supervisor CHERI Capability Encoding (vsycfg)
The <<vsycfg>> register is used to identify which CHERI capability encoding is used by the platform.
The capability encoding both determines the in-memory representation of a CHERI capability
and entails a set of extensions present atop {cheri_base_ext_name}.
The CSR exists in the _writable_ namespace and all bits are defined to be WARL,
but, absent any future extensions, it is expected that each implementation has exactly one legal value.
For the meaning of the individual fields, refer to the <<uycfg>> register in the unprivileged specification.

.Virtual Supervisor CHERI capability encoding CSR (`vsycfg`) format
[#vsycfg_csr_structure]
include::img/ycfgreg.edn[]


=== "Smstateen/Ssstateen" Integration
The new TID bit controls access to the <<vstidc>> CSR.

.Hypervisor State Enable 0 Register (`hstateen0`)
[wavedrom, ,svg,subs=attributes+]
....
{reg: [
{bits: 1, name: 'C'},
{bits: 1, name: 'FCSR'},
{bits: 1, name: 'JVT'},
{bits: 1, name: 'TID'},
{bits: 53, name: 'WPRI'},
{bits: 1, name: 'CONTEXT'},
{bits: 1, name: 'IMSIC'},
{bits: 1, name: 'AIA'},
{bits: 1, name: 'CSRIND'},
{bits: 1, name: 'WPRI'},
{bits: 1, name: 'ENVCFG'},
{bits: 1, name: 'SE0'},
], config: {bits: 64, lanes: 4, hspace:1024}}
....

=== Hypervisor Load and Store Instructions For Capability Data

Hypervisor virtual-machine load (<<HLV_CAP>>) and store (<<HSV_CAP>>)
instructions read or write YLEN bits from memory as though V=1. These
instructions change behavior depending on the CHERI execution mode although
the instruction's encoding remains unchanged.

When in {cheri_cap_mode_name}, the hypervisor
load and store capability instructions behave as described in
xref:section_existing_riscv_insns[xrefstyle=short]. In
{cheri_int_mode_name}, the instructions use the low XLEN bits of the base register as the effective address for the memory access and the capability authorizing the memory access is <<ddc>>.

ifdef::cheri_standalone_spec[]
include::insns/hypv-virt-load-cap.adoc[]
include::insns/hypv-virt-store-cap.adoc[]
endif::[]
