== Introduction

ifdef::cheri_standalone_spec[]
WARNING: This chapter is only included in the standalone CHERI spec and not part of the integrated document.
endif::[]

=== CHERI Concepts and Terminology

Current CPU architectures (including RISC-V) allow memory access solely by
specifying and dereferencing a memory address stored as an integer value in
a register or in memory. Any accidental or malicious action that modifies
such an integer value can result in unrestricted access to the memory that
it addresses. Unfortunately, this weak memory protection model has resulted
in the majority of software security vulnerabilities present in software
today.

CHERI enables software to efficiently implement fine-grained memory protection
and scalable software compartmentalization by providing strong, efficient
hardware mechanisms to support software execution and enable it to prevent
and mitigate vulnerabilities.

Design goals include incremental adoptability from current ISAs and software
stacks, low performance overhead for memory protection, significant performance
improvements for software compartmentalization, formal grounding, and
programmer-friendly underpinnings. It has been designed to provide strong,
non-probabilistic protection rather than depending on short random numbers or
truncated cryptographic hashes that can be leaked and reinjected, or that could
be brute forced.

=== CHERI Extensions to RISC-V

This specification is based on publicly available documentation including
CHERI v9 cite:[cheri-v9-spec] and CHERI Concentrate cite:[woodruff2019cheri]. It defines the following
extensions to support CHERI alongside RISC-V

==== Extensions to the unprivileged specification

<<rv32y,{cheri_base_ext_name}>>:: Unprivileged specification for {cheri_base_ext_name} to support CHERI.
<<SENTRY,{rvy_sentry_ext_name}>>:: Unprivileged extension for sentry support, for CFI.
<<section_cheri_hybrid_ext,{cheri_default_ext_name}>>:: Unprivileged extension to support switching <<cheri_execution_mode>>.

The following extension is useful independently of CHERI:

<<abhlrsc_ext,{lr_sc_bh_ext_name}>>:: Addition of LR.B, LR.H, SC.B, SC.H for more accurate atomic locking as the memory ranges are restricted by using bounds, therefore precise locking is needed.

==== Privileged specifications

The following privileged specifications are updated for {cheri_base_ext_name}:

<<section_priv_cheri,{cheri_priv_m_ext}>>:: Machine-Level Privileged specification to support CHERI (implies, and required by, Machine-Level ISA).
<<section_priv_cheri,{cheri_priv_s_ext}>>:: Supervisor-Level Privileged specification to support CHERI (implies, and required by, Supervisor-Level ISA).
<<section_priv_cheri_vmem,{cheri_priv_vmem_ext}>>:: Privileged specification for integrating CHERI with virtual memory (implies, and required by, by Sv39).
<<section_priv_cheri,{cheri_priv_h_ext}>>:: Privileged specification to integrate CHERI with the Hypervisor extensions (implies, and required by, H).

The following privileged extensions are added for {cheri_base_ext_name}:

ifdef::support_varxlen[]
<<section_cheri_dyn_xlen,{cheri_priv_m_dyn_xlen_ext}>>:: Privileged extension to allow dynamic XLEN and endianness changes.
endif::support_varxlen[]
<<section_cheri_priv_crg_ext,{cheri_priv_crg_ext}>>^1^:: CHERI extension for capability revocation on RISC-V harts supporting page-based virtual-memory (implies {cheri_priv_vmem_ext}).

^1^ {cheri_priv_crg_load_tag_ext} is available for improved software revocation performance if {cheri_priv_crg_ext} is implemented.

==== Debug specifications (#need to move to a separate document#)

<<section_debug_integration_ext,Sdext ({cheri_base_ext_name})>>:: Debug specification for integrating CHERI with external debug mode (implies, and required by, Sdext).
<<section_debug_integration_trig,{cheri_priv_debug_trig}>>:: Debug specification for integrating CHERI with debug triggers (implies, and required by, Sdtrig).

CAUTION: The extension names are provisional and subject to change.

==== Extension and specification status

.Unprivileged {cheri_base_ext_name} extension and specification status and summary
[#unpriv-extension-status,reftext="Extension Status and Summary"]
[options=header,align=center,width="90%",cols="25,15,52"]
|=============================================================================================================================================================
| Extension                                                 | Status        | Comment
|<<rv32y,{cheri_base_ext_name}>>                            | Stable        | This extension is a candidate for freezing
|<<SENTRY,{rvy_sentry_ext_name}>>                           | Stable        | This extension is a candidate for freezing
|<<section_cheri_hybrid_ext,{cheri_default_ext_name}>>      | Stable        | This extension is a candidate for freezing
|=============================================================================================================================================================

.Other unprivileged extension status and summary (used by CHERI software), status and summary
[#zabhlrsc_unpriv-extension-status,reftext="Extension Status and Summary"]
[options=header,align=center,width="90%",cols="25,15,52"]
|=============================================================================================================================================================
| Extension                                                 | Status        | Comment
|<<abhlrsc_ext,     {lr_sc_bh_ext_name}>>                   | Stable        | This extension is a candidate for freezing
|=============================================================================================================================================================

.Privileged extension and specification status and summary
[#priv-extension-status,reftext="Extension Status and Summary"]
[options=header,align=center,width="90%",cols="25,15,52"]
|=============================================================================================================================================================
| Extension                                                 | Status        | Comment
|<<section_priv_cheri,{cheri_priv_m_ext}>>                  | Stable        | This specification is a candidate for freezing
|<<section_priv_cheri,{cheri_priv_s_ext}>>                  | Stable        | This specification is a candidate for freezing
|<<section_cheri_disable,{cheri_priv_m_reg_enable_ext}>>    | Stable        | This extension is a candidate for freezing
ifdef::support_varxlen[]
|<<section_cheri_dyn_xlen,{cheri_priv_m_dyn_xlen_ext}>>     | Stable        | This extension is a candidate for freezing
endif::support_varxlen[]
|<<section_priv_cheri_vmem,{cheri_priv_vmem_ext}>>          | Stable        | This specification is a candidate for freezing
|<<section_debug_integration_ext,Sdext ({cheri_base_ext_name})>>   | Stable | This specification is a candidate for freezing
|<<section_debug_integration_trig,{cheri_priv_debug_trig}>> | Stable        | This specification is a candidate for freezing
|<<section_priv_cheri,{cheri_priv_h_ext}>>                  | Stabilizing   | This specification is a candidate for freeze, software evaluation currently ongoing
|<<section_cheri_priv_crg_ext,    {cheri_priv_crg_ext}>>^1^ | Stabilizing   | This extension is a candidate for freeze, software evaluation currently ongoing
|=============================================================================================================================================================

{cheri_base_ext_name} is defined as the base ISA that all CHERI RISC-V implementations must support.
{cheri_default_ext_name} and {cheri_priv_crg_ext} are examples of optional extensions in addition to
{cheri_base_ext_name}.

We refer to software as _purecap_ if it utilizes CHERI capabilities for all
memory accesses -- including loads, stores and instruction fetches -- rather
than integer addresses. Purecap software requires the CHERI RISC-V hart to
support {cheri_base_ext_name}. We refer to software as _hybrid_ if it uses
integer addresses *or* CHERI capabilities for memory accesses. Hybrid software
requires the CHERI RISC-V hart to support {cheri_base_ext_name} and
{cheri_default_ext_name}.

See xref:app_cheri_instructions[xrefstyle=short] for compatibility with other RISC-V
extensions.

=== Risks and Known Uncertainty

* All extensions could be divided up differently in the future, including after
ratification
* The RISC-V Architecture Review Committee (ARC) are likely to update all
encodings
* The ARC are likely to update all CSR addresses
* Instruction mnemonics may be renamed
    ** Any changes will affect assembly code, but assembler aliases can provide
backwards compatibility

==== Partially Incompatible Extensions

There are RISC-V extensions in development that may duplicate some aspects of
CHERI functionality or directly conflict with CHERI and should only be
available in {cheri_int_mode_name} on a CHERI-enabled hart.
These include:

* RISC-V CFI specification
* "J" Pointer Masking (see xref:section_pointer_masking_integration[xrefstyle=short]).
