== Introduction

ifdef::cheri_standalone_spec[]
WARNING: This chapter is only included in the standalone CHERI spec and not part of the integrated document.
endif::[]

=== CHERI Concepts and Terminology

Current CPU architectures (including RISC-V) allow memory access solely by
specifying and dereferencing a memory address stored as an integer value in
a register or in memory. Any accidental or malicious action that modifies
such an integer value can result in unrestricted access to the memory that
it addresses. Unfortunately, this weak memory protection model has resulted
in the majority of software security vulnerabilities present in software
today.

CHERI enables software to efficiently implement fine-grained memory protection
and scalable software compartmentalization by providing strong, efficient
hardware mechanisms to support software execution and enable it to prevent
and mitigate vulnerabilities.

Design goals include incremental adoptability from current ISAs and software
stacks, low performance overhead for memory protection, significant performance
improvements for software compartmentalization, formal grounding, and
programmer-friendly underpinnings. It has been designed to provide strong,
non-probabilistic protection rather than depending on short random numbers or
truncated cryptographic hashes that can be leaked and reinjected, or that could
be brute forced.

=== CHERI Extensions to RISC-V

This specification is based on publicly available documentation including
cite:[cheri-v9-spec] and cite:[woodruff2019cheri]. It defines the following
extensions to support CHERI alongside RISC-V

==== Extensions to the unprivileged specification

<<cheri_base_ext,{cheri_base_ext_name}>>:: Introduces key, minimal CHERI concepts and features to
the RISC-V ISA. The resulting extended ISA is not
backwards-compatible with RISC-V.
<<cheri_default_ext,{cheri_default_ext_name}>>:: Extends {cheri_base_ext_name} with features to ensure
that the ISA extended with CHERI allows backwards binary compatibility with
RISC-V.
<<tid_ext,{tid_ext_name}>>:: Extension for supporting thread identifiers. This extension
improves software compartmentalization on CHERI systems.
<<cheri_levels_ext,{cheri_levels_ext_name}>>:: Extension for supporting capability flow control.
This extension allows limiting storing of capabilities to specific regions and can be used e.g. for safer data sharing between compartments.

The following two extensions are useful independent of CHERI:

<<sh4add_ext,{sh4add_ext_name}>>:: Addition of <<SH4ADD>> and <<SH4ADD_UW>> for RV64 only, as CHERI capabilities are 16 bytes when XLEN=64
<<lr_sc_bh_ext,{lr_sc_bh_ext_name}>>:: Addition of <<LR_B>>, <<LR_H>>, <<SC_B>>, <<SC_H>> for more accurate atomic locking as the memory ranges are restricted by using bounds, therefore precise locking is needed.

==== Extensions to the privileged specification
The following extensions are added to the privleged specification

<<section_priv_cheri,{cheri_priv_m_ext}>>:: Machine-Level Privileged extension to support CHERI.
<<section_priv_cheri,{cheri_priv_s_ext}>>:: Supervisor-Level Privileged extension to support CHERI.
<<section_priv_cheri_vmem,{cheri_priv_vmem_ext}>>:: Privileged extension for integrating CHERI with virtual memory.
<<section_priv_cheri,{cheri_priv_h_ext}>>:: Privileged extension to integrate CHERI with the Hypervisor extensions.
<<section_cheri_disable,{cheri_priv_m_reg_enable_ext}>>:: Privileged extension to disable explicit access to CHERI registers and instructions.
<<section_cheri_dyn_xlen,{cheri_priv_m_dyn_xlen_ext}>>:: Privileged extension to allow dynamic XLEN and endianness changes.
<<section_cheri_priv_crg_ext,{cheri_priv_crg_ext}>>:: CHERI extension for RISC-V harts supporting page-based
virtual-memory.

CAUTION: The extension names are provisional and subject to change.

.Extension status and summary
[#extension-status,reftext="Extension Status and Summary"]
[options=header,align=center,width="90%",cols="25,23,52"]
|==============================================================================
| Extension                                        | Status        | Comment
|<<cheri_base_ext,   {cheri_base_ext_name}>>        | Stable        | This extension is a candidate for freezing
|<<cheri_default_ext,{cheri_default_ext_name}>>     | Stable        | This extension is a candidate for freezing
|<<sh4add_ext,       {sh4add_ext_name}>>            | Stable        | This extension is a candidate for freezing
|<<lr_sc_bh_ext,     {lr_sc_bh_ext_name}>>          | Stable        | This extension is a candidate for freezing
|<<section_priv_cheri,{cheri_priv_m_ext}>>          | Stable        | This extension is a candidate for freezing
|<<section_priv_cheri,{cheri_priv_s_ext}>>          | Stable        | This extension is a candidate for freezing
|<<section_cheri_disable,{cheri_priv_m_reg_enable_ext}>> | Stable        | This extension is a candidate for freezing
|<<section_cheri_dyn_xlen,{cheri_priv_m_dyn_xlen_ext}>> | Stable        | This extension is a candidate for freezing
|<<section_priv_cheri_vmem,{cheri_priv_vmem_ext}>> | Stable        | This extension is a candidate for freezing
|<<section_priv_cheri,{cheri_priv_h_ext}>>          | Stabilizing   | This extension is a candidate for freeze, software evaluation currently ongoing
|<<section_cheri_priv_crg_ext,    {cheri_priv_crg_ext}>>         | Stabilizing   | This extension is a candidate for freeze, software evaluation currently ongoing
|<<tid_ext,          {tid_ext_name}>>               | Stabilizing   | This extension is a candidate for freeze, software evaluation currently ongoing
|<<cheri_levels_ext, {cheri_levels_ext_name}>> with `LVLBITS=1` | Stabilizing   | This extension is a candidate for freeze, software evaluation currently ongoing
|==============================================================================

{cheri_base_ext_name} is defined as the base extension which all CHERI RISC-V
implementations must support. {cheri_default_ext_name}
and {cheri_priv_crg_ext} are optional extensions in addition to
{cheri_base_ext_name}.

We refer to software as _purecap_ if it utilizes CHERI capabilities for all
memory accesses -- including loads, stores and instruction fetches -- rather
than integer addresses. Purecap software requires the CHERI RISC-V hart to
support {cheri_base_ext_name}. We refer to software as _hybrid_ if it uses
integer addresses *or* CHERI capabilities for memory accesses. Hybrid software
requires the CHERI RISC-V hart to support {cheri_base_ext_name} and
{cheri_default_ext_name}.

See xref:app_cheri_instructions[xrefstyle=short] for compatibility with other RISC-V
extensions.

=== Risks and Known Uncertainty

* All extensions could be divided up differently in the future, including after
ratification
* The RISC-V Architecture Review Committee (ARC) are likely to update all
encodings
* The ARC are likely to update all CSR addresses
* Instruction mnemonics may be renamed
    ** Any changes will affect assembly code, but assembler aliases can provide
backwards compatibility

==== Partially Incompatible Extensions

There are RISC-V extensions in development that may duplicate some aspects of
CHERI functionality or directly conflict with CHERI and should only be
available in {cheri_int_mode_name} on a CHERI-enabled hart.
These include:

* RISC-V CFI specification
* "J" Pointer Masking (see xref:section_pointer_masking_integration[xrefstyle=short]).
