ifdef::cheri_standalone_spec[]
[#section_cheri_pointer_masking_integration, reftext="Ssnpm, Smnpm, Smmpm, Sspm, Supm ({cheri_base_ext_name})"]
== Pointer Masking (Ssnpm, Smnpm, Smmpm, Sspm, Supm)  ({cheri_base64_ext_name})

endif::[]

IMPORTANT: {not_v1_ratification_package_experimental}

When PMM!=0 pointer masking is enabled, the "ignore" transformation is always applied _before_ bounds are decoded.

Therefore:

* <<pcc>> bounds checks are unaffected, as pointer masking does not affect the PC.
** Therefore no ignore transformation is applied before the checks on writing to __xtvec__.
* The ignore transformation is applied _before_ memory access bounds decoding.
* Instructions which handle capability addresses and/or bounds apply the ignore transformation _before_ processing the input. If the output is a capability the output address is determined first and the upper PMLEN bits from the input address are copied to the output address afterwards.
** If instructions take more than one capability source operand, then the specific instruction needs to specify _which_ input the PMLEN upper bits are copied from.

In summary, for the base ISA:

* <<CADD>>, <<CADDI>>, <<SCADDR>>, <<SCBNDS>>, <<SCBNDSI>>, <<SCBNDSR>> all apply the ignore transformation before processing the input and propagate the upper PMLEN bits from the input address to the output address.
* <<GCBASE>>, <<GCLEN>>, <<GCTOP>> all apply the ignore transformation before processing the input and so report integer values based upon bounds decoded using the transformed addresses.
* <<CBLD>>, <<YSUNSEAL>> copy the upper PMLEN bits of `{cs2}` to `{cd}`

NOTE: Because dynamically changing the number of masked bits changes the interpretation of a capability,
software must take the same care when sharing capabilities between address spaces with differing pointer masking
as it generally must when sharing capabilities between address spaces with different page mappings.

NOTE: Because <<pcc>> bounds aren't masked but data memory access bounds are, if the PMLEN upper bits of a capability address is modified by the ignore transformation then the capability will only be usable for data memory access, as the address will be invalid for instruction fetch.
