ifdef::cheri_standalone_spec[]
[#section_cheri_pointer_masking_integration, reftext="Ssnpm, Smnpm, Smmpm, Sspm, Supm ({cheri_base_ext_name})"]
== Pointer Masking (Ssnpm, Smnpm, Smmpm, Sspm, Supm)  ({cheri_base64_ext_name})

endif::[]

IMPORTANT: {not_v1_ratification_package_experimental}

Pointer masking is enabled when PMM{ne}0 and applies to data memory access but not instruction memory access.

NOTE:  The "ignore" transformation has a dependency on the current virtual memory translation scheme, i.e. `satp.MODE`.

=== <<pcc>> checks

<<pcc>> bounds checks are unaffected, as pointer masking does not affect the PC.

Therefore no ignore transformation is applied before the checks on writing to __xtvec__.

=== Capability Address Increment or Replacement Instructions

Instructions which derive a new capability by incrementing or replacing the capability address all determine the output address without taking pointer masking into account.

The associated representability check, however, does use the ignore transformation.

The rule from xref:section_rep_check_concept[xrefstyle=short] states that:

_All instructions that derive a capability with a new address (such as <<SCADDR>>, <<CADD>>, and <<CADDI>>) must check that the new address does not change the decoding of the bounds._

This rule is extended to support pointer masking by applying the ignore transformation to both the original and new addresses, and checking that the transformed new address does not change the decoding of the bounds.
If the bounds decoding does change then the output capability is invalidated.

=== Interaction With Bounds Setting Instructions

Bounds setting instructions only calculate new values for the capability metadata and {ctag}, the address field is copied directly from input to output.

The ignore transformation is applied to the address before calculating the new bounds.

This affects <<SCBNDS>>, <<SCBNDSI>>, and <<SCBNDSR>>.

If {rvy_bndsrdw_insn_ext_name} is implemented, <<SCBNDSRD>> follows the same rule.

=== Interaction With Memory Access Instructions

The ignore transformation is applied before capability bounds calculations, so that the bounds for memory accesses are calculated relative to the transformed address.

This affects all loads, stores and AMOs.

=== Interaction With Bounds Reading Instructions

The ignore transformation is applied before capability bounds reading instructions, so that all returned values are based upon the transformed address.

This affects <<GCBASE>>, <<GCLEN>>, and <<GCTOP>>.

=== Interaction With Capability Subsets

The definition of <<cap_subset>> is extended to apply the transformation to both `cap1` and `cap2` before the bounds calculation.

This affects <<CBLD>>, <<SCSS>> and <<YSUNSEAL>>.

WARNING: Because dynamically changing the number of masked bits changes the interpretation of a capability,
software must take the same care when sharing capabilities between address spaces with differing pointer masking settings as it generally must when sharing capabilities between address spaces with different page mappings.

WARNING: Because <<pcc>> bounds aren't masked but data memory access bounds are, if the PMLEN upper bits of a capability address are modified by the ignore transformation then the capability will only be usable for data memory access, as the address will be invalid for instruction fetch.

WARNING: A capability with its address in the illegal VA space while PMM=0 will have its address and bounds move into the valid VA space if PMM is subsequently set to a nonzero value.
Such a capability is only possible if capabilities are available which have at least some of the gap between valid VA spaces in their representable ranges.
It is recommended that software should not create such capabilities.

WARNING: Disabling translation affects the ignore transformation and so would relocate capabilities from the upper VA space where the upper bits are all one to the lower VA space where the upper bits are all zero.
Disabling translation also treats all addresses as physical which changes the interpretation, so this problem is not specific to pointer masking.
