[#section_priv_cheri]
== "Machine/Supervisor-Level ISA ({cheri_base_ext_name})" Extensions, Version 1.0

ifdef::cheri_standalone_spec[]
WARNING: This chapter will appear in the priv spec. Exact location TBD.
endif::[]

This chapter describes integration of {cheri_base_ext_name} with the RISC-V privileged architecture.

=== Machine-Level CSRs added or extended by {cheri_base_ext_name}

{cheri_base_ext_name} extends some M-mode CSRs to hold capabilities or
otherwise add new functions. <<asr_perm>> in the <<pcc>> is always required for access
to privileged CSRs.

[#mtvec_y,reftext="mtvec ({cheri_base_ext_name})"]
==== Machine Trap Vector Base Address Capability Register (mtvec)

The <<mtvec>> register is extended to hold a code capability.
Its reset value is nominally a <<root-rx-cap>> capability.

NOTE: <<mtvec_y>> exists in all CHERI implementations, and so may be used as a source of a <<root-rx-cap>> capability after reset.

.Machine-mode trap-vector base-capability register
include::img/mtveccreg.edn[]

The fields in the metadata are WARL as many fields can be implemented as constants.

NOTE: Examples of WARL behavior include always setting <<x_perm>> to 1 and setting the reserved fields to zero, otherwise the capability is unusable.
 Another example is to partially or fully restrict the bounds to constant values.

NOTE: Care must be taken however that suitable root capabilities are available to software after reset if this CSR does not represent one.

When traps are taken into machine mode, the pc is updated following the standard `mtvec` behavior.
The {ctag} and metadata from <<mtvec_y>> are also written to the <<pcc>>.

Following the standard `mtvec` behavior, the value of `mtvec.address` can be viewed with a range of different addresses:

. The MODE field is included in `mtvec.address[1:0]` but it does not form part of the trap vector address.
. When MODE=Vectored, the trap vector address is incremented by four times the interrupt number.
. CSR reads include MODE in `mtvec.address[1:0]`.

`HICAUSE` is defined to be the largest interrupt cause value that the implementation can write
to `__x__cause` when an interrupt is taken.

Therefore the minimum observable address is `mtvec.address & ~3` and the maximum is `(mtvec.address & ~3) + 4 x HICAUSE`.

All possible observable values must be in the <<section_cap_representable_check>>.
Software must ensure this is true when writing to <<mtvec_y>>, and the hardware sets the {ctag} to zero if any values are out of the <<section_cap_representable_check>>.

NOTE: Modifying the address of any capability outside of the <<section_cap_representable_check>> without clearing the {ctag} causes a security hole as the interpretation of the bounds changes.
Therefore requiring that all possible observable addresses are representable but not necessary in bounds is the minimum security requirement.

<<mtvec_y>> is always updated using the semantics of the <<SCADDR>> instruction and so writing a sealed capability will cause the {ctag} to be set to zero.

NOTE: The capability in <<mtvec_y>> is _not_ unsealed when it is written to <<pcc>>, unlike other executing from other CSRs such as <<mepc_y>>.

<<mtvec_y>> follows the rule from `mtvec` about not needing to be able to hold all possible invalid addresses (see <<section_invalid_addr_conv>>).

[#mscratch_y, reftext="mscratch ({cheri_base_ext_name})"]
==== Machine Scratch Capability Register (mscratch)

The <<mscratch>> register is extended to hold a capability.

{TAG_RESET_MCSR}

It is not WARL, all capability fields must be implemented.

.Machine-mode scratch capability register
include::img/mscratchcreg.edn[]

[#mepc_y,reftext="mepc ({cheri_base_ext_name})"]
==== Machine Exception Program Counter Capability (mepc)

The <<mepc>> is extended to hold a capability.
Its reset value is nominally a <<root-rx-cap>> capability.

.Machine exception program counter capability register
include::img/mepccreg.edn[]

`mepc.address` is the `mepc` CSR, and so the follows the standard rules meaning that:

.  `mepc.address[0]=0`, and
.  `mepc.address[1]=0` when IALIGN is fixed to 32
.  `mepc.address[1]` reads as zero when IALIGN is programmable and is set to 32

As listed above for <<mtvec_y>>, this means that `mepc.address` can represent multiple different values.
Therefore software must ensure that all possible values are in the <<section_cap_representable_check>> on writing, otherwise the hardware sets the written {ctag} to zero.

Sealed capabilities may be written to <<mepc_y>>.
The {ctag} is set to zero on writing if:

.  `mepc.address[0]=1`, or
.  `mepc.address[1]=1` when IALIGN=32

In the following case the value of the {ctag} observable in the CSR depends on the value of IALIGN:

. <<mepc_y>> is sealed, the {ctag} is set, and
. `mepc.address[1]=1` and IALIGN=16 when writing the CSR

The {ctag} is zero then IALIGN=32 when reading the CSR, or executing <<MRET_CHERI>>, and the {ctag} is one when IALIGN=16.

When a trap is taken into M-mode, the pc is written to `mepc.address` following the standard behavior.
The {ctag} and metadata of the <<pcc>> are also written to <<mepc_y>>.

On execution of an <<MRET_CHERI>> instruction, the capability value from <<mepc_y>> is unsealed and written to <<pcc>>.

<<mepc_y>> follows the rule from `mepc` about not needing to be able to hold all possible invalid addresses (see <<section_invalid_addr_conv>>).

[#mtidc,reftext="mtidc"]
==== Machine Thread Identifier Capability (mtidc)

The <<mtidc>> register is used to identify the current software thread in machine mode, using the method defined in the section for the unprivileged <<utidc>> CSR.
On reset the {ctag} of <<mtidc>> will be set to zero and the remainder
of the data is UNSPECIFIED.

.Machine thread identifier capability register
include::img/mtidcreg.edn[]

[#mycfg,reftext="mycfg"]
==== Machine CHERI Capability Encoding (mycfg)
The <<mycfg>> register is used to identify which CHERI capability encoding is used by the platform.
The capability encoding both determines the in-memory representation of a CHERI capability
and entails a set of extensions present atop {cheri_base_ext_name}.
The CSR exists in the _writable_ namespace and all bits are defined to be WARL,
but, absent any future extensions, it is expected that each implementation has exactly one legal value.
For the meaning of the individual fields, refer to the <<uycfg>> register in the unprivileged specification.

.Machine CHERI capability encoding CSR (`mycfg`) format
[#mycfg_csr_structure]
include::img/ycfgreg.edn[]

=== Machine-Level CSRs modified by {cheri_base_ext_name}

[#mstatus_y, reftext="mstatus ({cheri_base_ext_name})"]
==== Machine Status Registers (mstatus and mstatush)

The *mstatus* and *mstatush* registers operate as described in
<<mstatus_y>> with two restrictions:

* The <<xlen-control, MXL, SXL and UXL>> fields that control the
value of XLEN for S-mode and U-mode must be read-only and equal to MXL in {cheri_base_ext_name} implementations.
  Only 1 and 2 are supported values.

* The <<endianness-control,MBE, SBE, and UBE>> fields that control the memory system endianness for M-mode, S-mode, and U-mode must be read-only in {cheri_base_ext_name} implementations.
   SBE and UBE must be read only and equal to MBE, if S-mode or
U-mode, respectively, is implemented, or read-only zero otherwise.

Changing XLEN or endianness would change the interpretation of all in-memory capabilities, so allowing these fields to change at runtime is prohibited.

NOTE: These restrictions may be relaxed by a future extension. Such an extension is likely to enforce the constraint that any privilege level with XLEN less than MXLEN has CHERI disabled.

MXR has no effect on the CHERI permission checking.

NOTE: CHERI does not need to make use execute only memory for security reasons, and so MXR has no relevance.
 Additionally the 32-bit encoding format does not allow <<x_perm>> to be encoded without <<r_perm>>.

[#mcause_y, reftext="mcause ({cheri_base_ext_name})"]
==== Machine Cause Register (mcause)

{cheri_base_ext_name} adds new exception codes for CHERI exceptions that <<mcause>> must be able to represent.
The new exception codes and priorities are listed in
xref:mcauses[xrefstyle=short] and xref:exception-priority-cheri[xrefstyle=short] respectively.

[[exception-priority-cheri]]
.Synchronous exception priority in decreasing priority order. Entries added in {cheri_base_ext_name} are in *bold*
[float="center",align="center",cols="<1,>1,<8",options="header"]
|===
|Priority |Exc.Code |Description
|_Highest_ |3 |Instruction address breakpoint
| .>|*{cheri_excep_cause_pc}* .<|*Prior to instruction address translation:* +
*{cheri_excep_name_pc} due to {pcc} checks ({ctag}, execute permission, bounds^1^)*
| .>|12, 1 .<|During instruction address translation: +
First encountered page fault or access fault
| .>|1 .<|With physical address for instruction: +
Instruction access fault

| .>|2 +
*{cheri_excep_cause_pc}* +
0 +
8,9,11 +
3 +
3 .<|Illegal instruction +
*{cheri_excep_name_pc} due to {pcc} <<asr_perm>> clear* +
Instruction address misaligned +
Environment call +
Environment break +
Load/store/AMO address breakpoint

| .>|*{cheri_excep_cause_ls_list}* .<|*Prior to address translation for an explicit memory access:* +
*{cheri_excep_name_ld}, {cheri_excep_name_st} due to capability checks ({ctag}, sealed, permissions, bounds)*
| .>|4,6 .<|*Load/store/AMO capability address misaligned* +
Optionally: +
Load/store/AMO address misaligned
| .>|*{cheri_excep_cause_pte_ld}, {cheri_excep_cause_pte_st},* 13, 15, 5, 7 .<|During address translation for an explicit memory access: +
First encountered *{cheri_excep_name_pte_ld}^2^, {cheri_excep_name_pte_st}*, page fault or access fault
| .>|5,7 .<|With physical address for an explicit memory access: +
Load/store/AMO access fault
| .>|4,6 .<|If not higher priority: +
Load/store/AMO address misaligned
.>|_Lowest_ .>|*{cheri_excep_cause_pte_ld}* .<|*If not higher priority: +
{cheri_excep_name_pte_ld}^3^*
|===

^1^ {pcc} bounds are checked against all bytes of fetched instructions.
 If the instructions could not be decoded to determine the length, then the <<pcc>> bounds check is made against the minimum sized instruction supported by the implementation which can be executed, when prioritizing against Instruction Access Faults.

^2^ The higher priority {cheri_excep_name_pte_ld} covers capability loads or atomics where the loaded {ctag} _is not_ checked ({cheri_priv_crg_ext} is implemented) .

^3^ The lower priority {cheri_excep_name_pte_ld} covers capability loads or atomics where the loaded {ctag} _is_ checked ({cheri_priv_crg_load_tag_ext} is implemented).

NOTE: The full details of the CHERI exceptions are in xref:cheri_exception_combs_descriptions[xrefstyle=short].

ifdef::cheri_standalone_spec[]
==== Machine Trap Delegation Register (medeleg)

Bits {cheri_excep_cause_list} of <<medeleg>> refer to a valid CHERI exception and so can be used to
delegate CHERI exceptions to supervisor mode.

[[mtval_y]]
==== Machine Trap Value Register (mtval)

ifdef::cheri_v9_annotations[]
WARNING: *CHERI v9 Note:* Encoding and values changed, and generally were
simplified.
endif::[]

For all CHERI faults, <<mtval>> is written with the MXLEN-bit effective address which caused the fault.

.Machine trap value register
[#mtval-format]
include::img/mtvalreg.edn[]

==== "Smstateen/Ssstateen" Integration
The TID bit in `mstateen0` controls access to the <<stidc>> CSR.

.Machine State Enable 0 Register (`mstateen0`)
[wavedrom, ,svg,subs=attributes+]
....
{reg: [
{bits: 1, name: 'C'},
{bits: 1, name: 'FCSR'},
{bits: 1, name: 'JVT'},
{bits: 1, name: 'TID'},
{bits: 52, name: 'WPRI'},
{bits: 1, name: 'P1P13'},
{bits: 1, name: 'CONTEXT'},
{bits: 1, name: 'IMSIC'},
{bits: 1, name: 'AIA'},
{bits: 1, name: 'CSRIND'},
{bits: 1, name: 'WPRI'},
{bits: 1, name: 'ENVCFG'},
{bits: 1, name: 'SE0'},
], config: {bits: 64, lanes: 4, hspace:1024}}
....

endif::[]

[#supervisor-level-csrs-section]
=== Supervisor-Level CSRs added or extended by {cheri_base_ext_name}

{cheri_base_ext_name} extends some of the existing RISC-V CSRs to be able to
hold capabilities or with other new functions. <<asr_perm>> in the <<pcc>> is required for access to all privileged CSRs.

[#stvec_y,reftext="stvec ({cheri_base_ext_name})"]
==== Supervisor Trap Vector Base Address Capability Register (stvec)

The <<stvec>> register is extended to hold a capability.

{ROOT_RX_RESET_SCSR}

.Supervisor trap-vector base-capability register
include::img/stveccreg.edn[]

The handling of <<stvec_y>> is otherwise identical to <<mtvec_y>>, but in supervisor mode.

[#sscratch_y, reftext="sscratch ({cheri_base_ext_name})"]
==== Supervisor Scratch Capability Register (sscratch)

The <<sscratch>> register is extended to hold a capability.

{TAG_RESET_SCSR}

It is not WARL, all capability fields must be implemented.

.Supervisor scratch capability register
include::img/sscratchcreg.edn[]

[#sepc_y,reftext="sepc ({cheri_base_ext_name})"]
==== Supervisor Exception Program Counter Capability (sepc)

The <<sepc>> register is extended to hold a capability.

{ROOT_RX_RESET_SCSR}

As shown in xref:CSR_exevectors[xrefstyle=short], <<sepc_y>> is a code capability, so it does not need to be able to hold all possible invalid addresses (see <<section_invalid_addr_conv>>).
Additionally, the capability in <<sepc_y>> is unsealed when it is written to <<pcc>> on execution of an <<SRET_CHERI>> instruction.
The handling of <<sepc_y>> is otherwise identical to <<mepc_y>>, but in supervisor mode.

.Supervisor exception program counter capability register
include::img/sepccreg.edn[]

[#stidc,reftext="stidc"]
==== Supervisor Thread Identifier Capability (stidc)

The <<stidc>> register is used to identify the current software thread in supervisor mode, using the method defined in the section for the unprivileged <<utidc>> CSR.

{TAG_RESET_SCSR}

.Supervisor thread identifier capability register
include::img/stidcreg.edn[]

[#sycfg,reftext="sycfg"]
==== Supervisor CHERI Capability Encoding (sycfg)
The <<sycfg>> register is used to identify which CHERI capability encoding is used by the platform.
The capability encoding both determines the in-memory representation of a CHERI capability
and entails a set of extensions present atop {cheri_base_ext_name}.
The CSR exists in the _writable_ namespace and all bits are defined to be WARL,
but, absent any future extensions, it is expected that each implementation has exactly one legal value.
For the meaning of the individual fields, refer to the <<uycfg>> register in the unprivileged specification.

.Supervisor CHERI capability encoding CSR (`sycfg`) format
[#sycfg_csr_structure]
include::img/ycfgreg.edn[]

=== Supervisor-Level CSRs modified by {cheri_base_ext_name}
ifdef::cheri_standalone_spec[]
==== Supervisor Cause Register (scause)

{cheri_base_ext_name} adds new exception codes for CHERI exceptions that <<scause>> must be able to represent.
The new exception code is listed in xref:scauses[xrefstyle=short].
The behavior and usage of <<scause>> otherwise remains as described in xref:scause[xrefstyle=short].

See <<mcause_y>> for the new exceptions priorities when {cheri_base_ext_name} is implemented.

[[stval-cheri]]
==== Supervisor Trap Value Register (stval)

<<stval>> is updated following the same rules as <<mtval_y>> for CHERI exceptions
and <<cheri_pte_fault,CHERI page faults>> which are delegated to HS-mode or S-mode.


==== "Smstateen/Ssstateen" Integration
The TID (thread ID) bit in `sstateen0` controls access to the <<utidc>> CSR.
See <<utidc>> for a description of the usage.

.Supervisor State Enable 0 Register (`sstateen0`)
[wavedrom, ,svg,subs=attributes+]
....
{reg: [
{bits: 1, name: 'C'},
{bits: 1, name: 'FCSR'},
{bits: 1, name: 'JVT'},
{bits: 1, name: 'TID'},
{bits: 28, name: 'WPRI'}
], config:{bits: 32, lanes: 2, hspace:1024}}
....

endif::[]

[#sec_cheri_exception_handling]
=== CHERI Exception handling

CHERI faults are typically higher priority than standard RISC-V faults. E.g., CHERI faults on the <<pcc>> are higher priority than any other fault effecting the program counter such as instruction access fault.

NOTE: `auth_cap` is `{cs1}`, unless in {cheri_int_mode_name} when it is <<ddc>> (if {cheri_default_ext_name} is implemented).

.Valid CHERI exception combination description
[#cheri_exception_combs_descriptions]
[width="100%",options=header,cols="2,1,3,4"]
|=========================================================================================
| Instructions | Xcause | Description | Check
4+| *All instructions have these exception checks first*
| All                                            | {cheri_excep_cause_pc}     | {cheri_excep_name_pc} | <<pcc>> {ctag} is zero
| All                                            | {cheri_excep_cause_pc}     | {cheri_excep_name_pc} | <<pcc>> is sealed
| All                                            | {cheri_excep_cause_pc}     | {cheri_excep_name_pc} | <<pcc>> does not have <<x_perm>>
| All                                            | {cheri_excep_cause_pc}     | {cheri_excep_name_pc} | Any byte of current instruction out of <<pcc>> bounds^1^
| All                                            | {cheri_excep_cause_pc}     | {cheri_excep_name_pc} | <<pcc>> failed any <<section_cap_integrity,integrity>> check.
4+| *CSR/Xret additional exception check*
| CSR*, <<MRET_CHERI>>, <<SRET_CHERI>>, <<CBO_INVAL_CHERI>> | Illegal instruction | {cheri_excep_name_pc} | <<pcc>> does not have <<asr_perm>> when required for CSR access or execution of <<MRET_CHERI>>, <<SRET_CHERI>> or <<CBO_INVAL_CHERI>>
4+| *Load additional exception checks*
| All loads                                      | {cheri_excep_cause_ld}     | {cheri_excep_name_ld} | `auth_cap` {ctag} is zero
| All loads                                      | {cheri_excep_cause_ld}     | {cheri_excep_name_ld} | `auth_cap` is sealed
| All loads                                      | {cheri_excep_cause_ld}     | {cheri_excep_name_ld} | `auth_cap` does not have <<r_perm>>
| All loads                                      | {cheri_excep_cause_ld}     | {cheri_excep_name_ld} | Any byte of load access out of `auth_cap` bounds^1^
| All loads                                      | {cheri_excep_cause_ld}     | {cheri_excep_name_ld} | `auth_cap` failed any <<section_cap_integrity,integrity>> check.
| Capability loads                               | 5^2^                       | Load access fault     | Misaligned capability load
4+| *Store/atomic/cache-block-operation additional exception checks*
| All stores, all atomics, all CBOs              | {cheri_excep_cause_st}     | {cheri_excep_name_st} | `auth_cap` {ctag} is zero
| All stores, all atomics, all CBOs              | {cheri_excep_cause_st}     | {cheri_excep_name_st} | `auth_cap` is sealed
| All stores,  CBO.ZERO                          | {cheri_excep_cause_st}     | {cheri_excep_name_st} | `auth_cap` does not have <<w_perm>>
| All atomics, CBO.CLEAN, CBO.FLUSH, CBO.INVAL   | {cheri_excep_cause_st}     | {cheri_excep_name_st} | `auth_cap` does not have both <<r_perm>> and <<w_perm>>
| All stores, all atomics                        | {cheri_excep_cause_st}     | {cheri_excep_name_st} | any byte of access out of `auth_cap` bounds^1^
| CBO.ZERO, CBO.INVAL                            | {cheri_excep_cause_st}     | {cheri_excep_name_st} | any byte of cache block out of `auth_cap` bounds^1^
| CBO.CLEAN, CBO.FLUSH                           | {cheri_excep_cause_st}     | {cheri_excep_name_st} | all bytes of cache block out of `auth_cap` bounds^1^
| All stores, all atomics, all CBOs              | {cheri_excep_cause_st}     | {cheri_excep_name_st} | `auth_cap` failed any <<section_cap_integrity,integrity>> check.
| Capability stores                              | 7^2^                       | Store access fault    | Misaligned capability store
|=========================================================================================

^1^ The bounds checks include the cases where the bounds could not be decoded.

^2^ Misaligned capability accesses raise access faults instead of misaligned faults since they cannot be emulated in software.

NOTE: <<CBO_ZERO_CHERI>> is performed as a cache block wide store.  All
CMOs operate on the cache block which contains the address.  Prefetch instructions check
that the authorizing capability is has its {ctag} set, is not sealed, has the required permission (<<r_perm>>,
<<w_perm>>, <<x_perm>>) corresponding to the instruction, and has bounds which
include at least one byte of the cache block; if any check fails, the prefetch
is not performed but no exception is generated.

[#CHERI_SPEC,reftext="CHERI Exceptions and speculative execution"]
=== CHERI Exceptions and speculative execution

#should be non-normative - and needs more details - move to appendix?#

CHERI adds architectural guarantees that can prove to be microarchitecturally useful.
Speculative-execution attacks can -- among other factors -- rely on instructions that fail CHERI permission checks not to take effect.
When implementing any of the extensions proposed here, microarchitects need to carefully consider the interaction of late-exception raising and side-channel attacks.

[#section_pma]
=== Physical Memory Attributes (PMA)

Typically, only parts of the entire memory space need to support CHERI {ctag}s.
Therefore, it is desirable that harts supporting {cheri_base_ext_name} extend PMAs with Physical Memory Attributes indicating whether a memory region allows storing CHERI {ctag}s.
If they are not supported, then what the behavior is when attempting to access them.

There are three levels of support:

.CHERI PMAs
[#cheri_pmas]
[width="100%",options=header]
|=========================================================================================
| PMA                          | Load Behavior    | Store Behavior                      | Comment
| _CHERI {ctag_title}_       | Load {ctag}      | Store {ctag}                        | Tagged memory supporting {ctag}s
| _CHERI {ctag_title} Strip_ | Load zero {ctag} | Ignore stored {ctag}                | No support for {ctag}s, ignore them
| _CHERI {ctag_title} Fault_ | Load zero {ctag} | Store/AMO Access Fault on {ctag}^1^ | No support for {ctag}s, trap on storing one
|=========================================================================================

^1^ The access fault is triggered on all capability stores or atomics such as <<STORE_CAP>> or <<AMOSWAP_CAP>> when <<c_perm>> and <<w_perm>> are granted and the {ctag} is set to one.

Memory regions that do not have the _CHERI {ctag_title}_ PMA do not require storage for {ctag}s.

[#section_vm]
=== Virtual Memory

CHERI checks are made on the effective address according to the current translation scheme.
I.e., on the virtual address if translation is enabled or the physical address if translation is disabled.

Implicit memory accesses made by the page table walker are not subject to CHERI checks.

NOTE: A future extension may add CHERI checks to the page table walker.


=== Modified Trap-Return Instructions Behavior

When the {cheri_base_ext_name} base ISA is implemented, the <<otherpriv,trap-return instructions>> (`MRET` and `SRET`) read the full YLEN bits of the <<mepc_y>>/<<sepc_y>> register and unseal it prior to exception return if it is a <<sentry_cap>>.

include::insns/mret_sret.adoc[]

[#section_cheri_disable]
== "{cheri_priv_m_reg_enable_ext}" Extension, Version 1.0

ifdef::cheri_v9_annotations[]
NOTE: *CHERI v9 Note:* This feature is new and different from CHERI v9's
per-privilege enable bits.

NOTE: *CHERI v9 Note:* The rules for excepting have been tightened here. Also,
it is not possible to disable CHERI checks completely.
endif::[]

When using a system with {cheri_default_ext_name}, it may be desirable to disable CHERI register and instruction access to some (or all) privilege levels such that they operate as a RV32I/RV64I system without any observable presence of CHERI features.
{cheri_default_ext_name} includes functions to disable explicit access to CHERI
registers and instructions (hereafter referred to _disabling CHERI_).

NOTE: When _CHERI is disabled_ for a specific privilege level, <<pcc>> and <<ddc>> bounds are _still_ enforced.

The {cheri_default_ext_name} extension makes the {CRE} bit of <<misa>>, <<menvcfg>>, and <<senvcfg>> writable to allow CHERI to be disabled.

//future extensions - currently they must match
//CHERI is disabled if
//
//* XLEN in the current mode is less than MXLEN, or
//* the endianness in the current mode is not the reset value of <<mstatus_y>>.MBE, or
//* the effective CHERI-enable for the current privilege is 0.

The effective CHERI-enable for the current privilege is:

* Machine: `<<misa>>.{CRE}`
* Supervisor: `<<misa>>.{CRE} & <<menvcfg>>.{CRE}`
* User: `<<misa>>.{CRE} & <<menvcfg>>.{CRE} & <<senvcfg>>.{CRE}`

NOTE: On reset CHERI is always disabled for backwards compatibility (<<misa>>.{CRE} resets to zero, <<ddc>> and <<pcc>> bounds are nominally root capabilities (see <<root-cap>>).

The following occurs when executing code in a privilege mode that has CHERI disabled:

* Instructions from <<rvy_insn_table>> and <<rvy_hybrid_insn_table>> cause illegal instruction exceptions.
* Executing CSR instructions accessing any natively YLEN CSR causes an illegal instruction exception.
* Executing CSR instructions accessing any CSR extended to YLEN only allows XLEN access (this is identical to {cheri_int_mode_name} access).

Disabling CHERI has no effect on implicit accesses or security checks.
The last capability written to <<pcc>> and <<ddc>> before disabling CHERI will be used to authorize instruction execution and data memory accesses.

[NOTE]
====
Disabling CHERI prevents low-privileged {cheri_int_mode_name} software
from interfering with the correct operation of higher-privileged {cheri_int_mode_name} software
that do not perform <<ddc>> switches on trap entry and return.

Disabling CHERI allows harts supporting CHERI to be fully
compatible with standard RISC-V, so CHERI instructions, such as <<CRAM>>, that
do not change any CHERI state, raise exceptions.
This is the default behavior on reset.
====

xref:cheri_behavior_cre_mode[xrefstyle=short] summarizes the behavior of a hart
in connection with the effective CHERI enable and the <<cheri_execution_mode>> while in a privilege other than debug mode.

.Hart's behavior depending on the effective <<section_cheri_disable,CHERI enable>> and <<cheri_execution_mode>>
[#cheri_behavior_cre_mode,width=100%,options=header,align=center,%autowidth,cols="40,20,20,20"]
|==============================================================================
|                                      | {CRE}^1^=0        | {CRE}=1, M-bit={int_mode_value} | {CRE}=1, M-bit={cap_mode_value}
| Authorizing capability for data memory accesses | <<ddc>>| <<ddc>> | capability in `rs1`
| natively YLEN CSR Access Width       | ✘                 | YLEN                  | YLEN
| Extended YLEN CSR Access Width       | XLEN              | XLEN                  | YLEN
| CHERI Instructions Allowed           | ✘                 | ✔^3^                  | ✔
| Summary                              | **_Fully RISC-V compatible_**^2^ | **{cheri_int_mode_name}** | **{cheri_cap_mode_name}**
|==============================================================================

^1^ _{CRE}_ represents the effective CHERI enable for the current privilege mode.

^2^ The hart is fully compatible with standard RISC-V when {CRE}=0 provided that <<pcc>>, Xtvec, Xepc and <<ddc>> have not been changed from the default reset state (i.e., hold <<root-rx-cap>> and <<root-rw-cap>> capabilities).

^3^ The compressed instructions operating on capability data are unavailable as their encoding will revert to non-CHERI (see <<section_cheri_hybrid_ext>>).

ifdef::support_varxlen[]
[#section_cheri_dyn_xlen]
== "{cheri_priv_m_dyn_xlen_ext}" Extension, Version 1.0

{cheri_priv_m_dyn_xlen_ext} eliminates some restrictions for SXL and UXL imposed in {cheri_priv_m_ext} to allow implementations supporting multiple base ISAs.
This extension allows the SXL, UXL, MBE, SBE, and UBE fields of <<mstatus_y>> to be writable (which is prohibited by {cheri_priv_m_ext} otherwise).

Changing XLEN::
Setting the SXL or UXL field to a value that is not MXLEN disables most CHERI features and instructions, as described in xref:section_cheri_disable[xrefstyle=short], while in that privilege mode.
+
NOTE: If CHERI must be disabled in a mode for security reasons, software should set {CRE} to 0 regardless of the SXL and UXL fields.
+
Whenever XLEN in any mode is set to a value less than MXLEN, standard RISC-V rules are followed.
This means that all operations must ignore source operand register bits above the configured XLEN, and must sign-extend results to fill all MXLEN bits in the destination register.
Similarly, *pc* bits above XLEN are ignored, and when the *pc* is written, it is sign-extended to fill MXLEN.
The integer writing rule from CHERI is followed, so that every register write also zeroes the metadata and {ctag} of the
destination register.
+
However, CHERI operations and security checks will continue using the entire hardware register (i.e., YLEN bits) to correctly decode capability bounds.

Changing endianness::
Setting the MBE, SBE, or UBE field to a value that is not the reset value of MBE disables most CHERI features and instructions, as described in xref:section_cheri_disable[xrefstyle=short], while in that privilege mode.

endif::support_varxlen[]

[#section_priv_cheri_vmem]
== "{cheri_priv_vmem_ext}" Extension, Version 1.0 for {cheri_base64_ext_name}

Virtual memory support for {cheri_base64_ext_name} requires at least one additional bit to be allocated in the page table entries, to control access to capabilities in virtual memory pages.

[#section_crw_bit]
=== Capability Read-Write (CRW) Bit

{cheri_priv_vmem_ext} defines the Capability Read-Write (CRW) bit in Page Table Entries (PTEs) for Sv39, Sv48, and Sv57 virtual memory systems on {cheri_base64_ext_name} harts. The CRW bit controls whether capabilities with their {ctag} set can be written to and loaded from a virtual page.

NOTE: _Sv32_ does not have any spare PTE bits, and so this bit does not exist for RV32.

IMPORTANT: Any {cheri_base64_ext_name} hart that supports Sv39 must also implement the PTE.CRW bit.

[#limit_cap_prop]
==== Limiting Capability Propagation

Page table enforcement can allow the operating system to limit the flow of capabilities between processes.
It is highly desirable that a process should only possess capabilities that have been issued for that address space by the operating system.
Unix processes may share memory for efficient communication, but capability pointers must not be shared across these channels into a foreign address space.
An operating system might defend against this by only issuing a capability to the shared region that does not grant the load/store capability permission.
However, there are circumstances where portions of general-purpose, mmapped^*^ memory become shared, and the operating system must prevent future capability communication through those pages.
This is not possible without restructuring software, as the capability for the original allocation, which spans both shared memory and private memory, would need to be deleted and replaced with a list of distinct capabilities with appropriate permissions for each range.
Such a change would not be transparent to the program.
Such sharing through virtual memory is on the page granularity, so preventing capability writes with a PTE permission is a natural solution.

^*^ _allocated using mmap_

[#cheri_pte_fault]
=== CHERI page faults

CHERI adds the concept of _CHERI page faults_. They are split into :

* {cheri_excep_name_pte_ld} (cause value {cheri_excep_cause_pte_ld}), and
* {cheri_excep_name_pte_st} (cause value {cheri_excep_cause_pte_st})

They are prioritized against other fault types as shown in <<exception-priority-cheri>>.

The PTE.CRW bit allows {cheri_excep_name_pte_st}s to be raised.

CHERI harts which implement Sv39 must also implement a revocation scheme to prevent use-after-free attacks.

The current revocation scheme (<<section_cheri_priv_crg_ext,{cheri_priv_crg_ext}>>) also allows {cheri_excep_name_pte_ld}s to be raised.

NOTE: A future extension may define an improved scheme.

==== Extending the Page Table Entry Format

The page table entry format remains unchanged for Sv32.
However, a new bit, Capability Read-Write (CRW), is added to leaf PTEs in Sv39, Sv48 and Sv57 as shown in xref:sv39pte_crw[xrefstyle=short], xref:sv48pte_crw[xrefstyle=short] and xref:sv57pte_crw[xrefstyle=short] respectively.
For non-leaf PTEs this bit remains reserved and must be cleared by software for forward compatibility, or else a page-fault exception is raised.
Additionally, if the hypervisor extension is enabled this bit remains reserved for leaf and non-leaf PTEs used in guest address translation.

.Sv39 page table entry
[#sv39pte_crw]
include::img/sv39pte_crw.edn[]

.Sv48 page table entry
[#sv48pte_crw]
include::img/sv48pte_crw.edn[]

.Sv57 page table entry
[#sv57pte_crw]
include::img/sv57pte_crw.edn[]

The CRW bit indicates whether reading or writing capabilities with the {ctag} set to the virtual page is permitted.
When the CRW bit is set, capabilities are written as usual.

If the CRW bit is clear then:

* When a capability load or AMO instruction is executed, the {ctag} bit of the
loaded capability is cleared before it is written to the destination register.
* A <<cheri_pte_fault,_{cheri_excep_name_pte_st}_>> exception is raised when a capability store or AMO instruction is executed and the {ctag} bit of the to-be-stored capability is set.

[[pte_crw_summary]]
.Summary of memory access behavior depending on CRW in the PTEs
[%autowidth,float="center",align="center",cols="<,<,<",options="header"]
|===
|PTE.CRW  |Instruction          | Behavior
| 0       |Capability load      | Set loaded {ctag} to zero
| 0       |Capability store/AMO | Raise a _{cheri_excep_name_pte_st}_ if the {ctag} of the to-be-stored capability is set
| 1       |Any                  | Normal operation.
|===

[NOTE]
====
The {ctag} bit of the stored capability is checked _after_ it is potentially cleared due to missing permissions.
Therefore, the behavior in this section isn't relevant if:

* The authorizing capability doesn't have <<c_perm>>.
* Any extension-specific mediation has already cleared the {ctag} of the to-be-stored capability.
====

[#section_invalid_addr_conv,reftext="Invalid address conversion"]
=== Invalid Address Handling

When address translation is in effect for {cheri_base64_ext_name}, the upper bits of virtual
memory addresses must match for the address to be valid.

The CSRs shown in xref:CSR_exevectors[xrefstyle=short], as well as the pc, need not hold all possible invalid addresses.
Implementations may convert an invalid address into some other invalid address that the register is capable of holding.

However, the bounds encoding of capabilities depends on the address value if the bounds are not infinite.

Therefore implementations must not convert invalid addresses to other arbitrary invalid addresses in an unrestricted manner if the bounds are not infinite.

If the bounds could not be decoded due to the address being invalid, then a _{cheri_excep_name_pc}_, _{cheri_excep_name_ld}_ or _{cheri_excep_name_st}_ exception is raised as appropriate.

NOTE: In all cases, if the authorizing capability has bounds that cover all addresses, then the behavior is identical to the normal RISC-V behavior without CHERI.

NOTE: Not requiring to the implementation to decode the bounds for invalid addresses reduces the size of bounds comparators from 64-bits to the supported virtual address width.

==== Updating CSRs

A CSR may be updated to hold a capability with an invalid address, due to:

* executing instructions, such as <<CSRRW_CHERI>>
* hardware updates to CSRs such as storing the <<pcc>> into  <<mepc_y>>/<<sepc_y>> etc. when taking an exception.

To ensure that the bounds of a valid capability cannot be corrupted:

* If the new address is invalid and the capability bounds do not cover all addresses, then set the {ctag} to zero before writing to the CSR.

NOTE: When the capability's address is invalid and happens to match an invalid address which the CSR
can hold, then it is implementation defined whether to set the {ctag} to zero.

==== Branches and Jumps

If the effective target address of the jump or branch is invalid, and the authorizing capability's bounds do not cover all addresses, then set the {ctag} of the target <<pcc>> to zero.
This will cause a {cheri_excep_name_pc} exception when executing the target instruction.

NOTE: RISC-V harts that do not support {cheri_base_ext_name} normally raise an
instruction access fault or page fault after jumping or branching to an invalid address.
Therefore, {cheri_base_ext_name} aims to preserve that behavior to ensure that
harts supporting {cheri_base_ext_name} and {cheri_default_ext_name} are fully
compatible with RISC-V harts provided that <<pcc>> and <<ddc>> are set to
<<root-rx-cap>> and <<root-rw-cap>> capabilities, respectively.

==== Memory Accesses

If the effective address of the memory access is invalid, and the authorizing capability's bounds do not cover all addresses, then raise a {cheri_excep_name_ld} or {cheri_excep_name_st} exception because the bounds cannot be reliably decoded.

ifndef::cheri_standalone_spec[]

==== List of terms defined in the unprivileged manual

NOTE: Due to links to the unprivileged manual being broken, this improves readability.
 Once the two manuals are merged the links will work.

[#asr_perm, reftext="ASR-permission"]
Access System Registers Permission (ASR)::
 See the unprivileged manual for the definition of ASR-permission.

[#c_perm, reftext="C-permission"]
Capability Permission \(C)::
 See the unprivileged manual for the definition of C-permission.

[#r_perm, reftext="R-permission"]
Read Permission \(R)::
 See the unprivileged manual for the definition of R-permission.

[#w_perm, reftext="W-permission"]
Write Permission (W)::
 See the unprivileged manual for the definition of W-permission.

[#x_perm, reftext="X-permission"]
Execute Permission (X)::
 See the unprivileged manual for the definition of X-permission.

[#m_bit, reftext="M-bit"]
M-bit::
 See the unprivileged manual for the definition of the M-bit.

[#pcc, reftext="pc"]
PC::
 See the unprivileged manual for the definition of the program counter capability.

[#ddc, reftext="ddc"]
DDC::
 See the unprivileged manual for the definition of the default data capability CSR.

[#cheri_execution_mode, reftext="CHERI execution modes"]
CHERI execution modes::
 See the unprivileged manual for the definition of the CHERI execution modes.

[#utidc, reftext="utidc"]
utidc::
 See the unprivileged manual for the definition of the utidc CSR.

[#uycfg, reftext="uycfg"]
uycfg::
See the unprivileged manual for the definition of the uycfg CSR.

[#root-cap, reftext="Root"]
Root Capability::
 See the unprivileged manual for the definition of Root capabilities.

[#root-rw-cap, reftext="Root Data"]
Root Data Capability::
 See the unprivileged manual for the definition of Root Data capabilities.

[#root-rx-cap, reftext="Root Executable"]
Root Executable Capability::
 See the unprivileged manual for the definition of Root Executable capabilities.

[#sentry_cap,reftext="sentry capability"]
Sentry Capabilities::
 See the unprivileged manual for the definition of sentry capabilities.

[#null-cap,reftext="NULL"]
NULL Capability::
 See the unprivileged manual for the definition of NULL capabilities.

[#section_cap_representable_check, reftext="Representable Range"]
Representable Range::
 See the unprivileged manual for the definition of the Representable Range of a capability.

[#CBO_INVAL_CHERI, reftext="CBO.INVAL (RVY)"]
CBO.INVAL (RVY)::
   See the unprivileged manual for the behavior of CBO.INVAL for RVY.

[#CBO_ZERO_CHERI, reftext="CBO.ZERO (RVY)"]
CBO.ZERO (RVY)::
   See the unprivileged manual for the behavior of CBO.ZERO for RVY.

[#AUIPC_CHERI, reftext="AUIPC (RVY)"]
AUIPC (RVY)::
   See the unprivileged manual for the behavior of AUIPC for RVY.

[#CSRRW_CHERI, reftext="CSRRW (RVY)"]
CSRRW (RVY)::
   See the unprivileged manual for the behavior of CSRRW for RVY.

[#AMOSWAP_CAP, reftext="AMOSWAP.{LD_ST_DOT_CAP}"]
AMOSWAP.Y::
   See the unprivileged manual for the definition of AMOSWAP.Y.

[#STORE_CAP, reftext="{STORE_CAP_NAME}"]
SY::
   See the unprivileged manual for the definition of SY.

[#LOAD_CAP, reftext="{LOAD_CAP_NAME}"]
LY::
   See the unprivileged manual for the definition of LY.

[#CRAM, reftext="{CRAM}"]
YAMASK::
   See the unprivileged manual for the definition of {CRAM}.

[#SCADDR, reftext="{SCADDR}"]
YADDRW::
   See the unprivileged manual for the definition of {SCADDR}.

[#MODESW_CAP, reftext="{MODESW_CAP}"]
{MODESW_CAP}::
   See the unprivileged manual for the definition of {MODESW_CAP}.

[#MODESW_INT, reftext="{MODESW_INT}"]
{MODESW_INT}::
   See the unprivileged manual for the definition of {MODESW_INT}.

[#default-csrnames-added, reftext="Unprivileged YLEN-wide CSRs added in {cheri_default_ext_name}"]
Unprivileged YLEN-wide CSRs added in {cheri_default_ext_name}::
  See the unprivileged manual for the table of these CSRs.

[#section_existing_riscv_insns, reftext="Changes to Existing RISC-V Base ISA Instructions"]
Changes to Existing RISC-V Base ISA Instructions::
  See the unprivileged manual for the behavior of these instructions.

[#section_cap_integrity, reftext="Integrity of Capabilities"]
Integrity of Capabilities::
  See the unprivileged manual for how to check the Integrity of Capabilities.

[#section_cap_encoding, reftext="Capability Encoding"]
Integrity of Capabilities::
  See the unprivileged manual for details of the capability encoding.

[#rvy_insn_table, reftext="{cheri_base_ext_name}"]
Integrity of Capabilities::
  See the unprivileged manual for instructions added by {cheri_base_ext_name}.

[#rvy_hybrid_insn_table, reftext="{cheri_default_ext_name}"]
Integrity of Capabilities::
  See the unprivileged manual for instructions added by {cheri_default_ext_name}.

endif::[]
