[[rv32ch]]
== RV32CH and RV64CH Base Capability Instruction Sets, Version 1.0

ifdef::cheri_standalone_spec[]
WARNING: This chapter will appear in the unpriv spec after the RV32I chapter.
endif::[]

This chapter describes the RV32CH and RV64CH base capability
instruction sets, that extend the RV32I and RV64I integer instruction sets with CHERI.

CHERI enhances the base ISA to add hardware memory access control.
It has an additional memory access mechanism that protects _references to code and data_ (pointers), rather than the _location of code and data_ (integer addresses).
This mechanism is implemented by providing a new primitive, called a *capability*, that software components can use to implement strongly protected pointers within an address space.

{cheri_base_ext_name} introduces a new data type, the _capability_, generally used for architectural pointers.
Capabilities are unforgeable and delegatable tokens of authority that grant software the ability to perform a specific set of operations.
In CHERI, integer-based pointers are replaced by capabilities to provide memory access control.

=== CHERI protection model

The CHERI model is motivated by the _principle of least privilege_, which
argues that greater security can be obtained by minimizing the privileges
accessible to running software. A second guiding principle is the _principle of
intentional use_, which argues that, where many privileges are available to a
piece of software, the privilege to use should be explicitly named rather than
implicitly selected. While CHERI does not prevent the expression of vulnerable
software designs, it provides strong vulnerability mitigation: attackers have a
more limited vocabulary for attacks, and should a vulnerability be successfully
exploited, they gain fewer rights, and have reduced access to further attack
surfaces.

Protection properties for capabilities include the ISA ensuring that
capabilities are always derived via valid manipulations of other capabilities
(_provenance_), that corrupted in-memory capabilities cannot be dereferenced
(_integrity_), and that rights associated with capabilities shall only ever be
equal or less permissive (_monotonicity_). Tampering or modifying capabilities
in an attempt to elevate their rights will yield an invalid capability as the
tag will be cleared. Attempting to dereference via an invalid capability
will result in a hardware exception.

CHERI capabilities may be held in registers or in memories, and are loaded,
stored, and dereferenced using CHERI-aware instructions that expect capability
operands rather than integer addresses. On hardware reset, initial capabilities
are made available to software via capability
registers. All other capabilities will be derived from these initial valid
capabilities through valid capability transformations.

Developers can use CHERI to build fine-grained spatial and temporal memory
protection into their system software and applications and significantly
improve their security.

[#sec_capability_field]
=== CHERI capability registers

Capability registers extend existing XLEN-bit integer registers to `2*XLEN` (hereafter referred to as CLEN), adding metadata to protect its integrity, limit how it is manipulated, and control its use.
In addition to widening to CLEN, each capability register also gains an out-of-band one-bit validity tag.
The exact bitwise layout of capabilities as well as the precise encoding of each field for XLEN=32 and XLEN=64 is described in <<app_cap_description>>, but always contain the fields listed in the following paragraphs.

NOTE: Future extensions to {cheri_base_ext_name} are permitted to choose a different capability encoding but must include these fields and .

.CHERI Capability structure
[#cap_structure]
[bytefield]
----
(defattrs :plain [:plain {:font-family "M+ 1p Fallback" :font-size 25}])
(def row-height 80)
(def row-header-fn nil)
(def boxes-per-row 32)
(draw-column-headers {:height 50 :font-size 18 :labels (reverse (concat ["0"] (repeat 28 "") ["XLEN-1" "" ""]))})

(draw-box "V"    {:span 1})
(draw-box "" {:span 1 :borders {}})
(draw-box "Metadata (bounds, permissions, etc.)"    {:span 30})
(draw-box "" {:span 2 :borders {}})
(draw-box "Address"     {:span 30})
(draw-box "" {:span 2 :borders {}})
(draw-box "XLEN" {:span 30 :borders {}})
----

==== Address

The lower XLEN bits of a capability encode the address of where the capability points.
This is also referred to as the integer part of capabilities.
For registers that are extended but (currently) only hold integer data, all other components are zero.

[#cap_validity_tag,reftext="validity tag"]
==== Validity Tag

The validity tag is an additional hardware managed bit added to addressable memory and registers.
It is stored separately and may be referred to as "out of band".
It indicates whether a register or CLEN-aligned memory location contains a valid capability.
If the validity tag is set, the capability is valid and can be dereferenced (contingent on checks such as permissions or bounds).

The capability is invalid if the validity tag is clear.
Using an invalid capability to dereference memory or authorize any operation gives rise to exceptions.
All capabilities derived from invalid capabilities are themselves invalid i.e. their validity tags are 0.

All locations in registers or memory able to hold a capability are CLEN+1 bits wide including the validity tag bit.
Those locations are referred as being _CLEN-bit_ or _capability_-wide in this specification.

[#sec_cap_bounds]
==== Bounds

The bounds encode the _base_ and _top_ addresses that constrain accesses authorized by this capability.
The capability can be used to access any memory location `A` in the range `base &#8804; A < top`.
The bounds are decoded as described in xref:section_cap_bounds_decoding[xrefstyle=short].

IMPORTANT: Bounds can only be reduced, and any attempt to increase them zeroes the validity tag.

NOTE: As there is only XLEN bits of metadata to encode two XLEN bit bounds values, the bounds are encoded in a compressed format.
  This means it may not be possible to precisely encode any arbitrary combination of base and top addresses.

[#sec_cap_type]
==== Capability Type (CT)

This metadata field indicates the type of the capability.
The type determines which operations the capability authorizes.
The following capability types are defined in {cheri_base_ext_name}:

.Capability types in {cheri_base_ext_name}
[#tab_cap_types,%autowidth,options=header,align="center"]
|===
|Type |Hardware interpretation

|0    | Unsealed capability
|1    | Sentry capability
|===

[#unsealed_cap,reftext="unsealed capability]
Unsealed capabilities::
When `CT=0`, the capability authorizes access to a region of memory as defined by the permissions and bounds.

[#sentry_cap,reftext="sentry capability"]
Sentry capabilities::
Capabilities with `CT=1` are immutable
capabilities that describe function entry points, known as sealed entry (sentry) capabilities.
They cannot be dereferenced to access memory and are immutable.
Modifying any of its fields clears the validity tag of the output capability.
The only permitted operation for sentry capabilities is jumping to a sentry capability to begin executing the instructions it references.
+
NOTE: Sentry capabilities can establish a form of control-flow integrity between mutually distrusting code.
For example, the <<JALR_CHERI>>
instruction with zero offset automatically unseals a sentry target capability and installs it in the
<<pcc,program counter capability>>.
The jump-and-link instructions also seal the return register, so the callee can return to the caller but cannot access the memory pointed at by the return register.
+
NOTE: In addition to using them for secure entry points, sentry capabilities can also be useful to software as secure software tokens.
They can be converted to an unsealed capability by rebuilding via a superset capability with the <<CBLD>> instruction.

[#sec_cap_ap]
==== Architectural Permissions (AP)

This metadata field encodes architecturally defined permissions of the capability.
Permissions grant access subject to the <<cap_validity_tag>> being set, the capability being unsealed, and bounds checks passing.
Any operation is also contingent on requirements imposed by other RISC-V architectural features, such as virtual memory, PMP and PMAs, even if the capability grants sufficient permissions.
The permissions currently defined in {cheri_base_ext_name} are listed below.

IMPORTANT: Permissions can only be removed, and any attempt to add permissions zeroes the validity tag.

[#r_perm,reftext="R-permission"]
Read Permission \(R):: Allow reading integer data from memory. Tags are always
read as zero when reading integer data.

[#w_perm,reftext="W-permission"]
Write Permission (W):: Allow writing integer data to memory. Validity tags are always
written as zero when writing integer data. Every CLEN aligned word in memory
has a tag, if any byte is overwritten with integer data then the validity tag for all
CLEN-bits is cleared.

[#c_perm,reftext="C-permission"]
Capability Permission \(C):: Allow reading capability data from memory if the
authorizing capability also grants <<r_perm>>. Allow writing capability data to
memory if the authorizing capability also grants <<w_perm>>.

[#x_perm,reftext="X-permission"]
Execute Permission (X):: Allow instruction execution.

[#lm_perm,reftext="LM-permission"]
Load Mutable Permission (LM):: Allow preserving the <<w_perm>> of capabilities loaded from memory.
If a capability grants <<r_perm>> and <<c_perm>>, but no <<lm_perm>>, then a capability loaded via this authorizing capability will have <<w_perm>> and <<lm_perm>> removed.
Clearing a capability's <<lm_perm>> and <<w_perm>> allows sharing a read-only version of a data structure (e.g. a tree or linked list) without making a copy.

NOTE: The permission stripping behavior only applies to loaded capability that have their validity tag set and are not sealed; loaded capabilities that are sealed or invalid do not have their permissions changed.
  This ensures that capability loads/stores of non-capability data do not modify the stored value.

[#asr_perm,reftext="ASR-permission"]
Access System Registers Permission (ASR):: Allow read and write access to all privileged CSRs as well as privileged instructions.
Removing this permission constraining restricting privileged software to a sandbox that cannot be subverted by changing privileged state.

// TODO: add levels permissions here
// TODO: add CL here
// NOTE: The <<section_cap_level>> field can be reduced even if the capability is sealed, see <<cap_level_load_summary>>.

[#sec_cap_sdp]
==== Software-Defined Permissions (SDP)
The metadata also contains a encoding-dependent number of software-defined permission (SDP) bits.
They can by inspected by the kernel or application programs to enforce restrictions on API calls (e.g. permit/deny system calls, memory allocation, etc.), but are not interpreted by the CPU otherwise.

NOTE: While these bits are not interpreted by the hardware, modification follows the same rules as architectural permissions: SDP bits can only be cleared and never set.
This property is required to ensure restricted programs cannot forge capabilities that would pass the software-enforced checks.


=== Added State

.CHERI Capability registers extending existing integer registers in {cheri_base_ext_name}
[#base_cap_registers]
[bytefield]
----
(defattrs :plain [:plain {:font-family "M+ 1p Fallback" :font-size 40}])
(def row-height 100)
(def row-header-fn nil)
(def boxes-per-row 65)
(draw-column-headers {:height 30 :font-size 25 :labels (concat ["" "2*XLEN (CLEN)"] (repeat 31 "") ["XLEN"] (repeat 30 "") ["0"])})

(draw-box "" [:box-first {:span 1}]) (draw-box "c0" [:box-related {:span 32}]) (draw-box "x0" [:box-last {:span 32 }])
(draw-box "" [:box-first {:span 1}]) (draw-box "c1" [:box-related {:span 32}]) (draw-box "x1" [:box-last {:span 32 }])
(draw-gap "c2-c30 (extending x2-x30)")
(draw-box "" [:box-first {:span 1}]) (draw-box "c31" [:box-related {:span 32}]) (draw-box "x31" [:box-last {:span 32 }])
(draw-box nil [:box-first {:span 1}]) (draw-box "pcc" [:box-related {:span 32}]) (draw-box "pc" [:box-last {:span 32 }])
(draw-box "V" {:span 1 :borders {}}) (draw-box "Metadata" {:span 32 :borders {}}) (draw-box "Address" {:span 32 :borders {}})
----

A CHERI core adds state to allow capabilities to be used from within registers, and to ensure they are not corrupted as they flow through the system.
This means the following state is added by {cheri_base_ext_name}:

==== Extended general purpose integer registers
These <<gprs,XLEN-wide integer registers>> (e.g. `sp`, `a0`) are all extended with another XLEN bits of capability metadata plus a validity tag bit.
When referring to the extended register, the `x` prefix is replaced with a `c`: i.e. the capability extended version of `x0` becomes `c0`.
The existing integer register names refer to the address part of the capability.
For the ABI register names the a `c` prefix is added, i.e. `csp`, `ca0`.
The zero register is extended with zero metadata and a cleared tag: this is called the <<null-cap>> capability.

==== Extended CSRs
Registers that store addresses are extended to contain capabilities.
In the base {cheri_base_ext_name}, the only such register is the program counter `pc` that is extended to the program counter capability (<<pcc>>). Extending `pc` ensures that the range of branches and jumps for currently executing code can be restricted.

NOTE: All CSRs that hold pointers are extended to CLEN bits, but since no CSRs are defined in the RV32I/RV64I base instruction set, any such change is described in the corresponding chapters.

[#pcc,reftext="pcc"]
===== PCC - The Program Counter Capability

An authorizing capability with appropriate permissions is required to execute
instructions in {cheri_base_ext_name}. Therefore, the unprivileged program
counter (*pc*) register is extended so that it is able to hold a capability.
The extended register is called the program counter capability (<<pcc>>). The
<<pcc>> address field is effectively the *pc* in the base RISC-V ISA so that the
hardware automatically increments as instructions are executed. The <<pcc>>'s
metadata and tag are reset to the <<infinite-cap>> capability metadata and tag
with the address field set to the core boot address.

The hardware performs the following checks on <<pcc>> for each instruction
executed in addition to the checks already required by the base RISC-V ISA. A
failing check causes a CHERI exception.

* The validity tag must be set
* The capability must not be sealed
* The capability must grant execute permission
* All bytes of the instruction must be in bounds

NOTE: Operations that update <<pcc>>, such as changing privilege or executing
jump instructions, unseal capabilities prior to writing. Therefore,
implementations do not need to check that that <<pcc>> is unsealed when
executing each instruction. However, this property has not yet been formally verified and may not hold if additional CHERI extensions beyond {cheri_base_ext_name} are implemented.

.Program Counter Capability
[#pcc-format]
include::img/pccreg.edn[]

<<pcc>> is a code capability, so it does not need to be able to hold all possible invalid addresses (see <<section_invalid_addr_conv>>).

==== Tags in registers, caches, and memory

Every register has a one-bit tag, indicating whether the capability in the register is valid to be dereferenced.
This tag is cleared whenever an invalid capability operation is performed. Such invalid operations include e.g. writing only the integer portion of the register or attempting to increase bounds or permissions.

The validity tags are also tracked through the memory subsystem: every aligned CLEN-bits wide region has a non-addressable one-bit tag, which the hardware manages atomically with the data.
The validity tag is cleared if the memory region is ever written using an operation other than a store of a full capability register.
Any caches must preserve this abstraction.

[#sec_cheri_cap_mode_int_mode]
=== {cheri_cap_mode_name} and {cheri_int_mode_name}
Existing RV32I/RV64I instructions as well as instructions defined by unprivileged extensions are largely unmodified.
The one difference is that a hart using {cheri_base_ext_name} instead of RV32I/RV64I as the base ISA uses capabilities for all memory accesses.
This is called executing in {cheri_cap_mode_name}.
In {cheri_cap_mode_name}, instructions that access memory, as well as branches and jumps are modified to check against the full capability from the base address register (e.g. `lw t0, 16(c3)`) instead of just the integer address (i.e. `lw t0, 16(x3)`).
In some cases, they are also changed to return a full capability value, e.g. <<AUIPC_CHERI>> will return the full <<pcc>> including the metadata.
For the full list of instructions that change behavior with {cheri_base_ext_name}, see <<app_cheri_instructions>>.

The new CHERI state and instructions can also be made available to a hart using RV32I/RV64I as the base ISA with full binary compatibility.
The mechanics for this mode are described by the <<section_cheri_hybrid_ext,{cheri_default_ext_name}>> extension.
When a hart supports CHERI but is using RV32I/RV64I as the base ISA, it is executing in {cheri_int_mode_name}.
{cheri_int_mode_name} mode allows full compatibility with existing RV32I/RV32E binaries, but with additional capability checks for all data memory accesses and instruction fetches.

=== Capability checks

Every memory access performed by a CHERI core must be authorized by a capability.
The authorizing capability is either named explicitly (the base register of a load/store operation) or implicitly (when executing a branch, <<pcc>> is used for authorization).
For example, `lw t0, 16(csp)` loads a word from memory, getting the address, bounds, and permissions from the `csp` register.

Instruction fetch is also authorized by a capability: the program counter capability (<<pcc>>) which extends PC.
This allows code fetch to be bounded, preventing a wide range of attacks that subvert control flow with integer data.

With {cheri_base_ext_name}, instruction fetches, jumps, and memory accesses may result in a fatal trap if the authorizing capability does grant the required permissions or the access is out of bounds.
No other exception paths are added: in particular, capability manipulations do not trap, but may clear the validity tag on the result capability if the operation is not permitted.

[#section_cap_instructions]
=== New and modified Instructions

{cheri_base_ext_name} adds new instructions to interact with the extended registers.
These added instructions can be split into the following categories:

* Capability manipulations (e.g. <<CADD>>, <<SCBNDS>>): for security, capabilities can only be modified in restricted ways.
  Special instructions are provided to copy capabilities or perform these allowed operations, for example _shrinking_ the bounds or _reducing_ the permissions.
  Any attempt to manipulate capabilities without using the instructions clears the validity tag, rendering them unusable for accessing memory.
  They do not cause exceptions.

* Capability inspection (e.g. <<GCBASE>>, <<GCPERM>>): capability fields (for example the _bounds_ describing what addresses the capability gives access to) are stored compressed in registers and memory.
These instructions give convenient access to allow software to query them.
  They do not cause exceptions.

* Memory access instructions (e.g. <<LC>>, <<SC>>): capabilities must be read from and written to memory atomically along with their tag.
Instructions are added to perform these wider accesses, allowing capabilities to flow between the memory and the register file.

* Miscellaneous instructions (e.g. <<SCSS>>): These instructions either compare capabilities or allow software to determine the alignment of bounds.
  They do not cause exceptions.

Additionally, all instructions which handle addresses have altered behavior when using {cheri_base_ext_name} as the base ISA.
The lower XLEN-bits of the result is always the same, but {cheri_base_ext_name} adds checks which may result in exceptions and specifies handling of the metadata.

The new and modified instructions are listed in the following sections of this chapter.

<<<

=== Capability Manipulation Instructions

include::insns/acperm_32bit.adoc[]
include::insns/cmv_32bit.adoc[]
include::insns/cadd_32bit.adoc[]
include::insns/scaddr_32bit.adoc[]
include::insns/schi_32bit.adoc[]
include::insns/scbnds_32bit.adoc[]
include::insns/scbndsr_32bit.adoc[]
include::insns/sentry_32bit.adoc[]
include::insns/cbld_32bit.adoc[]

<<<

=== Capability Inspection Instructions

include::insns/gctag_32bit.adoc[]
include::insns/gcperm_32bit.adoc[]
include::insns/gctype_32bit.adoc[]
include::insns/gcbase_32bit.adoc[]
include::insns/gclen_32bit.adoc[]
include::insns/gchi_32bit.adoc[]

=== Miscellaneous Instructions

include::insns/sceq_32bit.adoc[]
include::insns/scss_32bit.adoc[]
include::insns/cram_32bit.adoc[]

<<<

=== Capability Load, Store and Atomic Instructions

New loads, stores and atomics are introduced to handle capabilities.
They all operate in the same manner as the base ISA but access CLEN bits and also the validity tag.

* <<LC>> - load capability
* <<SC>> - store capability
// FIXME: atomics should move to A chapter
* <<AMOSWAP_C>> - atomic capability swap
** other atomic operations are not currently available
* <<LR_C>>/<<SC_C>> - load-reserved/store-conditional of a capability

All capability memory access requires <<c_perm>>. If <<c_perm>> is not granted then:

* All capability loads will return CLEN-bits from memory, and a zero validity tag.
* All capability stores will write CLEN-bits to memory, and write a zero validity tag.

All capability memory access instructions require CLEN aligned addresses, and will
take the appropriate misaligned exception if this requirement is not met.

NOTE: Misaligned capability memory accesses cannot be emulated.
  To transfer CLEN misaligned bits without a validity tag, use integer loads and stores.

include::insns/load_32bit_cap.adoc[]
//include::insns/load_16bit_cap_sprel.adoc[] // need to be C subsection
include::insns/store_32bit_cap.adoc[]
//include::insns/store_16bit_cap_sprel.adoc[] // need to be C subsection
include::insns/amoswap_32bit_cap.adoc[]
include::insns/load_res_cap_32bit.adoc[]
include::insns/store_cond_cap_32bit.adoc[]

[#section_existing_riscv_insns]
=== Changes to Existing RISC-V Instructions

#Tariq: I plan to continue from here....#

{cheri_base_ext_name} introduces minor changes to the execution existing instructions.
In general, any time an operand is used as a base pointer, {cheri_base_ext_name} changes this operand to a full capability (*c* register) instead of interpreting it as a XLEN-bit address (*x* register).
For memory accesses and control transfers, all CHERI checks are performed against this operand.
Additionally, instructions that perform pointer arithmetic are modified to write back a full capability and/or take full capability inputs (e.g. <<AUIPC_CHERI>>).
The following subsection list all changes to instructions from the <<rv32,base ISA>>, but these same modifications rules also apply to instructions added by other extensions (e.g. floating-point loads/stores or the shift-and-add instruction from <<zba,Zba>>).
Additionally, <<app_cheri_instructions>> has listings for all unprivileged instructions that change behavior when {cheri_base_ext_name} is used as the base ISA.

==== Integer Computational Instructions

Most integer computational instructions operate on XLEN bits of values held in *x* registers.
Therefore, these instructions only operate on the address field if the input register of the instruction holds a capability.
The output is XLEN bits written to an *x* register; the validity tag and capability metadata of that register are zeroed.

The only integer computational instruction from the <<rv32,base ISA>> that has changed behavior in {cheri_base_ext_name} is <<int-comp-lui-aiupc,AUIPC>>.
Instead of returning a XLEN bits address, <<AUIPC_CHERI>> returns a full capability registers with the metadata and tag obtained from <<pcc>>.

include::insns/auipc_32bit.adoc[]

==== Unconditional Jumps

Unconditional jumps operate as described in <<ct-insns,the base RISC-V ISA>> but with added bounds and permission checks.
For jump-and-link instructions, the value written to the link register is a full capability derived from <<pcc>> with the address updated to the link address.
The resulting jump address is checked against <<pcc>> as described below.
Additionally, the link register is sealed (as if executing an implicit <<SENTRY>>) to ensure that the callee cannot modify the return address and (maliciously) return to an incorrect instruction.

For indirect jumps, the authorizing capability is not <<pcc>> but the base register (which is read as a full capability instead of an XLEN-bit address).
The target capability is unsealed if it is a sentry and the instructions has a zero immediate offset.

<<JALR_CHERI>> causes a CHERI exception when:

* The target capability's validity tag is zero
* The target capability is sealed and the immediate is not zero
* A minimum sized instruction (2 or 4 bytes depending on enabled extensions) at the target capability's address is not
within bounds
* The target capability does not grant execute permission

<<JAL_CHERI>> and <<JALR_CHERI>> can also cause instruction address misaligned exceptions
following the standard RISC-V rules.

include::insns/jal_32bit.adoc[]
include::insns/jalr_32bit.adoc[]

[#condbr-purecap]
==== Conditional Branches

Conditional branch instructions compare two *x* registers as described in the base RISC-V
ISA, so the metadata and tag values are disregarded in the comparison if the
operand registers hold capabilities. If the comparison evaluates to true, then
the target address is installed in the <<pcc>>'s address field.
These instructions cause CHERI exceptions when a minimum sized instruction at the target address is not within the <<pcc>>'s bounds.

include::insns/condbr_32bit.adoc[]

[#section_int_load_store_insns]
==== Load and Store Instructions

Load and store instructions behave as described in <<ldst>> with one difference:
For the base operand, the full capability register is used to check the resulting memory access.
All load and store instructions cause CHERI exceptions if any of these checks fails:

* The validity tag must be set
* The capability must be unsealed
* All bytes of accessed memory must be inside the capability's bounds
* For loads, the <<r_perm,read permission>> must be present
* For stores, the <<w_perm,write permission>> must be present

Non-capability load instructions always zero the validity tag and metadata of the result register.

Non-capability stores write zero to the validity tag associated with the memory locations that are naturally aligned to CLEN.
Therefore, misaligned stores may clear up to two validity tag bits in memory.

NOTE: The changed interpretation of the base register also applies to all loads and stores defined in later chapters of this specification (including floating-point and vector loads/stores).

include::insns/load_32bit.adoc[]

include::insns/store_32bit.adoc[]
