= RISC-V Specification for CHERI Extensions
Authors: Thomas Aird, Hesham Almatary, Andres Amaya Garcia, John Baldwin, Paul Buxton, David Chisnall, Jessica Clarke, Brooks Davis, Nathaniel Wesley Filardo, Franz A. Fuchs, Timothy Hutt, Alexandre Joannou, Martin Kaiser, Tariq Kurd, Ben Laurie, Marno van der Maas, Maja Malenko, A. Theodore Markettos, David McKay, Jamie Melling, Stuart Menefy, Simon W. Moore, Peter G. Neumann, Robert Norton, Alexander Richardson, Michael Roe, Peter Rugg, Peter Sewell, Carl Shaw, Ricki Tura, Robert N. M. Watson, Toby Wenman, Jonathan Woodruff, Jason Zhijingcheng Yu
include::attributes-standalone.adoc[]
:cheri_standalone_spec: 1

///////////////////////////////////////////////////////////////////////////////
// Preface
///////////////////////////////////////////////////////////////////////////////

ifdef::github_commit_sha[]
[IMPORTANT]
This document is a specification snapshot built from https://github.com/riscv/riscv-cheri/commit/{github_commit_sha} and is not a versioned release.
The latest versioned PDF release can be downloaded from https://github.com/riscv/riscv-cheri/releases.
endif::[]

[WARNING]
.This document is in the link:https://lf-riscv.atlassian.net/wiki/display/HOME/Specification+States[Stable state]
====
Assume anything could still change, but limited change should be expected.
====

[preface]
== Copyright and license information
This specification is licensed under the Creative Commons
Attribution 4.0 International License (CC-BY 4.0). The full
license text is available at
https://creativecommons.org/licenses/by/4.0/.

Copyright 2024 by RISC-V International.

[preface]
include::contributors.adoc[]

///////////////////////////////////////////////////////////////////////////////
// Document body
///////////////////////////////////////////////////////////////////////////////

include::introduction.adoc[]

include::riscv-unpriv-integration.adoc[]

include::riscv-hybrid-integration.adoc[]

include::level-ext.adoc[]

include::riscv-priv-integration.adoc[]

include::cheri-pte-ext.adoc[]

include::debug-integration.adoc[]

include::trigger-integration.adoc[]

include::hypervisor-integration.adoc[]

include::vector-integration.adoc[]

include::ptrmask-integration.adoc[]

include::tid-ext.adoc[]

include::app-cap-description.adoc[]

include::app-cheri-instructions.adoc[]

include::system.adoc[]

include::tables.adoc[]

[appendix]
[sec_priv_unpriv_refs]
== Placeholder references to (un)privileged spec
To allow building this document both as an extension to the RISC-V ISA documents and standalone, the following references point to the appropriate chapter in the (un)privileged specification:

[[rv32]]RV32I::
See Chapter _RV32I Base Integer Instruction Set_ in cite:[riscv-unpriv-spec].
[[gprs]]General purpose registers::
See Chapter _RV32I Base Integer Instruction Set_ in cite:[riscv-unpriv-spec].
[[ldst]]Load and Store Instructions::
See Chapter _RV32I Base Integer Instruction Set_ in cite:[riscv-unpriv-spec].
[[int-comp-lui-aiupc]]Integer Register-Immediate Instructions::
See Chapter _RV32I Base Integer Instruction Set_ in cite:[riscv-unpriv-spec].
[[ct-insns]]Control Transfer Instructions::
See Chapter _RV32I Base Integer Instruction Set_ in cite:[riscv-unpriv-spec].
[[zba]]Zba::
See Chapter _"B" Extension for Bit Manipulation_ in cite:[riscv-unpriv-spec].


///////////////////////////////////////////////////////////////////////////////
// Index and bibliography
///////////////////////////////////////////////////////////////////////////////

// The index must precede the bibliography
include::index.adoc[]

include::bibliography.adoc[]
