[#section_cheri_hybrid_ext]
== "{cheri_default_ext_name}" Extension for CHERI {cheri_int_mode_name}

ifdef::cheri_standalone_spec[]
WARNING: This chapter will appear in the unpriv spec somewhere after the Zicsr chapter (since it depends on Zicsr).
endif::[]

{cheri_default_ext_name} is an optional extension to the {cheri_base_ext_name} base architectures.
{cheri_default_ext_name} adds the ability to dynamically change the base ISA between using capability pointers for all memory references ({cheri_base_ext_name}) and using integer pointers (RV32I/RV64I).
The ability to choose between these two behaviors (referred to as _CHERI Execution Modes_) ensures CHERI can be fully compatible with the base RISC-V integers ISAs while saving instruction encoding space.

Additionally, {cheri_default_ext_name} adds a new unprivileged CSR: the default data capability, <<ddc>>, that is used to authorize all data memory accesses when treating pointers as integers.

NOTE: Together with <<pcc>>, <<ddc>> allows confining code runs to a compartment (also called a _sandbox_), where all data memory and instruction memory accesses are bounded to fixed memory regions.


The remainder of this section describes these features in detail as well as their integration with the primary base integer variants of the base RISC-V ISA.

IMPORTANT: Implementations that support both {cheri_base_ext_name} and {cheri_default_ext_name} have full binary compatibility with all existing ratified RISC-V base architectures and extensions.

[#cheri_execution_mode,reftext="CHERI Execution Mode"]
=== CHERI Execution Mode

The two execution modes are:

{cheri_int_mode_name}::
Executing with RV32I/RV64I base ISA.
+
All {cheri_base_ext_name} instructions and CSRs are also available in {cheri_default_ext_name}.
+
IMPORTANT: All instructions from existing RISC-V extensions can be run in {cheri_int_mode_name}.
  This execution mode is fully binary compatible with non-CHERI-aware programs.

{cheri_cap_mode_name}::
Executing with the {cheri_base_ext_name} base ISA.
+
Some instructions in the RV32I/RV64I base ISA (and in some other extensions) use capabilities instead of integers for memory references (see xref:section_existing_riscv_insns[xrefstyle=short]). In these cases, such as <<SH1ADD_CHERI>>, the lower XLEN bits of the result is the same in either mode and the upper XLEN bits, and valid tag, are either handled as capabilities in {cheri_cap_mode_name}, or are ignored in the source and written to zero in {cheri_int_mode_name}

The _<<cheri_execution_mode>>_ impacts the instruction set in the following way:

* The authorizing capability used to execute memory access instructions depends on the mode.
In {cheri_int_mode_name}, <<ddc>> is implicitly used. In {cheri_cap_mode_name}, the authorizing  capability is supplied as an explicit *c* operand to the instruction.
// XXX: This only affects the floating-point compressed isns, no need to mention here:
// * The set of instructions that is available for execution. Some instructions are available in {cheri_int_mode_name} but not {cheri_cap_mode_name} and vice-versa (see xref:app_cheri_instructions[xrefstyle=short]).

// NOTE: The _<<cheri_execution_mode>>_ is effectively an extension to some RISC-V instruction encodings.
//   For example, the encoding of an instruction like <<LW>> remains unchanged, but the mode indicates whether the capability authorizing the load is the register operand `cs1` ({cheri_cap_mode_name}).
// The mode is shown in the assembly syntax.

The _<<cheri_execution_mode>>_ is key in providing backwards compatibility with the base RV32I/RV64I ISA.
RISC-V software is able to execute unchanged in implementations supporting both {cheri_base_ext_name} and {cheri_default_ext_name} provided that the privileged environment sets up <<ddc>> and <<pcc>> appropriately.

NOTE: The CHERI execution mode is always {cheri_cap_mode_name} on implementations that support {cheri_base_ext_name}, but not {cheri_default_ext_name}.

NOTE: {cheri_base_ext_name} implementations which support {cheri_default_ext_name} are typically referred to as CHERI Hybrid, whereas implementations which do not support {cheri_default_ext_name} are typically referred to as CHERI purecap.

==== CHERI Execution Mode Effect On Existing Encodings

All RV32I/RV64I instructions are available in both CHERI execution modes.



[#m_bit,reftext="M-bit"]
==== CHERI Execution Mode Encoding

The _<<cheri_execution_mode>>_ is determined by a bit in the metadata of the <<pcc>> called the <<m_bit>>.
{cheri_default_ext_name} adds a new _<<cheri_execution_mode>>_ field (M) to the capability format.
Although always present, it only takes effect in code capabilities, i.e., when the <<x_perm>> is set.
The exact location of the M-bit in the capability format for XLEN=32 and XLEN=64 is described in <<app_cap_description>>.

* Mode (M)={CAP_MODE_VALUE} indicates {cheri_cap_mode_name}.
* Mode (M)={INT_MODE_VALUE} indicates {cheri_int_mode_name}.

IMPORTANT: While the <<m_bit>> only has a effect when installed in <<pcc>>, it needs to be encoded in all capabilities.
  Since indirect jumps copy the full target capability into <<pcc>>, it allows indirect jumps to change between modes (see <<sec_changing_cheri_execution_mode>>).

The <<m_bit>> of the <<pcc>>, may be overridden by the execution environment which may not grant permission to enter {cheri_cap_mode_name}.

[#sec_changing_cheri_execution_mode]
==== Changing CHERI Execution Mode
The <<m_bit>> of <<pcc>> can be updated by the instructions listed in <<tab_cheri_mode_sw_summary>>:

.{cheri_default_ext_name} instructions that can perform mode changes
[#tab_cheri_mode_sw_summary,%autowidth,options=header,align="center",cols="2,2,4"]
|=======================
|Mnemonic        | From mode          | Description
| <<JALR_CHERI>> |{cheri_cap_mode_name}| Install `cs1` in the <<pcc>> and so update `pcc.M`
| <<MODESW.INT>> |{cheri_cap_mode_name}| Switch to {cheri_int_mode_name}.
| <<MODESW.CAP>> |{cheri_int_mode_name}| Switch to {cheri_cap_mode_name}.
|=======================

NOTE: The mode can also be updated by setting the <<m_bit>> of a target capability using <<SCMODE>> followed by a <<JALR_CHERI>>.

[#m_bit_observe,reftext="Observing the CHERI Execution Mode"]
==== Observing the CHERI Execution Mode

The effective CHERI execution mode cannot be determined just by reading the <<m_bit>> from <<pcc>> since it also depends on the execution environment.
The following code sequence demonstrate how a program can observe the current, effective CHERI execution mode.
It will write {CAP_MODE_VALUE} for {cheri_cap_mode_name} and {INT_MODE_VALUE} for {cheri_int_mode_name} to `x1`:

[source]
----
auipc c1, 0
gctag x1, c1
----

=== Added State

{cheri_default_ext_name} adds the CLEN-wide CSRs shown in
xref:default-csrnames-added[xrefstyle=short].

[[default-csrnames-added]]
.Unprivileged CLEN-wide CSRs added in {cheri_default_ext_name}
[%autowidth,float="center",align="center",cols="<,<,<,<",options="header"]
|===
|CLEN CSR|Address|Permissions|Description
|<<ddc>>|0x416|RW|User Default Data Capability
|===

[#ddc,reftext="ddc"]
==== Default Data Capability CSR (ddc)

<<ddc>> is a read-write, user mode accessible capability CSR.
It does not require <<asr_perm>> in <<pcc>> for writes or reads.
Similarly to <<pcc>> authorizing all control flow and instruction fetches, this capability register is implicitly checked to authorize all data memory accesses  when the current CHERI mode is {cheri_int_mode_name}.
On startup <<ddc>> bounds and permissions must be set such that the program can run successfully (e.g., by setting it to <<infinite-cap>> to ensure _all_ data references are in bounds).

.Unprivileged default data capability register
include::img/ddcreg.edn[]

NOTE: <<section_cheri_disable,CHERI register and instruction access>> is not required for the implicit access required by checking memory accesses against <<ddc>>.

NOTE: <<ddc>> is a data pointer, so it does not need to be able to hold all possible invalid addresses (see <<section_invalid_addr_conv>>).

=== {cheri_default_ext_name} Memory Accesses

In {cheri_cap_mode_name} all memory accesses behave as defined by <<rv32y,{cheri_base_ext_name}>> and are authorised by the base register (`cs1`), from which the bounds and permissions are taken. For example:

* `lw t0, 16(ca0)`

In {cheri_int_mode_name} the `lw` has the same behavior and assembly syntax as the RV32I/RV64I:

* `lw t0, 16(a0)`

All memory accesses must still be checked, but now they are authorized by the capability in <<ddc>> instead.

//Load and store instructions change behavior depending on the CHERI execution
//mode although the instruction's encoding remains unchanged.
//
//Loads and stores behave as described in
//xref:section_existing_riscv_insns[xrefstyle=short] when in {cheri_cap_mode_name}.
//In {cheri_int_mode_name}, the instructions behave as described in
//the RISC-V base ISA and rely on *x* operands
//only. The capability authorizing the memory access is <<ddc>> and the memory
//address is given by sign-extending the 12-bit immediate offset and adding it to
//the base address in the *x* register operand.
//
//The exception cases remain as described in
//xref:section_existing_riscv_insns[xrefstyle=short] regardless of the CHERI
//execution mode.

=== {cheri_default_ext_name} Branches and Jumps

The rules from xref:section_existing_riscv_insns[xrefstyle=short] are applied, so that all branch and jump targets are checked against <<pcc>>.

NOTE: In {cheri_int_mode_name} JALR does _not_ copy the target capability register `cs1` into <<pcc>>, instead it updates the address of <<pcc>> with the target value.
The only difference to RV32I/RV64I without {cheri_default_ext_name}, is that the target address is checked against the bounds of <<pcc>>.

[#section_hybrid_ext_instructions]
=== {cheri_default_ext_name} Instructions

{cheri_default_ext_name} introduces new instructions to switch CHERI execution modes.
Additionally, {cheri_default_ext_name} makes all instructions defined by {cheri_default_ext_name} available.

.Instructions summary for {cheri_default_ext_name}
[#tab_hybrid_summary,%autowidth,options=header,align="center",cols="1,4"]
|=======================
|Mnemonic     |Description
|<<SCMODE>>    |Set capability CHERI execution mode (<<m_bit>>)
// The output is written to an unprivileged *c* register, not <<pcc>>.
|<<GCMODE>>    |Get capability CHERI execution mode (<<m_bit>>)
|<<MODESW_CAP>>|Set current CHERI execution mode to {cheri_cap_mode_name}
|<<MODESW_INT>>|Set current CHERI execution mode to {cheri_int_mode_name}
|=======================

include::insns/scmode_32bit.adoc[]

include::insns/gcmode_32bit.adoc[]

include::insns/modesw_32bit.adoc[]

<<<

=== Changes to {cheri_base_ext_name} Instructions

The load and store capability instructions introduced in {cheri_base_ext_name} change behavior depending on the
CHERI execution mode although the instruction's encoding remains unchanged.

==== <<LC>>
When the CHERI execution mode is {cheri_cap_mode_name}; the instruction behaves as described in xref:sec_cap_load_store[xrefstyle=short].
In {cheri_int_mode_name}, the capability authorizing the memory access is <<ddc>>, so the effective address is obtained by adding the *x* register to the sign-extended offset.

==== <<SC>>

When the CHERI execution mode is {cheri_cap_mode_name}; the instruction behaves as described in xref:sec_cap_load_store[xrefstyle=short].
In {cheri_int_mode_name}, the capability authorizing the memory access is <<ddc>>, so the effective address is obtained by adding the *x* register to the sign-extended offset.

[#zicsr-section-default]
=== Changes to Zicsr Instructions

When in {cheri_int_mode_name}, there is a special rule for updating extended CSRs (e.g., <<jvtc>>/<<jvt_cheri>>)

* Writing an extended CSR writes the address field (XLEN bits) only, and the full CSR is updated using <<SCADDR>> semantics.
* Reading an extended CSR reads the address field (XLEN bits) only

For this purpose the assembly syntax will refer to <<jvt_cheri>>.
Accesses to extended CSRs in {cheri_int_mode_name} must only access XLEN bits for compatibility, and so use <<SCADDR>> semantics to determine the final written value.

.CLEN-bit CSR and Extended CSR access summary for {cheri_default_ext_name}
[#clen_access_summary_default,%autowidth,options=header,align="center"]
|=======================
|                   2+| CLEN-bit CSR^1^           2+| Extended CSR^2^
|Instruction          | Read Width  | Write Width   | Read Width  | Write Width
|CSRRW       rd==x0   |             | CLEN          |             | XLEN
|CSRRW       rd!=x0   |CLEN         | CLEN          |XLEN         | XLEN
|CSRR[C\|S]  rs1==x0  |CLEN         |               |XLEN         |
|CSRR[C\|S]  rs1!=x0  |CLEN         | XLEN          |XLEN         | XLEN
|CSRRWI      rd==x0   |             | XLEN          |             | XLEN
|CSRRWI      rd!=x0   |CLEN         | XLEN          |XLEN         | XLEN
|CSRR[C\|S]I uimm==x0 |CLEN         |               |XLEN         |
|CSRR[C\|S]I uimm!=x0 |CLEN         | XLEN          |XLEN         | XLEN
|=======================

^1^ e.g., <<utidc>>
^2^ e.g., <<jvt_cheri>>

include::insns/csrr_32bit.adoc[]
include::insns/csrrw_32bit.adoc[]
