[[rv32ch]]
== RV32CH and RV64CH Base Capability Instruction Sets, Version 1.0

ifdef::cheri_standalone_spec[]
WARNING: This chapter will appear in the unpriv spec after the RV32I chapter.
endif::[]

This chapter describes the RV32CH and RV64CH base capability instruction sets, that extend the RV32I and RV64I integer instruction sets with CHERI.

[CAUTION]
====
#ARC-QUESTION: We have used the suggested RV*CH placeholder name here.#
#Filed https://github.com/riscv/riscv-cheri/issues/572 with possible single-character options.#
====

CHERI enhances the base ISA to add hardware memory access control.
It has an additional memory access mechanism that protects _references to code and data_ (pointers), rather than the _location of code and data_ (integer addresses).
This mechanism is implemented by providing a new primitive, called a *capability*, that software components can use to implement strongly protected pointers within an address space.
Capabilities are unforgeable and delegatable tokens of authority that grant software the ability to perform a specific set of operations.
In CHERI, integer-based pointers are replaced by capabilities to provide memory access control.

=== CHERI protection model

The CHERI model is motivated by the _principle of least privilege_, which
argues that greater security can be obtained by minimizing the privileges
accessible to running software. A second guiding principle is the _principle of
intentional use_, which argues that, where many privileges are available to a
piece of software, the privilege to use should be explicitly named rather than
implicitly selected. While CHERI does not prevent the expression of vulnerable
software designs, it provides strong vulnerability mitigation: attackers have a
more limited vocabulary for attacks, and should a vulnerability be successfully
exploited, they gain fewer rights, and have reduced access to further attack
surfaces.

Protection properties for capabilities include the ISA ensuring that
capabilities are always derived via valid manipulations of other capabilities
(_provenance_), that corrupted in-memory capabilities cannot be dereferenced
(_integrity_), and that rights associated with capabilities shall only ever be
equal or less permissive (_monotonicity_). Tampering or modifying capabilities
in an attempt to elevate their rights will yield an invalid capability as the
tag will be cleared. Attempting to dereference via an invalid capability
will result in a hardware exception.

CHERI capabilities may be held in registers or in memories, and are loaded,
stored, and dereferenced using CHERI-aware instructions that expect capability
operands rather than integer addresses. On hardware reset, initial capabilities
are made available to software via capability
registers. All other capabilities will be derived from these initial valid
capabilities through valid capability transformations.

Developers can use CHERI to build fine-grained spatial and temporal memory
protection into their system software and applications and significantly
improve their security.

[#sec_capability_registers]
=== CHERI capability registers

Capability registers extend existing XLEN-bit integer registers to `2*XLEN` (hereafter referred to as CLEN), adding metadata to protect its integrity, limit how it is manipulated, and control its use.
In addition to widening to CLEN, each capability register also gains an out-of-band one-bit validity tag.
The exact bitwise layout of capabilities as well as the precise encoding of each field for XLEN=32 and XLEN=64 is described in <<app_cap_description>>, but always contain the fields listed in the following paragraphs.

NOTE: Extensions to {cheri_base_ext_name} are permitted to use a modified capability encoding but must conform to all rules and include all fields listed in this chapter.

.CHERI Capability structure
[#cap_structure]
[bytefield]
----
(defattrs :plain [:plain {:font-family "M+ 1p Fallback" :font-size 25}])
(def row-height 80)
(def row-header-fn nil)
(def boxes-per-row 32)
(draw-column-headers {:height 50 :font-size 18 :labels (reverse (concat ["0"] (repeat 28 "") ["XLEN-1" "" ""]))})

(draw-box "V"    {:span 1})
(draw-box "" {:span 1 :borders {}})
(draw-box "Metadata (bounds, permissions, etc.)"    {:span 30})
(draw-box "" {:span 2 :borders {}})
(draw-box "Address"     {:span 30})
(draw-box "" {:span 2 :borders {}})
(draw-box "XLEN" {:span 30 :borders {}})
----

==== Address

The lower XLEN bits of a capability encode the address of where the capability points.
This is also referred to as the integer part of the capability.
For registers that are extended but (currently) only hold integer data, all other fields are zero.

[#cap_validity_tag,reftext="validity tag"]
==== Validity Tag

The validity tag is an additional hardware managed bit added to addressable memory and registers.
It is stored separately and may be referred to as "out of band".
It indicates whether a register or CLEN-aligned memory location contains a valid capability.
If the validity tag is set, the capability is valid and can be dereferenced (contingent on checks such as permissions or bounds).

The capability is invalid if the validity tag is clear.
Using an invalid capability to dereference memory or authorize any operation gives rise to exceptions.
All capabilities derived from invalid capabilities are themselves invalid i.e. their validity tags are 0.

All locations in registers or memory able to hold a capability are CLEN+1 bits wide including the validity tag bit.
Those locations are referred as being _CLEN-bit_ or _capability_-wide in this specification.

[#sec_cap_bounds]
==== Bounds

The bounds encode the _base_ and _top_ addresses that constrain accesses authorized by this capability.
The capability can be used to access any memory location `A` in the range `base &#8804; A < top`.
The bounds are decoded as described in xref:section_cap_bounds_decoding[xrefstyle=short].

IMPORTANT: Bounds can only be reduced, and any attempt to increase them zeroes the validity tag.

NOTE: As the base and top addresses together cannot fit within XLEN bits of metadata, they are encoded in a compressed format.
  This means it may not be possible to precisely encode any arbitrary combination of base and top addresses.

[#sec_cap_type]
==== Capability Type (CT)

This metadata field indicates the type of the capability.
The type determines which operations the capability authorizes.
The following capability types are defined in {cheri_base_ext_name}:

.Capability types in {cheri_base_ext_name}
[#tab_cap_types,%autowidth,options=header,align="center"]
|===
|Type |Hardware interpretation

|0    | Unsealed capability
|1    | Sentry capability
|===

[#unsealed_cap,reftext="unsealed capability]
Unsealed capabilities::
When `CT=0`, the capability authorizes access to a region of memory as defined by the permissions and bounds.

[#sentry_cap,reftext="sentry capability"]
Sentry capabilities::
Capabilities with `CT=1` are immutable
capabilities that describe function entry points, known as sealed entry (sentry) capabilities.
They cannot be dereferenced to access memory and are immutable.
Modifying any of its fields clears the validity tag of the output capability.
The only permitted operation for sentry capabilities is jumping to a sentry capability to begin executing the instructions it references.
+
NOTE: Sentry capabilities can establish a form of control-flow integrity between mutually distrusting code.
For example, the <<JALR_CHERI>>
instruction with zero offset automatically unseals a sentry target capability and installs it in the
<<pcc,program counter capability>>.
The jump-and-link instructions also seal the return register, so the callee can return to the caller but cannot access the memory pointed at by the return register.
+
NOTE: In addition to using them for secure entry points, sentry capabilities can also be useful to software as secure software tokens.
They can be converted to an unsealed capability by rebuilding via a superset capability with the <<CBLD>> instruction.

[#sec_cap_ap]
==== Architectural Permissions (AP)

This metadata field encodes architecturally defined permissions of the capability.
Permissions grant access subject to the <<cap_validity_tag>> being set, the capability being unsealed, and bounds checks passing.
Any operation is also contingent on requirements imposed by other RISC-V architectural features, such as virtual memory, PMP and PMAs, even if the capability grants sufficient permissions.
The permissions currently defined in {cheri_base_ext_name} are listed below.

IMPORTANT: Permissions can only be removed, and any attempt to add permissions zeroes the validity tag.

[#r_perm,reftext="R-permission"]
Read Permission \(R):: Allow reading integer data from memory. Tags are always
read as zero when reading integer data.

[#w_perm,reftext="W-permission"]
Write Permission (W):: Allow writing integer data to memory. Validity tags are always
written as zero when writing integer data. Every CLEN aligned word in memory
has a tag, if any byte is overwritten with integer data then the validity tag for all
CLEN-bits is cleared.

[#c_perm,reftext="C-permission"]
Capability Permission \(C):: Allow reading capability data from memory if the
authorizing capability also grants <<r_perm>>. Allow writing capability data to
memory if the authorizing capability also grants <<w_perm>>.

[#x_perm,reftext="X-permission"]
Execute Permission (X):: Allow instruction execution.

[#lm_perm,reftext="LM-permission"]
Load Mutable Permission (LM):: Allow preserving the <<w_perm>> of capabilities loaded from memory.
If a capability grants <<r_perm>> and <<c_perm>>, but no <<lm_perm>>, then a capability loaded via this authorizing capability will have <<w_perm>> and <<lm_perm>> removed.
Clearing a capability's <<lm_perm>> and <<w_perm>> allows sharing a read-only version of a data structure (e.g. a tree or linked list) without making a copy.

NOTE: The permission stripping behavior only applies to loaded capabilities that have their validity tag set and are not sealed; loaded capabilities that are sealed or invalid do not have their permissions changed.
  This ensures that capability loads/stores of non-capability data do not modify the stored value.

[#asr_perm,reftext="ASR-permission"]
Access System Registers Permission (ASR):: Allow read and write access to all privileged CSRs as well as privileged instructions.
Removing this permission constraining restricting privileged software to a sandbox that cannot be subverted by changing privileged state.

[#sl_perm,reftext="SL-permission"]
Store Level Permission (SL):: This is a variable width field that allows limiting the propagation of capabilities using the following logic: capabilities with a <<section_cap_level>> less than the inverse of the authorizing capability's <<sl_perm>> will be stored with the validity tag cleared.
With `LVLBITS=1` there is a single bit comparison, so it behaves as follows:
- If this field (as well as <<c_perm>> and <<w_perm>>) is set to 1 then capabilities may be stored via this capability regardless of their associated <<section_cap_level>>.
- If this field is zero, then any capability with a <<section_cap_level>> of zero (i.e. _local_), will be stored with the validity tag cleared.

NOTE: For `LVLBITS=1` this permission is equivalent to _StoreLocal_ in CHERI v9, Morello and CHERIoT.

[#el_perm,reftext="EL-permission"]
Elevate Level Permission (EL):: Any unsealed capability with its tag set to 1 that is loaded from memory has its <<el_perm>> cleared and its <<section_cap_level>> restricted to the authorizing capability's <<section_cap_level>> if the authorizing capability does not grant <<el_perm>>.
If sealed, then only <<section_cap_level,CL>> is modified, <<el_perm>> is unchanged.
This permission is similar to the existing <<lm_perm>>, but instead of applying to the <<w_perm>> on the loaded capability it restricts the <<section_cap_level,CL>> field.

ifdef::cheri_v9_annotations[]
NOTE: *CHERI v9 Note:* This permission does not exist in CHERI v9, but is similar to CHERIoT's _LoadGlobal_ permission, except that any _global_ capability implicitly grants _LoadGlobal_.
endif::[]

[#section_cap_level,reftext="Capability Level (CL)"]
==== Capability Level (CL)

The _Capability Level_ (CL) is a variable width field that allows enforcing invariants on capability propagation.
For example, the _Capability Level_ can be used to ensure that a callee can only write a copy of the passed-in argument capability to specific locations in memory (e.g. the callee's stack frame but not the heap).
It can also be used to avoid sharing of compartment-local data (such as pointers to a stack object) between compartments.

NOTE: This specification only defines the architectural mechanics of this feature, for further information on how this can be used by software please refer to cite:[cheri-v9-spec].

The width of this field depends on whether the {cheri_0levels_ext_name} or {cheri_1levels_ext_name} extension is implemented:

===== {cheri_0levels_ext_name}
In this case the field is hardwired to 1 and all checks based on the _Capability Level_ can be omitted (since they always pass).

===== {cheri_1levels_ext_name}
The _Capability Level_ can hold two values: when set to 1 the capability is _global_ (in general allowing it to be stored using any authorizing capability), and when set to 0 the capability is _local_, and can only be stored by authorizing capabilities with the <<sl_perm>> set.
  Furthermore, the <<el_perm>> can be used to restrict loading of _global_ capabilities -- causing the hardware to automatically set the level of loaded capabilities to _local_ instead.

As with permissions, the capability level can only be decreased but never increased (without deriving from a capability with a higher level).
// Therefore, the capability level is adjusted using the <<ACPERM>> instruction (see <<section_cap_level_change>>) and are queried using <<GCPERM>>.
But unlike architectural permissions, CL can be reduced even if the capability is sealed.

NOTE: A capability with <<section_cap_level,CL>>=1 is referred to as _global_ and with <<section_cap_level,CL>>=0 as _local_.

.{cheri_1levels_ext_name} summary table for stored capabilities
[#cap_level_store_summary,width="100%",options=header,halign=center,cols="1,1,1,1,5"]
|==============================================================================
   3+|Auth cap field       | Data cap field |
    h|*W*    h|*C* h|*SL* h|*CL* h| Notes
.3+.^|1  .3+.^| 1   | 1    | X    | Store data capability unmodified
               .2+.^| 0    | 1    | Store data capability unmodified (`CL ≥ ~SL`)
                           | 0    | Store data capability with validity tag cleared (`CL < ~SL`)
|==============================================================================

NOTE: if W=0 or C=0 then SL is irrelevant

.{cheri_1levels_ext_name} additional rules for loading capabilities
[#cap_level_load_summary,width="100%",options=header,align=center,cols="1,1,1,1,1,1,6"]
|==============================================================================
   4+|Auth cap field                  2+| Data cap field |
    h|*R*   h|*C* h|*EL*      h|*CL*   h| Tag h| Sealed h|Action
.2+.^|1 .2+.^| 1 .2+.^| 0 .2+.^| X .2+.^| 1    | Yes     |Load data capability with `CL=min(auth.CL, data.CL)`, EL unchanged
                                               | No      |Load data capability with `EL=0, CL=min(auth.CL, data.CL)`
   6+| All other cases                                   |Load data capability with EL, CL unmodified
|==============================================================================

NOTE: The current specification only defines up to two levels, equivalent to _local_ and _global_ capabilities from CHERI v9, Morello and CHERIoT.
Future extensions are permitted to add more levels.

[#sec_cap_sdp]
==== Software-Defined Permissions (SDP)
The metadata also contains an encoding-dependent number of software-defined permission (SDP) bits.
They can be inspected by the kernel or application programs to enforce restrictions on API calls (e.g. permit/deny system calls, memory allocation, etc.), but are not interpreted by the CPU otherwise.

NOTE: While these bits are not interpreted by the hardware, modification follows the same rules as architectural permissions: SDP bits can only be cleared and never set.
This property is required to ensure restricted programs cannot forge capabilities that would pass the software-enforced checks.

[#section_special_caps]
==== Special Capabilities

[#infinite-cap,reftext="Infinite"]
===== Infinite Capability

The _Infinite_ capability grants all permissions while its bounds also cover the whole address space.
All capability checks pass when performed against an <<infinite-cap>> capability.
The in-memory encoding of the _Infinite_ capability is described in <<section_infinite_cap_encoding>>.

NOTE: The _Infinite_ capability is also known as 'default', 'almighty', or 'root' capability in other CHERI documentation.

[#null-cap,reftext="NULL"]
===== NULL Capability
A capability with all-zeroes metadata, an unset validity tag, and an address of zero is referred to as the _NULL_ capability.
This capability grants no permissions and any dereference results in a CHERI exception.
The memory representation of the <<null-cap>> capability is all zeroes.

=== Added State

A CHERI core adds state to allow capabilities to be used from within integer (X) registers, and to ensure they are not corrupted as they flow through the system.
This means the following state is added by {cheri_base_ext_name}:

.CHERI Capability registers extending existing integer registers in {cheri_base_ext_name}
[#base_cap_registers]
[bytefield]
----
(defattrs :plain [:plain {:font-family "M+ 1p Fallback" :font-size 40}])
(def row-height 100)
(def row-header-fn nil)
(def boxes-per-row 65)
(draw-column-headers {:height 30 :font-size 25 :labels (concat ["" "2*XLEN (CLEN)"] (repeat 31 "") ["XLEN"] (repeat 30 "") ["0"])})

(draw-box "" [:box-first {:span 1}]) (draw-box "c0" [:box-related {:span 32}]) (draw-box "x0" [:box-last {:span 32 }])
(draw-box "" [:box-first {:span 1}]) (draw-box "c1" [:box-related {:span 32}]) (draw-box "x1" [:box-last {:span 32 }])
(draw-gap "c2-c30 (extending x2-x30)")
(draw-box "" [:box-first {:span 1}]) (draw-box "c31" [:box-related {:span 32}]) (draw-box "x31" [:box-last {:span 32 }])
(draw-box nil [:box-first {:span 1}]) (draw-box "pcc" [:box-related {:span 32}]) (draw-box "pc" [:box-last {:span 32 }])
(draw-box "V" {:span 1 :borders {}}) (draw-box "Metadata" {:span 32 :borders {}}) (draw-box "Address" {:span 32 :borders {}})
----

==== Extended general purpose integer registers
The <<gprs,XLEN-wide integer registers>> (e.g. `sp`, `a0`) are all extended with another XLEN bits of capability metadata plus a validity tag bit.
When referring to the extended register, the `x` prefix is replaced with a `c`: i.e. the capability extended version of `x0` becomes `c0`.
The existing integer register names refer to the address part of the capability.
For the ABI register names the `c` prefix is added, i.e. `csp`, `ca0`.
The zero register is extended with zero metadata and a cleared validity tag: this is called the <<null-cap>> capability.

NOTE: Instruction encodings refer to capability registers when they use `cs1`, `cd`, etc. instead of `rs1`, `rd` (which reads/writes the XLEN-bit subset of the register).

==== Extended CSRs
All registers that store addresses are extended to contain capabilities.
In the base {cheri_base_ext_name} ISA, only the program counter (`pc`) register is extended to become the Program Counter Capability (<<pcc>>).
``

NOTE: All CSRs that hold pointers are extended to CLEN bits, but since no CSRs are defined in the RV32I/RV64I base instruction set, any such change is described in the corresponding chapters.

[#pcc,reftext="pcc"]
===== The Program Counter Capability (`pcc`)

The `pc` is extended to be the Program Counter Capability.
Extending the `pc` allows the range of branches, jumps and linear execution for currently executing code to be restricted.
The <<pcc>> address field is the `pc` in the base RISC-V ISA so that the
hardware automatically updates it as instructions are executed.

The hardware performs the following checks on <<pcc>> for each instruction
executed in addition to the checks already required by the base RISC-V ISA. A
failing check causes a CHERI exception.

* The validity tag must be set
* The capability must not be sealed
* The capability must grant execute permission
* All bytes of the instruction must be in bounds

On startup <<pcc>> bounds and permissions must be set such that the program can run successfully (e.g. by setting it to <<infinite-cap>> to ensure _all_ instructions are in bounds).

NOTE: Operations that update <<pcc>>, such as changing privilege or executing jump instructions, unseal capabilities prior to writing.
Therefore, implementations do not need to check that that <<pcc>> is unsealed when executing each instruction.
However, this property has not yet been formally verified and may not hold if additional CHERI extensions beyond {cheri_base_ext_name} are implemented.

.Program Counter Capability
[#pcc-format]
include::img/pccreg.edn[]

<<pcc>> is a code capability, so it does not need to be able to hold all possible invalid addresses.
//FIXME! ref to priv here, need associated text there instead?
// (see <<section_invalid_addr_conv>>).

==== Tags in registers, caches, and memory

Every register has a one-bit validity tag, indicating whether the capability in the register is valid to be dereferenced.
This validity tag is cleared whenever an invalid capability operation is performed.
Examples of such invalid operations include writing only the integer portion of the register or attempting to increase bounds or permissions.

The validity tags are also tracked through the memory subsystem: every aligned CLEN-bit wide region has a non-addressable one-bit validity tag, which the hardware manages atomically with the data.
The validity tag is cleared if the memory region is ever written using an operation other than a store of a full capability register with <<c_perm>> granted.
Any system memory and caches that store capabilities must preserve this abstraction.

[#sec_cap_checks]
=== Capability checks

With {cheri_base_ext_name}, every memory access performed by a CHERI core must be authorized by a capability.
Instruction fetches, branches, jumps, and data memory accesses may result in a fatal trap if the authorizing capability is missing the required <<sec_cap_ap,permissions>> or the access is out of <<sec_cap_bounds,bounds>>.
For example, loads instruction requires <<r_perm>>, stores require <<w_perm>> and jumps require <<x_perm>>.
See <<sec_cheri_exception_handling,_CHERI Exception handling_ in the privileged specification>> for further details on the exception reporting mechanism.
Instruction fetch is also authorized by a capability: the program counter capability (<<pcc>>) which extends PC.
This allows code fetch to be bounded, preventing a wide range of attacks that subvert control flow with integer data.

The authorizing capability is either named explicitly (the base register of a load/store operation) or implicitly (when executing a branch, <<pcc>> is used for authorization).
For example, `lw t0, 16(csp)` loads a word from memory, getting the address, bounds, and permissions from the `csp` (capability stack pointer) register.

No other exception paths are added by {cheri_base_ext_name}: in particular, capability manipulations do not trap, but may clear the validity tag on the result capability if the operation is not permitted.

[#section_cap_instructions]
=== New and modified Instructions

{cheri_base_ext_name} adds new instructions to interact with the extended registers.
These added instructions can be split into the following categories:

Capability manipulations (e.g. <<SCBNDS>>, <<ACPERM>>)::
For security, capabilities can only be modified in restricted ways.
Special instructions are provided to copy capabilities or perform these allowed operations, for example _shrinking_ the bounds or _reducing_ the permissions.
Any attempt to manipulate capabilities without using the instructions clears the validity tag, rendering them unusable for accessing memory.
They do not cause exceptions.

Pointer arithmetic (e.g. <<CADD>>, <<CADDI>>)::
To update where a capability points new capability instructions must be used instead of an integer ADD/ADDI.
These instructions include a check that the result can be <<section_cap_representable_check,represented exactly>>, therefore is still valid for the current metadata.
Invalid (e.g., significantly out-of-bounds) updates clear the validity tag.

Capability inspection (e.g. <<GCBASE>>, <<GCPERM>>)::
Capability fields (for example the _bounds_ describing what addresses the capability gives access to) are stored compressed in registers and memory.
These instructions give convenient access to allow software to query them.
  They do not cause exceptions.

Memory access instructions (e.g. <<LC>>, <<SC>>)::
Capabilities must be read from and written to memory atomically along with their validity tag.
Instructions are added to perform these capability-width accesses, allowing capabilities to flow between the memory and the register file.

Miscellaneous instructions (e.g. <<SCSS>>)::
These instructions either compare capabilities or allow software to determine the alignment of bounds.
They do not cause exceptions.

Additionally, all instructions that handle addresses have altered behavior when using {cheri_base_ext_name} as the base ISA.
The lower XLEN-bits of the result is always the same, but {cheri_base_ext_name} adds checks that may result in exceptions and specifies handling of the metadata.

The new and modified instructions are listed in the following sections of this chapter.

<<<

=== Capability Manipulation Instructions

.Capability manipulation instruction summary in {cheri_base_ext_name}
[#tab_cap_manip_summary,%autowidth,options=header,align="center",cols="1,4"]
|=======================
|Mnemonic     |Description
|<<ACPERM>>   |AND capability permissions (expand to 1-bit per permission before ANDing)
|<<CADDI>>    |Increment capability address by immediate, representability check
|<<CADD>>     |Increment capability address by register, representability check
|<<CMV>>      |Move capability register
|<<SCADDR>>   |Replace capability address, representability check
|<<SCHI>>     |Set metadata and clear tag
|<<SCBNDSI>>  |Set immediate bounds on capability with rounding, clear tag if rounding is required
|<<SCBNDS>>   |Set register bounds on capability with rounding, clear tag if rounding is required
|<<SCBNDSR>>  |Set bounds on capability with rounding up as required
|<<SENTRY>>   |Seal capability
|<<CBLD>>     |Set cd to cs2 with its tag set after checking that cs2 is a subset of cs1
|=======================

//|<<CSRRW_CHERI>>|✔|✔|||||||||||||CSR write - can also read/write a full capability through an address alias
//|<<CSRRS_CHERI>>|✔|✔|||||||||||||CSR set - can also read/write a full capability through an address alias
//|<<CSRRC_CHERI>>|✔|✔|||||||||||||CSR clear - can also read/write a full capability through an address alias
//|<<CSRRWI_CHERI>>|✔|✔|||||||||||||CSR write - can also read/write a full capability through an address alias
//|<<CSRRSI_CHERI>>|✔|✔|||||||||||||CSR set - can also read/write a full capability through an address alias
//|<<CSRRCI_CHERI>>|✔|✔|||||||||||||CSR clear - can also read/write a full capability through an address alias
//|<<CBO.INVAL>>|✔|✔|||✔||||||||||Cache block invalidate (implemented as clean)
//|<<CBO.CLEAN>>|✔|✔|||✔||||||||||Cache block clean
//|<<CBO.FLUSH>>|✔|✔|||✔||||||||||Cache block flush
//|<<CBO.ZERO>>|✔|✔|||✔||||||||||Cache block zero
//|<<PREFETCH.R>>|✔|✔|||✔||||||||||Prefetch instruction cache line, always valid
//|<<PREFETCH.W>>|✔|✔|||✔||||||||||Prefetch read-only data cache line
//|<<PREFETCH.I>>|✔|✔|||✔||||||||||Prefetch writeable data cache line
//|<<LR.C>>|✔|✔|✔||||||||||||Load reserved capability
//|<<SC.C>>|✔|✔|✔||||||||||||Store conditional capability
//|<<AMOSWAP.C>>|✔|✔|✔||||||||||||Atomic swap of cap
//|<<HLV.C>>|✔|✔|||||||||||||Hypervisor virtual machine load capability
//|<<HSV.C>>|✔|✔|||||||||||||Hypervisor virtual machine store capability

include::insns/acperm_32bit.adoc[]
include::insns/cadd_32bit.adoc[]
include::insns/cmv_32bit.adoc[]
include::insns/scaddr_32bit.adoc[]
include::insns/schi_32bit.adoc[]
include::insns/scbnds_32bit.adoc[]
include::insns/scbndsr_32bit.adoc[]
include::insns/sentry_32bit.adoc[]
include::insns/cbld_32bit.adoc[]

<<<

=== Capability Inspection Instructions

.Capability inspection instruction summary in {cheri_base_ext_name}
[#tab_cap_inspection_summary,%autowidth,options=header,align="center",cols="1,4"]
|=======================
|Mnemonic   |Description
|<<GCTAG>>  |Get tag field
|<<GCPERM>> |Get hperm and uperm fields as 1-bit per permission, packed together
|<<GCTYPE>> |Get capability type
|<<GCBASE>> |Get capability base
|<<GCLEN>>  |Get capability length
|<<GCHI>>   |Get metadata
|=======================

include::insns/gctag_32bit.adoc[]
include::insns/gcperm_32bit.adoc[]
include::insns/gctype_32bit.adoc[]
include::insns/gcbase_32bit.adoc[]
include::insns/gclen_32bit.adoc[]
include::insns/gchi_32bit.adoc[]

<<<

=== Miscellaneous Capability Instructions

.Miscellaneous capability instruction summary in {cheri_base_ext_name}
[#tab_cap_misc_summary,%autowidth,options=header,align="center",cols="1,4"]
|=======================
|Mnemonic   |Description
|<<SCEQ>>   |Full capability bitwise compare, set result true if both are fully equal
|<<SCSS>>   |Set result true if cs1 and cs1 tags match and cs2 bounds and permissions are a subset of cs1
|<<CRAM>>   |Representable Alignment Mask: Return mask to apply to address to get the requested bounds
|=======================

include::insns/sceq_32bit.adoc[]
include::insns/scss_32bit.adoc[]
include::insns/cram_32bit.adoc[]

<<<

[#sec_cap_load_store]
=== Capability Load, Store Instructions

New loads and stores are introduced to handle capabilities.
They all operate in the same manner as the base ISA but access CLEN bits and also the validity tag.

All capability memory accesses requires <<c_perm>> in the authorizing capability.
If <<c_perm>> is not granted then:

* All capability loads will return CLEN-bits from memory, and a zero validity tag.
* All capability stores will write CLEN-bits to memory, and write a zero validity tag.

All capability memory access instructions require CLEN aligned addresses, and will
take the appropriate misaligned exception if this requirement is not met.

All capability memory accesses require permission from the authorizing capability in *cs1*.

* All capability loads require <<r_perm>>, otherwise they will take an exception
* All capability stores require <<w_perm>>, otherwise they will take an exception

NOTE: Misaligned capability memory accesses cannot be emulated.
  To transfer CLEN misaligned bits without a validity tag, use integer loads and stores.

Under some circumstances <<LC>> will _modify_ metadata before returning the value.
See <<LC>> for details.

.Capability load/store instruction summary in {cheri_base_ext_name}
[#tab_cap_ldst_summary,%autowidth,options=header,align="center",cols="1,4"]
|=======================
|Mnemonic   |Description
|<<LC>>     |Load capability
|<<SC>>     |Store capability
|=======================

include::insns/load_32bit_cap.adoc[]
include::insns/store_32bit_cap.adoc[]

<<<

[#section_existing_riscv_insns]
=== Changes to Existing RISC-V Base ISA Instructions

{cheri_base_ext_name} extend existing instructions which are used for handling addresses so that they manipulate a whole capability.
The affected operands change type from *x* to *c* to represent this, and/or the PC is replaced by the <<pcc>>

In the base ISA this affects <<AUIPC_CHERI>> and all jumps and branches as well as loads and stores.

The rules for modifying the behavior of such instructions are:

* Whenever the PC is handled, it is _always_ the <<pcc>>.
* Any instruction that has a base address register (generally `rs1`) reads the full capability register instead.
** This capability register is used to <<sec_cap_checks,check whether the access should be permitted>>.
* Any instruction writes back an address (e.g. <<AUIPC_CHERI>>), writes a full capability register instead.
* Whenever the address field of any capability (including the <<pcc>>) is modified, it is _always_ updated using <<SCADDR>> semantics.
** This includes adding an offset to the <<pcc>> from jumps and branches for both the target address and the link register.
 In this case, for example, `new_pcc = SCADDR(old_pcc, offset)`
* All jumps and branches check that a minimum sized instruction (2 or 4 bytes) is in bounds the target PC.
** An exception is taken on failure.
* <<JALR_CHERI>> copies _all_ of `cs1` into the <<pcc>>. If `cs1` is not suitable for execution then an exception is taken (see <<pcc>> for the definition).

These rules affect the following <<rv32,base ISA>> instructions listed in <<tab_cap_base_summary>>.

IMPORTANT: These rules also apply to instructions added by other extensions (e.g. floating-point/vector loads/stores or the shift-and-add instruction from <<zba,Zba>>).

//TODO: <<app_cheri_instructions>> has listings for all unprivileged instructions that change behavior when {cheri_base_ext_name} is used as the base ISA.

.Changed RISC-V base ISA instructions summary in {cheri_base_ext_name}
[#tab_cap_base_summary,%autowidth,options=header,align="center",cols="2,4"]
|=======================
|Mnemonic                   |Description
|<<AUIPC_CHERI>>            |Add immediate to PCC address, return capability
|<<JAL_CHERI>>              |Jump to PC+offset, bounds check minimum size target instruction, link to cd
|<<JALR_CHERI>>             |Indirect jump and link, bounds check minimum size target instruction.
|<<insns-conbr-32bit_CHERI,BEQ, BNE, BLT[U], BGE[U]>>|Conditional branches (checked by <<pcc>>)
|<<section_int_load_store_insns,LD, LW[U], LH[U], LB[U]>>|Integer loads (authorized by capability registers)
|<<section_int_load_store_insns,SD, SW, SH, SB>>|Integer stores (authorized by capability registers)
|=======================

include::insns/auipc_32bit.adoc[]
include::insns/jal_32bit.adoc[]
include::insns/jalr_32bit.adoc[]

//==== Unconditional Jumps
//
//Unconditional jumps operate as described in <<ct-insns,the base RISC-V ISA>> but with added bounds and permission checks.
//For jump-and-link instructions, the value written to the link register is a full capability derived from <<pcc>> with the address updated //to the link address.
// //CHERIoT compatiblity
//If the resulting capability cannot be <<section_cap_representable_check,<<section_cap_representable_check,represented exactly>> then the validity tag is cleared.
//The resulting jump address is checked against <<pcc>> as described below.
//Additionally, the link register is sealed (as if executing an implicit <<SENTRY>>) to ensure that the callee cannot modify the return //address and (maliciously) return to an incorrect instruction.
//
//For indirect jumps, the authorizing capability is not <<pcc>> but the base capability register in *cs1*.
//
//The target capability is unsealed if it is a sentry and the instructions has a zero immediate offset.
//
//<<JALR_CHERI>> causes a CHERI exception when:
//
//* The target capability's validity tag is zero
//* The target capability is sealed and the immediate is not zero
//* A minimum sized instruction (2 or 4 bytes depending on enabled extensions) at the target capability's address is not
//within bounds
//* The target capability does not grant <<x_perm>>
//
//<<JAL_CHERI>> and <<JALR_CHERI>> can also cause instruction address misaligned exceptions
//following the standard RISC-V rules.


//[#condbr-purecap]
//==== Conditional Branches
//
//Conditional branch instructions compare two *x* registers as described in the base RISC-V
//ISA, so the metadata and tag values are disregarded in the comparison if the
//operand registers hold capabilities. If the comparison evaluates to true, then
//the target address is installed in the <<pcc>>'s address field.
//These instructions cause CHERI exceptions when a minimum sized instruction at the target address is not within the <<pcc>>'s bounds.

include::insns/condbr_32bit.adoc[]

[#section_int_load_store_insns,reftext="Loads and Stores"]
==== Load and Store Instructions ({cheri_base_ext_name})

All load and store instructions behave as described in <<ldst>> with one fundamental difference:

* For the base operand (`rs1`), the full capability register `cs1` is used to authorize the resulting memory access.

All load and store instructions authorized by `cs1` cause CHERI exceptions if any of these checks fails:

* `cs1` must not be `c0`^1^
* The validity tag (`cs1.tag`) must be set, and there must be no reserved bits set in `cs1`.
* `cs1` must be unsealed
* The virtual address in `cs1` must not be invalid if virtual memory is enabled.
* All bytes of accessed memory must be inside `cs1's` bounds, and the bounds can't be <<section_cap_malformed,malformed>>.
* For loads, the <<r_perm,read permission>> must be set in `cs1`
* For stores, the <<w_perm,write permission>> must be set in `cs1`

^1^ All load/store encodings are _reserved_ if `cs1=c0` (since dereferencing <<null-cap>> always faults).
 This principle is extended to _all_ loads and stores authorized by `cs1`.

Non-capability load instructions always zero the validity tag and metadata of the result register.

Non-capability stores write zero to the validity tag associated with the memory locations that are naturally aligned to CLEN.
Therefore, misaligned stores may clear up to two validity tag bits in memory.

NOTE: The changed interpretation of the base register also applies to all loads and stores defined in later chapters of this specification (including floating-point and vector loads/stores).
 Under {cheri_base_ext_name} _all_ loads and stores are authorized by `cs1`.
