= RISC-V Debug Specification for CHERI Extensions
Authors: Thomas Aird, Hesham Almatary, Andres Amaya Garcia, John Baldwin, Paul Buxton, David Chisnall, Jessica Clarke, Brooks Davis, Nathaniel Wesley Filardo, Franz A. Fuchs, Timothy Hutt, Alexandre Joannou, Martin Kaiser, Tariq Kurd, Ben Laurie, Marno van der Maas, Maja Malenko, A. Theodore Markettos, David McKay, Jamie Melling, Stuart Menefy, Simon W. Moore, Peter G. Neumann, Robert Norton, Alexander Richardson, Michael Roe, Peter Rugg, Peter Sewell, Carl Shaw, Ricki Tura, Robert N. M. Watson, Toby Wenman, Jonathan Woodruff, Jason Zhijingcheng Yu, Robert Riglar, Florian Schmaus
include::attributes-standalone.adoc[]

///////////////////////////////////////////////////////////////////////////////
// Preface
///////////////////////////////////////////////////////////////////////////////

ifdef::github_commit_sha[]
[IMPORTANT]
This document is a specification snapshot built from https://github.com/riscv/riscv-cheri/commit/{github_commit_sha} and is not a versioned release.
The latest versioned PDF release can be downloaded from https://github.com/riscv/riscv-cheri/releases.
endif::[]

[WARNING]
.This document is in the link:https://lf-riscv.atlassian.net/wiki/display/HOME/Specification+States[Stable state]
====
Assume anything could still change, but limited change should be expected.
====

include::debug-integration.adoc[]
