[#tid_ext]
== "{tid_ext_name}" Extension for Software Thread Identification

{tid_ext_name} is an optional extension to the RISC-V base ISA.
Implementations that support {cheri_base_ext_name} and {tid_ext_name}
define a variant of the CHERI ISA that allows for more efficient
software compartmentalization of CHERI programs.

=== Control and Status Registers (CSRs)

{tid_ext_name} adds new CSRs to implement a trusted software thread
identifier (TID) used in compartmentalization. These CSRs are listed in
xref:tid-mcsrnames-added[xrefstyle=short],
xref:tid-scsrnames-added[xrefstyle=short],
xref:tid-vscsrnames-added[xrefstyle=short] and
xref:tid-ucsrnames-added[xrefstyle=short].

[[tid-mcsrnames-added]]
.Added machine-mode CSRs in {tid_ext_name}
[%autowidth,float="center",align="center",cols="<,<,<,<,<,<",options="header"]
|===
|{tid_ext_name} CSR|Address|Prerequisites|Read-Permission|Write-Permission|Description
|<<mtid>>|0x780|M-mode|M|M, <<asr_perm>>|Machine Thread Identifier
|===

[[tid-scsrnames-added]]
.Added supervisor-mode CSRs in {tid_ext_name}
[%autowidth,float="center",align="center",cols="<,<,<,<,<,<",options="header"]
|===
|{tid_ext_name} CSR|Address|Prerequisites|Read-Permission|Write-Permission|Description
|<<stid>>|0x580|S-mode|S|S, <<asr_perm>>|Supervisor Thread Identifier
|===

[[tid-vscsrnames-added]]
.Added virtual supervisor-mode CSRs in {tid_ext_name}
[%autowidth,float="center",align="center",cols="<,<,<,<,<,<",options="header"]
|===
|{tid_ext_name} CSR|Address|Prerequisites|Read-Permission|Write-Permission|Description
|<<vstid>>|0xA80|VS-mode|S|H, <<asr_perm>>|Virtual Supervisor Thread Identifier
|===

[[tid-ucsrnames-added]]
.Added user-mode CSRs in {tid_ext_name}
[%autowidth,float="center",align="center",cols="<,<,<,<,<,<",options="header"]
|===
|{tid_ext_name} CSR|Address|Prerequisites|Read-Permission|Write-Permission|Description
|<<utid>>|0x480|U-mode|U|U, <<asr_perm>>|User Thread Identifier
|===



=== Machine-Level, Supervisor-Level and Unprivileged CSRs

[#mtid,reftext="mtid"]
==== Machine Thread Identifier (mtid)

The <<mtid>> register is an MXLEN-bit read-write register. It is used to
identify the current software thread in machine mode. The reset value of this
register is UNSPECIFIED.

.Supervisor thread identifier register
include::img/mtidreg.edn[]

[#stid,reftext="stid"]
==== Supervisor Thread Identifier (stid)

The <<stid>> register is an SXLEN-bit read-write register. It is used to
identify the current software thread in supervisor mode. The reset value of
this register is UNSPECIFIED.

.Supervisor thread identifier register
include::img/stidreg.edn[]

[#vstid,reftext="vstid"]
==== Virtual Supervisor Thread Identifier (vstid)

The <<vstid>> register is a VSLEN-bit read-write register. It is VS-mode's
version of supervisor register <<stid>> used to identify the current
software thread in virtual supervisor mode. As other Virtual Supervisor registers
when V=1, <<vstid>> substitutes for <<stid>>, so that
instructions that normally read or modify <<stid>> actually access
<<vstid>> instead. When V=0, <<vstid>> does not directly affect the
behavior of the machine.

The reset value of this register is UNSPECIFIED.

.Virtual supervisor thread identifier register
include::img/vstidreg.edn[]

[#utid,reftext="utid"]
==== User Thread Identifier (utid)

The <<utid>> register is an UXLEN-bit read-write register. It is used to
identify the current software thread in user mode. The reset value of
this register is UNSPECIFIED.

.User thread identifier register
include::img/utidreg.edn[]

When {cheri_base_ext_name} is implemented, the {tid_ext_name} CSRs are
extended as follows:

[#mtidc,reftext="mtidc"]
==== Machine Thread Identifier Capability (mtidc)

The <<mtidc>> register extends <<mtid>> to hold a capability.
It is used to identify the current software thread in machine mode.
On reset the tag of <<mtidc>> will be set to 0 and the remainder
of the data is UNSPECIFIED.

.Machine thread identifier capability register
include::img/mtidcreg.edn[]

[#stidc,reftext="stidc"]
==== Supervisor Thread Identifier Capability (stidc)

The <<stidc>> register extends <<stid>> to hold a capability.
It is used to identify the current software thread in supervisor mode.
On reset the tag of <<stidc>> will be set to 0 and the remainder
of the data is UNSPECIFIED.

.Supervisor thread identifier capability register
include::img/stidcreg.edn[]

[#vstidc,reftext="vstidc"]
==== Virtual Supervisor Thread Identifier Capability (vstidc)

The <<vstidc>> register extends <<vstid>> to hold a capability.
It is used to identify the current software thread in virtual supervisor mode.
As other Virtual Supervisor registers when V=1, <<vstidc>> substitutes
for <<stidc>>, so that instructions that normally read or modify
<<stidc>> actually access <<vstidc>> instead.
When V=0, <<vstidc>> does not directly affect the
behavior of the machine.
On reset the tag of <<vstidc>> will be set to 0 and the remainder
of the data is UNSPECIFIED.

.Virtual supervisor thread identifier capability register
include::img/vstidcreg.edn[]

[#utidc,reftext="utidc"]
==== User Thread Identifier Capability (utidc)

The <<utidc>> register extends <<utid>> to hold a capability.
It is used to identify the current software thread in user mode.
On reset the tag of <<utidc>> will be set to 0 and the remainder
of the data is UNSPECIFIED.

.User thread identifier capability register
include::img/utidcreg.edn[]

=== "Smstateen/Ssstateen" Integration

The TID bit controls access to the CSRs in
xref:tid-scsrnames-added[xrefstyle=short],
xref:tid-vscsrnames-added[xrefstyle=short] and
xref:tid-ucsrnames-added[xrefstyle=short] provided by the {tid_ext_name}
extension.

.Machine State Enable 0 Register (`mstateen0`)
[wavedrom, ,svg]
....
{reg: [
{bits: 1, name: 'C'},
{bits: 1, name: 'FCSR'},
{bits: 1, name: 'JVT'},
{bits: 1, name: 'TID'},
{bits: 52, name: 'WPRI'},
{bits: 1, name: 'P1P13'},
{bits: 1, name: 'CONTEXT'},
{bits: 1, name: 'IMSIC'},
{bits: 1, name: 'AIA'},
{bits: 1, name: 'CSRIND'},
{bits: 1, name: 'WPRI'},
{bits: 1, name: 'ENVCFG'},
{bits: 1, name: 'SE0'},
], config: {bits: 64, lanes: 4, hspace:1024}}
....

.Hypervisor State Enable 0 Register (`hstateen0`)
[wavedrom, ,svg]
....
{reg: [
{bits: 1, name: 'C'},
{bits: 1, name: 'FCSR'},
{bits: 1, name: 'JVT'},
{bits: 1, name: 'TID'},
{bits: 53, name: 'WPRI'},
{bits: 1, name: 'CONTEXT'},
{bits: 1, name: 'IMSIC'},
{bits: 1, name: 'AIA'},
{bits: 1, name: 'CSRIND'},
{bits: 1, name: 'WPRI'},
{bits: 1, name: 'ENVCFG'},
{bits: 1, name: 'SE0'},
], config: {bits: 64, lanes: 4, hspace:1024}}
....

.Supervisor State Enable 0 Register (`sstateen0`)
[wavedrom, ,svg]
....
{reg: [
{bits: 1, name: 'C'},
{bits: 1, name: 'FCSR'},
{bits: 1, name: 'JVT'},
{bits: 1, name: 'TID'},
{bits: 28, name: 'WPRI'}
], config:{bits: 32, lanes: 2, hspace:1024}}
....

[#CHERI_COMP,reftext="CHERI Compartmentalization]
=== CHERI Compartmentalization

This section describes how this specification enables support for
compartmentalization for CHERI systems. Compartmentalization seeks
to separate the privileges between different protection units, e.g.,
two or more libraries. Code can be separated by sentries, which allow
for giving out code capabilities to untrusted code where the untrusted
code can only call the code capability, but not modify it. Sentries can
be called from different software threads and thus there needs to be a way of
identifying the current software thread. While identifying the current software thread
can be done by privileged code, e.g., the kernel, the implied performance
overhead of this is not bearable for CHERI systems with many compartments.

The RISC-V ABI includes a _thread pointer (tp)_ register, which is not
usable for the purpose of reliably identifying the current software thread because
the tp register is a general purpose register and can be changed arbitrarily
by untrusted code. Therefore, this specification offers additional CSRs
that facilitate a trusted source for the thread ID. All registers are readable
from their respective privilege levels and writeable with <<asr_perm>>.

This extension extends <<mtid>>, <<stid>>, <<vstid>> and <<utid>> to their respective
capability variants <<mtidc>>, <<stidc>>, <<vstidc>> and <<utidc>>. This presents software with the
freedom to still use these registers with capabilities or leave the metadata
untouched and only use the registers to store integers.
