[#section_cheri_vector_integration]
=== Vector with {cheri_base_ext_name}

ifdef::cheri_standalone_spec[]
WARNING: This chapter should appear as a section in the vector chapter. Exact location TBD.
endif::[]

The Vector extension is orthogonal to {cheri_base_ext_name} because the vector registers do not support valid tags.

NOTE: A future extension may allow valid tags to be stored in vector registers.
  Until that time, vector load and store instructions must not be used to implement generic
  memory copying in software, such as the `memcpy()` standard C library function,
  because the vector registers do not hold capabilities, so the valid tags of any
  copied capabilities will be set to 0 in the destination memory.

Under {cheri_base_ext_name}, vector loads and stores follow the standard rules for _active_ elements:

* Only _active_ elements are subject to CHERI exception checks.
* If there are no _active_ elements then no CHERI exceptions will be raised.
* CHERI exceptions are only raised on fault-only-first loads if element 0 is both _active_ and fails any exception checks.

NOTE: Indexed loads check the bounds of every access against the authorizing capability in `cs1`.
 Therefore the approach of having a zero base register and treating every element as an absolute address may not work well in this mode.
