[#section_zysentry,reftext="{cheri_sentry_ext_name}"]
== "{cheri_sentry_ext_name}" Extension for CHERI Sentry Capabilities

[#sentry_cap,reftext="sentry capability"]
=== Sentry Capabilities

It is useful to have *immutable* function pointers within a CHERI software system.
<<sealed_cap,Sealed capabilities>> are a natural foundation;
sealed capabilities which become unsealed via <<JALR_CHERI>> are dubbed "sentries"
(a portmanteau of "sealed entries").
Sentry capabilities can establish a form of control-flow integrity between mutually distrusting code.

=== Added Capability Type (CT) Semantics

With {cheri_sentry_ext_name}, capability encodings _may_ define:

1. Architectural interpretation of zero or more particular <<sec_cap_type>>
   values when a capability is passed as the input to <<JALR_CHERI>>.

2. Zero or more <<sec_cap_type>> values for use by <<JALR_CHERI>> to seal the
   return capability installed in the link register.

3. Conditional behavior of <<JALR_CHERI>> based on the _register selectors_
   used in an instance of the instruction and the <<sec_cap_type>> value of the
   input capability.

[NOTE]
=====
An example, relatively minimal use of {cheri_sentry_ext_name} could be to
introduce "backward-arc sentries" and require software to explicitly indicate
its intent to return.  Concretely, this could entail defining a single sentry
type and adjusting <<JALR_CHERI>>'s semantics such that...

* All return capabilities are sealed at this sentry type.
* A <<JALR_CHERI>> instruction with input capability register selector `ra`
  must also have zero offset, have a `null` output register selector, and
  require that the capability held in `ra` is a sentry.
* Input sentry capabilities are rejected in all other cases.
=====

=== Common Aspects of <<JALR_CHERI>> And Sentries

In all cases, when a sealed capability is used as the input to <<JALR_CHERI>>,
the instruction must have a zero offset or an exception will be thrown.
If the type of the input capability is suitable for the call
(subject to conditions of point 3 above, but, generally,
`0` or one of the types designated by points 1 or 2 above),
then <<JALR_CHERI>> automatically unseals said input and installs it as the new
<<pcc,program counter capability>>.
The capability encoding may, for a given <<JALR_CHERI>> instance,
also seal the generated link capability (with one of the types from point 2);
this provides some constraints on the callee's behavior,
granting it the right to return _exactly_ to the generated link capability.
(While the callee may hold other capabilities,
possibly even those allowing arbitrary control or data flow,
a sealed link capability generated by <<JALR_CHERI>> does not grant the callee
the rights to return to displaced a address or read or write memory.)

[NOTE]
=====
If a capability encoding also entails the presence of <<section_zyseal>>,
it will be possible for software (bearing suitably permissive capabilities)
to arbitrarily seal and unseal the sentry types that that encoding defines.
This is deliberate.
Software should ensure that the capabilities requisite for such operations are
attenuated, confined to sufficiently trusted components, and/or destroyed.
=====

=== Interaction With <<CBLD>>

#This presumes that https://github.com/riscv/riscv-cheri/pull/760 lands#

Systems which wish both to instantiate {cheri_sentry_ext_name}
with one or more <<sec_cap_type>> values and
to store capabilities separated from their tags
(say, paged out to disk)
should also ensure that the type(s) used with {cheri_sentry_ext_name}
are made architecturally available to software
which reconstitutes capabilities from their encoded bit patterns.
Possible mechanisms for this reconstruction include:

* Instantiation of a sufficient subset of <<section_zyseal>>.
  (This option is recommended, as it affords software
  the implementation of fine-grained security models.)

* If only a single type is used with {cheri_sentry_ext_name},
  instantiating {rvy_sentry_ext_name} such that
  its <<SENTRY>> instruction also seals with this same type.

* Instantiating <<section_zyseal_amb>> such that
  the type(s) used with {cheri_sentry_ext_name}
  are ambiently available to <<YSEAL>>.

* Instantiating <<section_zyseal_amb>>
  the type(s) used with {cheri_sentry_ext_name}
  are available to its <<YBLDS>> instruction.

