[#section_rvy_sentry_jalr_ext,reftext="{rvy_sentry_jalr_ext_name}"]
== "{rvy_sentry_jalr_ext_name}" Extension for CHERI Sentry Capabilities

#New since last ARC review#

[#sentry_cap,reftext="sentry capability"]
=== Sentry Capabilities

It is useful to have *immutable* function pointers within a CHERI software system.
<<sealed_cap,Sealed capabilities>> are a natural foundation;
sealed capabilities which become unsealed via <<JALR_CHERI>> are dubbed "sentries"
(a portmanteau of "sealed entries").
Sentry capabilities can establish a form of control-flow integrity between mutually distrusting code.

=== Added Capability Type (CT) Semantics

With {rvy_sentry_jalr_ext_name}, capability encodings _may_ define:

1. Architectural interpretation of zero or more particular <<sec_cap_type>>
   values when a capability is passed as the input to <<JALR_CHERI>>.

2. Zero or more <<sec_cap_type>> values for use by <<JALR_CHERI>> to seal the
   return capability installed in the link register.

3. Conditional behavior of <<JALR_CHERI>> based on the _register selectors_
   used in an instance of the instruction and the <<sec_cap_type>> value of the
   input capability.

NOTE: All type(s) defined for sealing return capabilities must be acceptable
for unsealing as inputs to <<JALR_CHERI>> as well (in at least some conditions).

NOTE: Unless other mechanisms to construct sealed capabilities are available,
all type(s) defined for sealing return capabilities should be
<<sec_cap_type_ambient,ambiently available>> for (re)construction by <<CBLD>>.

=== Common Aspects of <<JALR_CHERI>> And Sentries

In all cases, when a sealed capability is used as the input to <<JALR_CHERI>>,
the instruction must have a zero offset or an exception will be thrown.
If the type of the input capability is suitable for the call
(subject to conditions of point 3 above, but, generally,
`0` or one of the types designated by points 1 or 2 above),
then <<JALR_CHERI>> automatically unseals said input and installs it as the new
<<pcc,program counter capability>>.
The capability encoding may, for a given <<JALR_CHERI>> instance,
also seal the generated link capability (with one of the types from point 2);
this provides some constraints on the callee's behavior,
granting it the right to return _exactly_ to the generated link capability.
(While the callee may hold other capabilities,
possibly even those allowing arbitrary control or data flow,
a sealed link capability generated by <<JALR_CHERI>> does not grant the callee
the rights to return to displaced a address or read or write memory.)

NOTE: If <<JALR_CHERI>> seals the return capabilities it constructs
and the callee does not otherwise have access to the caller's <<pcc>>,
then the callee is ability to return to the caller.
The callee can return exactly to the instruction after the caller's call,
but cannot apply an offset or displacement to a return sentry.
Moreover, a return sentry does not grant the callee access to the
memory pointed at by the caller's <<pcc>>.
