<<<

[#CLRPERM,reftext="{CLRPERM}"]
==== {CLRPERM}

ifdef::cheri_v9_annotations[]
NOTE: *CHERI v9 Note:* The implementation of this instruction changes
because the permission fields are encoded differently in the new
capability encoding format.

NOTE: *CHERI v9 Note:* this instruction was called CANDPERM.
endif::[]

include::new_encoding_note.adoc[]

Synopsis::
{CLRPERM_DESC}

Mnemonics::
`{clrperm} {cd}, {cs1}, rs2`

Encoding::
include::wavedrom/acperm.adoc[]

Description::
<<CLRPERM>> performs the following operations:

. Convert the <<AP-field>> and <<SDP-field>> fields of capability `{cs1}` into a bit field with the format shown in xref:acperm_bit_field[xrefstyle=short].
. The initial value in register `rs2[XLEN-1:0]` is treated as a bit mask that specifies bit positions to be cleared in the bit field. Any bit that is high in `rs2` will cause the corresponding bit to be cleared in the bit field.
+
NOTE: Future extensions may include hardwired permission bits, in which case they are not cleared by set bits in `rs2`.
. Encode the resulting architectural permissions as specified by the capability encoding format in use.
  This involves applying the rules in <<sec_permission_transitions>>, as well as any rules added by extensions or the capability encoding format.
.. If the capability encoding format does not support the requested set of permissions then <<CLRPERM>> will return a minimal set of permissions, which may be no permissions.
 Therefore, it is possible that requesting to clear a permission also clears others, but <<CLRPERM>> will never _add_ new permissions.
. Copy `{cs1}` to `{cd}`, and update the <<AP-field>> and <<SDP-field>>s with the newly calculated versions.
. Set `{cd}.tag=0` if `{cs1}` is sealed and any bits in the <<AP-field>> or <<SDP-field>> were affected by <<CLRPERM>>.
.. Extensions such as <<section_zylevels1>> add a field to the metadata which is reduced by <<CLRPERM>> even when the capability is sealed.
. Set `{cd}.tag=0` if any <<section_cap_integrity,integrity>> checks fail.

.Capability permissions bit field
[#acperm_bit_field]
include::../img/acperm_bit_field.edn[]

NOTE: If a future extension adds a new permission that is dependent on an existing permission then clearing the original must also clear the new permission.
This ensures software forward-compatibility: for example, a kernel that does not know about finer-grained <<asr_perm, ASR permissions>> must still be able to prevent all access to privileged instructions and CSRs simply by clearing <<asr_perm>>.
Such dependent permissions must be allocated to the bits that are currently reported as 1 to ensure forward-compatibility

Operation::
[source,SAIL,subs="verbatim,quotes"]
----
SAIL TO BE UPDATED
----
