<<<

[#ACPERM,reftext="ACPERM"]
==== ACPERM

ifdef::cheri_v9_annotations[]
NOTE: *CHERI v9 Note:* The implementation of this instruction changes
because the permission fields are encoded differently in the new
capability format.

NOTE: *CHERI v9 Note:* this instruction was called CANDPERM.
endif::[]

include::new_encoding_note.adoc[]

Synopsis::
Mask capability permissions

Mnemonics::
`acperm cd, cs1, rs2`

Encoding::
include::wavedrom/acperm.adoc[]

Description::
ACPERM performs the following operations:

. Convert the AP and SDP fields of capability `cs1` into a bit field with the
format shown in xref:acperm_bit_field[xrefstyle=short].
. Calculate the bitwise AND of the bit field with the mask `rs2`.
+
NOTE: Some permission bits may be hardwired, in which case they are not included in this bitwise AND.
. Encode the resulting architectural permissions following the rules in <<sec_permission_transitions>>.
+
IMPORTANT: Depending on the base ISA and supported extensions, some combinations of permissions cannot be encoded or are not useful.
In case the requested permissions combination falls into this category, <<ACPERM>> will return useful minimal sets of permissions, which may be no permissions.
Therefore, it is possible that requesting to clear a permission also clears others, but <<ACPERM>> will never _add_ new permissions.
. Copy `cs1` to `cd`, and update the AP and SDP fields with the newly calculated versions.
. Set `cd.tag=0` if `cs1` is sealed.
// TODO: reserved fields can only be set through a memory error, should all of this go into an appendix?
// or if any reserved fields of `cs1` are set.

IMPORTANT: The <<el_perm,EL>>, <<sl_perm,SL>> and <<section_cap_level,CL>> fields are only modifiable if the implementation supports {cheri_1levels_ext_name}, for {cheri_0levels_ext_name} they are hardwired to 1.

.Capability permissions bit field
[#acperm_bit_field]
include::../img/acperm_bit_field.edn[]

NOTE: If a future extension adds a new permission that overlaps with an existing permission (e.g., finer-grained <<asr_perm>>), then clearing the original must also clear the new permission.
This ensures software forward-compatibility: for example, a kernel that does not know about finer-grained <<asr_perm>> subsets must still be able to prevent all access to privileged instructions and CSRs by clearing <<asr_perm>>.

[#section_cap_level_change]
[NOTE]
====
While <<section_cap_level,capability levels (CL)>> are conceptually a label on the capability rather than a permission granted by the capability, they are still adjusted using the <<ACPERM>> instruction.
This avoids the need for a dedicated instruction and allows reducing the level and removing <<el_perm>> in a single instruction.
====

Operation::
+
sail::execute[clause="ACPERM(_, _, _)",part=body,unindent]
