<<<

[#C_ADDI4SPN,reftext="C.ADDI4SPN"]
==== C.ADDI4SPN

Synopsis::
Stack pointer increment in blocks of 4 (C.ADDI4SPN), 16-bit encoding

{cheri_cap_mode_name} Mnemonic::
`c.addi4spn cd', nzuimm`

{cheri_cap_mode_name} Expansion::
`caddi cd', ysp, nzuimm`

{cheri_int_mode_name} Mnemonic::
`c.addi4spn rd', nzuimm`

{cheri_int_mode_name} Expansion::
`addi rd', sp, nzuimm`

Encoding::
include::wavedrom/c-ciw.adoc[]

{cheri_cap_mode_name} Description::

Add a zero-extended non-zero immediate, scaled by 4, to the stack pointer, `ysp`, and writes the result to `cd'`. This instruction is used to generate pointers to stack-allocated variables. Clear the valid tag if the resulting capability is unrepresentable or `ysp` is sealed.

include::malformed_clear_tag_csp.adoc[]

{cheri_int_mode_name} Description::

Add a zero-extended non-zero immediate, scaled by 4, to the stack pointer, `sp`, and writes the result to `rd'`. This instruction is used to generate pointers to stack-allocated variables.

Prerequisites for C.ADDI4SPN::
{c_cheri_base_ext_names}

Prerequisites for C.ADDI4SPN::
{c_cheri_default_ext_names}

{cheri_cap_mode_name} Operation::
+
sail::execute[clause="C_ADDI4SPN_capmode(_, _)",part=body,unindent]
