<<<

[#C_ADDI4SPN_CHERI,reftext="C.ADDI4SPN ({cheri_base_ext_name})"]
==== C.ADDI4SPN ({cheri_base_ext_name})

Synopsis::
Stack pointer increment in blocks of 4 (C.ADDI4SPN), 16-bit encoding

Mnemonic::
`c.addi4spn cd', nzuimm`

Expansion::
`caddi cd', ysp, nzuimm`

NOTE: The suggested assembly syntax distinguishes from integer `c.addi4spn` by operand type.

//{cheri_int_mode_name} Mnemonic::
//`c.addi4spn rd', nzuimm`

//{cheri_int_mode_name} Expansion::
//`addi rd', sp, nzuimm`

Encoding::
include::wavedrom/c-ciw.adoc[]

include::cheri_mode_dependent.adoc[]

Description::

Copy `ysp` to `cd'`. Add a zero-extended non-zero immediate, scaled by 4, to `cd'.address`.
+
Set `cd'.tag=0` if `ysp` is sealed.
+
Set `cd'.tag=0` if the resulting capability cannot be <<section_cap_representable_check,represented exactly>>.
+
Set `cd'.tag=0` if `ysp` 's bounds are <<section_cap_malformed,malformed>>, or if any of the reserved fields are set.

{cheri_int_mode_name} Description::

Add a zero-extended non-zero immediate, scaled by 4, to the stack pointer, `sp`, and writes the result to `rd'`. This instruction is used to generate pointers to stack-allocated variables.

Prerequisites for C.ADDI4SPN::
{c_cheri_base_ext_names}

Prerequisites for C.ADDI4SPN::
{c_cheri_default_ext_names}

{cheri_cap_mode_name} Operation::
+
sail::execute[clause="C_ADDI4SPN_capmode(_, _)",part=body,unindent]
