<<<

[#C_ADDI4SPN_CAP,reftext="{C_ADDI4SPN_CAP}"]
==== {C_ADDI4SPN_CAP}

Synopsis::
Stack pointer increment in blocks of 4 ({C_ADDI4SPN_CAP}), 16-bit encoding

Mnemonic::
`{C_ADDI4SPN_CAP_LC} cd', nzuimm`

Expansion::
`{caddi_lc} cd', {abi_creg}sp, nzuimm`

Encoding::
include::wavedrom/c-ciw.adoc[]

NOTE: This encoding is shared with integer `c.addi4spn`.

include::cheri_mode_dependent.adoc[]

Description::

Copy `{abi_creg}sp` to `cd'`. Add a zero-extended non-zero immediate, scaled by 4, to `cd'.address`.
+
Set `cd'.tag=0` if `{abi_creg}sp` is sealed.
+
Set `cd'.tag=0` if the resulting capability cannot be <<section_cap_representable_check,represented exactly>>.
+
Set `cd'.tag=0` if `{abi_creg}sp` 's bounds are <<section_cap_malformed,malformed>>, or if any of the reserved fields are set.

{cheri_int_mode_name} Description::

Add a zero-extended non-zero immediate, scaled by 4, to the stack pointer, `sp`, and writes the result to `rd'`. This instruction is used to generate pointers to stack-allocated variables.

Prerequisites::
{c_cheri_default_ext_names}

{cheri_cap_mode_name} Operation::
+
sail::execute[clause="C_ADDI4SPN_capmode(_, _)",part=body,unindent]
