<<<

[#C_ADDI16SP, reftext="C.ADDI16SP"]
==== C.ADDI16SP

Synopsis::
Stack pointer increment in blocks of 16 (C.ADDI16SP), 16-bit encodings

{cheri_cap_mode_name} Mnemonic::
`c.addi16sp nzimm`

{cheri_cap_mode_name} Expansion::
`caddi csp, csp, nzimm`

{cheri_int_mode_name} Mnemonic::
`c.addi16sp nzimm`

{cheri_int_mode_name} Expansion::
`addi sp, sp, nzimm`

Encoding::
include::wavedrom/c-int-reg-immed.adoc[]

{cheri_cap_mode_name} Description::

Add the non-zero sign-extended 6-bit immediate to the value in the stack pointer (`csp=c2`), where the immediate is scaled to represent multiples of 16 in the range (-512,496). Clear the validity tag if the resulting capability is
unrepresentable or `csp` is sealed.

include::malformed_clear_tag_csp.adoc[]

{cheri_int_mode_name} Description::

Add the non-zero sign-extended 6-bit immediate to the value in the stack pointer (`sp=x2`), where the immediate is scaled to represent multiples of 16 in the range (-512,496).

Prerequisites for {cheri_cap_mode_name}::
{c_cheri_base_ext_names}

Prerequisites for {cheri_int_mode_name}::
{c_cheri_default_ext_names}

{cheri_cap_mode_name} Operation::
+
sail::execute[clause="C_ADDI16SP_capmode(_)",part=body,unindent]
