<<<

[#ADD_UW,reftext="ADD.UW"]
==== ADD.UW

Synopsis::
Add unsigned word for address generation

{cheri_cap_mode_name} Mnemonic (RV64)::
`add.uw yd, rs1, ys2`

{cheri_int_mode_name} Mnemonic (RV64)::
`add.uw rd, rs1, rs2`

Encoding::
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x3b, attr: ['OP'] },
    { bits:  5, name: 'yd' },
    { bits:  3, name: 0x0, attr: ['rv64: ADD.UW'] },
    { bits:  5, name: 'rs1' },
    { bits:  5, name: 'ys2' },
    { bits:  7, name: 0x04, attr: ['rv64: ADD.UW'] },
]}
....

{cheri_cap_mode_name} Description::
Increment the address field of `ys2` by the unsigned word in `rs1`. Clear the valid tag if the resulting capability is unrepresentable or `ys2` is sealed.

{cheri_int_mode_name} Description::
Increment `rs2` by the unsigned word in `rs1`.

Prerequisites for {cheri_cap_mode_name}::
RV64, {cheri_base_ext_name}, Zba

Prerequisites for {cheri_int_mode_name}::
RV64, {cheri_default_ext_name}, Zba

{cheri_cap_mode_name} Operation::
+
sail::execute[clause="ZBA_RTYPEUW_capmode(_, _, _, _)",part=body,unindent]

{cheri_int_mode_name} Operation::
+
sail::execute[clause="ZBA_RTYPEUW(_, _, _, _)",part=body,unindent]
