<<<

[#ADD_UW_CHERI,reftext="ADD.UW ({cheri_base_ext_name})"]
==== ADD.UW ({cheri_base_ext_name})

Synopsis::
Add unsigned word for address generation

Mnemonic (RV64)::
`add.uw cd, rs1, cs2`

//{cheri_int_mode_name} Mnemonic (RV64)::
//`add.uw rd, rs1, rs2`

Encoding::
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x3b, attr: ['OP'] },
    { bits:  5, name: 'cd' },
    { bits:  3, name: 0x0, attr: ['rv64: ADD.UW'] },
    { bits:  5, name: 'rs1' },
    { bits:  5, name: 'cs2' },
    { bits:  7, name: 0x04, attr: ['rv64: ADD.UW'] },
]}
....

include::cheri_mode_dependent.adoc[]

Description::
Copy the capability in `cs2` to `cd`.
+
Increment `cd.address` by the unsigned word in `rs1`.
+
Set `cd.tag=0` if `cs2` is sealed.
+
include::rep_range_check.adoc[]
+
include::malformed_shadd_clear_tag.adoc[]

//{cheri_int_mode_name} Description::
//Increment `rs2` by the unsigned word in `rs1`.

Prerequisites::
RV64, {cheri_base_ext_name}, Zba

//Prerequisites for {cheri_int_mode_name}::
//RV64, {cheri_default_ext_name}, Zba

{cheri_cap_mode_name} Operation::
+
sail::execute[clause="ZBA_RTYPEUW_capmode(_, _, _, _)",part=body,unindent]

//{cheri_int_mode_name} Operation::
//+
//sail::execute[clause="ZBA_RTYPEUW(_, _, _, _)",part=body,unindent]
