<<<

[#CADDI,reftext="{CADDI}"]
==== {CADDI}

See <<CADD>>.

[#CADD,reftext="{CADD}"]
==== {CADD}

include::new_encoding_note.adoc[]

ifdef::cheri_v9_annotations[]
NOTE: *CHERI v9 Note:* these instructions were called CINCOFFSET and
 CINCOFFSETIMM.

NOTE: *CHERI v9 Note:* the immediate format has changed
endif::[]

Synopsis::
{CADD_DESC}

Mnemonic::
`{cadd_lc}  {creg_pref}d, {creg_pref}s1, rs2` +
`{caddi_lc} {creg_pref}d, {creg_pref}s1, imm`

Suggested assembly syntax::
`add {creg_pref}d, {creg_pref}s1, rs2` +
`addi {creg_pref}d, {creg_pref}s1, imm`

NOTE: The suggested assembly syntax distinguishes from integer `add`/`addi` by operand type.

Encoding::
include::wavedrom/cadd.adoc[]

NOTE: <<CADD>> with `rs2=x0` is decoded as <<CMV>> instead, the key
difference being that capabilities cannot have their {ctag}
cleared by <<CMV>>.

Description::
Copy the capability `{creg_pref}s1` to `{creg_pref}d`.
+
For <<CADD>>,  increment `{creg_pref}d.address` by the value in `rs2` . +
For <<CADDI>>, increment `{creg_pref}d.address` by the immediate value `imm`.
+
Set `{creg_pref}d.tag=0` if `{creg_pref}s1` is sealed.
+
include::rep_range_check.adoc[]
+
include::malformed_cs1_clear_tag.adoc[]

Operation for {CADD}::
+
sail::execute[clause="CADD(_, _, _)",part=body,unindent]

Operation for {CADDI}::
+
sail::execute[clause="CADDI(_, _, _)",part=body,unindent]
