<<<

[#CADDI,reftext="CADDI"]
==== CADDI

See <<CADD>>.

[#CADD,reftext="CADD"]
==== CADD

include::new_encoding_note.adoc[]

ifdef::cheri_v9_annotations[]
NOTE: *CHERI v9 Note:* these instructions were called CINCOFFSET and
 CINCOFFSETIMM.

NOTE: *CHERI v9 Note:* the immediate format has changed
endif::[]

Synopsis::
Capability pointer increment

Mnemonic::
`cadd cd, cs1, rs2` +
`caddi cd, cs1, imm`

Suggested assembly syntax::
`add cd, cs1, rs2` +
`add cd, cs1, imm`

NOTE: The suggested assembly syntax distinguishes from integer `add` by operand type.

Encoding::
include::wavedrom/cadd.adoc[]

NOTE: <<CADD>> with `rs2=x0` is decoded as <<CMV>> instead, the key
difference being that capabilities cannot have their validity tag
cleared by <<CMV>>.

Description::
Increment the address field of the capability `cs1`  and write the result to ``cd``.
Set `cd.tag=0` if `cs1.tag=0` or `cs1`  is sealed.
+
For <<CADD>>, the address is incremented by the value in `rs2` . +
For <<CADDI>>, the address is incremented by the immediate value `imm`.
+
include::rep_range_check.adoc[]
+
include::malformed_clear_tag.adoc[]

Prerequisites for CADD, CADDI::
{cheri_base_ext_name}

Operation for CADD assuming {cheri_default_cap}::
+
sail::execute[clause="CADD(_, _, _)",part=body,unindent]

Operation for CADDI assuming {cheri_default_cap}::
+
sail::execute[clause="CADDI(_, _, _)",part=body,unindent]
