<<<

[#CADDI,reftext="CADDI"]
==== CADDI

See <<CADD>>.

[#CADD,reftext="CADD"]
==== CADD

include::new_encoding_note.adoc[]

ifdef::cheri_v9_annotations[]
NOTE: *CHERI v9 Note:* these instructions were called CINCOFFSET and
 CINCOFFSETIMM.

NOTE: *CHERI v9 Note:* the immediate format has changed
endif::[]

Synopsis::
Capability pointer increment

Mnemonic::
`cadd yd, ys1, rs2` +
`caddi yd, ys1, imm`

Suggested assembly syntax::
`add yd, ys1, rs2` +
`add yd, ys1, imm`

NOTE: The suggested assembly syntax distinguishes from integer `add` by operand type.

Encoding::
include::wavedrom/cadd.adoc[]

NOTE: <<CADD>> with `rs2=x0` is decoded as <<CMV>> instead, the key
difference being that capabilities cannot have their valid tag
cleared by <<CMV>>.

Description::
Increment the address field of the capability `ys1`  and write the result to ``yd``.
Set `yd.tag=0` if `ys1.tag=0` or `ys1` is sealed.
+
For <<CADD>>, the address is incremented by the value in `rs2` . +
For <<CADDI>>, the address is incremented by the immediate value `imm`.
+
include::rep_range_check.adoc[]
+
include::malformed_clear_tag.adoc[]

Operation for CADD::
+
sail::execute[clause="CADD(_, _, _)",part=body,unindent]

Operation for CADDI::
+
sail::execute[clause="CADDI(_, _, _)",part=body,unindent]
