<<<

[#CADDI,reftext="{CADDI}"]
==== {CADDI}

See <<CADD>>.

[#CADD,reftext="{CADD}"]
==== {CADD}

include::new_encoding_note.adoc[]

ifdef::cheri_v9_annotations[]
NOTE: *CHERI v9 Note:* these instructions were called CINCOFFSET and
 CINCOFFSETIMM.

NOTE: *CHERI v9 Note:* the immediate format has changed
endif::[]

Synopsis::
{CADD_DESC}

Mnemonic::
`{cadd_lc}  {cd}, {cs1}, rs2` +
`{caddi_lc} {cd}, {cs1}, imm`

Suggested assembly syntax::
`add {cd}, {cs1}, rs2` +
`addi {cd}, {cs1}, imm`

NOTE: The suggested assembly syntax distinguishes from integer `add`/`addi` by operand type.

Encoding::
include::wavedrom/cadd.adoc[]

NOTE: <<CADD>> with `rs2=x0` is decoded as <<CMV>> instead, the key
difference being that capabilities cannot have their {ctag}
cleared by <<CMV>>.

Description::
Copy the capability `{cs1}` to `{cd}`.
+
For <<CADD>>,  increment `{cd}.address` by the value in `rs2[XLEN-1:0]` . +
For <<CADDI>>, increment `{cd}.address` by the immediate value `imm`.
+
Set `{cd}.tag=0` if `{cs1}` is sealed.
+
include::rep_range_check.adoc[]
+
include::malformed_cs1_clear_tag.adoc[]

Operation for {CADD}::
+
sail::execute[clause="CADD(_, _, _)",part=body,unindent]

Operation for {CADDI}::
+
sail::execute[clause="CADDI(_, _, _)",part=body,unindent]
