
[#CBLD,reftext="{CBLD}"]
==== {CBLD}

ifdef::cheri_v9_annotations[]
NOTE: *CHERI v9 Note:* {CBLD} does not use ddc if {cs1}=0

NOTE: *CHERI v9 Note:* this instruction was called CBUILDCAP.
endif::[]

include::new_encoding_note.adoc[]

Synopsis::
{CBLD_DESC}

Mnemonic::
`{cbld} {cd}, {cs1}, {cs2}`

Encoding::
include::wavedrom/cbld.adoc[]

Description::
Copy `{cs2}` to `{cd}`.
ifndef::cheri_ratification_v1_only[]
+
// This only applies once we include non-ambient otypes
If `{cd}.ct` (that is, its <<sec_cap_type>>) is
neither 0 nor an <<sec_cap_type_ambient,ambient>> type, then
set `{cd}.ct` to 0.
endif::[]
+
Set `{cd}.tag=1` if:
+
. `{cs1}.tag=1`, and
. `{cs1}` is not sealed, and
. `{cs2}` is a <<cap_subset>> of `{cs1}`,
+
Otherwise, set `{cd}.tag=0`

NOTE: The <<section_cap_integrity,integrity>> check on `{cs2}` (included in the subset check) is required to prevent authorizing a capability with a lack of integrity.
 The <<section_cap_integrity,integrity>> check on `{cs1}` is optional.
ifndef::cheri_ratification_v1_only[]
NOTE: <<CBLD>> will construct a sealed capability only if its type is <<sec_cap_type_ambient,ambiently available>>.
endif::[]

NOTE: <<CBLD>> is typically used alongside <<SCHI>> to build
capabilities from integer values.

NOTE: <<CBLD>> can be used to speed up operations such as paging in memory after swap.

NOTE: When `{cs1}` is `{creg}0` <<CBLD>> will copy `{cs2}` to `{cd}` and clear `{cd}.tag`.
However future extensions may add additional behavior to update currently reserved fields,
and so software should not assume `{cs1}=0` to be a pseudo-instruction for {ctag} clearing.

Operation::
[source,SAIL,subs="verbatim,quotes"]
----
SAIL TO BE UPDATED
----
//sail::execute[clause="CBLD(_, _, _)",part=body,unindent]
