<<<

[#CBLD,reftext="CBLD"]
==== CBLD

ifdef::cheri_v9_annotations[]
NOTE: *CHERI v9 Note:* CBLD does not use ddc if cs1==0

NOTE: *CHERI v9 Note:* this instruction was called CBUILDCAP.
endif::[]

include::new_encoding_note.adoc[]

Synopsis::
Capability build

Mnemonic::
`cbld cd, cs1, cs2`

Encoding::
include::wavedrom/cbld.adoc[]

Description::
Copy `cs2` to `cd` and set `cd.tag` to 1 if

. `cs1.tag` is set, and
. `cs1` 's bounds are not <<section_cap_malformed,malformed>>, and all reserved fields are zero, and
. `cs1` 's permissions could have been legally produced by <<ACPERM>>, and
. `cs1` is not sealed, and
. `cs2` 's permissions and bounds are equal to or a subset of `cs1` 's, and
. `cs2` 's <<section_cap_level>> is equal to or lower than `cs1` 's, and
+
NOTE: With {cheri_0levels_ext_name} this check always passes as the level is hardwired.
. `cs2` 's bounds are not <<section_cap_malformed,malformed>>, and all reserved fields are zero, and
. `cs2` 's permissions could have been legally produced by <<ACPERM>>, and
. All reserved bits in `cs2` 's metadata are 0;

Otherwise, copy `cs2` to `cd` and clear `cd` 's tag.

<<CBLD>> is typically used alongside <<SCHI>> to build
capabilities from integer values.

NOTE: When `cs1` is `c0` this will copy `cs2` to `cd` and clear `cd.tag`.
However this may change in future extensions, and so software should not
assume `cs1==0` to be a pseudoinstruction for tag clearing.

Operation::
+
sail::execute[clause="CBLD(_, _, _)",part=body,unindent]
