<<<

[#CBO_ZERO_CHERI,reftext="CBO.ZERO ({cheri_base_ext_name})"]
==== CBO.ZERO ({cheri_base_ext_name})

Synopsis::
Store zeros to the full set of bytes corresponding to a cache block

Mnemonic::
`CBO.ZERO 0({cs1})`

Encoding::
[wavedrom, ,svg,subs=attributes+]
....
{reg: [
  {bits: 7,  name: 'opcode',    attr: ['7','MISC-MEM=0001111'],  type: 8},
  {bits: 5,  name: 'funct5',    attr: ['5','CBO=00000'],     type: 2},
  {bits: 3,  name: 'funct3',    attr: ['3','CBO=010'],  type: 8},
  {bits: 5,  name: 'rs1{ne}0',  attr: ['5','base'],     type: 4},
  {bits: 12, name: 'funct12',   attr: ['12','CBO.ZERO=000000000100'],   type: 3},
]}
....

Description::
A `cbo.zero` instruction performs stores of zeros to the full set of bytes
corresponding to the cache block whose effective address is the base address
specified in `{cs1}`. An implementation may or may not update the entire set of
bytes atomically although each individual write must atomically set the {ctag}
of the corresponding aligned YLEN-bit location to zero. The authorizing capability
for this instruction is `{cs1}`.

Exceptions::
include::store_exceptions.adoc[]

Prerequisites::
Zicboz, {cheri_base_ext_name}

Operation::
// Not bundled in the JSON due to build system, inserted manually for now.

NOTE: This listing is manually maintained rather than extracted from the Sail model.
[source,SAIL,subs="verbatim,quotes"]
----
let cache_block_size = 2 ^ plat_cache_block_size_exp();
let negative_offset = (X(cs1) & ~(zero_extend(ones(plat_cache_block_size_exp())))) - X(cs1);
match ext_data_get_addr(cs1, negative_offset, Cache(Zero), cache_block_size) {
  Ext_DataAddr_Error(e) => { ext_handle_data_check_error(e); RETIRE_FAIL },
  Ext_DataAddr_OK(vaddr) => match translateAddr(vaddr, Write(Data)) {
    TR_Failure(e, ext_ptw) => { handle_translate_exception(vaddr - negative_offset, e, ext_ptw); RETIRE_FAIL },
    TR_Address(paddr, pbmt, _) => {
      let ep = effectivePrivilege(Cache(Zero), mstatus, cur_privilege());
      let _ = mem_write_value_priv_meta(pbmt, paddr, cache_block_size, zeros(),
                                        Cache(Zero), ep, default_meta, false, false, false);
      RETIRE_SUCCESS
    }
  }
}
----
