<<<

[#CBO_ZERO_CHERI,reftext="CBO.ZERO ({cheri_base_ext_name})"]
==== CBO.ZERO ({cheri_base_ext_name})

Synopsis::
Store zeros to the full set of bytes corresponding to a cache block

Mnemonic::
`cbo.zero 0(ys1)`

//{cheri_int_mode_name} Mnemonic::
//`cbo.zero 0(rs1)`

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7,  name: 'opcode',    attr: ['7','MISC-MEM=0001111'],  type: 8},
  {bits: 5,  name: 'funct5',    attr: ['5','CBO=00000'],     type: 2},
  {bits: 3,  name: 'funct3',    attr: ['3','CBO=010'],  type: 8},
  {bits: 5,  name: 'cs1≠0',     attr: ['5','base'],     type: 4},
  {bits: 12, name: 'funct12',   attr: ['12','CBO.ZERO=00.0100'],   type: 3},
]}
....

Description::
A `cbo.zero` instruction performs stores of zeros to the full set of bytes
corresponding to the cache block whose effective address is the base address
specified in `ys1`. An implementation may or may not update the entire set of
bytes atomically although each individual write must atomically clear the valid tag
bit of the corresponding aligned YLEN-bit location. The authorizing capability
for this instruction is `ys1`.

//{cheri_int_mode_name} Description::
//A `cbo.zero` instruction performs stores of zeros to the full set of bytes
//corresponding to the cache block whose effective address is the base address
//specified in `ys1`. An implementation may or may not update the entire set of
//bytes atomically although each individual write must atomically clear the valid tag
//bit of the corresponding aligned YLEN-bit location. The authorizing capability
//for this operation is <<ddc>>.

include::store_exceptions.adoc[]

Prerequisites::
Zicboz, {cheri_base_ext_name}

//Prerequisites for {cheri_int_mode_name}::
//Zicboz, {cheri_default_ext_name}

Operation::
[source,SAIL,subs="verbatim,quotes"]
--
TBD
--
