<<<

[#CSRRW_CHERI,reftext="CSRRW ({cheri_base_ext_name})"]
==== CSRRW ({cheri_base_ext_name})

ifdef::cheri_v9_annotations[]
NOTE: *CHERI v9 Note:* CSpecialRW is removed and this functionality replaces it
endif::[]


Synopsis::
CSR access (CSRRW) 32-bit encodings for {cheri_base_ext_name}

Mnemonic::
`csrrw {cd}, csr, {cs1}`

//Mnemonic for accessing widened csrs in {cheri_cap_mode_name}::
//`csrrw {cd}, csr, {cs1}`
//
//Mnemonic for accessing widened csrs in {cheri_int_mode_name}::
//`csrrw rd, csr, rs1`

Encoding::
include::wavedrom/csrw-instr.adoc[]

Description::
CSRRW has extended functionality for accessing <<ylen_csrs>>.
+
Access to <<xlen_csrs>> is as defined in Zicsr.
+
CSRRW accesses to <<ylen_csrs>> read YLEN bits into `{cd}` and write YLEN bits of `{cs1}` into the CSR.
+
When writing YLEN bits of `{cs1}`, if any <<section_cap_integrity,integrity>> checks fail then set the {ctag} to zero before writing to the CSR.
+
NOTE: Any <<ylen_csrs, YLEN-bit>> CSRs may have additional rules defined to determine the final written value of the metadata and/or to write zero to the {ctag}.
ifdef::cheri_standalone_spec[]
These rules are shown in <<extended_CSR_writing_u>>, <<extended_CSR_writing_s>>, and <<extended_CSR_writing_m>>.
endif::[]
ifndef::cheri_standalone_spec[]
These rules are shown in <<extended_CSR_writing_u>>, and there are further references in the _Privileged Specification_.
endif::[]
+
If {cheri_default_ext_name} is implemented, and the current mode is {cheri_int_mode_name}, writes to natively XLEN-bit CSRs are XLEN bits and the final write data is determined using the semantics of the <<SCADDR>> instruction.

Permissions::
Accessing CSRs may require <<asr_perm>>.

Prerequisites::
{cheri_base_ext_name}, Zicsr, optional {cheri_default_ext_name}

Operation::
+
sail::execute[clause="CSR(_, _, _, _, _)",part=body,unindent]
