<<<

[#CSRRW_CHERI,reftext="CSRRW ({cheri_base_ext_name})"]
==== CSRRW ({cheri_base_ext_name})

ifdef::cheri_v9_annotations[]
NOTE: *CHERI v9 Note:* CSpecialRW is removed and this functionality replaces it
endif::[]


Synopsis::
CSR access (CSRRW) 32-bit encodings for ({cheri_base_ext_name})

Mnemonic for accessing CLEN-wide CSRs::
`csrrw cd, csr, cs1`

Mnemonic for accessing extended CSRs in {cheri_cap_mode_name}::
`csrrw cd, csr, cs1`

Mnemonic for accessing extended CSRs in {cheri_int_mode_name}::
`csrrw rd, csr, rs1`

Encoding::
include::wavedrom/csrw-instr.adoc[]

Description::
CSRRW has extended functionality for accessing CLEN-bit CSRs, and XLEN-bit CSRs extended to CLEN-bits (_Extended CSRs_).
+
Access to XLEN-bit CSRs is as defined in Zicsr.
+
CSRRW accesses to CLEN-bit CSRs read CLEN-bits into `cd` and write `cs1` into the CSR.
+
CSRRW accesses to extended CSRs in {cheri_cap_mode_name} read CLEN-bits into `cd` and write `cs1` into the CSR.
+
CSRRW accesses to extended CSRs in {cheri_int_mode_name} read XLEN-bits into `rd` and write `rs1` into the CSR.
The final write data is determined using <<SCADDR>> semantics.
+
In all cases, when writing `cs1`, if any <<section_cap_integrity,integrity>> check fails then set the valid tag to zero before writing to the CSR.

Permissions::
Accessing CSRs may require <<asr_perm>>.

Prerequisites for {cheri_cap_mode_name}::
{cheri_base_ext_name}, Zicsr

Prerequisites for {cheri_int_mode_name}::
{cheri_default_ext_name}, Zicsr

Operation::
[source,SAIL,subs="verbatim,quotes"]
--
TBD
--
