<<<
//[#insns-csrr-32bit,reftext="CSR access (CSRRW[I], CSRRS[I], CSRRC[I]), 32-bit encoding"]

[#CSRRWI_CHERI,reftext="CSRRWI ({cheri_base_ext_name})"]
==== CSRRWI ({cheri_base_ext_name})
See <<CSRRCI_CHERI>>.

[#CSRRS_CHERI,reftext="CSRRS ({cheri_base_ext_name})"]
==== CSRRS ({cheri_base_ext_name})
See <<CSRRCI_CHERI>>.

[#CSRRSI_CHERI,reftext="CSRRSI ({cheri_base_ext_name})"]
==== CSRRSI ({cheri_base_ext_name})
See <<CSRRCI_CHERI>>.

[#CSRRC_CHERI,reftext="CSRRC ({cheri_base_ext_name})"]
==== CSRRC ({cheri_base_ext_name})
See <<CSRRCI_CHERI>>.

[#CSRRCI_CHERI,reftext="CSRRCI ({cheri_base_ext_name})"]
==== CSRRCI ({cheri_base_ext_name})

ifdef::cheri_v9_annotations[]
NOTE: *CHERI v9 Note:* CSpecialRW is removed and this functionality replaces it
endif::[]


Synopsis::
CSR access (CSRRWI, CSRRS, CSRRSI, CSRRC, CSRRCI) 32-bit encodings for {cheri_base_ext_name}

Mnemonics for accessing CLEN-wide CSRs in {cheri_cap_mode_name}::
`csrrs  cd, csr, rs1` +
`csrrc  cd, csr, rs1` +
`csrrwi cd, csr, imm` +
`csrrsi cd, csr, imm` +
`csrrci cd, csr, imm`

Mnemonics for accessing XLEN-wide CSRs or extended CSRs in {cheri_int_mode_name}::
`csrrs  rd, csr, rs1` +
`csrrc  rd, csr, rs1` +
`csrrwi rd, csr, imm` +
`csrrsi rd, csr, imm` +
`csrrci rd, csr, imm`

Encoding::
include::wavedrom/csr-instr.adoc[]

Description::
These are standard RISC-V CSR instructions with extended functionality for accessing CLEN-wide CSRs.
+
For CLEN-wide CSRs, the full capability is read into `cd` in {cheri_cap_mode_name}.
In {cheri_int_mode_name}, the address field is instead read into `rd`.
+
Unlike <<CSRRW_CHERI>>, these instructions only update the address field and the valid tag
as defined in xref:extended_CSR_writing[xrefstyle=short] when writing
CLEN-wide CSRs regardless of the execution mode. The CSR update is made using <<SCADDR>> semantics.
+
NOTE: If the CSR accessed is a capability, and `rs1` is `x0` for <<CSRRS_CHERI,CSRRS>> and <<CSRRC_CHERI,CSRRC>>, or `imm` is 0 for <<CSRRSI_CHERI,CSRRSI>> and <<CSRRCI_CHERI,CSRRCI>>, then the CSR is not written so no representability check is needed in this case.

Permissions::
Accessing CSRs may require <<asr_perm>>.

Prerequisites for {cheri_cap_mode_name}::
{cheri_base_ext_name}, Zicsr

Prerequisites for {cheri_int_mode_name}::
{cheri_default_ext_name}, Zicsr

Operation::
[source,SAIL,subs="verbatim,quotes"]
--
TBD
--
