<<<
//[#insns-csrr-32bit,reftext="CSR access (CSRRW[I], CSRRS[I], CSRRC[I]), 32-bit encoding"]

[#CSRRW_CHERI,reftext="CSRRW ({cheri_base_ext_name})"]
==== CSRRW ({cheri_base_ext_name})

ifdef::cheri_v9_annotations[]
NOTE: *CHERI v9 Note:* CSpecialRW is removed and this functionality replaces it
endif::[]


Synopsis::
CSR access (CSRRW) 32-bit encodings for ({cheri_base_ext_name})

Mnemonic for accessing capability CSRs in {cheri_cap_mode_name}::
`csrrw yd, csr, ys1`

Mnemonic for accessing XLEN-wide CSRs or extended CSRs in {cheri_int_mode_name}::
`csrrw rd, csr, rs1`

Encoding::
include::wavedrom/csrw-instr.adoc[]

Description::
These are standard RISC-V CSR instructions with extended functionality for
accessing capability CSRs (see xref:all_capability_CSRs[xrefstyle=short]).
+
See xref:aliased_CSRs[xrefstyle=short] for a list of CSRs extended to capabilities and
xref:extended_CSR_writing[xrefstyle=short] for the action taken on writing each one.
+
Capability CSRs and the action taken on accessing them is shown in xref:new_cap_CSR_writing[xrefstyle=short].
+
CSRRW writes `ys1` to extended CSRs in {cheri_cap_mode_name}, and reads a full capability into `yd`.
+
CSRRW writes `ys1` to capability CSRs in both modes, and reads a full capability into `yd`.
+
CSRRW writes `rs1` to extended CSRs in {cheri_int_mode_name}, and reads the address field into `rd`.
+
If `yd` is `c0` (or `rd` is `x0`), then the instruction shall not read the CSR
and shall not cause any of the side effects that might occur on a CSR read.
+
The assembler pseudoinstruction to write a capability CSR
`csrw csr, ys1`, is encoded as `csrrw c0, csr, ys1`.
+
Access to XLEN-wide CSRs from other extensions is as specified by RISC-V.

NOTE: When writing `ys1`, if the bounds are <<section_cap_malformed,malformed>>, any reserved bits are set,
or the permission could not have been produced by <<ACPERM>> then clear the valid tag before writing to the CSR.

Permissions::
Accessing privileged CSRs may require <<asr_perm>>, including existing RISC-V
CSRs, as described in cite:[riscv-priv-spec].

Prerequisites for {cheri_cap_mode_name}::
{cheri_base_ext_name}

Prerequisites for {cheri_int_mode_name}::
{cheri_default_ext_name}

Operation::
[source,SAIL,subs="verbatim,quotes"]
--
TBD
--
