<<<
//[#insns-csrr-32bit,reftext="CSR access (CSRRW[I], CSRRS[I], CSRRC[I]), 32-bit encoding"]

[#CSRRW_CHERI,reftext="CSRRW ({cheri_base_ext_name})"]
==== CSRRW ({cheri_base_ext_name})

ifdef::cheri_v9_annotations[]
NOTE: *CHERI v9 Note:* CSpecialRW is removed and this functionality replaces it
endif::[]


Synopsis::
CSR access (CSRRW) 32-bit encodings for ({cheri_base_ext_name})

Mnemonic for accessing CLEN-wide CSRs::
`csrrw cd, csr, cs1`

Mnemonic for accessing XLEN-wide CSRs or extended CSRs in {cheri_int_mode_name}::
`csrrw rd, csr, rs1`

Encoding::
include::wavedrom/csrw-instr.adoc[]

Description::
This is a  standard RISC-V CSR instruction with extended functionality for accessing CLEN-wide CSRs.
+
CSRRW writes `cs1` to extended CSRs in {cheri_cap_mode_name}, and reads a full capability into `cd`.
+
CSRRW writes `cs1` to CLEN-wide CSRs in both modes, and reads a full capability into `cd`.
+
CSRRW writes `rs1` to extended CSRs in {cheri_int_mode_name}, and reads the address field into `rd`.
+
If `cd` is `c0` (or `rd` is `x0`), then the instruction shall not read the CSR
and shall not cause any of the side effects that might occur on a CSR read.
+
In all cases, when writing `cs1`, if the bounds are <<section_cap_malformed,malformed>>, any reserved bits are set,
or the permission could not have been produced by <<ACPERM>> then clear the valid tag before writing to the CSR.

Permissions::
Accessing CSRs may require <<asr_perm>>.

Prerequisites for {cheri_cap_mode_name}::
{cheri_base_ext_name}, Zicsr

Prerequisites for {cheri_int_mode_name}::
{cheri_default_ext_name}, Zicsr

Operation::
[source,SAIL,subs="verbatim,quotes"]
--
TBD
--
