<<<

[#CSRRW_CHERI,reftext="CSRRW ({cheri_base_ext_name})"]
==== CSRRW ({cheri_base_ext_name})

ifdef::cheri_v9_annotations[]
NOTE: *CHERI v9 Note:* CSpecialRW is removed and this functionality replaces it
endif::[]


Synopsis::
CSR access (CSRRW) 32-bit encodings for ({cheri_base_ext_name})

Mnemonic::
`csrrw {cd}, csr, {cs1}`

//Mnemonic for accessing extended CSRs in {cheri_cap_mode_name}::
//`csrrw {cd}, csr, {cs1}`
//
//Mnemonic for accessing extended CSRs in {cheri_int_mode_name}::
//`csrrw rd, csr, rs1`

Encoding::
include::wavedrom/csrw-instr.adoc[]

Description::
CSRRW has extended functionality for accessing YLEN-bit CSRs, and XLEN-bit CSRs extended to YLEN bits (_Extended CSRs_).
+
Access to XLEN bit CSRs is as defined in Zicsr.
+
CSRRW accesses to YLEN bit CSRs read YLEN bits into `{cd}` and write YLEN bits of `{cs1}` into the CSR.
+
CSRRW accesses to extended CSRs read YLEN bits into `{cd}` and write YLEN bits of `{cs1}` into the CSR, or if {cheri_default_ext_name} is supported, XLEN bit accesses are made in {cheri_int_mode_name}. The final write data is determined using semantics of the <<SCADDR>> instruction.
+
In all cases, when writing YLEN bits of `{cs1}`, if any <<section_cap_integrity,integrity>> check fails then set the {ctag} to zero before writing to the CSR.

Permissions::
Accessing CSRs may require <<asr_perm>>.

Prerequisites::
{cheri_base_ext_name}, Zicsr

Included in::
<<rvy_i_mod_insn_table>>

Operation::
[source,SAIL,subs="verbatim,quotes"]
--
TBD
--
