<<<

[#CSRRWI_CHERI,reftext="CSRRWI ({cheri_base_ext_name})"]
==== CSRRWI ({cheri_base_ext_name})
See <<CSRRCI_CHERI>>.

[#CSRRS_CHERI,reftext="CSRRS ({cheri_base_ext_name})"]
==== CSRRS ({cheri_base_ext_name})
See <<CSRRCI_CHERI>>.

[#CSRRSI_CHERI,reftext="CSRRSI ({cheri_base_ext_name})"]
==== CSRRSI ({cheri_base_ext_name})
See <<CSRRCI_CHERI>>.

[#CSRRC_CHERI,reftext="CSRRC ({cheri_base_ext_name})"]
==== CSRRC ({cheri_base_ext_name})
See <<CSRRCI_CHERI>>.

[#CSRRCI_CHERI,reftext="CSRRCI ({cheri_base_ext_name})"]
==== CSRRCI ({cheri_base_ext_name})

ifdef::cheri_v9_annotations[]
NOTE: *CHERI v9 Note:* CSpecialRW is removed and this functionality replaces it
endif::[]


Synopsis::
CSR access (CSRRWI, CSRRS, CSRRSI, CSRRC, CSRRCI) 32-bit encodings for {cheri_base_ext_name}

Mnemonics for accessing CLEN-bit CSRs::
`csrrs  cd, csr, rs1` +
`csrrc  cd, csr, rs1` +
`csrrwi cd, csr, imm` +
`csrrsi cd, csr, imm` +
`csrrci cd, csr, imm`

Mnemonics for accessing extended CSRs in {cheri_cap_mode_name}::
`csrrs  cd, csr, rs1` +
`csrrc  cd, csr, rs1` +
`csrrwi cd, csr, imm` +
`csrrsi cd, csr, imm` +
`csrrci cd, csr, imm`

Mnemonics for accessing extended CSRs in {cheri_int_mode_name}::
`csrrs  rd, csr, rs1` +
`csrrc  rd, csr, rs1` +
`csrrwi rd, csr, imm` +
`csrrsi rd, csr, imm` +
`csrrci rd, csr, imm`

Encoding::
include::wavedrom/csr-instr.adoc[]

Description::
These CSR instructions have extended functionality for accessing CLEN-bit CSRs, and XLEN-bit CSRs extended to CLEN-bits (_Extended CSRs_).
+
Access to XLEN-bit CSRs is as defined in Zicsr.
+
Zicsr rules are followed when determining whether to read or write the CSR.
+
Suppressed read or write actions have no side-effects on the CSR.
+
All writes are XLEN-bits only, as determined by Zicsr, and use <<SCADDR>> semantics to determine the final write data.
+
Read data from extended CSRs is CLEN-bits in {cheri_cap_mode_name} or XLEN-bits in {cheri_int_mode_name}.
+
Read data from CLEN-bit CSRs is always CLEN-bits.

Permissions::
Accessing CSRs may require <<asr_perm>>.

Prerequisites for {cheri_cap_mode_name}::
{cheri_base_ext_name}, Zicsr

Prerequisites for {cheri_int_mode_name}::
{cheri_default_ext_name}, Zicsr

Operation::
[source,SAIL,subs="verbatim,quotes"]
--
TBD
--
