<<<

[#GCHI_BASE,reftext="{GCHI_BASE}"]
==== {GCHI_BASE}

Synopsis::
{GCHI_BASE_DESC}

Mnemonic::
`{gchi_base_lc} rd, rs1, shamt`

Encoding::
include::wavedrom/gchi.adoc[]

Description::
Logical right shift of Y register `rs1` to `rd`, zero-filling the upper bits of the result.

NOTE: Currently the only valid shift distance is XLEN places, a future extension may add an arbitrary shift distance.

NOTE: For {cheri_base32_ext_name}, `{gchi_base_lc} rd, rs1, 32` has an identical encoding and operation to the RV64 instruction `srli rd, rs1, 32`.

Operation::
+
TODO

[#GCHI,reftext="{GCHI}"]
==== {GCHI}

include::new_encoding_note.adoc[]

ifdef::cheri_v9_annotations[]
NOTE: *CHERI v9 Note:* this instruction was called CGETHIGH.
endif::[]

Synopsis::
{GCHI_DESC}

Mnemonic::
`{gchi_lc} rd, cs1`

Encoding::
`{gchi_lc} rd, cs1` is a pseudoinstruction for `{gchi_base_lc} rd, rs1, XLEN`

Description::
Copy the metadata (bits [YLEN-1:XLEN]) of capability `cs1` into `rd`.
+
include::no_tag_affect.adoc[]

Operation::
+
sail::execute[clause="GCHI(_, _)",part=body,unindent]
