<<<

[#GCPERM,reftext="GCPERM"]
==== GCPERM

include::new_encoding_note.adoc[]

ifdef::cheri_v9_annotations[]
NOTE: *CHERI v9 Note:* this instruction was called CGETPERM.
endif::[]

Synopsis::
Capability get permissions

Mnemonic::
`gcperm rd, cs1`

Encoding::
include::wavedrom/gcperm.adoc[]

Description::
If MXLEN=32 unpack permissions from the format in <<cap_perms_encoding32>>.
+
Convert the unpacked AP permissions as well as the SDP fields of capability `cs1`
into a bit field, with the format shown in xref:gcperm_bit_field[xrefstyle=short],
and write the result to `rd`. A bit set to 1 in the bit field indicates that
`cs1` grants the corresponding permission.
All bits in the `[0:23]` range that are reserved or assigned to extensions that are not implemented by the current hart always report 1.
+
If the AP field cannot be produced by <<ACPERM>> then all architectural
permission bits in `rd` are set to 0.
+
.Capability permissions bit field
[#gcperm_bit_field]
include::../img/acperm_bit_field.edn[]
+
NOTE: Any future extension that defines new permission that are a refinement of existing permissions (e.g., finer-grained <<asr_perm>>) must be allocated to the bits that are currently reported as 1 to ensure forward-compatibility.
Completely new permissions (e.g., sealing) should use the bits that are reported as zero in the current specification.
+
include::no_tag_affect.adoc[]

Operation::
+
sail::execute[clause="GCPERM(_, _)",part=body,unindent]
