<<<

[#GCPERM,reftext="GCPERM"]
==== GCPERM

include::new_encoding_note.adoc[]

ifdef::cheri_v9_annotations[]
NOTE: *CHERI v9 Note:* this instruction was called CGETPERM.
endif::[]

Synopsis::
Capability get permissions

Mnemonic::
`gcperm rd, cs1`

Encoding::
include::wavedrom/gcperm.adoc[]

Description::
If MXLEN=32 unpack the <<AP-field>> from the format in <<cap_perms_encoding32>>.
+
Convert the unpacked <<AP-field>> as well as the <<SDP-field>> and <<section_cap_level, CL-field>> of capability `cs1`
into a bit field, with the format shown in xref:gcperm_bit_field[xrefstyle=short],
and write the result to `rd`.
All bits in the `[23:0]` range that are reserved or assigned to extensions that are not implemented by the current hart always report 1.
+
All architectural permission bits in `rd` are set to 0 if any <<section_cap_integrity,integrity>> checks failed.
+
.Capability permissions bit field
[#gcperm_bit_field]
include::../img/acperm_bit_field.edn[]
+
NOTE: Any future extension that defines new permissions that are a refinement of existing permissions (e.g., finer-grained <<asr_perm>>) must be allocated to the bits that are currently reported as 1 to ensure forward-compatibility.
Completely new permissions (e.g., sealing) should use the bits that are reported as zero in the current specification.
+
include::no_tag_affect.adoc[]

Operation::
+
sail::execute[clause="GCPERM(_, _)",part=body,unindent]
