<<<

[#HLV_B,reftext="HLV.B"]
==== HLV.B

See <<HLV_W>>.

[#HLV_BU,reftext="HLV.BU"]
==== HLV.BU

See <<HLV_W>>.

[#HLV_H,reftext="HLV.H"]
==== HLV.H

See <<HLV_W>>.

[#HLV_HU,reftext="HLV.HU"]
==== HLV.HU

See <<HLV_W>>.

[#HLV_WU,reftext="HLV.WU"]
==== HLV.WU

See <<HLV_W>>.

[#HLV_D,reftext="HLV.D"]
==== HLV.D

See <<HLV_W>>.

<<<

[#HLV_W,reftext="HLV.W"]
==== HLV.W

Synopsis::
Hypervisor virtual-machine load

{cheri_cap_mode_name} Mnemonics (RV64)::
`hlv.b[u] rd, {cs1}` +
`hlv.h[u] rd, {cs1}` +
`hlv.w[u] rd, {cs1}` +
`hlv.d    rd, {cs1}`

{cheri_int_mode_name} Mnemonics (RV64)::
`hlv.b[u] rd, rs1` +
`hlv.h[u] rd, rs1` +
`hlv.w[u] rd, rs1` +
`hlv.d    rd, rs1`

{cheri_cap_mode_name} Mnemonics (RV32)::
`hlv.b[u] rd, {cs1}` +
`hlv.h[u] rd, {cs1}` +
`hlv.w    rd, {cs1}`

{cheri_int_mode_name} Mnemonics (RV32)::
`hlv.b[u] rd, rs1` +
`hlv.h[u] rd, rs1` +
`hlv.w    rd, rs1`

Encoding::
include::wavedrom/hypv-virt-load.adoc[]

{cheri_cap_mode_name} Description::
Performs a load as though V=1; i.e., with the address translation and
protection, and endianness, that apply to memory accesses in either VS-mode or
VU-mode. The effective address is `{cs1}.address`. The authorizing
capability for the operation is `{cs1}`. A copy of the loaded value is written to
`rd`.
+
include::load_store_creg0.adoc[]

{cheri_int_mode_name} Description::
Performs a load as though V=1; i.e., with the address translation and
protection, and endianness, that apply to memory accesses in either VS-mode or
VU-mode. The effective address is the is `rs1`. The authorizing capability for
the operation is <<ddc>>. A copy of the loaded value is written to `rd`.

include::load_exceptions.adoc[]

Prerequisites for {cheri_cap_mode_name} HLV.B[U], HLV.H[U], HLV.W::
{cheri_base_ext_name}, H

Prerequisites for {cheri_int_mode_name} HLV.B[U], HLV.H[U], HLV.W::
{cheri_base_ext_name}, {cheri_default_ext_name}, H

Prerequisites for {cheri_cap_mode_name} HLV.WU, HLV.D::
RV64, {cheri_base_ext_name}, H

Prerequisites for {cheri_int_mode_name} HLV.WU, HLV.D::
RV64, {cheri_base_ext_name}, {cheri_default_ext_name}, H

{cheri_cap_mode_name} Operation::
+
--
TBD
--

{cheri_int_mode_name} Operation::
+
--
TBD
--
