<<<

[#HLVX_HU,reftext="HLVX.HU"]
==== HLVX.HU

See <<HLVX_WU>>.

[#HLVX_WU,reftext="HLVX.WU"]
==== HLVX.WU

Synopsis::
Hypervisor virtual machine load from executable memory

{cheri_cap_mode_name} Mnemonics::
`hlvx.hu rd, cs1` +
`hlvx.wu rd, cs1`

{cheri_int_mode_name} Mnemonics::
`hlvx.hu rd, rs1` +
`hlvx.wu rd, rs1`

Encoding::
include::wavedrom/hypv-virt-loadx.adoc[]

{cheri_cap_mode_name} Description::
Performs a load with the *execute* permission taking the place of *read*
permission during address translation and as though V=1; i.e., with the address
translation and protection, and endianness, that apply to memory access in
either VS-mode or VU-mode. The effective address is `cs1.address`. The
authorizing capability for the operation is `cs1`. A copy of the loaded value
is written to `rd`.
+
include::load_store_c0.adoc[]

{cheri_int_mode_name} Description::
Performs a load with the *execute* permission taking the place of *read*
permission during address translation and as though V=1; i.e., with the address
translation and protection, and endianness, that apply to memory access in
either VS-mode or VU-mode. The effective address is `rs1`. The authorizing
capability for the operation is <<ddc>>. A copy of the loaded value is written
to `rd`.

Exceptions::
+
[%autowidth,options=header,align=center]
|==============================================================================
| Kind                       | Reason
| {cheri_excep_name_ld}      | {cheri_excep_desc_ytag}, or
|                            | {cheri_excep_desc_seal}, or
|                            | {cheri_excep_desc_perm} where only <<r_perm>> is required, or
|                            | {cheri_excep_desc_bnds}
|==============================================================================

Prerequisites for {cheri_cap_mode_name}::
{cheri_base_ext_name}, H

Prerequisites for {cheri_int_mode_name}::
{cheri_base_ext_name}, {cheri_default_ext_name}, H

{cheri_cap_mode_name} Operation::
+
--
TBD
--

{cheri_int_mode_name} Operation::
+
--
TBD
--
