
<<<

[#JAL_CHERI,reftext="JAL ({cheri_base_ext_name})"]
==== JAL ({cheri_base_ext_name})

Synopsis::
{JAL_CHERI_DESC}

Mnemonic::
`jal {cd}, offset`

Encoding::
include::wavedrom/ct-unconditional.adoc[]

Description::

Direct jump with an address offset.
+
. The target address is obtained by adding the sign-extended 20-bit J-immediate to `<<pcc>>.address`.
. The target <<pcc>> is obtained by applying the target address to the <<pcc>> of the JAL instruction, using the semantics of the <<SCADDR>> instruction.
. The <<pcc>> of the next instruction is _sealed_ as a _backward-edge_ <<sentry_cap>> and written to `{cd}`.
. Jump to the target <<pcc>>.
+
NOTE: If the only supported <<sec_cap_type>> is zero, then no backward-edge <<sentry_cap, sentry capabilities>> exist, and so _sealing_ has no effect.
 This behavior requires non-zero <<sec_cap_type>> values to be implemented, such as by the <<section_rvy_sentry_insn_ext>> extension.
+
NOTE: A future extension may raise an exception on the branch instruction itself if fetching a minimum sized instruction at the target <<pcc>> will raise a _{cheri_excep_name_pc}_.
  Performing the <<pcc>> bounds check at the branch source instead of on instruction fetch is helpful for debugging and can simplify the implementation of CPUs with very short pipelines.

Included in::
<<rvy_i_mod_insn_table>>

Operation::
+
TODO

//commented out as it still has exception checks
//sail::execute[clause="JAL_capmode(_, _)",part=body,unindent]
