<<<

[#JALR_CHERI,reftext="JALR ({cheri_base_ext_name})"]
==== JALR ({cheri_base_ext_name})

Synopsis::
{JALR_CHERI_DESC}

Mnemonic::
`jalr {cd}, {cs1}, offset`

Encoding::
include::wavedrom/ct-unconditional-2.adoc[]

include::base_isa_extension.adoc[]

Description::
Indirect jump to the target capability in `{cs1}` with an address offset.
+
NOTE: The description below is generic, and implementations which need control-flow-integrity will include at least one extension which defines one or more <<sentry_cap, sentry capabilities>>.
 All such extensions are required to detail the specialized behavior of JALR to remove any ambiguity.
 For example, see <<section_rvy_sentry_insn_ext>>.
+
. `{cs1}` is written to the target <<pcc>>.
. If `{cd}`≠x0, `{cs1}` is _sealed_ and `{cs1}` is not a _forward-edge_ <<sentry_cap>>, then the behavior is _reserved_^1^.
. If `{cd}=x0`, '{cs1}' is the link register , `{cs1}` is _sealed_ and `{cs1}` is not a _backward-edge_ <<sentry_cap>>, then the behavior is _reserved_^1^.
. The target address is obtained by adding the sign-extended 12-bit I-immediate to `{cs1}.address`, then setting the least-significant bit of the result to zero.
. Unseal the target <<pcc>> if it is any <<sentry_cap>>, `{cs1}.address[0]` is zero, and the I-immediate is zero.
. Set the address of the target <<pcc>> to the target address using the semantics of the <<SCADDR>> instruction.
. The <<pcc>> of the next instruction is sealed as a _backward-edge_ <<sentry_cap>> and written to `{cd}`.
. Jump to the target <<pcc>>.
+
^1^ Extensions that introduce new sealed types must define how they interact with <<JALR_CHERI>>, otherwise the behaviour is to set the {ctag} of the target <<pcc>> to zero.
+
[NOTE]
====
If the only supported <<sec_cap_type>> is zero, then no <<sentry_cap, sentry capabilities>> exist, and so _sealing_ and _unsealing_ have no effect on JALR.
In this case the specialized operation becomes:

 . `{cs1}` is written to the target <<pcc>>.
 . The target address is obtained by adding the sign-extended 12-bit I-immediate to `{cs1}.address`, then setting the least-significant bit of the result to zero.
 . Set the address of the target <<pcc>> to the target address using the semantics of the <<SCADDR>> instruction.
 . The <<pcc>> of the next instruction is written to `{cd}`.
 . Jump to the target <<pcc>>.
====
+
NOTE: A future extension may raise an exception on the <<JALR_CHERI>> instruction itself if the target <<pcc>> will raise a {cheri_excep_name_pc} at the target.
+
NOTE: The standard software calling convention uses 'x1' as the link register.

Included in::
<<rvy_i_mod_insn_table>>

Operation::
+
TODO

//commented out as it still has exception checks
//sail::execute[clause="JALR_capmode(_, _)",part=body,unindent]
