<<<

[#JALR_CHERI,reftext="JALR ({cheri_base_ext_name})"]
==== JALR ({cheri_base_ext_name})

Synopsis::
{JALR_CHERI_DESC}

Mnemonic::
`jalr {cd}, {cs1}, offset`

Encoding::
include::wavedrom/ct-unconditional-2.adoc[]

include::base_isa_extension.adoc[]

Description::
Indirect jump to the target capability in `{cs1}` with an address offset.
+
NOTE: The  description below includes behavior depending on the implemented <<sec_cap_type>> values.
 See the notes below the description.
+
. `{cs1}` is written to the target <<pcc>>.
. If `{cd}` is the link register, `{cs1}` is _sealed_ and `{cs1}` is not a _forward-edge_ <<sentry_cap>>, then set the {ctag} of the target <<pcc>> to zero.
. If `{cd}=x0`, `{cs1}` is the link register, `{cs1}` is _sealed_ and `{cs1}` is not a _backward-edge_ <<sentry_cap>>, then set the {ctag} of the target <<pcc>> to zero.
. Unseal the target <<pcc>> if it is any <<sentry_cap>>.
. The target address is obtained by adding the sign-extended 12-bit I-immediate to `{cs1}.address`, then setting the least-significant bit of the result to zero.
. Set the address of the target <<pcc>> to the target address using the semantics of the <<SCADDR>> instruction.
. The <<pcc>> of the next instruction is sealed as a _backward-edge_ <<sentry_cap>> and written to `{cd}`.
. Jump to the target <<pcc>>.
+
NOTE: If the only supported <<sec_cap_type>> is zero, then no <<sentry_cap, sentry capabilities>> exist, and so _sealing_ and _unsealing_ have no effect.
 This behavior requires non-zero <<sec_cap_type>> values to be implemented, such as by the <<section_rvy_sentry_insn_ext>> extension.
+
NOTE: When any sealed capability is passed as the input to <<JALR_CHERI>>, its address must have bit zero clear and the instruction must have a zero offset, or the target <<pcc>> will have its {ctag} set to zero, since updates to its address are interpreted with the semantics of the <<SCADDR>> instruction.
 As such, a <<sentry_cap>> defines a secure function entry point and so the offset in the JALR instruction must be zero.
+
NOTE: A future extension may raise an exception on the <<JALR_CHERI>> instruction itself if the target <<pcc>> will raise a {cheri_excep_name_pc} at the target.
+
NOTE: The standard software calling convention uses 'x1' as the link register.

Included in::
<<rvy_i_mod_insn_table>>

Operation::
+
TODO

//commented out as it still has exception checks
//sail::execute[clause="JALR_capmode(_, _)",part=body,unindent]
