<<<

[#JALR_CHERI,reftext="JALR ({cheri_base_ext_name})"]
==== JALR ({cheri_base_ext_name})

Synopsis::
{JALR_CHERI_DESC}

Mnemonic::
`jalr {cd}, {cs1}, offset`

Encoding::
include::wavedrom/ct-unconditional-2.adoc[]

include::base_isa_extension.adoc[]

Description::
Indirect jump to the target capability in `{cs1}` with an address offset.
+
ifndef::cheri_ratification_v1_only[]
NOTE: The  description below contains three hooks for extending <<JALR_CHERI>> behavior, used by extensions to give a large degree of extensibility.
 Unless an instruction, such as <<SENTRY>>, is implemented which explicitly reference any of the hooks, then take no action for any of them.
+
endif::[]
. The target address is obtained by adding the sign-extended 12-bit I-immediate to the register `{cs1}`, then setting the least-significant bit of the result to zero.
. The target <<pcc>> is obtained by applying the target address to `{cs1}` using the semantics of the <<SCADDR>> instruction.
ifndef::cheri_ratification_v1_only[]
. HOOK 1: Optionally clear the {ctag} of the target <<pcc>> depending on the <<sec_cap_type>> value and the numerical values of `{cd}` and `{cs1}`
. Unseal the target <<pcc>> if it is a <<sentry_cap>>.
endif::[]
ifndef::cheri_ratification_v1_only[]
. Clear the {ctag} of the target <<pcc>> if it is any other sealed type.
endif::[]
. The <<pcc>> of the next instruction is written to `{cd}`.
ifndef::cheri_ratification_v1_only[]
.. HOOK 2: Optionally seal the return capability as a <<sentry_cap>> with a <<sec_cap_type>> defined by the implemented extensions.
. HOOK 3: Optionally make other architectural state updates.
endif::[]
. Jump to the target <<pcc>>.
+
NOTE: A future extension may raise an exception on the <<JALR_CHERI>> instruction itself if the target <<pcc>> will raise a {cheri_excep_name_pc} at the target.

Included in::
<<rvy_i_mod_insn_table>>

Operation::
+
TODO

//commented out as it still has exception checks
//sail::execute[clause="JALR_capmode(_, _)",part=body,unindent]
