==== Integer Loads ({cheri_base_ext_name})
[#LD,reftext="LD"]
===== LD
[#LWU,reftext="LWU"]
===== LWU
[#LW,reftext="LW"]
===== LW
[#LHU,reftext="LHU"]
===== LHU
[#LH,reftext="LH"]
===== LH
[#LBU,reftext="LBU"]
===== LBU
[#LB,reftext="LB"]
===== LB

Synopsis::
Integer Load (LD, LW[U], LH[U], LB[U])

{cheri_cap_mode_name} Mnemonics::
`ld    rd, offset(cs1)` +
`lw[u] rd, offset(cs1)` +
`lh[u] rd, offset(cs1)` +
`lb[u] rd, offset(cs1)`

// {cheri_int_mode_name} Mnemonics::
// `ld    rd, offset(rs1)` +
// `lw[u] rd, offset(rs1)` +
// `lh[u] rd, offset(rs1)` +
// `lb[u] rd, offset(rs1)`

Encoding::
include::wavedrom/load.adoc[]

Description::
Load data of the indicated size (byte, halfword, word, double-word)
from memory. The effective address of the load is obtained by adding the
sign-extended 12-bit offset to the address of `cs1`. The authorizing capability
for the operation is `cs1`. A copy of the loaded value is written to `rd`.
+
include::load_store_c0.adoc[]

{cheri_int_mode_name} Description::
Load data of the indicated size (byte, halfword, word, double-word)
from memory. The effective address of the load is obtained by adding the
sign-extended 12-bit offset to `rs1`. The authorizing capability for the
operation is <<ddc>>. A copy of the loaded value is written to `rd`.

include::load_exceptions.adoc[]

Prerequisites for LD::
RV64 or RV32 with Zilsd
