<<<

[#LOAD_CAP,reftext="{LOAD_CAP_NAME}"]
==== {LOAD_CAP_NAME}

Synopsis::
{LOAD_CAP_DESC}

Mnemonic::
`{load_cap_name} {cd}, offset({cs1})`

Encoding::
include::wavedrom/loadcap.adoc[]

include::load_store_creg0.adoc[]


Description::
Calculate the effective address of the memory access by adding `{cs1}.address` to the sign-extended 12-bit offset.
+
Authorize the memory access with the capability in `{cs1}`.
+
Load a naturally aligned YLEN-bit data value and associated {ctag} from memory.
+
NOTE: The loaded {ctag} may be set to zero under platform specified conditions, such as by a hardware based use-after-free prevention scheme.
 Privileged mechanisms may also set the loaded {ctag} to zero such as PMA settings or virtual memory system page table entry configuration.
+
NOTE: Extensions may also specify additional conditions which set the {ctag} to zero.
+
The final value of `{cd}` is determined as follows:
+
. Write the loaded YLEN data to `{cd}` and the loaded {ctag} into `{cd}.tag`.
+
. If `{cs1}` does not grant <<c_perm>> then set `{cd}.tag=0`.
+
. If `{cd}.tag=1`, `{cs1}` does not grant <<lm_perm>> and `{cd}` is not sealed, then an implicit <<CLRPERM>> is performed to clear <<w_perm>> and <<lm_perm>> from `{cd}`.
+
NOTE: The implicit <<CLRPERM>> is not required to set `{cd}.tag=0` if the loaded data fails any <<section_cap_integrity,integrity>> checks.
 A suggested implementation is to only check the <<AP-field>> for legal values, and set the whole <<AP-field>> to zero if the check fails.
+
NOTE: Metadata modifications on loaded capabilities are on naturally aligned data.
 Therefore on the read path from a data cache, the modification typically happens in parallel with data alignment multiplexers.
+
NOTE: <<section_zylevels1>> adds to the <<CLRPERM>> rules on loaded capability data.
+
When sending load data to a trace interface, implementations trace the final value written to `{cd}` which may not match the value in memory.
+
include::load_exceptions.adoc[]
+
Operation::
+
sail::execute[clause="LoadCapImm(_, _, _)",part=body,unindent]
