<<<

[#FLD,reftext="FLD"]
==== FLD
See <<FLH>>.

[#FLW,reftext="FLW"]
==== FLW
See <<FLH>>.

[#FLH,reftext="FLH"]
==== FLH

Synopsis::
Floating point loads (FLD, FLW, FLH), 32-bit encodings

{cheri_cap_mode_name} Mnemonics::
`fld frd, offset({cs1})` +
`flw frd, offset({cs1})` +
`flh frd, offset({cs1})`

{cheri_int_mode_name} Mnemonics::
`fld rd, offset(rs1)` +
`flw rd, offset(rs1)` +
`flh rd, offset(rs1)`

Encoding::
include::wavedrom/fpload.adoc[]

{cheri_cap_mode_name} Description::
Standard floating point load instructions, authorized by the capability in `{cs1}`.
+
include::load_store_creg0.adoc[]

{cheri_int_mode_name} Description::
Standard floating point load instructions, authorized by the capability in <<ddc>>.

:!cap_load:
include::load_exceptions.adoc[]

Prerequisites for {cheri_cap_mode_name} FLD::
{cheri_base_ext_name}, and D

Prerequisites for {cheri_int_mode_name} FLD::
{cheri_default_ext_name}, and D

Prerequisites for {cheri_cap_mode_name} FLW::
{cheri_base_ext_name}, and F

Prerequisites for {cheri_int_mode_name} FLW::
{cheri_default_ext_name}, and F

Prerequisites for {cheri_cap_mode_name} FLH::
{cheri_base_ext_name}, and Zfhmin or Zfh

Prerequisites for {cheri_int_mode_name} FLH::
{cheri_default_ext_name}, and Zfhmin or Zfh

Operation::
+
--
TODO
--
