<<<

[#MODESW_INT,reftext="MODESW.INT"]
==== MODESW.INT
See <<MODESW_CAP>>.

[#MODESW_CAP,reftext="MODESW.CAP"]
==== MODESW.CAP

Synopsis::
Switch execution mode to {cheri_cap_mode_name} (MODESW.CAP), or {cheri_int_mode_name} (MODESW.INT), 32-bit encodings

Mnemonic::
`modesw.cap` +
`modesw.int`

Encoding::
include::wavedrom/modesw_32bit.adoc[]

Description::
Set the current CHERI execution mode in <<pcc>>.
+
* MODESW.CAP: If the current mode in <<pcc>> is {cheri_int_mode_name} ({INT_MODE_VALUE}), then the <<m_bit>> in <<pcc>> is set to {cheri_cap_mode_name} ({CAP_MODE_VALUE}). Otherwise no effect.
* MODESW.INT: If the current mode in <<pcc>> is {cheri_cap_mode_name} ({CAP_MODE_VALUE}), then the <<m_bit>> in <<pcc>> is set to {cheri_int_mode_name} ({INT_MODE_VALUE}). Otherwise no effect.

//TODO: move to debug spec
//NOTE: Executing <<MODESW_CAP>> or <<MODESW_INT>> from the program buffer in debug mode updates the <<m_bit>> of <<dinfc>>.
// The <<m_bit>> of <<dinfc>> sets the CHERI execution mode for the execution of the next instruction from the program buffer, and is used to control which CHERI execution mode to enter next time debug mode is entered.
// The CHERI execution mode is *only* controlled by the <<m_bit>> of <<dinfc>> in debug mode.

Operation::
+
sail::execute[clause="MODESW()",part=body,unindent]
