<<<

==== {MODESW_CAP}, {MODESW_INT}
anchor:MODESW_CAP[{MODESW_CAP}]
anchor:MODESW_INT[{MODESW_INT}]

Synopsis::
Switch execution mode to {cheri_cap_mode_name} ({MODESW_CAP}), or {cheri_int_mode_name} ({MODESW_INT}), 32-bit encodings

Mnemonics::
`{modesw_cap}` +
`{modesw_int}`

Encoding::
include::wavedrom/modesw_32bit.adoc[]

Description::
Set the current {cheri_mode_name} in <<pcc>>.
+
* {MODESW_CAP}: If the current mode in <<pcc>> is {cheri_int_mode_name} ({INT_MODE_VALUE}), then the <<p_bit>> in <<pcc>> is set to {cheri_cap_mode_name} ({CAP_MODE_VALUE}). Otherwise no effect.
* {MODESW_INT}: If the current mode in <<pcc>> is {cheri_cap_mode_name} ({CAP_MODE_VALUE}), then the <<p_bit>> in <<pcc>> is set to {cheri_int_mode_name} ({INT_MODE_VALUE}). Otherwise no effect.

Prerequisites::
{cheri_default_ext_name}

Operation::
// Manually updated for the current spec: MODESW.CAP and MODESW.INT are separate
// instructions now. The Sail model additionally updates drootc (from the debug
// specification) when in debug mode; that line is omitted here as this specification
// does not include the debug extension.

NOTE: This listing is manually maintained rather than extracted from the Sail model.
[source,SAIL,subs="verbatim,quotes"]
----
let target : ExecutionMode = match op {
  MODESW_CAP => CapPtrMode,
  MODESW_INT => IntPtrMode,
};
set_next_pcc(setCapMode(PCC, target));
RETIRE_SUCCESS
----
//sail::execute[clause="MODESW()",part=body,unindent]
