<<<

[#SCBNDSI,reftext="{SCBNDSI}"]
==== {SCBNDSI}

See <<SCBNDS>>.

[#SCBNDS,reftext="{SCBNDS}"]
==== {SCBNDS}

ifdef::cheri_v9_annotations[]
NOTE: *CHERI v9 Note:* {SCBNDS} was called CSETBOUNDSEXACT.

NOTE: *CHERI v9 Note:* {SCBNDSI} would have been CSETBOUNDSEXACTIMM if it had existed.
endif::[]

include::new_encoding_note.adoc[]

ifdef::cheri_v9_annotations[]
NOTE: *CHERI v9 Note:* the immediate format has changed
endif::[]

Synopsis::
{SCBNDS_DESC}

Mnemonics::
`{scbnds_lc} {cd}, {cs1}, rs2` +
`{scbndsi_lc} {cd}, {cs1}, uimm`

Encoding::
include::wavedrom/scbnds_32bit.adoc[]

Description::
Capability register `{cd}`  is set to capability register `{cs1}`  with the base
address of its bounds replaced with the value of `{cs1}.address` and
the length of its bounds set to `rs2[XLEN-1:0]` for <<SCBNDS>>, or `imm` for <<SCBNDSI>>.
+
Set `{cd}.tag=0` if `{cs1}.tag=0`, `{cs1}` is sealed or if `{cd}` 's bounds exceed `{cs1}` 's bounds.
+
Set `{cd}.tag=0` if the requested bounds cannot be encoded exactly.
+
include::malformed_cs1_clear_tag.adoc[]
+
<<SCBNDSI>> uses the `s` bit to scale the immediate by 4 places
+
`immediate = ZeroExtend(s ? uimm<<4 : uimm)`

NOTE: The <<SCBNDSI>> encoding with `s=1` and `uimm ≤ 1` is RESERVED since these immediates can also be encoded with `s=0`.

Included in::
{rvyi_xref}

Operation for {SCBNDS}::
+
sail::execute[clause="SCBNDS(_, _, _)",part=body,unindent]

Operation for {SCBNDSI}::
+
sail::execute[clause="SCBNDSI(_, _, _, _)",part=body,unindent]
