<<<

[#SCBNDSI,reftext="{SCBNDSI}"]
==== {SCBNDSI}

See <<SCBNDS>>.

[#SCBNDS,reftext="{SCBNDS}"]
==== {SCBNDS}

ifdef::cheri_v9_annotations[]
NOTE: *CHERI v9 Note:* {SCBNDS} was called CSETBOUNDSEXACT.

NOTE: *CHERI v9 Note:* {SCBNDSI} would have been CSETBOUNDSEXACTIMM if it had existed.
endif::[]

include::new_encoding_note.adoc[]

ifdef::cheri_v9_annotations[]
NOTE: *CHERI v9 Note:* the immediate format has changed
endif::[]

Synopsis::
{SCBNDS_DESC}

Mnemonics::
`{scbnds_lc} {cd}, {cs1}, rs2` +
`{scbndsi_lc} {cd}, {cs1}, imm`

Encoding::
include::wavedrom/scbnds_32bit.adoc[]

NOTE: 99.5% of uses of unrestricted allocation of {cs1} and {cd} for {SCBNDSI} have {cs1}={cd}, and so the cases where they do not match are reserved.

Description::
Copy the capability from register `{cs1}` to register `{cd}`.
Set the base address of its bounds to the value of `{cs1}.address` and
set the length of its bounds to `rs2[XLEN-1:0]` for <<SCBNDS>>, or `imm` for <<SCBNDSI>>.
+
Set `{cd}.tag=0` if `{cs1}.tag=0`, `{cs1}` is sealed or if `{cd}` 's bounds exceed `{cs1}` 's bounds.
+
Set `{cd}.tag=0` if the requested bounds cannot be encoded exactly.
+
include::malformed_cs1_clear_tag.adoc[]
+
<<SCBNDSI>> uses the following formula to determine the requested length:

* `((imm[7:0] + 257) << imm[9:8]) - 256`

Included in::
<<rvy_insn_table>>

Operation for {SCBNDS}::
+
sail::execute[clause="SCBNDS(_, _, _)",part=body,unindent]

Operation for {SCBNDSI}::
+
TODO
//this is out of date
//sail::execute[clause="SCBNDSI(_, _, _, _)",part=body,unindent]
