<<<

[#SCBNDSI,reftext="{SCBNDSI}"]
==== {SCBNDSI}

See <<SCBNDS>>.

[#SCBNDS,reftext="{SCBNDS}"]
==== {SCBNDS}

ifdef::cheri_v9_annotations[]
NOTE: *CHERI v9 Note:* {SCBNDS} was called CSETBOUNDSEXACT.

NOTE: *CHERI v9 Note:* {SCBNDSI} would have been CSETBOUNDSEXACTIMM if it had existed.
endif::[]

include::new_encoding_note.adoc[]

ifdef::cheri_v9_annotations[]
NOTE: *CHERI v9 Note:* the immediate format has changed
endif::[]

Synopsis::
{SCBNDS_DESC}

Mnemonics::
`{scbnds} {cd}, {cs1}, rs2` +
`{scbndsi} {cd}, {cs1}, imm`

Encoding::
include::wavedrom/scbnds_32bit.adoc[]

// NOTE: 99.5% of uses of unrestricted allocation of {cs1} and {cd} for {SCBNDSI} have {cs1}={cd}.
// We could have reserved those, but not doing so is more consistent with overall RISC-V design.

Description::
Copy the capability from register `{cs1}` to register `{cd}`.
Set the base address of its bounds to the value of `{cs1}.address` and
set the length of its bounds to `rs2[XLEN-1:0]` for <<SCBNDS>>, or `imm` for <<SCBNDSI>>.
+
Set `{cd}.tag=0` if `{cs1}.tag=0`.
+
Set `{cd}.tag=0` if `{cs1}` is sealed.
+
Set `{cd}.tag=0` if `{cd}` 's bounds exceed `{cs1}` 's bounds.
+
Set `{cd}.tag=0` if the requested bounds cannot be encoded exactly.
+
include::malformed_cs1_clear_tag.adoc[]
+
<<SCBNDSI>> decodes the 9-bit immediate value `imm[8:0]` to the requested length `result` as follows:

* If `imm[8:0] = 0`, `result` is `4096`.
* If `imm[8] = 0` and `imm[7:0] != 0`, `result` is `imm[7:0]`.
* If `imm[8] = 1` and `imm[7:5] = 0`, `result` is `256 | (imm[3:0] << 4) | (imm[4] << 3)`.
* Otherwise, `result` is `imm[7:0] << 4`.

+
The resulting logical encodable regions and step sizes are summarized in the table below:

[%autowidth,options="header",align="left"]
|===
| Region | Decoded range (bytes) | Immediate decoding condition

| Byte granular
| `1, 2, ..., 255`
| `imm[8] = 0` and `imm[7:0] > 0`

| 8-byte granular
| `256, 264, ..., 504`
| `imm[8:5] = 4'b1000`

<| 16-byte granular
| `512, 528, ..., 4080`
| `imm[8:5] > 4'b1000`

<| Page-sized
| `4096`
| `imm[8:0] = 0`
|===

[NOTE]
====
This immediate encoding scheme achieves coverage of almost all observed immediate values while decoding the 9-bit immediate field without any adders or variable shifts.
Mapping `imm = 0` to `4096` reclaims the redundant zero encoding (already covered by `{scbnds} dst, src, x0`) to support highly common page-sized objects.

The hardware implementation is a simple bit-remapping: +
`result[12] = (imm[8:0] == 0);` +
`result[11:9] = imm[8] ? imm[7:5] : 0;` +
`result[8] = imm[8] ? (imm[7:5] == 0b000 || imm[4]) : 0;` +
`result[7:4] = imm[8] ? imm[3:0] : imm[7:4];` +
`result[3] = imm[8] ? (imm[7:4] == 0b0001) : imm[3];` +
`result[2:0] = imm[8] ? 0 : imm[2:0];`
====

Operation for {SCBNDS}::
+
sail::execute[clause="SCBNDS(_, _, _)",part=body,unindent]

Operation for {SCBNDSI}::
// YBNDSWI in the JSON uses a different immediate, add it manually.
WARNING: Manually written code, to be replaced when updated SAIL is available.
[source,SAIL,subs="verbatim,quotes"]
----
let cs1_val = C(cs1);
// Decode the requested length from the 9-bit immediate.
let length : xlenbits =
  if imm == 0b000000000 then to_bits(xlen, 4096)
  else if imm[8] == bitzero then zero_extend(imm[7 .. 0])
  else if imm[7 .. 5] == 0b000 then zero_extend(0b1 @ imm[3 .. 0] @ imm[4 .. 4] @ 0b000)
  else zero_extend(imm[7 .. 0] @ 0b0000);
let newBase = cs1_val.address;
let newTop : CapLenBits = zero_extend(newBase) + zero_extend(length);
// inCapBoundsNoWrap returns false if the input bounds are malformed.
let inBounds = inCapBoundsNoWrap(cs1_val, newBase, unsigned(length));
let (exact, newCap) : (bool, Capability) = setCapBounds(cs1_val, newBase, newTop);
let cond = not(inBounds & exact) |
           boundsMalformed(newCap) |
           not(capReservedValid(newCap)) |
           capIsSealed(newCap);
C(cd) = clearTagIf(newCap, cond);
RETIRE_SUCCESS
----
