<<<

[#SCBNDSI,reftext="{SCBNDSI}"]
==== {SCBNDSI}

See <<SCBNDS>>.

[#SCBNDS,reftext="{SCBNDS}"]
==== {SCBNDS}

ifdef::cheri_v9_annotations[]
NOTE: *CHERI v9 Note:* {SCBNDS} was called CSETBOUNDSEXACT.

NOTE: *CHERI v9 Note:* {SCBNDSI} would have been CSETBOUNDSEXACTIMM if it had existed.
endif::[]

include::new_encoding_note.adoc[]

ifdef::cheri_v9_annotations[]
NOTE: *CHERI v9 Note:* the immediate format has changed
endif::[]

Synopsis::
{SCBNDS_DESC}

Mnemonics::
`{scbnds_lc} {cd}, {cs1}, rs2` +
`{scbndsi_lc} {cd}, {cs1}, imm`

Encoding::
include::wavedrom/scbnds_32bit.adoc[]

// NOTE: 99.5% of uses of unrestricted allocation of {cs1} and {cd} for {SCBNDSI} have {cs1}={cd}.
// We could have reserved those, but not doing so is more consistent with overall RISC-V design.

Description::
Copy the capability from register `{cs1}` to register `{cd}`.
Set the base address of its bounds to the value of `{cs1}.address` and
set the length of its bounds to `rs2[XLEN-1:0]` for <<SCBNDS>>, or `imm` for <<SCBNDSI>>.
+
Set `{cd}.tag=0` if `{cs1}.tag=0`, `{cs1}` is sealed or if `{cd}` 's bounds exceed `{cs1}` 's bounds.
+
Set `{cd}.tag=0` if the requested bounds cannot be encoded exactly.
+
include::malformed_cs1_clear_tag.adoc[]
+
<<SCBNDSI>> decodes the 9-bit immediate value `imm[8:0]` to the requested length `result` as follows:

* If `imm[8:0] == 0`, `result` is `4096`.
* If `imm[8] == 0` and `imm[7:0] > 0`, `result[7:0] = imm[7:0]` with all other bits set to `0`.
* If `imm[8] == 1`, `result` is decoded as follows, with all other bits set to `0`:
  * If `imm[7:4] != 0000`, then `result[11:4] = imm[7:0]`.
  * If `imm[7:4] == 0000`, then `result[8] = 1`, `result[7:4] = imm[3:0]`, `result[3] = 1`.

The resulting logical encodable regions and step sizes are summarized in the table below:

[%autowidth,options="header",align="left"]
|===
| Region | Decoded range (bytes) | Immediate decoding condition

| Byte granular
| `1, 2, ..., 255`
| `imm[8] == 0` and `imm[7:0] > 0`

.2+<| 8-byte granular
.2+<| `256, 264, ..., 504`
| `imm[8] == 1` and `imm[7:4] == 0001` (even multiples of 8)

| `imm[8] == 1` and `imm[7:4] == 0000` (odd multiples of 8)

.2+<| 16-byte granular
| `512, 528, ..., 4080`
| `imm[8] == 1` and `imm[7:4] >= 0010`

| `4096`
| `imm[8:0] == 0`
|===

[NOTE]
====
This immediate encoding scheme achieves coverage of almost all observed immediate values while decoding the 9-bit immediate field without any adders or variable shifts.
The linear range, stride-16 range, and stride-8 region are decoded via simple multiplexers and bit wiring.
Mapping `imm == 0` to `4096` reclaims the redundant zero encoding (already covered by `{scbnds_lc} dst, src, x0`) to support highly common page-sized objects.
====

Included in::
<<rvy_insn_table>>

Operation for {SCBNDS}::
+
sail::execute[clause="SCBNDS(_, _, _)",part=body,unindent]

Operation for {SCBNDSI}::
+
TODO
//this is out of date
//sail::execute[clause="SCBNDSI(_, _, _, _)",part=body,unindent]
