<<<

[#SCSS,reftext="SCSS"]
==== SCSS

ifdef::cheri_v9_annotations[]
NOTE: *CHERI v9 Note:* this instruction was called CTESTSUBSET.

NOTE: *CHERI v9 Note:* this instruction does not use ddc if cs1==0


endif::[]

include::new_encoding_note.adoc[]

Synopsis::
Set Capability Subset

Mnemonic::
`scss rd, cs1, cs2`

Encoding::
include::wavedrom/scss.adoc[]

Description::
`rd` is set to 1 if:
. the validity tag of capabilities `cs1` and `cs2` are equal, and
. the bounds and permissions of `cs2` are a subset of those of `cs1`, and
. `cs2` 's <<section_cap_level>> is equal to or lower than `cs1` 's
+
NOTE: With {cheri_0levels_ext_name} this check always passes as the level is hardwired.
. neither `cs1` or `cs2` have bounds which are <<section_cap_malformed,malformed>>, and
. neither `cs1` or `cs2` have any bits set in reserved fields, and
. neither `cs1` or `cs2` have permissions that could not have been legally produced by <<ACPERM>>

Otherwise set `rd` to 0.

NOTE: The implementation of this instruction is similar to <<CBLD>>, although
<<SCSS>> does not include the sealed bit in the check.

Operation::
+
sail::execute[clause="SCSS(_, _, _)",part=body,unindent]
