[#YSEAL,reftext="{YSEAL}"]
==== {YSEAL}

include::new_encoding_note.adoc[]

ifdef::cheri_v9_annotations[]
NOTE: *CHERI v9 Note:* this instruction was called CSEALENTRY.
endif::[]

Synopsis::
{YSEAL_DESC}

Mnemonic::
`{yseal_lc} {cd}, {cs1}, {cs2}`

Encoding::
include::wavedrom/sentry.adoc[]

NOTE: `{cs1}{ne}x0` is currently _reserved_.

Description::
Copy `{cs2}` to `{cd}`.
+
Seal the capability in `{cd}` by setting `{cd}.ct=1`.
+
Set `{cd}.tag=0` if `{cs2}` is sealed.
+
NOTE: Future extensions may allow `{cs1}{ne}x0` to specify an authorizing capability to perform the sealing action, and also to specify the destination <<sec_cap_type>> value.
+
NOTE: If the capability encoding format does not support a <<CT-field>> of type 1, then this instruction is _reserved_.
 Future capability formats may redefine the behavior for <<CT-field>> values greater than 1.

Included in::
<<rvy_insn_table>>

Operation::
+
TODO

<<<

[#SENTRY,reftext="{SENTRY}"]
==== {SENTRY}

Synopsis::
{SENTRY_DESC}

Mnemonic::
`{sentry_lc} {cd}, {cs2}`

Encoding::
{SENTRY} is a pseudoinstruction for <<YSEAL>> with `{cs1}=x0`.

Description::
Copy `{cs2}` to `{cd}`.
+
Seal the capability in `{cd}` by setting `{cd}.ct=1`.
+
Set `{cd}.tag=0` if `{cs2}` is sealed.

Included in::
<<rvy_insn_table>>
