<<<

[#SENTRY,reftext="{SENTRY}"]
==== {SENTRY}

include::new_encoding_note.adoc[]

ifdef::cheri_v9_annotations[]
NOTE: *CHERI v9 Note:* this instruction was called CSEALENTRY.
endif::[]

Synopsis::
Seal capability as indicated type.

Mnemonic::
`{sentry_lc} cd, cs1`

#FIXME: This needs an immediate field set to 1 for SENTRY#

NOTE: Only value 1 for sentry is supported at this time. Future extensions will add more types.

Encoding::
include::wavedrom/sentry.adoc[]

Description::
Copy `cs1` to `cd`. Set the capability type of `cd` to <<sentry_cap>>.
+
Set `cd.tag=0` if `cs1` is sealed.
+
ifdef::cheri_standalone_spec[]
// Omit this note for ISA manual integration, CHERIoT-specific
NOTE: The <<SENTRY>> instruction may give rise to an illegal instruction fault
when the implementation does not support capability type 1 (unrestricted
sentry; see xref:sec_cap_type[xrefstyle=short]).
This is not the case when the implementation supports the capability encoding described in xref:app_cap_description[xrefstyle=short].
endif::[]

Operation::
+
sail::execute[clause="SENTRY(_, _)",part=body,unindent]
