[#SENTRY,reftext="{SENTRY}"]
==== {SENTRY}

include::new_encoding_note.adoc[]

ifdef::cheri_v9_annotations[]
NOTE: *CHERI v9 Note:* this instruction was called CSEALENTRY.
endif::[]

Synopsis::
{SENTRY_DESC}

Mnemonic::
`{sentry} {cd}, {cs2}`

Encoding::
include::wavedrom/sentry.adoc[]

NOTE: `{cs1}{ne}x0` is currently _reserved_ to decode as a future YSEAL instruction.

Description::
Copy `{cs2}` to `{cd}`.
+
Seal the capability in `{cd}` by setting `{cd}.ct=1`.
+
Set `{cd}.tag=0` if `{cs2}` is sealed or fails any <<section_cap_integrity,integrity>> checks.
+
NOTE: A future extension will allow YSEAL, which has `{cs1}` specifying an authorizing capability, to perform the sealing action and to specify the destination <<sec_cap_type>> value.
+
NOTE: If the capability encoding format does not support a <<CT-field>> of type 1, then this instruction is _reserved_.
 Future capability encoding formats may redefine the behavior for <<CT-field>> values greater than 1.

Operation::
// The Sail SENTRY clause seals its cs1 operand; the current instruction seals
// cs2 (cs1 is reserved for a future YSEAL) and also invalidates on a failed
// integrity check.

NOTE: This listing is manually maintained rather than extracted from the Sail model.
[source,SAIL,subs="verbatim,quotes"]
----
let cs2_val = C(cs2);
let inCap = clearTagIf(cs2_val, capIsSealed(cs2_val) | not(capReservedValid(cs2_val)));
C(cd) = sealCap(inCap);
RETIRE_SUCCESS
----
//sail::execute[clause="SENTRY(_, _)",part=body,unindent]
