[#SENTRY,reftext="{SENTRY}"]
==== {SENTRY}

include::new_encoding_note.adoc[]

ifdef::cheri_v9_annotations[]
NOTE: *CHERI v9 Note:* this instruction was called CSEALENTRY.
endif::[]

Synopsis::
{SENTRY_DESC}

Mnemonic::
`{sentry_lc} {cd}, {cs1}`

Encoding::
include::wavedrom/sentry.adoc[]

#Begin changed since last ARC review#

Description::
Copy `{cs1}` to `{cd}`.
+
Set the capability type (<<sec_cap_type>>) of `{cd}` to
the <<sec_cap_type_ambient,ambient>> value specified by the capability encoding.
+
Set `{cd}.tag=0` if `{cs1}` is sealed.
+
ifdef::cheri_standalone_spec[]
// Omit this note for ISA manual integration, CHERIoT-specific
NOTE: The <<SENTRY>> instruction may give rise to an illegal instruction fault
when the implementation does not support capability type 1 (unrestricted
sentry; see xref:sec_cap_type[xrefstyle=short]).
This is not the case when the implementation supports the capability encoding described in xref:app_cap_description[xrefstyle=short].
endif::[]

#End changed since last ARC review#

Included in::
<<rvy_sentry_insn_table>>

Operation::
+
sail::execute[clause="SENTRY(_, _)",part=body,unindent]
