<<<

[#SH1ADD,reftext="SH1ADD"]
==== SH1ADD
See <<SH3ADD>>.

[#SH2ADD,reftext="SH2ADD"]
==== SH2ADD
See <<SH3ADD>>.

[#SH3ADD,reftext="SH3ADD"]
==== SH3ADD

Synopsis::
Shift by _n_ and add for address generation (SH1ADD, SH2ADD, SH3ADD)

{cheri_cap_mode_name} Mnemonics::
`sh[1|2|3]add cd, rs1, cs2`

{cheri_int_mode_name} Mnemonics::
`sh[1|2|3]add rd, rs1, rs2`

Encoding::
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x33, attr: ['OP'] },
    { bits:  5, name: 'cd' },
    { bits:  3, name: 'func3', attr: ['SH1ADD=010', 'SH2ADD=100', 'SH3ADD=110'] },
    { bits:  5, name: 'rs1' },
    { bits:  5, name: 'cs2' },
    { bits:  7, name: 0x10, attr: ['SH[1|2|3]ADD'] },
]}
....

{cheri_cap_mode_name} Description::
Increment the address field of `cs2` by `rs1` shifted left by _n_ bit positions
and write the result to `cd`. The validity tag bit of the output capability is 0 if
`cs2` did not have its tag set to 1, the incremented address is outside `cs2`
's <<section_cap_representable_check>> or `cs2` is sealed.

include::malformed_shadd_clear_tag.adoc[]

{cheri_int_mode_name} Description::
Increment `rs2` by `rs1` shifted left by _n_ bit positions and write the result
to `rd`.

Exceptions::
None

Prerequisites for {cheri_cap_mode_name}::
{cheri_base_ext_name}, Zba

Prerequisites for {cheri_int_mode_name}::
{cheri_default_ext_name}, Zba

{cheri_cap_mode_name} Operation::
+
sail::execute[clause="ZBA_RTYPE_capmode(_, _, _, _)",part=body,unindent]

{cheri_int_mode_name} Operation::
+
sail::execute[clause="ZBA_RTYPE(_, _, _, _)",part=body,unindent]
