<<<

==== {SH1ADD_UW_CHERI}, {SH2ADD_UW_CHERI}, {SH3ADD_UW_CHERI}, {SH4ADD_UW_CHERI}  ({cheri_base64_ext_name})

anchor:SH1ADD_UW_CHERI[{SH1ADD_UW_CHERI}]
anchor:SH2ADD_UW_CHERI[{SH2ADD_UW_CHERI}]
anchor:SH3ADD_UW_CHERI[{SH3ADD_UW_CHERI}]
anchor:SH4ADD_UW_CHERI[{SH4ADD_UW_CHERI}]

Synopsis::
Shift by _n_ and add unsigned words for address generation ({SH1ADD_UW_CHERI}, {SH2ADD_UW_CHERI}, {SH3ADD_UW_CHERI}, {SH4ADD_UW_CHERI})

Mnemonics ({cheri_base64_ext_name})::
`{sh1add_uw_cheri} {cd}, rs1, {cs2}` +
`{sh2add_uw_cheri} {cd}, rs1, {cs2}` +
`{sh3add_uw_cheri} {cd}, rs1, {cs2}` +
`{sh4add_uw_cheri} {cd}, rs1, {cs2}`

Encoding::
[wavedrom, , svg,subs=attributes+]
....
{reg: [
  {bits:  7, name: 'opcode',     attr: ['7', 'RVY-A=1111011'],    type: 8},
  {bits:  5, name: '{cd}',       attr: ['5', 'dest'],             type: 2},
  {bits:  3, name: 'funct3',     attr: ['3', 'RVY-R=000'],        type: 8},
  {bits:  5, name: 'rs1',        attr: ['5', 'src1'],             type: 4},
  {bits:  5, name: '{cs2}',      attr: ['5', 'src2'],             type: 4},
  {bits:  7, name: 'funct7',     attr: ['7', '{SH1ADD_UW_CHERI}=0100101', '{SH2ADD_UW_CHERI}=0101101', '{SH3ADD_UW_CHERI}=0110101', '{SH4ADD_UW_CHERI}=0111101'], type: 3},
]}
....

WARNING: The instruction encoding is not final and is highly likely to change prior to v1.0


Description::
Copy the capability in `{cs2}` to `{cd}`.
+
Increment `{cd}.address` by the unsigned word `rs1` shifted left by _n_ bit positions.
+
Set `{cd}.tag=0` if `{cs2}` is sealed.
+
include::rep_range_check.adoc[]
+
include::malformed_cs2_clear_tag.adoc[]

Operation::
// Manually updated for the current spec, sail JSON file omitted SH4ADD.UW

NOTE: This listing is manually maintained rather than extracted from the Sail model.
[source,SAIL,subs="verbatim,quotes"]
----
let rs1_val = X(rs1);
let cs2_val = C(cs2);
let shamt : range(1,4) = match op {
  RISCV_SH1ADDUW => 1,
  RISCV_SH2ADDUW => 2,
  RISCV_SH3ADDUW => 3,
  RISCV_SH4ADDUW => 4,
};
let result = incCapAddrChecked(cs2_val, zero_extend(rs1_val[31..0]) << shamt);
C(cd) = result;
RETIRE_SUCCESS
----
//sail::execute[clause="ZBA_RTYPEUW_capmode(_, _, _, _)",part=body,unindent]
