<<<

[#SH1ADD_UW_CHERI,reftext="{SH1ADD_UW_CHERI}"]
==== {SH1ADD_UW_CHERI}
See <<SH3ADD_UW_CHERI>>.

[#SH2ADD_UW_CHERI,reftext="{SH2ADD_UW_CHERI}"]
==== {SH2ADD_UW_CHERI}
See <<SH3ADD_UW_CHERI>>.

[#SH3ADD_UW_CHERI,reftext="{SH3ADD_UW_CHERI}"]
==== {SH3ADD_UW_CHERI}

Synopsis::
Shift by _n_ and add unsigned word for address generation ({SH1ADD_UW_CHERI}, {SH2ADD_UW_CHERI}, {SH3ADD_UW_CHERI})

Mnemonics ({cheri_base64_ext_name})::
`{sh1add_uw_cheri_lc} cd, rs1, cs2` +
`{sh2add_uw_cheri_lc} cd, rs1, cs2` +
`{sh3add_uw_cheri_lc} cd, rs1, cs2`

Encoding::
[wavedrom, , svg,subs=attributes+]
....
{reg:[
    { bits:  7, name: 0x3b, attr: ['OP'] },
    { bits:  5, name: 'cd' },
    { bits:  3, name: 'func3', attr: ['rv64: {SH1ADD_UW_CHERI}=010', 'rv64: {SH1ADD_UW_CHERI}=100', 'rv64: {SH1ADD_UW_CHERI}=110'] },
    { bits:  5, name: 'rs1' },
    { bits:  5, name: 'cs2' },
    { bits:  7, name: 0x10 },
]}
....

NOTE: #these encodings needs to be separate from the integer versions, and sh4add needs moving here#

include::cheri_mode_dependent.adoc[]

Description::
Copy the capability in `cs2` to `cd`.
+
Increment `cd.address` by the unsigned word `rs1` shifted left by _n_ bit positions.
+
Set `cd.tag=0` if `cs2` is sealed.
+
include::rep_range_check.adoc[]
+
include::malformed_cs2_clear_tag.adoc[]

Prerequisites::
RV64, {cheri_base_ext_name}, Zba

Operation::
+
sail::execute[clause="ZBA_RTYPEUW_capmode(_, _, _, _)",part=body,unindent]
