<<<

[#SH1ADD_CHERI,reftext="{SH1ADD_CHERI}"]
==== {SH1ADD_CHERI}
See <<SH4ADD_CHERI>>.

[#SH2ADD_CHERI,reftext="{SH2ADD_CHERI}"]
==== {SH2ADD_CHERI}
See <<SH4ADD_CHERI>>.

[#SH3ADD_CHERI,reftext="{SH3ADD_CHERI}"]
==== {SH3ADD_CHERI}
See <<SH4ADD_CHERI>>.

[#SH4ADD_CHERI,reftext="{SH4ADD_CHERI} ({cheri_base64_ext_name})"]
==== {SH4ADD_CHERI} ({cheri_base64_ext_name})

Synopsis::
Shift by _n_ and add for address generation ({SH1ADD_CHERI}, {SH2ADD_CHERI}, {SH3ADD_CHERI}, {SH4ADD_CHERI})

Mnemonics ({cheri_base_ext_name})::
`{sh1add_cheri_lc} {cd}, rs1, {cs2}` +
`{sh2add_cheri_lc} {cd}, rs1, {cs2}` +
`{sh3add_cheri_lc} {cd}, rs1, {cs2}`

Mnemonics ({cheri_base64_ext_name})::
`{sh4add_cheri_lc} {cd}, rs1, {cs2}`

Encoding::
[wavedrom, , svg,subs=attributes+]
....
{reg: [
  {bits:  7, name: 'opcode',     attr: ['7', 'RVY-A=1111011'],    type: 8},
  {bits:  5, name: '{cd}',       attr: ['5', 'dest'],             type: 2},
  {bits:  3, name: 'funct3',     attr: ['3', 'RVY-R=000'],        type: 8},
  {bits:  5, name: 'rs1',        attr: ['5', 'src1'],             type: 4},
  {bits:  5, name: '{cs2}',      attr: ['5', 'src2'],             type: 4},
  {bits:  7, name: 'funct7',     attr: ['7', '{SH1ADD_CHERI}=0000101', '{SH2ADD_CHERI}=0001101', '{SH3ADD_CHERI}=0010101', '{SH4ADD_CHERI}=0011101'], type: 3},
]}
....

WARNING: The instruction encoding is not final and is highly likely to change prior to v1.0


Description::
Copy the capability in `{cs2}` to `{cd}`.
+
Increment `{cd}.address` by `rs1` shifted left by _n_ bit positions.
+
Set `{cd}.tag=0` if `{cs2}` is sealed.
+
include::rep_range_check.adoc[]
+
include::malformed_cs2_clear_tag.adoc[]

Included in::
<<rvy_zba_insn_table>>

Operation::
+
sail::execute[clause="ZBA_RTYPE_capmode(_, _, _, _)",part=body,unindent]
