<<<

[#SH1ADD_CHERI,reftext="{SH1ADD_CHERI}"]
==== {SH1ADD_CHERI}
See <<SH3ADD_CHERI>>.

[#SH2ADD_CHERI,reftext="{SH2ADD_CHERI}"]
==== {SH2ADD_CHERI}
See <<SH3ADD_CHERI>>.

[#SH3ADD_CHERI,reftext="{SH3ADD_CHERI}"]
==== {SH3ADD_CHERI}

Synopsis::
Shift by _n_ and add for address generation ({SH1ADD_CHERI}, {SH2ADD_CHERI}, {SH3ADD_CHERI})

Mnemonics ({cheri_base_ext_name})::
`{sh1add_cheri_lc} {creg_pref}d, rs1, {creg_pref}s2` +
`{sh2add_cheri_lc} {creg_pref}d, rs1, {creg_pref}s2` +
`{sh3add_cheri_lc} {creg_pref}d, rs1, {creg_pref}s2`

Encoding::
[wavedrom, , svg,subs=attributes+]
....
{reg:[
    { bits:  7, name: 0x33, attr: ['OP'] },
    { bits:  5, name: '{creg_pref}d' },
    { bits:  3, name: 'func3', attr: ['{SH1ADD_CHERI}=010', '{SH2ADD_CHERI}=100', '{SH3ADD_CHERI}=110'] },
    { bits:  5, name: 'rs1' },
    { bits:  5, name: '{creg_pref}s2' },
    { bits:  7, name: 0x10 },
]}
....

NOTE: These encodings are shared with integer `sh1add`, `sh2add`, `sh3add`.

include::cheri_mode_dependent.adoc[]

Description::
Copy the capability in `{creg_pref}s2` to `{creg_pref}d`.
+
Increment `{creg_pref}d.address` by `rs1` shifted left by _n_ bit positions.
+
Set `{creg_pref}d.tag=0` if `{creg_pref}s2` is sealed.
+
include::rep_range_check.adoc[]
+
include::malformed_cs2_clear_tag.adoc[]

Exceptions::
None

Prerequisites::
{cheri_base_ext_name}, Zba

Operation::
+
sail::execute[clause="ZBA_RTYPE_capmode(_, _, _, _)",part=body,unindent]
