<<<

[#SH1ADD_UW_CHERI,reftext="SH1ADD.UW ({cheri_base64_ext_name})"]
==== SH1ADD.UW ({cheri_base64_ext_name})
See <<SH3ADD_UW_CHERI>>.

[#SH2ADD_UW_CHERI,reftext="SH2ADD.UW ({cheri_base64_ext_name})"]
==== SH2ADD.UW ({cheri_base64_ext_name})
See <<SH3ADD_UW_CHERI>>.

[#SH3ADD_UW_CHERI,reftext="SH3ADD.UW ({cheri_base64_ext_name})"]
==== SH3ADD.UW ({cheri_base64_ext_name})

Synopsis::
Shift by _n_ and add unsigned word for address generation (SH1ADD.UW, SH2ADD.UW, SH3ADD.UW)

Mnemonics ({cheri_base64_ext_name})::
`sh[1|2|3]add.uw cd, rs1, cs2`

//{cheri_int_mode_name} Mnemonics (RV64)::
//`sh[1|2|3]add.uw rd, rs1, rs2`

Encoding::
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x3b, attr: ['OP'] },
    { bits:  5, name: 'cd' },
    { bits:  3, name: 'func3', attr: ['rv64: SH1ADD.UW=010', 'rv64: SH2ADD.UW=100', 'rv64: SH3ADD.UW=110'] },
    { bits:  5, name: 'rs1' },
    { bits:  5, name: 'cs2' },
    { bits:  7, name: 0x10, attr: ['rv64: SH[1|2|3]ADD.UW'] },
]}
....

include::cheri_mode_dependent.adoc[]

Description::
Copy the capability in `cs2` to `cd`.
+
Increment `cd.address` by the unsigned word `rs1` shifted left by _n_ bit positions.
+
Set `cd.tag=0` if `cs2` is sealed.
+
include::rep_range_check.adoc[]
+
include::malformed_shadd_clear_tag.adoc[]

//{cheri_int_mode_name} Description::
//Increment `rs2` by the unsigned word in `rs1` shifted left by _n_ bit positions
//and write the result to `rd`.

//Exceptions::
//None

Prerequisites::
RV64, {cheri_base_ext_name}, Zba

//Prerequisites for {cheri_int_mode_name}::
//RV64, {cheri_default_ext_name}, Zba

Operation::
+
sail::execute[clause="ZBA_RTYPEUW_capmode(_, _, _, _)",part=body,unindent]

//{cheri_int_mode_name} Operation::
//+
//sail::execute[clause="ZBA_RTYPEUW(_, _, _, _)",part=body,unindent]
