<<<

[#SH4ADD_CHERI,reftext="{SH4ADD_CHERI}"]
==== {SH4ADD_CHERI}, SH4ADD

ifdef::cheri_v9_annotations[]
NOTE: *CHERI v9 Note:* This instruction is *new*.
endif::[]

Synopsis::
Shift by 4 and add for address generation ({SH4ADD_CHERI})

Mnemonic ({cheri_base64_ext_name})::
`{SH4ADD_CHERI_LC} {creg_pref}d, rs1, {creg_pref}s2`

Mnemonic (RV64I)::
`sh4add rd, rs1, rs2`

Encoding::
[wavedrom, , svg,subs=attributes+]
....
{reg:[
    { bits:  7, name: 0x33, attr: ['OP'] },
    { bits:  5, name: '{creg_pref}d' },
    { bits:  3, name: 0x7, attr: ['rv64: {SH4ADD_CHERI}'] },
    { bits:  5, name: 'rs1' },
    { bits:  5, name: '{creg_pref}s2' },
    { bits:  7, name: 16, attr: ['rv64: {SH4ADD_CHERI}'] },
]}
....

NOTE: This encoding is shared with integer `sh4add`.

include::cheri_mode_dependent.adoc[]

{cheri_base64_ext_name} Description::
Copy the capability in `{creg_pref}s2` to `{creg_pref}d`.
+
Increment `{creg_pref}d.address` by `rs1` shifted left by 4 bit positions.
+
Set `{creg_pref}d.tag=0` if `{creg_pref}s2` is sealed.
+
include::rep_range_check.adoc[]
+
include::malformed_cs2_clear_tag.adoc[]

RV64I Description::
Increment `rs2` by `rs1` shifted left by 4 bit positions and write the result to `rd`.

Prerequisites for {cheri_base64_ext_name} ({SH4ADD_CHERI})::
{sh4add_ext_name}

Prerequisites for RV64I (sh4add)::
{sh4add_ext_name}

{cheri_base64_ext_name} Operation::
+
sail::execute[clause="ZBA_SH4ADD_capmode(_, _, _)",part=body,unindent]

RV64I Operation::
+
sail::execute[clause="ZBA_SH4ADD(_, _, _)",part=body,unindent]
