<<<

[#SH4ADD_UW,reftext="SH4ADD.UW"]
==== SH4ADD.UW

Synopsis::
Shift by 4 and add unsigned words for address generation (SH4ADD.UW)

Mnemonic ({cheri_base64_ext_name})::
`sh4add.uw cd, rs1, cs2`

Mnemonic (RV64I)::
`sh4add.uw rd, rs1, rs2`

Encoding::
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x3b, attr: ['OP-32'] },
    { bits:  5, name: 'cd' },
    { bits:  3, name: 0x7, attr: ['rv64: SH4ADD.UW'] },
    { bits:  5, name: 'rs1' },
    { bits:  5, name: 'cs2' },
    { bits:  7, name: 16, attr: ['rv64: SH4ADD.UW'] },
]}
....

include::cheri_mode_dependent.adoc[]

{cheri_base64_ext_name} Description::
Copy the capability in `cs2` to `cd`.
+
Increment `cd.address` by the unsigned word in `rs1` shifted left by 4 bit positions.
+
Set `cd.tag=0` if `cs2` is sealed.
+
include::rep_range_check.adoc[]
+
include::malformed_cs2_clear_tag.adoc[]

RV64I Description::
Increment `rs2` by the unsigned word in `rs1` shifted left by 4 bit positions
and write the result to `rd`.

//Exceptions::
//None

Prerequisites for {cheri_base64_ext_name}::
{cheri_base64_ext_name}, {sh4add_ext_name}

Prerequisites for RV64I::
RV64, {sh4add_ext_name}

{cheri_base64_ext_name}} Operation::
+
sail::execute[clause="ZBA_SH4ADDUW_capmode(_, _, _)",part=body,unindent]

RV64I Operation::
+
sail::execute[clause="ZBA_SH4ADDUW(_, _, _)",part=body,unindent]
