<<<

[#SH4ADD,reftext="SH4ADD"]
==== SH4ADD

ifdef::cheri_v9_annotations[]
NOTE: *CHERI v9 Note:* This instruction is *new*.
endif::[]

Synopsis::
Shift by 4 and add for address generation (SH4ADD)

Mnemonic ({cheri_base64_ext_name})::
`sh4add cd, rs1, cs2`

Mnemonic (RV64I)::
`sh4add rd, rs1, rs2`

Encoding::
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x33, attr: ['OP'] },
    { bits:  5, name: 'cd' },
    { bits:  3, name: 0x7, attr: ['rv64: SH4ADD'] },
    { bits:  5, name: 'rs1' },
    { bits:  5, name: 'cs2' },
    { bits:  7, name: 16, attr: ['rv64: SH4ADD'] },
]}
....

include::cheri_mode_dependent.adoc[]

{cheri_base64_ext_name} Description::
Copy the capability in `cs2` to `cd`.
+
Increment `cd.address` by `rs1` shifted left by 4 bit positions.
+
Set `cd.tag=0` if `cs2` is sealed.
+
include::rep_range_check.adoc[]
+
include::malformed_shadd_clear_tag.adoc[]

RV64I Description::
Increment `rs2` by `rs1` shifted left by 4 bit positions and write the result to `rd`.

//Exceptions::
//None

Prerequisites for {cheri_base64_ext_name}::
{sh4add_ext_name}

Prerequisites for RV64I::
{sh4add_ext_name}

Operation::
+
sail::execute[clause="ZBA_SH4ADD_capmode(_, _, _)",part=body,unindent]

{cheri_int_mode_name} Operation::
+
sail::execute[clause="ZBA_SH4ADD(_, _, _)",part=body,unindent]
