<<<

[#SC,reftext="SC"]
==== SC

NOTE: The RV64 encoding is intended to also allocate the encoding for SQ for RV128.

Synopsis::
Store capability

{cheri_cap_mode_name} Mnemonic::
`sc cs2, offset(cs1)`

{cheri_int_mode_name} Mnemonic::
`sc cs2, offset(rs1)`

Encoding::
include::wavedrom/storecap.adoc[]

{cheri_cap_mode_name} Description::
Store the CLEN+1 bit value in `cs2` to memory. The capability in `cs1`
authorizes the operation. The effective address of the memory access is
obtained by adding the address of `cs1` to the sign-extended 12-bit offset.
+
include::load_store_c0.adoc[]

{cheri_int_mode_name} Description::
Store the CLEN+1 bit value in `cs2` to memory. The capability
authorizing the operation is <<ddc>>. The effective address of the memory
access is obtained by adding `rs1` to the sign-extended 12-bit offset.

include::store_tag_perms.adoc[]

include::malformed_no_check.adoc[]

:has_cap_data:
include::store_exceptions.adoc[]

Prerequisites for {cheri_cap_mode_name}::
{cheri_base_ext_name}

Prerequisites for {cheri_int_mode_name}::
{cheri_default_ext_name}

SC Operation::
+
--
TODO
--
