<<<
[#C_FSD,reftext="C.FSD"]
==== C.FSD
See <<C.FSDSP>>.

[#C_FSDSP,reftext="C.FSDSP"]
==== C.FSDSP

Synopsis::
Double precision floating point stores (C.FSD, C.FSDSP), 16-bit encodings

{cheri_cap_mode_name} Mnemonics (RV32)::
`c.fsd fs2, offset(cs1')` +
`c.fsd fs2, offset({abi_creg}sp)`

{cheri_cap_mode_name} Expansions (RV32)::
`fsd fs2, offset(cs1')` +
`fsd fs2, offset({abi_creg}sp)`

{cheri_int_mode_name} Mnemonics::
`c.fsd fs2, offset(rs1')` +
`c.fsd fs2, offset(sp)`

{cheri_int_mode_name} Expansions::
`fsd fs2, offset(rs1)` +
`fsd fs2, offset(sp)`

Encoding::
include::wavedrom/c-sp-store-css-fp-dp.adoc[]
include::wavedrom/c-sp-store-css-fp-dp-sprel.adoc[]

{cheri_cap_mode_name} Description::
Standard floating point stack pointer relative store instructions, authorized by the capability in `cs1` or `{abi_creg}sp`.

{cheri_int_mode_name} Description::
Standard floating point stack pointer relative store instructions, authorized by the capability in <<ddc>>.

NOTE: These instructions are available in RV64 {cheri_int_mode_name} only.
In RV64 {cheri_cap_mode_name} they are remapped to <<C_STORE_CAP>>/<<C_STORE_CAP_SP>>.

NOTE: <<C.FSDSP>> may be remapped by the <<Zcmp>>, <<Zcmt>> standard extensions.
<<C.FSD>> may be remapped by future code-size reduction extensions.
The rule is that in RV64 {cheri_cap_mode_name}
they are *always* remapped to <<C_LOAD_CAP>>/<<C_LOAD_CAP_SP>>.

include::store_exceptions.adoc[]

Prerequisites for {cheri_cap_mode_name} C.FSD, C.FSDSP (RV32 only)::
{cheri_base_ext_name}, C and D; or +
{cheri_base_ext_name}, Zca and Zcd

Prerequisites for {cheri_int_mode_name} C.FSD, C.FSDSP::
{cheri_default_ext_name}, C and D; or +
{cheri_default_ext_name}, Zca and Zcd

Operation (after expansion to 32-bit encodings)::
 See <<FSD>>
