<<<

[#C_SD,reftext="C.SD"]
==== C.SD

See <<C.SW>>.

[#C_SW,reftext="C.SW"]
==== C.SW

Synopsis::
Stores (C.SD, C.SW), 16-bit encodings

{cheri_cap_mode_name} Mnemonics::
`c.sd rs2', offset({creg_pref}s1')` +
`c.sw rs2', offset({creg_pref}s1')`

{cheri_cap_mode_name} Expansions::
`sd rs2', offset({creg_pref}s1')` +
`sw rs2', offset({creg_pref}s1')`

{cheri_int_mode_name} Mnemonics::
`c.sd rs2', offset(rs1')` +
`c.sw rs2', offset(rs1')`

{cheri_int_mode_name} Expansions::
`sd rs2', offset(rs1')` +
`sw rs2', offset(rs1')`

Encoding::
include::wavedrom/c-cs-format-ls.adoc[]

{cheri_cap_mode_name} Description::
Standard store instructions, authorized by the capability in `{creg_pref}s1`.

{cheri_int_mode_name} Description::
Standard store instructions, authorized by the capability in <<ddc>>.

include::store_exceptions.adoc[]

Prerequisites for {cheri_cap_mode_name} C.SD::
RV64 or RV32 with Zclsd, and {c_cheri_base_ext_names}

Prerequisites for {cheri_int_mode_name} C.SD::
RV64 or RV32 with Zclsd, and {c_cheri_default_ext_names}

Prerequisites for {cheri_cap_mode_name} C.SW::
{c_cheri_base_ext_names}

Prerequisites for {cheri_int_mode_name} C.SW::
{c_cheri_default_ext_names}

Operation (after expansion to 32-bit encodings)::
 See <<SD>>, <<SW>>
