<<<

[#STORE_CAP,reftext="{STORE_CAP_NAME}"]
==== {STORE_CAP_NAME}

Synopsis::
{STORE_CAP_DESC}

Mnemonic::
`{store_cap_name} {cs2}, offset({cs1})`

Encoding::
include::wavedrom/storecap.adoc[]

include::load_store_creg0.adoc[]

Description::
Calculate the effective address of the memory access by adding `{cs1}.address` to the sign-extended 12-bit offset.
+
Authorize the memory access with the capability in `{cs1}`.
+
Store the YLEN-bit value in `{cs2}`, together with its {ctag}, to the naturally aligned memory location.
+
include::malformed_no_check.adoc[]
+
Stored {ctag_title} Value::
+
Set the stored {ctag} to zero if:
+
. `{cs2}.tag=0`, or
. `{cs1}` does not grant <<c_perm>>, or
. Platform specified conditions or privileged configurations (e.g., PMAs or PTEs) specify that it must be set to zero.
+
NOTE: Extensions may define further circumstances under which stored capabilities may have their {ctag}s set to zero.
 <<section_zylevels1>> is an example of this.
+
Exceptions::
Raise a store/AMO access fault exception when the effective address is not aligned to YLEN/8.
+
include::store_exceptions.adoc[]

Included in::
<<rvy_insn_table>>

Operation::
[source,SAIL,subs="verbatim,quotes"]
----
SAIL to be updated
----
//sail::execute[clause="StoreCapImm(_, _, _)",part=body,unindent]
