==== Integer Stores ({cheri_base_ext_name})
[#SD,reftext="SD"]
===== SD
[#SW,reftext="SW"]
===== SW
[#SH,reftext="SH"]
===== SH
[#SB,reftext="SB"]
===== SB

Synopsis::
Integer Stores (SD, SW, SH, SB)

{cheri_cap_mode_name} Mnemonics::
`sd rs2, offset({creg_pref}s1)` +
`sw rs2, offset({creg_pref}s1)` +
`sh rs2, offset({creg_pref}s1)` +
`sb rs2, offset({creg_pref}s1)`

Encoding::
include::wavedrom/store.adoc[]

Description::
Store data of the indicated size (byte, halfword, word, double-word) to memory.
The effective address of the store is obtained by adding the sign-extended 12-bit offset to `{creg_pref}s1.address`.
The authorizing capability for the operation is `{creg_pref}s1`.
A copy of `rs2` is written to memory at the location indicated by the effective address and the {ctag} bit of each block of memory naturally aligned to YLEN/8 is cleared.
+
include::load_store_creg0.adoc[]

// {cheri_int_mode_name} Description::
// Store data of the indicated size (byte, halfword, word, double-word) to
// memory. The effective address of the store is obtained by adding the
// sign-extended 12-bit offset to `rs1`. The authorizing capability for the
// operation is <<ddc>>. A copy of `rs2` is written to memory at the location
// indicated by the effective address and the {ctag} bit of each block of memory
// naturally aligned to YLEN/8 is cleared.

include::store_exceptions.adoc[]

Prerequisites for SD::
RV64 or RV32 with Zilsd
