<<<

[#FSD,reftext="FSD"]
==== FSD
See <<FSH>>.

[#FSW,reftext="FSW"]
==== FSW
See <<FSH>>.

[#FSH,reftext="FSH"]
==== FSH

Synopsis::
Floating point stores (FSD, FSW, FSH), 32-bit encodings

{cheri_cap_mode_name} Mnemonics::
`fsd fs2, offset(cs1)` +
`fsw fs2, offset(cs1)` +
`fsh fs2, offset(cs1)`

{cheri_int_mode_name} Mnemonics::
`fsd fs2, offset(rs1)` +
`fsw fs2, offset(rs1)` +
`fsh fs2, offset(rs1)`

Encoding::
include::wavedrom/fpstore.adoc[]

{cheri_cap_mode_name} Description::
Standard floating point store instructions, authorized by the capability in `cs1`.
+
include::load_store_creg0.adoc[]

{cheri_int_mode_name} Description::
Standard floating point store instructions, authorized by the capability in <<ddc>>.

include::store_exceptions.adoc[]

Prerequisites for {cheri_cap_mode_name} FSD::
{cheri_base_ext_name}, and D

Prerequisites for {cheri_int_mode_name} FSD::
{cheri_default_ext_name}, and D

Prerequisites for {cheri_cap_mode_name} FSW::
{cheri_base_ext_name}, and F

Prerequisites for {cheri_int_mode_name} FSW::
{cheri_default_ext_name}, and F

Prerequisites for {cheri_cap_mode_name} FSH::
{cheri_base_ext_name}, and Zfh or Zfhmin

Prerequisites for {cheri_int_mode_name} FSH::
{cheri_default_ext_name}, and Zfh or Zfhmin

Operation::
[source,SAIL,subs="verbatim,quotes"]
--
TBD
--
