<<<

[#C_SWSP,reftext="C.SWSP"]
==== C.SWSP

See <<C_SDSP>>.

[#C_SDSP,reftext="C.SDSP"]
==== C.SDSP

Synopsis::
Stack pointer relative stores (C.SWSP, C.SDSP), 16-bit encodings

{cheri_cap_mode_name} Mnemonics::
`c.sd rs2, offset({abi_creg}sp)` +
`c.sw rs2, offset({abi_creg}sp)`

{cheri_cap_mode_name} Expansions::
`sd rs2, offset({abi_creg}sp)` +
`sw rs2, offset({abi_creg}sp)`

{cheri_int_mode_name} Mnemonics::
`c.sd rs2, offset(sp)` +
`c.sw rs2, offset(sp)`

{cheri_int_mode_name} Expansions::
`sd rs2, offset(sp)` +
`sw rs2, offset(sp)`

Encoding::
include::wavedrom/c-sp-load-store-css.adoc[]

{cheri_cap_mode_name} Description::
Standard stack pointer relative store instructions, authorized by the capability in `{abi_creg}sp`.

{cheri_int_mode_name} Description::
Standard stack pointer relative store instructions, authorized by the capability in <<ddc>>.

include::store_exceptions.adoc[]

Prerequisites for {cheri_cap_mode_name} C.SDSP::
RV64 or RV32 with Zclsd, and {c_cheri_base_ext_names}

Prerequisites for {cheri_int_mode_name} C.SDSP::
RV64 or RV32 with Zclsd, and {c_cheri_default_ext_names}

Prerequisites for {cheri_cap_mode_name} C.SWSP::
{c_cheri_base_ext_names}

Prerequisites for {cheri_int_mode_name} C.SWSP::
{c_cheri_default_ext_names}

Operation (after expansion to 32-bit encodings)::
 See <<SD>>, <<SW>>
