<<<

[#C_STORE_CAP,reftext="{C_STORE_CAP_NAME}"]
==== {C_STORE_CAP_NAME}

see <<C_STORE_CAP_SP>>.

[#C_STORE_CAP_SP,reftext="{C_STORE_CAP_SP_NAME}"]
==== {C_STORE_CAP_SP_NAME}

Synopsis::
Capability stores ({C_STORE_CAP_NAME}, {C_STORE_CAP_SP_NAME}), 16-bit encodings

include::xlen_variable_warning.adoc[]

{cheri_cap_mode_name} Mnemonics::
`{C_STORE_CAP_NAME_LC} cs2', offset(cs1')` +
`{C_STORE_CAP_NAME_LC} cs2', offset(ysp)`

{cheri_cap_mode_name} Expansions::
`{STORE_CAP_NAME_LC} cs2', offset(cs1')` +
`{STORE_CAP_NAME_LC} cs2', offset(ysp)`

Encoding::
include::wavedrom/c-sp-store-cap.adoc[]

{cheri_cap_mode_name} Description::
Store the YLEN-bit value in `cs2'` to memory. The capability in `cs1/ysp`
authorizes the operation. The effective address of the memory access is
obtained by adding the address of `cs1/ysp` to the zero-extended offset.

NOTE: These mnemonics do not exist in {cheri_int_mode_name}.

Tag of the written capability value::

The capability written to memory has the {ctag} set to 0 if the {ctag} of `cs2'` is 0 or if the authorizing capability (`cs1/ysp`) does not grant <<c_perm>>.
+
The stored tag is also set to zero if the authorizing capability does not have <<sl_perm>> set but the stored data has a <<section_cap_level>> of 0 (_local_).

include::malformed_no_check.adoc[]

:has_cap_data:
include::store_exceptions.adoc[]

Prerequisites::
{c_cheri_base_ext_names}

Operation (after expansion to 32-bit encodings)::
 See <<STORE_CAP>>
