
<<<

[#C_STORE_CAP,reftext="{C_STORE_CAP_NAME}"]
==== {C_STORE_CAP_NAME}

see <<C_STORE_CAP_SP>>.

[#C_STORE_CAP_SP,reftext="{C_STORE_CAP_SP_NAME}"]
==== {C_STORE_CAP_SP_NAME}

Synopsis::
Capability stores ({C_STORE_CAP_NAME}, {C_STORE_CAP_SP_NAME}), 16-bit encodings

include::xlen_variable_warning.adoc[]

Mnemonics::
`{c_store_cap_name_lc} {cs2}', offset({cs1}')` +
`{c_store_cap_sp_name_lc} {cs2}', offset({abi_creg}sp)`

Expansions::
`{store_cap_name_lc} {cs2}', offset({cs1}')` +
`{store_cap_name_lc} {cs2}', offset({abi_creg}sp)`

Encoding::
include::wavedrom/c-sp-store-cap.adoc[]

{cheri_cap_mode_name} Description::
Store the YLEN-bit value in `{cs2}'` to memory. The capability in `{abi_creg}sp`
authorizes the operation. The effective address of the memory access is
obtained by adding the address of `{abi_creg}sp` to the zero-extended offset.

{ctag_title} of the written capability value::

The capability written to memory has the {ctag} set to 0 if the {ctag} of `{cs2}'` is 0 or if the authorizing capability (`{abi_creg}sp`) does not grant <<c_perm>>.
+
Extensions may define further circumstances under which stored capabilities may have their valid tags cleared.

include::malformed_no_check.adoc[]

:has_cap_data:
include::store_exceptions.adoc[]

Prerequisites::
{c_cheri_base_ext_names}

Included in::
{rvyc_xref}

Operation (after expansion to 32-bit encodings)::
 See <<STORE_CAP>>
