<<<

[#YSUNSEAL,reftext="{YSUNSEAL}"]
==== {YSUNSEAL}

include::new_encoding_note.adoc[]

Synopsis::
{YSUNSEAL_DESC}

Mnemonic::
`{ysunseal} {cd}, {cs1}, {cs2}`

Encoding::
include::wavedrom/ysunseal.adoc[]

Description::
Copy `{cs2}` to `{cd}`.
+
Set `{cd}.ct=0`.  (That is, unseal `{cd}`.)
+
Set `{cd}.tag=1` if:
+
. `{cs1}.tag=1`, and
. `{cs1}` is not sealed, and
. `{cs2}.tag=1`, and
. `{cs2}` is sealed, and
. `{cs2}` is a <<cap_subset>> of `{cs1}`
+
Otherwise, set `{cd}.tag=0`
+
NOTE: When `{cs1}` is `{creg}0` <<YSUNSEAL>> will copy `{cs2}` to `{cd}` and clear `{cd}.tag` and `{cd}.ct`.
However future extensions may add additional behavior to update currently reserved fields,
and so software should not assume `{cs1}=0` to be a pseudo-instruction for {ctag} and type clearing.

// [NOTE]
// =====
// <<YSUNSEAL>> is similar to <<CBLD>> except that it
//
// * requires `{cs2}` to be both tagged and sealed and
//
// * always sets `{cd}.ct` to `0`.
//
// Emulating <<YSUNSEAL>> with <<CBLD>> requires a branch on the tag of `{cs2}` and
// bit-level understanding of the capability encoding in use to zero `{cs2}.ct`;
// <<YSUNSEAL>> addresses both concerns.
// Extensions may further differentiate between <<YSUNSEAL>> and <<CBLD>>
// as appropriate for their intended uses.
// =====

ifndef::cheri_ratification_v1_only[]

//useful text but really belongs in a programmer's guide

[NOTE]
=====
<<YSUNSEAL>> is intended to enable "superset unsealing"
of opaque handles to software objects.
Specifically, a software component can:

1. allocate the memory for these objects from a region of address space,

2. render capabilities to these objects opaque by sealing with <<YSEAL>>,

3. distribute these handles to other software components, and

4. later use its (unsealed) capability to the backing region
   as the authority (in `{cs1}`) of a <<YSUNSEAL>> instruction
   to recover an unsealed capability to the object backing
   a handle (in `{cs2}`) received from other components.

The result of <<YSUNSEAL>> will have its {ctag} set to zero if the received capability
is not a handle to an object in the recipient's address space.
This makes it easy for recipient software to ensure that received capabilities
actually are handles to the recipient's objects.
=====

[NOTE]
=====
While <<YSUNSEAL>> requires that the capability in its `{cs2}` is sealed,
it imposes no requirements on _which_ non-zero <<sec_cap_type>> value
has been used to seal `{cs2}`.
If the capability encoding defines multiple non-zero <<sec_cap_type>> values
and software wishes to distinguish between them,
it must use <<GCTYPE>> on the sealed capability.
=====
endif::[]
Operation::
// YSUNSEAL is not in the Sail model; it reuses the CBLD logic but additionally
// requires cs2 to be tagged and sealed, and always unseals the result.
[source,SAIL,subs="verbatim,quotes"]
----
let cs1_val = C(cs1);
let cs2_val = C(cs2);

let tag = cs1_val.tag &
          not(capIsSealed(cs1_val)) &
          cs2_val.tag &
          capIsSealed(cs2_val) &
          capIsSubset(cs2_val, cs1_val); /* subset checks for malformed bounds, perms, reserved bits */

C(cd) = { unsealCap(cs2_val) with tag = tag };
RETIRE_SUCCESS
----
