<<<

[#CM_POPRET_CHERI,reftext="CM.POPRET ({cheri_base_ext_name})"]
==== CM.POPRET ({cheri_base_ext_name})

Synopsis::
Destroy stack frame (CM.POPRET): load the return address register and 0 to 12 saved registers from the stack frame, deallocate the stack frame. Return through the return address register. 16-bit encodings.

{cheri_cap_mode_name} Mnemonic (RV32)::
`cm.popret \{creg_list\}, -stack_adj`

{cheri_int_mode_name} Mnemonic::
`cm.popret \{xreg_list\}, -stack_adj`

Encoding::
[wavedrom, , svg]
....
{reg:[
    { bits:  2, name: 0x2,             attr: ['C2'] },
    { bits:  2, name: 'spimm\[5:4\]',  attr: [] },
    { bits:  4, name: 'rlist',         attr: [] },
    { bits:  5, name: 0x1e,            attr: [] },
    { bits:  3, name: 0x5,             attr: ['FUNCT3'] },
],config:{bits:16}}
....

[NOTE]

_rlist_ values 0 to 3 are reserved for a future EABI variant

include::cheri_mode_dependent.adoc[]

{cheri_cap_mode_name} Description::
Load capability registers as specified in _creg_list_ using <<LC>> semantics.
+
Deallocate stack frame.
+
Return by calling <<JALR_CHERI>> to `cra`.
+
All data accesses are authorized by `csp`.
+
The return destination is authorized by `cra`.

//{cheri_int_mode_name} Description::
//Load *x* registers as specified in _xreg_list_. Deallocate stack frame. Return by calling <<JALR_CHERI>> to `ra`. All data accesses are checked against <<ddc>>. The return destination is checked against <<pcc>>.

include::zcm_common.adoc[]

//include::load_exceptions.adoc[]

include::pcrel_debug_warning.adoc[]

Prerequisites::
{c_cheri_base_ext_names}, Zcmp

//Prerequisites for {cheri_int_mode_name}::
//{c_cheri_default_ext_names}, Zcmp

Operation::
[source,SAIL,subs="verbatim,quotes"]
--
TBD
--
