<<<

[#CM_POPRETZ_CHERI,reftext="CM.POPRETZ ({cheri_base32_ext_name})"]
==== CM.POPRETZ ({cheri_base32_ext_name})

Synopsis::
Destroy stack frame (CM.POPRETZ): load the return address register and register 0 to 12 saved registers from the stack frame, deallocate the stack frame. Move zero into argument register zero. Return through the return address register. 16-bit encoding.

Mnemonic::
`cm.popretz \{creg_list\}, -stack_adj`

//{cheri_int_mode_name} Mnemonic::
//`cm.popretz \{xreg_list\}, -stack_adj`

Encoding::
[wavedrom, , svg]
....
{reg:[
    { bits:  2, name: 0x2,             attr: ['C2'] },
    { bits:  2, name: 'spimm\[5:4\]',  attr: [] },
    { bits:  4, name: 'rlist',         attr: [] },
    { bits:  5, name: 0x1c,            attr: [] },
    { bits:  3, name: 0x5,             attr: ['FUNCT3'] },
],config:{bits:16}}
....

[NOTE]

_rlist_ values 0 to 3 are reserved for a future EABI variant

include::cheri_mode_dependent.adoc[]

Description::
Load capability registers as specified in _creg_list_ using <<LOAD_CAP>> semantics.
+
Deallocate stack frame.
+
Move zero into `{abi_creg}a0`.
+
Return by calling <<JALR_CHERI>> to `{abi_creg}ra`.
+
All data accesses are authorized by `{abi_creg}sp`.
+
The return destination is authorized by `{abi_creg}ra`.

include::zcm_common.adoc[]

include::pcrel_debug_warning.adoc[]

Prerequisites::
{c_cheri_base_ext_names}, Zcmp
for {cheri_cap_mode_name}

Operation::
[source,SAIL,subs="verbatim,quotes"]
--
TBD
--
