<<<

[#CM_JT_CHERI,reftext="CM.JT ({cheri_base_ext_name})"]
==== CM.JT ({cheri_base_ext_name})

Synopsis::
Jump via table with link (CM.JT), 16-bit encodings

{cheri_cap_mode_name} Mnemonic::
`cm.jt _index_`

{cheri_int_mode_name} Mnemonic::
`cm.jt _index_`

Encoding::
[wavedrom, , svg]
....
{reg:[
    { bits:  2, name: 0x2,      attr: ['C2'] },
    { bits:  8, name: 'index',  attr: [] },
    { bits:  3, name: 0x0,      attr: [] },
    { bits:  3, name: 0x5,      attr: ['FUNCT3'] },
],config:{bits:16}}
....

[NOTE]

  For this encoding to decode as <<CM_JT_CHERI>>, _index<32_, otherwise it decodes as <<CM_JALT_CHERI>>.

include::cheri_mode_dependent.adoc[]

{cheri_cap_mode_name} Description::
Redirect instruction fetch via the jump table defined by the indexing via `jvtc.address+ index*XLEN/8`, checking every byte of the jump table access against <<jvtc>> bounds (not against <<pcc>>) and requiring <<x_perm>>.

{cheri_int_mode_name} Description::
Redirect instruction fetch via the jump table defined by the indexing via `jvtc.address+ index*XLEN/8`, checking every byte of the jump table access against <<pcc>> bounds and requiring <<x_perm>>.

include::zcm_common.adoc[]

{cheri_cap_mode_name} Permissions::
Requires <<jvtc>> to be tagged, not sealed, have <<x_perm>> and for the full XLEN-wide access to be in <<jvtc>> bounds.

{cheri_cap_mode_name} Exceptions::
_CHERI instruction fetch fault_ (see <<sec_cheri_exception_handling,_CHERI Exception handling_ in the privileged specification>> for further details) can be triggered with one the following errors:
+
[width="50%",options=header,cols="2,^1",align=center]
|==============================================================================
| Kind                  |
| Tag violation         |  ✔
| Seal violation        |  ✔
| Permission violation  |  ✔
ifdef::invalid_address_viol[]
| Invalid address violation  |  ✔
endif::[]
| Bounds violation      |  ✔
|==============================================================================

include::pcrel_debug_warning.adoc[]

Prerequisites for {cheri_cap_mode_name}::
{c_cheri_base_ext_names}, Zcmt

Prerequisites for {cheri_int_mode_name}::
{c_cheri_default_ext_names}, Zcmt

Operation::
[source,SAIL,subs="verbatim,quotes"]
--
TBD
--
