<<<

[#CM_JT_CHERI,reftext="CM.JT ({cheri_base32_ext_name})"]
==== CM.JT ({cheri_base32_ext_name})

Synopsis::
Jump via table with link (CM.JT), 16-bit encodings

Mnemonic (RV32)::
`cm.jt _index_`

Encoding::
[wavedrom, , svg]
....
{reg:[
    { bits:  2, name: 0x2,      attr: ['C2'] },
    { bits:  8, name: 'index',  attr: [] },
    { bits:  3, name: 0x0,      attr: [] },
    { bits:  3, name: 0x5,      attr: ['FUNCT3'] },
],config:{bits:16}}
....

[NOTE]

  For this encoding to decode as <<CM_JT_CHERI>>, _index<32_, otherwise it decodes as <<CM_JALT_CHERI>>.

include::cheri_mode_dependent.adoc[]

Description ({cheri_base32_ext_name})::
Redirect instruction fetch via the jump table defined by the indexing via `jvtc.address+ index*XLEN/8`, checking every byte of the jump table access against <<jvtc>> bounds (not against <<pcc>>) and requiring <<x_perm>>.
+
The target <<pcc>> is calculated by replacing the current <<pcc>> address with the value read from the jump table, and is updated using <<SCADDR>> semantics.
+
If the <<jvtc>> check fails, then clear the tag of the target <<pcc>>.

include::zcm_common.adoc[]

Permissions ({cheri_base32_ext_name})::
Requires <<jvtc>> to have its {ctag} set, not be sealed, have <<x_perm>> and for the full XLEN-wide table access to be in <<jvtc>> bounds.

include::pcrel_debug_warning.adoc[]

Prerequisites for ({cheri_base32_ext_name})::
{c_cheri_base_ext_names}, Zcmt

Operation::
[source,SAIL,subs="verbatim,quotes"]
--
TBD
--
