[#section_sv_cheri]
== "Zcheripte" Extension for CHERI Page-Based Virtual-Memory Systems

CHERI is a security mechanism that is generally orthogonal to page-based
virtual-memory management as defined in cite:[riscv-priv-spec].
However, it is helpful in CHERI harts to extend RISC-V's virtual-memory
management to facilitate capability revocation and control the flow of
capabilities in memory at the page granularity. For this reason, the
{cheri_pte_ext_name} extension adds new bits to RISC-V's Page Table Entry (PTE)
format.

=== Limiting Capability Propagation

TODO

=== Capability Revocation

TODO

[#section_extending_pte]
=== Extending the Page Table Entry Format

ifdef::cheri_v9_annotations[]
NOTE: *CHERI v9 Note:* The current proposal is provisional and only includes
support for load-side revocation when compared to CHERI v9.
endif::[]

The page table entry format remains unchanged for Sv32. However, three new
bits, Capability Access (CA), Capability Dirty (CD) and Capability Read
Generation (CRG), are added to leaf PTEs in Sv39, Sv48 and Sv57 as shown in
xref:sv39pte[xrefstyle=short], xref:sv48pte[xrefstyle=short] and
xref:sv57pte[xrefstyle=short] respectively.

.Sv39 page table entry
[#sv39pte]
include::img/sv39pte.edn[]

.Sv48 page table entry
[#sv48pte]
include::img/sv48pte.edn[]

.Sv57 page table entry
[#sv57pte]
include::img/sv57pte.edn[]

The CA bit indicates whether reading or writing capabilities with tag set to
the virtual page is permitted. Capabilities are read and written as usual when
the CA bit is set. If the CA bit is clear then:

* When a capability store or AMO instruction is executed, the implementation
clears the tag bit of the capability written to the virtual page.
* When a capability load or AMO instruction is executed, the implementation
clears the tag bit of the capability read from the virtual page.

NOTE: The implementation of the CA bit does not force a dependency on the tag
bit's value of the capability read or written.

The CD bit indicates that a capability with tag set has been written to the
virtual page since the last time the CD bit was cleared. Two schemes
to manage the CD bit are permitted:

* A store page fault exception is raised when a capability store or AMO
instruction is executed, the authorizing capability grants <<w_perm>> and
<<c_perm>>, the tag bit of the capability being written is set and the address
written corresponds to a virtual page with the CD bit clear.
* When a capability store or AMO instruction is executed, the authorizing
capability grants <<w_perm>> and <<c_perm>>, the tag bit of the capability being written is set and
the store address corresponds to a virtual page with the CD bit clear, the
implementation sets the corresponding bit in the PTE. The PTE update must be
atomic with respect to other accesses to the PTE, and must atomically check
that the PTE is valid and grants sufficient permissions. Updates to the CD bit
must be exact (i.e. not speculative), and observed in program order by the
local hart. Furthermore, the PTE update must appear in the global memory order
no later than the explicit memory access, or any subsequent explicit memory
access to that virtual page by the local hart.  The ordering on loads and
stores provided by FENCE instructions and the acquire/release bits on atomic
instructions also orders the PTE updates associated with those loads and
stores as observed by remote harts.
+
The PTE update is not required to be atomic with respect to the explicit memory
access that caused the update, and the sequence is interruptible. However, the
hart must not perform explicit memory access before the PTE update is globally
visible.

NOTE: The behavior of the CA bit takes priority over the CD bit. Therefore,
implementations must not take action to change or raise an exception related to
the CD when CA is clear.

The CRG bit indicates the current generation of the virtual memory page with
regards to the ongoing capability revocation cycle. A load page fault
exception is raised when a capability load or AMO instruction is executed,
the capability read from memory has tag set and the virtual page's CRG bit does
not equal senvcfg.CRG.

[#senvcfg_pte,reftext="senvcfg PTE bits"]
=== Extending the Supervisor Environment Configuration Register (menvcfg)

The *senvcfg* register operates as described in cite:[riscv-priv-spec].
{cheri_pte_ext_name} adds a new Capability Read Generation (CRG) bit as shown
in xref:senvcfgreg_pte[xrefstyle=short] when XLEN=64. The CRG bit in *senvcfg*
is used as described in xref:section_extending_pte[xrefstyle=short].

.Supervisor environment configuration register (*senvcfg*)
[#senvcfgreg_pte]
include::img/senvcfgreg-pte.edn[]
