[#section_sv_cheri]
== "Zcheripte" Extension for CHERI Page-Based Virtual-Memory Systems

CHERI is a security mechanism that is generally orthogonal to page-based
virtual-memory management as defined in cite:[riscv-priv-spec].
However, it is helpful in CHERI harts to extend RISC-V's virtual-memory
management to control the flow of capabilities in memory at the page
granularity. For this reason, the {cheri_pte_ext_name} extension adds new bits
to RISC-V's Page Table Entry (PTE) format.

=== Extending the Page Table Entry Format

ifdef::cheri_v9_annotations[]
NOTE: *CHERI v9 Note:* The current proposal is provisional and is missing
PTE bits when compared to CHERI v9.
endif::[]

The page table entry format remains unchanged for Sv32. However, two new bits,
Capability Write (CW) and Capability Dirty (CD), are added to leaf PTEs in
Sv39, Sv48 and Sv57 as shown in xref:sv39pte[xrefstyle=short],
xref:sv48pte[xrefstyle=short] and xref:sv57pte[xrefstyle=short] respectively.

.Sv39 page table entry
[#sv39pte]
include::img/sv39pte.edn[]

.Sv48 page table entry
[#sv48pte]
include::img/sv48pte.edn[]

.Sv57 page table entry
[#sv57pte]
include::img/sv57pte.edn[]

The CW bit indicates whether writing capabilities with tag set to the virtual
page is permitted. Two schemes to manage the CW bit are permitted:

* A store page fault exception is raised when a capability store or AMO
instruction is executed, the authorizing capability grants <<w_perm>> and
<<c_perm>>, and the store address corresponds to a virtual page with the CW bit
clear.
* When a capability store or AMO instruction is executed, the implementation
clears the tag bit of the capability written to a virtual page with the CW bit
clear.

NOTE: The implementation of the CW bit does not force a dependency on the tag
bit's value of the capability written, so implementations must support the CW
bit.

The CD bit indicates that a capability with tag set has been written to the
virtual page since the last time the CD bit was cleared. Implementations are
strongly encouraged, but not required, to support CD. If supported, two schemes
to manage the CD bit are permitted:

* A store page fault exception is raised when a capability store or AMO
instruction is executed, the authorizing capability grants <<w_perm>> and
<<c_perm>>, the tag bit of the capability being written is set and the address
written corresponds to a virtual page with the CD bit clear.
* When a capability store or AMO instruction is executed, the authorizing
capability grants <<w_perm>> and <<c_perm>>, the tag bit of the capability being written is set and
the store address corresponds to a virtual page with the CD bit clear, the
implementation sets the corresponding bit in the PTE. The PTE update must be
atomic with respect to other accesses to the PTE, and must atomically check
that the PTE is valid and grants sufficient permissions. Updates to the CD bit
must be exact (i.e. not speculative), and observed in program order by the
local hart. Furthermore, the PTE update must appear in the global memory order
no later than the explicit memory access, or any subsequent explicit memory
access to that virtual page by the local hart.  The ordering on loads and
stores provided by FENCE instructions and the acquire/release bits on atomic
instructions also orders the PTE updates associated with those loads and
stores as observed by remote harts.
+
The PTE update is not required to be atomic with respect to the explicit memory
access that caused the update, and the sequence is interruptible. However, the
hart must not perform explicit memory access before the PTE update is globally
visible.

NOTE: The behavior of the CW bit takes priority over the CD bit. Therefore,
implementations must not take action to change or raise an exception related to
the CD bit when the CW bit is clear.

[#menvcfg_pte,reftext="menvcfg PTE bits"]
=== Extending the Machine Environment Configuration Register (menvcfg)

The *menvcfg* register is extended to allow discovering whether the
implementation supports the CD bit.

The *menvcfg* register operates as described in cite:[riscv-priv-spec]. {cheri_base_ext_name} adds a new enable bit as shown in
xref:menvcfgreg[xrefstyle=short] when XLEN=64.

.Machine environment configuration register (*menvcfg*)
[#menvcfgreg]
include::img/menvcfgreg.edn[]

The Capability Dirty Enable (CDE) bit controls whether the Capability Dirty
(CD) bit is available for use in S-mode address translation. When CDE=1, the CD
bit is available for S-mode address translation. When CDE=0, the implementation
behaves as though the CD bit were not implemented. If CD is not implemented,
CDE is read-only zero. If CD is implemented although not configurable, CDE is
read-only one.
