== "Zcheri_tid" Extension for CHERI Thread Identification

{cheri_tid_ext_name} is an optional extension to {cheri_base_ext_name}.
Implementations that support {cheri_base_ext_name} and {cheri_legacy_ext_name}
define a variant of the CHERI ISA that allows for software compartmentalisation
of CHERI programs.

=== Unprivileged CSRs

==== User Thread Identifier Capability (utidc)

The <<utidc>> register is an CLEN-wide read-only register. It is a read-only
copy of the <<stidc>> register. On reset the tag will be set to 0 and the
remainder of the data is UNSPECIFIED.

[#CHERI_COMP,reftext="CHERI Compartmentalization]
=== CHERI Compartmentalization

This section describes how this specification enables support for compartmentalization for CHERI systems.
Compartmentalization seeks to separate the privileges between different protection units, e.g., two or more libraries.
Code can be separated by sentries, which allow for giving out code capabilities to untrusted code where the untrusted code can only call code capability, but not modify it.
Sentries can be called from different threads and thus there needs to be a way of identifying the current thread.
While identifying the current thread can be done by privileged code, e.g., the kernel, the implied performance overhead of this is not bearable for CHERI systems with many compartments.

The RISC-V ABI includes a _thread pointer (tp)_ register, which is not usable for the purpose of reliably identifying the current thread because the tp register is a general purpose register and can be changed arbitrarily by untrusted code.
Therefore, this specification offers two additional CSRs that facilitate a trusted source for the thread ID.
The supervisor thread identifier (STID) register is readable and writeable with <<asr_perm>> from the supervisor mode allowing to change the thread ID on a context switch.
The user thread identifier (UTID) exposes the current value of STID as a read-only copy.