[#section_sv_cheri]
[#cheri_pte_ext]
== Extending Page-Based Virtual-Memory Systems for CHERI (RV64 only), including "{cheri_pte_ext_name}"

NOTE: _Sv32_ (for RV32) does not have any spare PTE bits, and so no features from this chapter can be implemented.

In CHERI harts the Page Table Entry (PTE) format is extended to control the flow of capabilities in memory (see <<limit_cap_prop>>).
This is achieved by adding the PTE.CW bit described below and is a mandatory feature when any virtual memory translation scheme (_Sv39_, _Sv48_ or _Sv57_) is implemented on an RV64 system.
By default PTE.CW=0 which will prevent legacy OSs from being able to load or store tagged capabilities without software modification.

Additionally the {cheri_pte_ext_name} extension adds the ability to perform capability revocation of user mode pages (see <<cap_revocation>>) by adding the PTE.CRG bit, and <<sstatusreg_pte,sstatus>>.UCRG as described below.

NOTE: {cheri_pte_ext_name} is strongly recommended but not mandatory as a future version of this specification may specify an improved method.

NOTE: There is no explicit mechanism for enabling or disabling {cheri_pte_ext_name}. Its presence can be tested for by probing the existence of <<sstatusreg_pte,sstatus>>.UCRG.

NOTE: A future version of this specification may include kernel revocation which may require an <<sstatusreg_pte,sstatus>>.SCRG bit.

The remainder of this chapter jointly specifies the behavior of PTE.CW, PTE.CRG and <<sstatusreg_pte,sstatus>>.UCRG.

NOTE: The description below assumes that {cheri_pte_ext_name} has been implemented.
 If that is _not_ the case then PTE.CRG and <<sstatusreg_pte,sstatus>>.UCRG should be taken as read-only-zero for purpose of the description in the remainder of this chapter only.
 PTE.CRG and <<sstatusreg_pte,sstatus>>.UCRG remain reserved in this case.

The minimum level of PTE support is to set CW to 1 in all PTEs intended for storing capabilities (i.e. anonymous mappings) and leave <<sstatusreg_pte,sstatus>>.UCRG and CRG in all PTEs set to 0, which will allow capabilities with their tags set to be loaded and stored successfully.


[#limit_cap_prop]
=== Limiting Capability Propagation

Page table enforcement can allow the operating system to limit the flow
of capabilities between processes.
It is highly desirable that a process should only possess capabilities that have
been issued for that address space by the operating system.
Unix processes may share memory for efficient communication,
but capability pointers must not be shared across these channels
into a foreign address space.
An operating system might defend against this by only issuing a capability
to the shared
region that does not grant the load/store capability permission.
However, there are circumstances where portions of general-purpose, mmapped^*^ memory become shared,
and the operating system must prevent future capability communication
through those pages.
This is not possible without restructuring software, as the capability for
the original allocation, which spans both shared memory and private memory, would need to
be deleted and replaced with a list of distinct capabilities with appropriate
permissions for each range.
Such a change would not be transparent to the program.
Such sharing through virtual memory is on the page granularity, so preventing
capability writes with a PTE permission is
a natural solution.

^*^ _allocated using mmap_

[#cap_revocation]
=== Capability Revocation

Page table enforcement can accelerate concurrent capability revocation
for temporal safety.
Without page table capability protection, a concurrent capability revocation
sweep must begin by visiting all PTEs to mark them unreadable, henceforth trapping on any
read to a new page to sweep it clean before proceeding.
With a page-granularity generational capability read permission, we can
eliminate the initial permission change of all PTEs.
In addition, a page-granularity capability write control can eliminate many pages
from the sweep that are known to not contain capabilities.


[#section_extending_pte]
=== Extending the Page Table Entry Format

ifdef::cheri_v9_annotations[]
NOTE: *CHERI v9 Note:* The current proposal is provisional and only includes
support for load-side revocation when compared to CHERI v9.
endif::[]

The page table entry format remains unchanged for Sv32. However, two new
bits, Capability Write (CW) and Capability Read
Generation (CRG), are added to leaf PTEs in Sv39, Sv48 and Sv57 as shown in
xref:sv39pte[xrefstyle=short], xref:sv48pte[xrefstyle=short] and
xref:sv57pte[xrefstyle=short] respectively. For non-leaf PTEs these bits
remain reserved and must be cleared by software for forward compatibility,
or else a page-fault exception is raised.

.Sv39 page table entry
[#sv39pte]
include::img/sv39pte.edn[]

.Sv48 page table entry
[#sv48pte]
include::img/sv48pte.edn[]

.Sv57 page table entry
[#sv57pte]
include::img/sv57pte.edn[]

NOTE: The behavior in this section isn't relevant if:

. The authorizing capability doesn't have <<c_perm>>, for loads, stores and AMOs.
. {cheri_levels_ext_name} has cleared the stored tag, for stores and AMOs.

The CW bit indicates whether reading or writing capabilities with the tag set to
the virtual page is permitted. When the CW bit is set, capabilities are written
as usual, and capability reads are controlled by the CRG bit.

If the CW bit is clear then:

* When a capability load or AMO instruction is executed, the implementation
 clears the tag bit of the capability read from the virtual page.
* When CRG is clear, the "no capability state", a store/AMO page fault exception
 is raised when a capability store or AMO instruction is executed and the tag bit
 of the capability being written is set.
* When CRG is set, the "pre-CW state", two schemes are permitted (also see <<section_hardware_pte_updates>>):

NOTE: The tag bit of the stored capability is checked _after_ it is potentially
cleared <<tags_cleared_by_permissions,due to lack of permissions>>.

** The same behavior as when CRG is clear, allowing software interpretation
of this state.
** When a capability store or AMO instruction is executed
and the tag bit of the capability being written is set, the
implementation sets the CW bit and assigns the CRG bit equal to <<sstatusreg_pte,sstatus>>.UCRG.
+
The PTE update must be
atomic with respect to other accesses to the PTE, and must atomically check
that the PTE is valid and grants sufficient permissions. Updates to the CW bit
and CRG bit
must be exact (i.e. not speculative), and observed in program order by the
local hart. Furthermore, the PTE update must appear in the global memory order
no later than the explicit memory access, or any subsequent explicit memory
access to that virtual page by the local hart.  The ordering on loads and
stores provided by FENCE instructions and the acquire/release bits on atomic
instructions also orders the PTE updates associated with those loads and
stores as observed by remote harts.
+
The PTE update is not required to be atomic with respect to the explicit memory
access that caused the update, and the sequence is interruptible. However, the
hart must not perform explicit memory access before the PTE update is globally
visible.

When CW is set, the CRG bit indicates the current generation of the virtual memory page with
regards to the ongoing capability revocation cycle. Two schemes are permitted:

* A load page fault exception is raised when a capability load or AMO instruction is executed
with <<c_perm>> granted and the virtual page's CRG bit does not equal <<sstatusreg_pte,sstatus>>.UCRG in user mode.
* A load page fault exception is raised when a capability load or AMO instruction is executed
with <<c_perm>> granted and the virtual page's CRG bit does not equal <<sstatusreg_pte,sstatus>>.UCRG in user mode.
and the capability read from memory optionally has its tag set^1^.

[[pte_cw_crg_load_summary]]
.Summary of Load CW and CRG behavior in the PTEs
[%autowidth,float="center",align="center",cols="<,<,<,<",options="header"]
|===
|PTE.CW |Mode^1^ |PTE.CRG                              |Load/AMO
| 0     | S/U | X                                      | Clear loaded tag
| 1     | U   |&#8800; <<sstatusreg_pte,sstatus>>.UCRG | Page fault, or page fault if tag is set^1^
| 1     | U   |=       <<sstatusreg_pte,sstatus>>.UCRG | Normal operation
| 1     | S   | X                                      | Normal operation^2^
|===

^1^ This is the current privilege mode, not the effective mode of the access and so is not affected by <<sstatusreg_pte,sstatus>>.SUM.

^2^ A future version of this specification may check an SCRG bit in <<sstatusreg_pte,sstatus>> for kernel revocation.

[[pte_cw_crg_store_summary]]
.Summary of Store CW and CRG behavior in the PTEs
[%autowidth,float="center",align="center",cols="<,<,<",options="header"]
|===
|PTE.CW |PTE.CRG |Store/AMO
| 0     | 0      | Page fault if stored tag is set
| 0     | 1      | Page fault if stored tag is set, or hardware CW and CRG update^2^
| 1     | X      | Normal operation
|===

^1^ The choice here is whether to take data dependent exceptions on loads or atomic operations.
 It is legal for the implementation to fault even if the tag is not set since this behavior is only an optimization for software.
 This means it is also legal to only check the tag under certain conditions and conservatively fault otherwise.
 Taking a trap when the tag is not set will introduce additional traps during revocation sweeps.
 Checking the loaded tag affects the exception priority, see <<exception-priority>>.

^2^ See <<section_hardware_pte_updates>>.

The exceptions added by {cheri_pte_ext_name} reuse the load page fault and store/AMO page fault exception cause values,
and so the cause of the exception can be determined by software by checking the value in <<mtval2>>,
<<stval2>> etc.

The behavior when multiple page fault types are detected at once is shown in <<mtval2-page-fault>>.

[#section_hardware_pte_updates]
=== Enabling Software or Hardware PTE updates

The decision about whether to take exceptions on capability stores with the tag set to a page with PTE.CW=0 and PTE.CRG=1 is determined by whether the _Svade_ and _Svadu_ extensions are enabled.
These cause PTE Accessed and Dirty updates to be done in software, via the exception handler, or by a hardware mechanism respectively.

* If only _Svade_ is implemented, or enabled through henvcfg.ADUE or menvcfg.ADUE, then take a page fault.
* If only _Svadu_ is implemented, or enabled through henvcfg.ADUE or menvcfg.ADUE, then do the hardware update of setting PTE.CW=1 and setting PTE.CRG=<<sstatusreg_pte,sstatus>>.UCRG as described in <<section_extending_pte>>.

[#xstatus_pte]
=== Extending the Supervisor (sstatus) and Virtual Supervisor (vsstatus) Status Registers

The <<sstatusreg_pte,sstatus>> and <<vsstatusreg_pte,vsstatus>> CSRs are extended to include the new Capability Read Generation (CRG) bit as shown.

When V=1 <<vsstatusreg_pte,vsstatus>>.UCRG is in effect.

<<mstatusreg_pte,mstatus>>.UCRG also exists. Reading or writing it is equivalent to reading or writing <<sstatusreg_pte,sstatus>>.UCRG.

NOTE: There is no current software use for <<mstatusreg_pte,mstatus>>.UCRG.
It is _only_ included not to break the rule that <<sstatusreg_pte,sstatus>> is required to be a subset of <<mstatusreg_pte,mstatus>>.


[#mstatusreg_pte]
.Virtual Supervisor-mode status (*mstatus*) register when MXLEN=64
[wavedrom, ,svg]
....
{reg: [
  {bits:  1, name: 'WPRI'},
  {bits:  1, name: 'SIE'},
  {bits:  1, name: 'WPRI'},
  {bits:  1, name: 'MIE'},
  {bits:  1, name: 'WPRI'},
  {bits:  1, name: 'SPIE'},
  {bits:  1, name: 'UBE'},
  {bits:  1, name: 'MPIE'},
  {bits:  1, name: 'SPP'},
  {bits:  2, name: 'VS[1:0]'},
  {bits:  2, name: 'MPP[1:0]'},
  {bits:  2, name: 'FS[1:0]'},
  {bits:  2, name: 'XS[1:0]'},
  {bits:  1, name: 'MPRV'},
  {bits:  1, name: 'SUM'},
  {bits:  1, name: 'MXR'},
  {bits:  1, name: 'TVM'},
  {bits:  1, name: 'TW'},
  {bits:  1, name: 'TSR'},
  {bits:  1, name: 'SPELP'},
  {bits:  1, name: 'SDT'},
  {bits:  7, name: 'WPRI'},
  {bits:  2, name: 'UXL[1:0]'},
  {bits:  2, name: 'SXL[1:0]'},
  {bits:  1, name: 'SBE'},
  {bits:  1, name: 'MBE'},
  {bits:  1, name: 'GVA'},
  {bits:  1, name: 'MPV'},
  {bits:  1, name: 'WPRI'},
  {bits:  1, name: 'MPELP'},
  {bits:  1, name: 'MDT'},
  {bits: 18, name: 'WPRI'},
  {bits:  1, name: 'UCRG'},
  {bits:  1, name: 'WPRI'},
  {bits:  1, name: 'SD'},
], config:{lanes: 4, hspace:1024}}
....

[#sstatusreg_pte]
.Supervisor-mode status (*sstatus*) register when SXLEN=64
[wavedrom, ,svg]
....
{reg: [
  {bits:  1, name: 'WPRI'},
  {bits:  1, name: 'SIE'},
  {bits:  3, name: 'WPRI'},
  {bits:  1, name: 'SPIE'},
  {bits:  1, name: 'UBE'},
  {bits:  1, name: 'WPRI'},
  {bits:  1, name: 'SPP'},
  {bits:  2, name: 'VS[1:0]'},
  {bits:  2, name: 'WPRI'},
  {bits:  2, name: 'FS[1:0]'},
  {bits:  2, name: 'XS[1:0]'},
  {bits:  1, name: 'WPRI'},
  {bits:  1, name: 'SUM'},
  {bits:  1, name: 'MXR'},
  {bits:  3, name: 'WPRI'},
  {bits:  1, name: 'SPELP'},
  {bits:  1, name: 'SDT'},
  {bits:  7, name: 'WPRI'},
  {bits:  2, name: 'UXL[1:0]'},
  {bits: 27, name: 'WPRI'},
  {bits:  1, name: 'UCRG'},
  {bits:  1, name: 'WPRI'},
  {bits:  1, name: 'SD'},
], config:{lanes: 4, hspace:1024}}
....

[#vsstatusreg_pte]
.Virtual Supervisor-mode status (*vsstatus*) register when VSXLEN=64
[wavedrom, ,svg]
....
{reg: [
  {bits:  1, name: 'WPRI'},
  {bits:  1, name: 'SIE'},
  {bits:  3, name: 'WPRI'},
  {bits:  1, name: 'SPIE'},
  {bits:  1, name: 'UBE'},
  {bits:  1, name: 'WPRI'},
  {bits:  1, name: 'SPP'},
  {bits:  2, name: 'VS[1:0]'},
  {bits:  2, name: 'WPRI'},
  {bits:  2, name: 'FS[1:0]'},
  {bits:  2, name: 'XS[1:0]'},
  {bits:  1, name: 'WPRI'},
  {bits:  1, name: 'MXR'},
  {bits:  1, name: 'SUM'},
  {bits: 12, name: 'WPRI'},
  {bits:  2, name: 'UXL[1:0]'},
  {bits: 27, name: 'WPRI'},
  {bits:  1, name: 'UCRG'},
  {bits:  1, name: 'WPRI'},
  {bits:  1, name: 'SD'}
], config:{lanes: 4, hspace:1024}}
....
