[#section_debug_integration]
=== Integrating Zcheri_purecap with Sdext

This section describes changes to integrate the Sdext ISA and
{cheri_base_ext_name}. It must be implemented to make external debug compatible
with {cheri_base_ext_name}. Modifications to Sdext are kept to a minimum.

WARNING: This section is preliminary as no-one has yet built debug support
 for CHERI-RISC-V so change is likely.

==== Debug Mode

When executing code due to an abstract command, the hart stays in debug mode
and the rules outlined in Section 4.1 of cite:[riscv-debug-spec]
apply.

==== Core Debug Registers

{cheri_base_ext_name} removes debug CSRs that are designated to hold addresses
and replaces them with analogous CSRs able to hold capabilities. The removed
debug CSRs are listed in xref:dcsrnames-removed[xrefstyle=short] and the
new CSRs are listed in xref:dcsrnames-replaced[xrefstyle=short].

The <<pcc>> must grant <<asr_perm>> to access debug CSRs. This permission is
automatically provided when the hart enters debug mode as described
in the <<dpcc>> section. The <<pcc>> metadata can only be changed if the
implementation supports executing control transfer instructions from the
program buffer -- this is an optional feature according to
cite:[riscv-debug-spec].

[#dpc,reftext="dpc"]
==== Debug Program Counter (dpc)

The <<dpc>> register is as defined in cite:[riscv-debug-spec]. It is a
DXLEN-bit register used as the PC saved when entering debug mode. <<dpc>> is
extended into <<dpcc>>.

.Debug program counter
include::img/dpcreg.edn[]

[#dpcc,reftext="dpcc"]
==== Debug Program Counter Capability (dpcc)

The <<dpcc>> register is an extension to <<dpc>> that is able to hold a
capability.

{TAG_RESET_CSR}

.Debug program counter capability
include::img/dpccreg.edn[]

Upon entry to debug mode, cite:[riscv-debug-spec], does not specify how to
update the PC, and says PC relative instructions may be illegal. This concept
is extended to include any instruction which reads or updates <<pcc>>, which refers to
all jumps, conditional branches and <<AUIPC>>. The exception is <<MODESW>>
which _is_ supported if {cheri_mode_ext_name} is implemented, see <<dinfc>>
for details.

As a result, the value of <<pcc>> is UNSPECIFIED in debug mode according
to this specification. The <<pcc>> metadata has no architectural effect in debug
mode. Therefore <<asr_perm>> is implicitly granted for access to all CSRs and
no PCC faults are possible.

<<dpcc>> (and consequently <<dpc>>) are updated with the
capability in <<pcc>> whose address field is set to the address of the next
instruction to be executed as described in cite:[riscv-debug-spec] upon
debug mode entry.

When leaving debug mode, the capability in <<dpcc>> is unsealed and written
into <<pcc>>.  A debugger may write <<dpcc>> to change where the hart resumes
and its mode, permissions, sealing or bounds.

[#dscratch0,reftext="dscratch0"]
==== Debug Scratch Register 0 (dscratch0)

The <<dscratch0>> register is as defined in cite:[riscv-debug-spec]. It is an
optional DXLEN-bit scratch register that can be used by implementations which
need it. <<dscratch0>> is extended into <<dscratch0c>>.

{TAG_RESET_CSR}

.Debug scratch 0 register
include::img/dscratch0reg.edn[]

[#dscratch0c,reftext="dscratch0c"]
==== Debug Scratch Register 0 (dscratch0c)

The <<dscratch0c>> register is a CLEN-bit plus tag bit extension to
<<dscratch0>> that is able to hold a capability. Its reset value is the
<<null-cap>> capability.

.Debug scratch 0 capability register
include::img/dscratch0creg.edn[]

[#dscratch1,reftext="dscratch1"]
==== Debug Scratch Register 1 (dscratch1)

The <<dscratch1>> register is as defined in cite:[riscv-debug-spec]. It is an
optional DXLEN-bit scratch register that can be used by implementations which
need it. <<dscratch1>> is extended into <<dscratch1c>>.

{TAG_RESET_CSR}

.Debug scratch 0 register
include::img/dscratch1reg.edn[]

[#dscratch1c,reftext="dscratch1c"]
==== Debug Scratch Register 1 (dscratch1c)

The <<dscratch1c>> register is a CLEN-bit plus tag bit extension to
<<dscratch1>> that is able to hold a capability. Its reset value is the
<<null-cap>> capability.

.Debug scratch 1 capability register
include::img/dscratch1creg.edn[]

[#dinfc,reftext="dinfc"]
==== Debug Infinite Capability Register (dinfc)

The <<dinfc>> register is a CLEN-bit plus tag bit CSR only accessible in debug mode.

The reset value is the <<infinite-cap>> capability.

If {cheri_mode_ext_name} (see xref:chapter-Zcheri-mode) is implemented:

. the core enters Capability Mode when entering debug mode
.. therefore <<dinfc>>.M is set whenever entering debug mode for any reason.
. the mode can be optionally switched using <<MODESW>>, and the result observed in <<dinfc>>.M.

<<dinfc>> is read/write but with no writeable fields, and so writes are
ignored.

NOTE: A future version of this specification may add writeable fields to allow creation
 of other capabilities, if, for example, a future extension requires multiple formats for
 the <<infinite-cap>> capability.

.Debug infinite capability register
include::img/dinfcreg.edn[]

==== Hardware Implementations

In an abstract command based implementation, <<dpcc>> will typically be an
alias for <<pcc>> accessible while the hart is halted. If
{cheri_legacy_ext_name} is implemented, <<dddc>> must be a separate register
from <<ddc>> since both are writable. <<ddc>> is copied into <<dddc>> when the
hart halts and is restored from <<dddc>> when the hart resumes. The abstract
commands used to access GPRs are not extended to handle capability metadata;
reads return the address portion only, while writes set the metadata and tag to
zero.

In an execution based implementation, entry to debug mode is typically treated
as a trap. <<dpcc>> and, if present, <<dddc>> are written from <<pcc>> and
<<ddc>> on debug mode entry, and restored to <<pcc>> and <<ddc>> when an
implementation-defined `DRET` instruction is executed to exit debug mode.
Since `x0` is not tagged, it cannot be used to access the debug module. A debug
ROM must use <<pcc>> to access debug module fields.

NOTE: These are illustrative only. The implementation requirements concern only
behavior observable through the Debug Module and execution of documented
instructions. The existence, encoding, and behavior of `DRET` may be chosen
freely to achieve the correct behavior of setting `dmcontrol.resumereq`.
