[#cheri_levels_ext]
== "{cheri_levels_ext_name}" Extension for Capability Levels

{cheri_levels_ext_name} is an extension to {cheri_base_ext_name} that adds support for associating a level with capabilities and limiting the flow of capabilities to specific memory region subsets.
This extension allows assigning a level to capabilities, which in conjunction with two new permissions allows enforcing invariants on capability propagation.
For example, this can be used to ensure that a callee can only write a copy of the passed-in argument capability to specific locations in memory (e.g. the callee's stack frame but not the heap).
It can also be used to avoid sharing of compartment-local data (such as pointers to a stack object) between compartments.

NOTE: This specification only defines the architectural mechanics of this feature, for further information on how this can be used by software please refer to cite:[cheri-v9-spec].

The number of supported capability levels is implementation-defined, but this specification currently only requires supporting two levels (_local_ and _global_).


=== Capability format changes
{cheri_levels_ext_name} adds a new `LVLBITS`-bit field to the <<section_cap_encoding,capability encoding>>, the _<<section_cap_level>>_.
It also adds two new permission fields, <<el_perm>> and <<sl_perm>>.

- For `MXLEN=64` <<section_cap_encoding,capability encoding>>, the AP field is widened by `LVLBITS+1` bits (i.e. 2 bits for `LVLBITS=1`)

NOTE: The <<cap_encoding_xlen64,`MXLEN=64` capability encoding>> diagram shows the layout for `LVLBITS=1`

- For `MXLEN=32` the capability's <<cap_encoding_xlen32,AP>> field is able to encode these permissions without increasing in size (provided that LVLBITS&#8804;2).

NOTE: {cheri_levels_ext_name} requires that LVLBITS&#8805;1 although LVLBITS>1 is considered an experimental enhancement of this extension.
See <<section_ext_cheri_multiple_levels>> for the mechanics when LVLBITS>1.

[#section_cap_level,reftext="Capability Level (CL)"]
==== Capability Level (CL)

The Capability Level (CL) is a new field added to the capability encoding, as shown in xref:section_cap_encoding[xrefstyle=short].

With `LVLBITS=1`, the _Capability Level_ can hold two values: when set to 1 the capability is _global_ (in general allowing it to be stored using any authorizing capability), and when set to 0 the capability is _local_, and can only be stored by authorizing capabilities with the <<sl_perm>> set.
Furthermore, the <<el_perm>> can be used to restrict loading of _global_ capabilities -- causing the hardware to automatically set the level of loaded capabilities to _local_ instead.

NOTE: The current specification only defines two levels, equivalent to _local_ and _global_ capabilities from CHERI v9, Morello and CHERIoT.

As with permissions, the capability level can only be decreased but never increased (without deriving from a capability with a higher level).
Therefore, the capability level is adjusted using the <<ACPERM>> instruction (see <<section_cap_level_change>>) and are queried using <<GCPERM>>.

==== New capability permissions
{cheri_levels_ext_name} introduces two new capability permissions:
[#sl_perm,reftext="SL-permission"]
Store Level Permission (SL):: This is a `LVLBITS` wide field that allows limiting the propagation of capabilities using the following logic: capabilities with a <<section_cap_level>> less than the inverse of the authorizing capability's <<sl_perm>> will be stored with the tag cleared.
With `LVLBITS=1` there is a single bit comparison, so it behaves as follows:
- If this field (as well as <<c_perm>> and <<w_perm>>) is set to 1 then capabilities may be stored via this capability regardless of their associated <<section_cap_level>>.
- If this field is zero, then any capability with a <<section_cap_level>> of zero (i.e. _local_), will be stored with the tag cleared.

NOTE: For `LVLBITS=1` this permission is equivalent to _StoreLocal_ in CHERI v9, Morello and CHERIoT.

[#el_perm,reftext="EL-permission"]
Elevate Level Permission (EL):: Any unsealed capability with its tag set to 1 that is loaded from memory has its <<el_perm>> cleared and its <<section_cap_level>> restricted to the authorizing capability's <<section_cap_level>> if the authorizing capability does not grant <<el_perm>>.
If sealed, then only <<section_cap_level,CL>> is modified, <<el_perm>> is unchanged.
This permission is similar to the existing <<lm_perm>>, but instead of applying to the <<w_perm>> on the loaded capability it restricts the <<section_cap_level,CL>> field.



ifdef::cheri_v9_annotations[]
NOTE: *CHERI v9 Note:* This permission does not exist in CHERI v9, but is similar to CHERIoT's _LoadGlobal_ permission, except that any _global_ capability implicitly grants _LoadGlobal_.
endif::[]

.Encoding of architectural permissions for MXLEN=32 when {cheri_levels_ext_name} is implemented
[#cap_perms_encoding_levels32,width="100%",options=header,cols="^2,^1,^1,^1,^1,^1,^1,^1,^1,^2,4",align="center"]
|==============================================================================
|Bits[4:3]| R | W | C | LM | EL | SL | X | ASR | Mode^1^ | Notes
11+| *Quadrant 0: Non-capability data read/write*
11+| bit[2] - write, bit[1] - reserved (0), bit[0] - read
11+| _Reserved bits for future extensions are 0 so new permissions are not implicitly granted_
| 0   |   |   |   |   |   |   |   |   | N/A | No permissions
| 1   | ✔ |   |   |   |   |   |   |   | N/A | Data RO
| 2-3   10+| reserved
| 4   |   | ✔ |   |   |   |   |   |   | N/A | Data WO
| 5   | ✔ | ✔ |   |   |   |   |   |   | N/A | Data RW
| 6-7   10+| reserved
11+| *Quadrant 1: Executable capabilities*
11+| bit[0] - <<m_bit>> ({CAP_MODE_VALUE}-{cheri_cap_mode_name}, {INT_MODE_VALUE}-{cheri_int_mode_name})
|Bits[4:3]| R | W | C | LM | EL | SL  | X | ASR | Mode^1^ |
| 0-1   | ✔ | ✔ | ✔ | ✔  | ✔  | ∞   | ✔ |  ✔  | Mode^1^  | Execute + ASR (see <<infinite-cap>>)
| 2-3   | ✔ |   | ✔ | ✔  | ✔  | ∞^2^| ✔ |     | Mode^1^  | Execute + Data & Cap RO
| 4-5   | ✔ | ✔ | ✔ | ✔  | ✔  | ∞   | ✔ |     | Mode^1^  | Execute + Data & Cap RW
| 6-7   | ✔ | ✔ |   |    |    | 0^2^| ✔ |     | Mode^1^  | Execute + Data RW
11+| *Quadrant 2: Restricted capability data read/write*
11+| bit[2] = write, bit[1:0] = store level. R and C implicitly granted, LM dependent on W permission.
|Bits[4:3]| R | W | C | LM | EL | SL    | X | ASR | Mode^1^ |
| 0-2   10+| reserved
| 3       | ✔ |   | ✔ |    |    | 0^1^  |   |     | N/A | Data & Cap R0 (without <<lm_perm>>)
| 4       | ✔ | ✔ | ✔ | ✔  |    | _(3)_ |   |     | N/A | _Reserved_ when `LVLBITS=1` ^3^
| 5       | ✔ | ✔ | ✔ | ✔  |    | _(2)_ |   |     | N/A | _Reserved_ when `LVLBITS=1` ^3^
| 6       | ✔ | ✔ | ✔ | ✔  |    | 1     |   |     | N/A | Data & Cap RW (with store _local_, no <<el_perm>>)
| 7       | ✔ | ✔ | ✔ | ✔  |    | 0     |   |     | N/A | Data & Cap RW (no store _local_, no <<el_perm>>)
11+| *Quadrant 3: Capability data read/write*
11+| bit[2] = write, bit[1:0] = store level. R and C implicitly granted.
11+| _Reserved bits for future extensions must be 1 so they are implicitly granted_
|Bits[4:3]| R | W | C | LM | EL | SL    | X | ASR | Mode^2^ |
| 0-2   10+| reserved
| 3       | ✔ |   | ✔ | ✔  | ✔  | 0^2^  |   |     | N/A | Data & Cap R0
| 4       | ✔ | ✔ | ✔ | ✔  | ✔  | _(3)_ |   |     | N/A | _Reserved_ when `LVLBITS=1` ^3^
| 5       | ✔ | ✔ | ✔ | ✔  | ✔  | _(2)_ |   |     | N/A | _Reserved_ when `LVLBITS=1` ^3^
| 6       | ✔ | ✔ | ✔ | ✔  | ✔  | 1     |   |     | N/A | Data & Cap RW (with store _local_)
| 7       | ✔ | ✔ | ✔ | ✔  | ✔  | 0     |   |     | N/A | Data & Cap RW (no store _local_)
|==============================================================================

^1^ _Mode (<<m_bit>>) can only be set on a tagged capability when {cheri_default_ext_name}
is supported. Despite being encoded here it is *not* an architectural permission._ +
^2^ SL isn't applicable in these cases, but this value is reported by <<GCPERM>> to simplify the rules followed by <<ACPERM>> +
^3^ These entries are reserved when `LVLBITS=1` and in use when `LVLBITS=2`

[#section_cap_level_change]
=== Changing capability levels and permissions
While capability levels (<<section_cap_level,CL>>) are conceptually a label on the capability rather than a permission granted by the capability, they are adjusted using the <<ACPERM>> instruction.
This avoids the need for a dedicated instruction and allows reducing the level and removing <<el_perm>> in a single instruction.

<<<

[#section_cap_level_summary]
=== Capability level summary table

NOTE: A capability with <<section_cap_level,CL>>=1 is _global_ and with <<section_cap_level,CL>>=0 is _local_.

.{cheri_levels_ext_name} `LVLBITS=1` summary table for stored capabilities
[#cap_level_store_summary,width="100%",options=header,halign=center,cols="1,1,1,1,5"]
|==============================================================================
   3+|Auth cap field       | Data cap field |
    h|*W*    h|*C* h|*SL* h|*CL* h| Notes
.3+.^|1  .3+.^| 1   | 1    | X    | Store data capability unmodified
               .2+.^| 0    | 1    | Store data capability unmodified (CL ≥ ~SL)
                           | 0    | Store data capability with tag cleared (CL < ~SL)
|==============================================================================

NOTE: if W=0 or C=0 then SL is irrelevant

.{cheri_levels_ext_name} additional rules for loading capabilities
[#cap_level_load_summary,width="100%",options=header,align=center,cols="1,1,1,1,1,1,6"]
|==============================================================================
   4+|Auth cap field                  2+| Data cap field |
    h|*R*   h|*C* h|*EL*      h|*CL*   h| Tag h| Sealed h|Action
.2+.^|1 .2+.^| 1 .2+.^| 0 .2+.^| X .2+.^| 1    | Yes     |Load data capability with `CL=min(auth.CL, data.CL)`, EL unchanged
                                               | No      |Load data capability with `EL=0, CL=min(auth.CL, data.CL)`
   6+| All other cases                                   |Load data capability with EL, CL unmodified
|==============================================================================

[#section_ext_cheri_multiple_levels]
=== Extending {cheri_levels_ext_name} to more than two levels
When `LVLBITS>1`, the behavior of <<ACPERM>> can no longer use masking to adjust the <<section_cap_level>> or <<sl_perm>>, but instead must perform an integer minimum operation on those `LVLBITS`-wide fields.
The <<section_cap_level,CL>> field of the resulting capability is set to `min(rs2[CL], cs1[CL])`  (equivalent to `rs2[CL] & cs1[CL]` for `LVLBITS=1`).
Similarly, <<sl_perm>> is set to `min(rs2[SL], cs1[SL])` (equivalent to `rs2[SL] & cs1[SL]` for `LVLBITS=1`).

When storing capabilities, the <<sl_perm>> checks need to perform a `LVLBITS`-wide integer comparison instead of just testing a single bit.
Considering for an example `LVLBITS=2`:

[options=header,grid=rows,cols="2,3,6"]
|===
|<<sl_perm>> | Permitted for levels| Resulting semantics
|3 | As low as `~0b11=0` | Authorizes stores of capabilities with any level
|2 | As low as `~0b10=1` | Strip tag for level 0 (most _local_), keep for 1,2,3
|1 | As low as `~0b01=2` | Strip tag for level 0&1, keep for 2&3
|0 | As low as `~0b00=3` | Strip tag for level 0,1,2, i.e. only the most _global_ can be stored
|===

NOTE: While this extra negation is non-intuitive, it is required such that <<ACPERM>> can use a monotonically decreasing operation for both <<section_cap_level,CL>> <<sl_perm>>.

NOTE: The layout of the <<ACPERM>> input / <<GCPERM>> result is not yet defined, but existing bits will not be moved around so the <<sl_perm,SL>>/<<section_cap_level,CL>> fields will be non-contiguous.
