[#section-cheri-execution-mode]
=== Capability format

{cheri_legacy_ext_name} adds a new CHERI execution mode bit (M) to capabilities.
The mode bit is encoded as shown in
xref:cap_encoding_xlen32_mode[xrefstyle=short] and
xref:cap_encoding_xlen64_mode[xrefstyle=short]. The current CHERI execution
mode is give by the M bit of the <<pcc>> and the CRE bits in <<mseccfg>>,
<<menvcfg>>, and <<senvcfg>> as follows:

* The mode is Capability when the M bit of the <<pcc>> is 1 and the effective
CRE=1 for the current privilege level
* The mode is Legacy when the effective CRE=0 for the current privilege level or the M bit of the <<pcc>> is 0

.Capability encoding when XLENMAX=32 and {cheri_legacy_ext_name} is supported
[#cap_encoding_xlen32_mode]
include::img/cap-encoding-xlen32-mode.edn[]

.Capability encoding when XLENMAX=64 and {cheri_legacy_ext_name} is supported
[#cap_encoding_xlen64_mode]
include::img/cap-encoding-xlen64-mode.edn[]

For RV64, the M bit can be set to 1 when the capability does not grant <<x_perm>>.
In this case, the M bit is superfluous, so the encoding may be used to support additional features in future extensions.

The M bit is 0 in both the <<null-cap>> and <<infinite-cap>> capabilities.

[#section_mode_cap_instructions]
=== Mode switching Instructions

{cheri_legacy_ext_name} introduces new instructions to the base RISC-V integer
ISA in addition to the instructions added in {cheri_base_ext_name}. These new
instructions allow modifying the CHERI mode bit in
capabilities and directly changing the current CHERI execution mode.

==== Capability Manipulation Instructions

A new <<SCMODE>> instruction allows setting a capability's CHERI execution
mode to the indicated value. The output is written to an unprivileged *c*
register, not <<pcc>>.

==== Mode Change Instructions

A new CHERI execution mode switch (<<MODESW>>) instruction allows software
to toggle the hart's current CHERI execution mode. If the current mode in the
<<pcc>> is Legacy, then the mode after executing <<MODESW>> is Capability
and vice-versa. This instruction effectively writes the CHERI execution mode
bit M of the capability currently installed in the <<pcc>>.

==== Unconditional Capability Jumps

{cheri_legacy_ext_name} allows changing the current CHERI execution mode when
executing either <<JALR>> from capability mode or <<JALR_MODE>> from legacy mode.
