= RISC-V Specification for CHERI Extensions
Authors: Hesham Almatary, Andres Amaya Garcia, John Baldwin, David Chisnall, Jessica Clarke, Brooks Davis, Nathaniel Wesley Filardo, Franz A. Fuchs, Timothy Hutt, Alexandre Joannou, Tariq Kurd, Ben Laurie, Marno van der Maas, A. Theodore Markettos, David McKay, Jamie Melling, Stuart Menefy, Simon W. Moore, Peter G. Neumann, Robert Norton, Alexander Richardson, Michael Roe, Peter Rugg, Peter Sewell, Carl Shaw, Robert N. M. Watson, Jonathan Woodruff
include::attributes.adoc[]

///////////////////////////////////////////////////////////////////////////////
// Preface
///////////////////////////////////////////////////////////////////////////////

ifdef::github_commit_sha[]
[IMPORTANT]
This document is a specification snapshot built from https://github.com/riscv/riscv-cheri/commit/{github_commit_sha} and is not a versioned release.
The latest versioned PDF release can be downloaded from https://github.com/riscv/riscv-cheri/releases.
endif::[]

[WARNING]
.This document is in the link:http://riscv.org/spec-state[Development state]
====
Expect potential changes. This draft specification is likely to evolve before
it is accepted as a standard. Implementations based on this draft
may not conform to the future standard.
====

[preface]
== Copyright and license information
This specification is licensed under the Creative Commons
Attribution 4.0 International License (CC-BY 4.0). The full
license text is available at
https://creativecommons.org/licenses/by/4.0/.

Copyright 2024 by RISC-V International.

[preface]
include::contributors.adoc[]

///////////////////////////////////////////////////////////////////////////////
// Document body
///////////////////////////////////////////////////////////////////////////////

include::introduction.adoc[]

include::cap-description.adoc[]

include::riscv-integration.adoc[]

include::debug-integration.adoc[]

include::trigger-integration.adoc[]

include::cheri-pte-ext.adoc[]

include::riscv-hybrid-integration.adoc[]

include::hypervisor-integration.adoc[]

include::vector-integration.adoc[]

include::ptrmask-integration.adoc[]

include::tid-ext.adoc[]

include::instructions.adoc[]

include::tables.adoc[]

///////////////////////////////////////////////////////////////////////////////
// Index and bibliography
///////////////////////////////////////////////////////////////////////////////

// The index must precede the bibliography
include::index.adoc[]

include::bibliography.adoc[]
