== "Zstid Extension for Thread Identification

{tid_ext_name} is an optional extension to the RISC-V base ISA.
Implementations that support {cheri_base_ext_name} and {tid_ext_name}
define a variant of the CHERI ISA that allows for more efficient
software compartmentalization of CHERI programs.

=== Control and Status Registers (CSRs)

{tid_ext_name} adds two new CSRs to implement a trusted thread
identifier (TID) used in compartmentalization. These CSRs are listed in
xref:tid-mcsrnames-added[xrefstyle=short],
xref:tid-scsrnames-added[xrefstyle=short], and
xref:tid-ucsrnames-added[xrefstyle=short].

[[tid-mcsrnames-added]]
.Added machine-mode CSRs in {tid_ext_name}
[%autowidth,float="center",align="center",cols="<,<,<,<,<,<",options="header"]
|===
|{tid_ext_name} CSR|Address|Prerequisites|Read-Permission|Write-Permission|Description
|<<mtid>>|0x780|M-mode|M|M, <<asr_perm>>|Machine Thread Identifier
|===

[[tid-scsrnames-added]]
.Added supervisor-mode CSRs in {tid_ext_name}
[%autowidth,float="center",align="center",cols="<,<,<,<,<,<",options="header"]
|===
|{tid_ext_name} CSR|Address|Prerequisites|Read-Permission|Write-Permission|Description
|<<stid>>|0x580|S-mode|S|S, <<asr_perm>>|Supervisor Thread Identifier
|===

[[tid-ucsrnames-added]]
.Added user-mode CSRs in {tid_ext_name}
[%autowidth,float="center",align="center",cols="<,<,<,<,<,<",options="header"]
|===
|{tid_ext_name} CSR|Address|Prerequisites|Read-Permission|Write-Permission|Description
|<<utid>>|0x480|U-mode|U|U, <<asr_perm>>|User Thread Identifier
|===



=== Machine-Level, Supervisor-Level and Unprivileged CSRs

[#mtid,reftext="mtid"]
==== Machine Thread Identifier (mtid)

The <<mtid>> register is an MXLEN-bit read-write register. It is used to
identify the current thread in machine mode. The reset value of this
register is UNSPECIFIED.

.Supervisor thread identifier register
include::img/mtidreg.edn[]

[#stid,reftext="stid"]
==== Supervisor Thread Identifier (stid)

The <<stid>> register is an SXLEN-bit read-write register. It is used to
identify the current thread in supervisor mode. The reset value of
this register is UNSPECIFIED.

.Supervisor thread identifier register
include::img/stidreg.edn[]


[#utid,reftext="utid"]
==== User Thread Identifier (utid)

The <<utid>> register is an UXLEN-bit read-write register. It is used to
identify the current thread in user mode. The reset value of
this register is UNSPECIFIED.

.User thread identifier register
include::img/utidreg.edn[]

When {cheri_base_ext_name} is implemented, the {tid_ext_name} CSRs are
extended as follows:

[#mtidc,reftext="mtidc"]
==== Machine Thread Identifier Capability (mtidc)

The <<mtidc>> register is an CLEN-bit read-write capability register.
It is the capability extension of the <<mtid>> register.
It is used to identify the current thread in machine mode.
On reset the tag of <<mtidc>> will be set to 0 and the remainder
of the data is UNSPECIFIED.

.Machine thread identifier capability register
include::img/mtidcreg.edn[]

[#stidc,reftext="stidc"]
==== Supervisor Thread Identifier Capability (stidc)

The <<stidc>> register is an CLEN-bit read-write capability register.
It is the capability extension of the <<stid>> register.
It is used to identify the current thread in supervisor mode.
On reset the tag of <<stidc>> will be set to 0 and the remainder
of the data is UNSPECIFIED.

.Supervisor thread identifier capability register
include::img/stidcreg.edn[]


[#utidc,reftext="utidc"]
==== User Thread Identifier Capability (utidc)

The <<utidc>> register is an CLEN-bit read-write capability register.
It is the capability extension of the <<utid>> register.
It is used to identify the current thread in user mode.
On reset the tag of <<utidc>> will be set to 0 and the remainder
of the data is UNSPECIFIED.

.User thread identifier capability register
include::img/utidcreg.edn[]

[#CHERI_COMP,reftext="CHERI Compartmentalization]
=== CHERI Compartmentalization

This section describes how this specification enables support for
compartmentalization for CHERI systems. Compartmentalization seeks
to separate the privileges between different protection units, e.g.,
two or more libraries. Code can be separated by sentries, which allow
for giving out code capabilities to untrusted code where the untrusted
code can only call the code capability, but not modify it. Sentries can
be called from different threads and thus there needs to be a way of
identifying the current thread. While identifying the current thread
can be done by privileged code, e.g., the kernel, the implied performance
overhead of this is not bearable for CHERI systems with many compartments.

The RISC-V ABI includes a _thread pointer (tp)_ register, which is not
usable for the purpose of reliably identifying the current thread because
the tp register is a general purpose register and can be changed arbitrarily
by untrusted code. Therefore, this specification offers three additional CSRs
that facilitate a trusted source for the thread ID. All registers are readable
from their respective privilege levels and writeable with <<asr_perm>>.

This extension extends <<mtid>>, <<stid>>, and <<utid>> to their respective
capability variants <<mtidc>>, <<stidc>>, and <<utidc>>. This presents software with the
freedom to still use these registers with capabilities or leave the metadata
untouched and only use the registers to storage integers.
