[#section_vector_integration]
== Integrating {cheri_base_ext_name} and {cheri_default_ext_name} with the Vector Extension

The RISC-V vector (V) extension is orthogonal to CHERI because the
vector registers only hold integer or floating-point data. The vector registers
are _not_ extended to hold capabilities.

NOTE: A future extension may allow tags to be stored in vector registers.
  Until that time, vector load and store instructions must not be used to implement generic
  memory copying in software, such as the `memcpy()` standard C library function,
  because the vector registers do not hold capabilities, so the tags of any
  copied capabilities will be set to 0 in the destination memory.

Vector loads and stores all following the behaviour as described in
xref:section_int_load_store_insns[xrefstyle=short], as all are treated as integer data.

The assembly syntax of all vector loads and stores are updated in
{cheri_cap_mode_name}, so that the address operand becomes a *c* operand instead
of an *x* operand.

According to the vector extension cite:[riscv-v-spec] only _active_ elements are
accessed or updated in memory. Therefore only _active_ elements are checked to be
within capability bounds. If a vector load or store has no _active_ elements then
no CHERI fault will be taken.

This is consistent with other exceptions such as page faults which are only taken
on _active_ elements.
