<<<

[#ACPERM,reftext="ACPERM"]
==== ACPERM

ifdef::cheri_v9_annotations[]
NOTE: *CHERI v9 Note:* The implementation of this instruction changes
because the permission fields are encoded differently in the new
capability format.

NOTE: *CHERI v9 Note:* this instruction was called CANDPERM.
endif::[]

include::new_encoding_note.adoc[]

Synopsis::
Mask capability permissions

Mnemonics::
`acperm cd, cs1, rs2`

Encoding::
include::wavedrom/acperm.adoc[]

Description::
Converts the AP and SDP fields of capability `cs1` into a bit field; one bit
per permission as shown below. Then calculate the bitwise AND of the bit field
with the mask `rs2` . Set the AP and SDP fields of `cs1` as indicated in the
resulting bit field -- the capability grants a permission if the corresponding
bit is set in the bit field -- and write the output capability to `cd` . The
output capability has its tag set to 0 if `cs1` is sealed.
+
The AP field is not able to encode all combinations of permissions when MXLEN=32, therefore removing a permission may yield a capability which cannot be encoded.
Valid combinations are shown in <<cap_perms_encoding32>>.
+
Additionally some combinations of permissions are not useful when XLENMAX=64.
These cases are defined to return useful minimal sets of permissions in each case, which may be no permissions.
+
NOTE: Future extensions may allow more combinations of permissions, especially for XLENMAX=64.

The common rules are:

. <<asr_perm>> cannot be set without <<x_perm>> being set
.. Clear <<asr_perm>> unless <<x_perm>> is set
. <<c_perm>> cannot be set without at least one of <<r_perm>> or <<w_perm>> being set.
.. Clear <<c_perm>> unless <<r_perm>> or <<w_perm>> are set.
. Clear the <<m_bit>> if clearing <<x_perm>>.

NOTE: The combination of <<x_perm>> clear and <<m_bit>> set is reserved for future extensions.

The XLENMAX=32 additional rules are:

. Clear <<asr_perm>> if _all_ other permissions are not set
. Clear <<c_perm>> and <<x_perm>> if <<r_perm>> is not set
. Clear <<x_perm>> if <<x_perm>> and <<r_perm>> _are_ set, but <<c_perm>> and <<w_perm>> _are not_ set.

include::../img/acperm_bit_field.edn[]

Prerequisites::
{cheri_base_ext_name}

Operation::
+
--
TODO: Sail does not have the new encoding of the permissions field.
--
