<<<

[#ACPERM,reftext="ACPERM"]
==== ACPERM

ifdef::cheri_v9_annotations[]
NOTE: *CHERI v9 Note:* The implementation of this instruction changes
because the permission fields are encoded differently in the new
capability format.

NOTE: *CHERI v9 Note:* this instruction was called CANDPERM.
endif::[]

include::new_encoding_note.adoc[]

Synopsis::
Mask capability permissions

Mnemonics::
`acperm cd, cs1, rs2`

Encoding::
include::wavedrom/acperm.adoc[]

Description::

include::../img/acperm_bit_field.edn[]

ACPERM performs the following operations:

. Convert the AP and SDP fields of capability `cs1` into the format shown above
.. SDPLEN is defined in <<sdp_bit_width>>
. Calculate the bitwise AND of the bit field with the mask `rs2`.
. If the AP and <<m_bit>> field in `cs1` could not have been produced by <<ACPERM>> then
clear all AP permissions and the <<m_bit>>, and skip the next step
. Clear AP permissions as required to meet the rules below.
. Encode the AP permissions for MXLEN=32 according to <<cap_perms_encoding32>>.
. Copy `cs1` to `cd`, and update the AP and SDP fields with the newly calculated versions.
. Set `cd.tag=0` if `cs1` is sealed.
+
Some combinations of permissions cannot be encoded for MXLEN=32, and are not useful when MXLEN=64.
These cases are defined to return useful minimal sets of permissions, which may be no permissions.
+
NOTE: Future extensions may allow more combinations of permissions, especially for MXLEN=64.

The common rules are:

. <<asr_perm>> cannot be set without <<x_perm>> being set
.. Clear <<asr_perm>> unless <<x_perm>> is set
. <<c_perm>> cannot be set without at least one of <<r_perm>> or <<w_perm>> being set.
.. Clear <<c_perm>> unless <<r_perm>> or <<w_perm>> are set.
. <<m_bit>> cannot be set without <<x_perm>> being set
.. Clear <<m_bit>> unless <<x_perm>> is set

NOTE: The combination of <<x_perm>> clear and <<m_bit>> set is reserved for future extensions.

The MXLEN=32 additional rules are:

. Clear <<asr_perm>> unless _all_ other permissions are set
. Clear <<c_perm>> and <<x_perm>> if <<r_perm>> is not set
. Clear <<x_perm>> if <<x_perm>> and <<r_perm>> _are_ set, but <<c_perm>> and <<w_perm>> _are not_ set.

Exceptions::
include::require_cre.adoc[]

Prerequisites::
{cheri_base_ext_name}

Operation::
+
--
TODO: Sail does not have the new encoding of the permissions field.
--
