<<<

[#ACPERM,reftext="ACPERM"]
==== ACPERM

ifdef::cheri_v9_annotations[]
NOTE: *CHERI v9 Note:* The implementation of this instruction changes
because the permission fields are encoded differently in the new
capability format.

NOTE: *CHERI v9 Note:* this instruction was called CANDPERM.
endif::[]

include::new_encoding_note.adoc[]

Synopsis::
Mask capability permissions

Mnemonics::
`acperm cd, cs1, rs2`

Encoding::
include::wavedrom/acperm.adoc[]

Description::
Converts the AP and SDP fields of capability `cs1` into a bit field; one bit
per permission as shown below. Then calculate the bitwise AND of the bit field
with the mask `rs2` . Set the AP and SDP fields of `cs1` as indicated in the
resulting bit field -- the capability grants a permission if the corresponding
bit is set in the bit field -- and write the output capability to `cd` . The
output capability has its tag set to 0 if `cs1` is sealed.

include::../img/acperm_bit_field.edn[]

NOTE: The AP field is not able to encode all combinations of permissions when
XLENMAX=32. If permissions that cannot be encoded are indicated, ACPERM
outputs a capability with all architectural permissions cleared.

CAUTION: TODO: this may not be correct - we should work through the
 different combinations which are possible for removing a permission
 for RV32, where it is restricted, and decide what to do in each case

Prerequisites::
{cheri_base_ext_name}

Operation::
+
--
TODO: Sail does not have the new encoding of the permissions field.
--
