<<<

[#C_ADDI16SP, reftext="C.ADDI16SP"]
==== C.ADDI16SP

Synopsis::
Stack pointer increment in blocks of 16 (C.ADDI16SP), 16-bit encodings

pass:attributes,quotes[{cheri_cap_mode_name}] Mnemonic::
`c.addi16sp imm`

pass:attributes,quotes[{cheri_cap_mode_name}] Expansion::
`cadd csp, csp, imm`

pass:attributes,quotes[{cheri_int_mode_name}] Mnemonic::
`c.addi16sp imm`

pass:attributes,quotes[{cheri_int_mode_name}] Expansion::
`add sp, sp, imm`

Encoding::
include::wavedrom/c-int-reg-immed.adoc[]

pass:attributes,quotes[{cheri_cap_mode_name}] Description::

Add the non-zero sign-extended 6-bit immediate to the value in the stack pointer (`csp=c2`), where the immediate is scaled to represent multiples of 16 in the range (-512,496). Clear the tag if the resulting capability is
unrepresentable or `csp` is sealed.

pass:attributes,quotes[{cheri_int_mode_name}] Description::

Add the non-zero sign-extended 6-bit immediate to the value in the stack pointer (`sp=x2`), where the immediate is scaled to represent multiples of 16 in the range (-512,496).

Prerequisites for pass:attributes,quotes[{cheri_cap_mode_name}]::
{c_cheri_base_ext_names}

Prerequisites for pass:attributes,quotes[{cheri_int_mode_name}]::
{c_cheri_default_ext_names}

pass:attributes,quotes[{cheri_cap_mode_name}] Operation::
+
--
TODO
--
