<<<

[#C_ADDI4SPN,reftext="C.ADDI4SPN"]
==== C.ADDI4SPN

See <<C.ADDI4SPN>>.

Synopsis::
Stack pointer increment in blocks of 4 (C.ADDI4SPN), 16-bit encoding

Capability Mode Mnemonic::
`c.addi4spn cd', uimm`

Capability Mode Expansion::
`cadd cd', csp, uimm`

Legacy Mode Mnemonic::
`c.addi4spn rd', uimm`

Legacy Mode Expansion::
`add rd', sp, uimm`

Encoding::
include::wavedrom/c-ciw.adoc[]

Capability Mode Description::

Add a zero-extended non-zero immediate, scaled by 4, to the stack pointer, `csp`, and writes the result to `cd'`. This instruction is used to generate pointers to stack-allocated variables. Clear the tag if the resulting capability is unrepresentable or `csp` is sealed.

Legacy Mode Description::

Add a zero-extended non-zero immediate, scaled by 4, to the stack pointer, `sp`, and writes the result to `rd'`. This instruction is used to generate pointers to stack-allocated variables.

Prerequisites for C.ADDI4SPN::
{c_cheri_base_ext_names}

Prerequisites for C.ADDI4SPN::
{c_cheri_legacy_ext_names}

Capability Mode Operation::
+
--
TODO
--
