<<<

[#C_ADDI16SP, reftext="C.ADDI16SP"]
==== C.ADDI16SP

Synopsis::
Stack pointer increment in blocks of 16 (C.ADDI16SP), 16-bit encodings

Capability Mode Mnemonic::
`c.addi16sp imm`

Capability Mode Expansion::
`cadd csp, csp, imm`

Legacy Mode Mnemonic::
`c.addi16sp imm`

Legacy Mode Expansion::
`add sp, sp, imm`

Encoding::
include::wavedrom/c-int-reg-immed.adoc[]

Capability Mode Description::

Add the non-zero sign-extended 6-bit immediate to the value in the stack pointer (`csp=c2`), where the immediate is scaled to represent multiples of 16 in the range (-512,496). Clear the tag if the resulting capability is
unrepresentable or `csp` is sealed.

Legacy Mode Description::

Add the non-zero sign-extended 6-bit immediate to the value in the stack pointer (`sp=x2`), where the immediate is scaled to represent multiples of 16 in the range (-512,496).

Prerequisites for Capability Mode::
{c_cheri_base_ext_names}

Prerequisites for Legacy Mode::
{c_cheri_legacy_ext_names}

Capability Mode Operation::
+
--
TODO
--
