<<<

[#ADD_UW,reftext="ADD.UW"]
==== ADD.UW

Synopsis::
Add unsigned word for address generation

pass:attributes,quotes[{cheri_cap_mode_name}] Mnemonic (RV64)::
`add.uw cd, rs1, cs2`

pass:attributes,quotes[{cheri_int_mode_name}] Mnemonic (RV64)::
`add.uw rd, rs1, rs2`

Encoding::
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x3b, attr: ['OP'] },
    { bits:  5, name: 'cd/rd' },
    { bits:  3, name: 0x0, attr: ['rv64: ADD.UW'] },
    { bits:  5, name: 'rs1' },
    { bits:  5, name: 'cs2/rs2' },
    { bits:  7, name: 0x04, attr: ['rv64: ADD.UW'] },
]}
....

pass:attributes,quotes[{cheri_cap_mode_name}] Description::
Increment the address field of `cs2` by the unsigned word in `rs1`. Clear the tag if the resulting capability is unrepresentable or `cs2` is sealed.

pass:attributes,quotes[{cheri_int_mode_name}] Description::
Increment `rs2` by the unsigned word in `rs1`.

Prerequisites for pass:attributes,quotes[{cheri_cap_mode_name}]::
RV64, {cheri_base_ext_name}, Zba

Prerequisites for pass:attributes,quotes[{cheri_int_mode_name}]::
RV64, {cheri_default_ext_name}, Zba

pass:attributes,quotes[{cheri_cap_mode_name}] Operation::
[source,SAIL,subs="verbatim,quotes"]
--
TBD
--

pass:attributes,quotes[{cheri_int_mode_name}] Operation::
+
--
TODO
--
