<<<

[#AMOOPW,reftext="AMO<OP>.W"]
==== AMO<OP>.W

See <<AMOOPD>>.

<<<

[#AMOOPD,reftext="AMO<OP>.D"]
==== AMO<OP>.D

Synopsis::
Atomic Operations (AMO<OP>.W, AMO<OP>.D), 32-bit encodings

pass:attributes,quotes[{cheri_cap_mode_name}] Mnemonics (RV64)::
`amo<op>.[w|d] rd, rs2, offset(cs1)`

pass:attributes,quotes[{cheri_cap_mode_name}] Mnemonics (RV32)::
`amo<op>.w rd, rs2, offset(cs1)`

pass:attributes,quotes[{cheri_int_mode_name}] Mnemonics (RV64)::
`amo<op>.[w|d] rd, rs2, offset(rs1)`

pass:attributes,quotes[{cheri_int_mode_name}] Mnemonics (RV32)::
`amo<op>.w rd, rs2, offset(rs1)`

Encoding::
include::wavedrom/amo.adoc[]

pass:attributes,quotes[{cheri_cap_mode_name}] Description::
Standard atomic instructions, authorised by the capability in `cs1`.

pass:attributes,quotes[{cheri_int_mode_name}] Description::
Standard atomic instructions, authorised by the capability in <<ddc>>.

include::atomic_exceptions.adoc[]

Prerequisites for pass:attributes,quotes[{cheri_cap_mode_name}] AMO<OP>.W, AMO<OP>.D::
{cheri_base_ext_name}, and A

Prerequisites for pass:attributes,quotes[{cheri_int_mode_name}] AMO<OP>.W, AMO<OP>.D::
{cheri_default_ext_name}, and A

pass:attributes,quotes[{cheri_cap_mode_name}] Operation::
[source,SAIL,subs="verbatim,quotes"]
--
TBD
--

pass:attributes,quotes[{cheri_int_mode_name}] Operation::
+
--
TODO
--
