<<<

[#AMOSWAP_C,reftext="AMOSWAP.C"]
==== AMOSWAP.C

NOTE: The RV64 encoding is intended to also allocate the encoding for AMOSWAP.Q for RV128.

Synopsis::
Atomic Operation (AMOSWAP.C), 32-bit encoding

include::xlen_variable_warning.adoc[]

pass:attributes,quotes[{cheri_cap_mode_name}] Mnemonic::
`amoswap.c cd, cs2, offset(cs1)`

pass:attributes,quotes[{cheri_int_mode_name}] Mnemonic::
`amoswap.c cd, cs2, offset(rs1)`

Encoding::
include::wavedrom/amoswap_cap.adoc[]

pass:attributes,quotes[{cheri_cap_mode_name}] Description::
Atomic swap of capability type, authorised by the capability in `cs1`.

pass:attributes,quotes[{cheri_int_mode_name}] Description::
Atomic swap of capability type, authorised by the capability in <<ddc>>.

:cap_atomic:

include::malformed_no_check.adoc[]

include::atomic_exceptions.adoc[]

Exceptions::
include::require_cre.adoc[]

Prerequisites for pass:attributes,quotes[{cheri_cap_mode_name}] AMOSWAP.C::
{cheri_base_ext_name}, and A

Prerequisites for pass:attributes,quotes[{cheri_int_mode_name}] AMOSWAP.C::
{cheri_default_ext_name}, and A

Operation::
+
--
TODO
--
