<<<

[#CADDI,reftext="CADDI"]
==== CADDI

See <<CADD>>.

[#CADD,reftext="CADD"]
==== CADD

include::new_encoding_note.adoc[]

ifdef::cheri_v9_annotations[]
NOTE: *CHERI v9 Note:* these instructions were called CINCOFFSET and
 CINCOFFSETIMM.

NOTE: *CHERI v9 Note:* the immediate format has changed
endif::[]

Synopsis::
Capability pointer increment

Mnemonic::
`cadd cd, cs1, rs2` +
`caddi cd, cs1, imm`

Suggested assembly syntax::
`add cd, cs1, rs2` +
`add cd, cs1, imm`

NOTE: the suggested assembly syntax distinguishes from integer `add` by operand type.

Encoding::
include::wavedrom/cadd.adoc[]

NOTE: <<CADD>> with `rs2=x0` is decoded as <<CMV>> instead, the key
difference being that tagged capabilities cannot have their tag
cleared by <<CMV>>.

Description::
Increment the address field of the capability `cs1`  and write the result to
`cd` . The tag bit of the output capability is 0 if `cs1`  did not have its tag
set to 1, the incremented address is outside `cs1` 's <<section_cap_representable_check>> or
`cs1`  is sealed. +
+
For <<CADD>>, the address is incremented by the value in
`rs2` . +
For <<CADDI>>, the address is incremented by the immediate value
`imm`.

NOTE: This instruction sets `cd.tag=0` if `cs1` 's bounds are <<section_cap_malformed,malformed>>,
or if any of the reserved fields are set.

Exceptions::
include::require_cre.adoc[]

Prerequisites::
{cheri_base_ext_name}

Operation (CADD)::
+
sail::execute[clause="CADD(_, _, _)",part=body,unindent]

Operation (CADDI)::
+
sail::execute[clause="CADDI(_, _, _)",part=body,unindent]
