<<<

[#CBLD,reftext="CBLD"]
==== CBLD

ifdef::cheri_v9_annotations[]
NOTE: *CHERI v9 Note:* CBLD does not use ddc if cs1==0

NOTE: *CHERI v9 Note:* this instruction was called CBUILDCAP.
endif::[]

include::new_encoding_note.adoc[]

Synopsis::
Capability build

Mnemonic::
`cbld cd, cs1, cs2`

Encoding::
include::wavedrom/cbld.adoc[]

Description::
Copy `cs2` to `cd` and set the tag to 1 if `cs1.tag` is set, `cs1` is not
sealed, `cs2` 's permissions and bounds are equal to or a subset of `cs1` 's,
`cs2` 's bounds are not malformed (see
xref:section_cap_malformed[xrefstyle=short]), and all reserved bits in `cs2` 's
metadata are 0; otherwise, copy `cs2` to `cd` and clear `cd` 's tag. <<CBLD>> is typically used alongside <<SCHI>> to build
capabilities from integer values.

NOTE: When `cs1` is `c0` this will set the tag to 0 and leave the metadata
otherwise unchanged. However this may change in future extensions,
and so software should not assume `cs1==0` to be a pseudo instruction
for tag clearing.

Exceptions::
include::require_cre.adoc[]

Prerequisites::
{cheri_base_ext_name}

Simplified Operation TODO #not debugged much easier to read than the existing SAIL# ::
[source,SAIL,subs="verbatim,quotes"]
--
let cs1_val = C(cs1);
let cs2_val = C(cs2) [with tag=1];
//isCapSubset includes derivability checks on both operands
let subset  = isCapSubset(cs1_val, cs2_val);
//Clear cd.tag if cs2 isn't a subset of cs1, or if
//cs1 is untagged or sealed, or if either is underivable
C(cd)       = clearTagIf(cs2_val, not(subset) |
                                  not(cs1_val.tag) |
                                  isCapSealed(cs1_val));
RETIRE_SUCCESS
--

Operation::
+
--
TODO: Original Sail looks at otype field, etc that don't exist
--
