<<<

[#CBLD,reftext="CBLD"]
==== CBLD

ifdef::cheri_v9_annotations[]
NOTE: *CHERI v9 Note:* CBLD does not use ddc if cs1==0

NOTE: *CHERI v9 Note:* this instruction was called CBUILDCAP.
endif::[]

include::new_encoding_note.adoc[]

Synopsis::
Capability build

Mnemonic::
`cbld cd, cs1, cs2`

Encoding::
include::wavedrom/cbld.adoc[]

Description::
Copy `cs2` to `cd` and set `cd.tag` to 1 if

. `cs1.tag` is set, and
. `cs1` 's bounds are not <<section_cap_malformed,malformed>>, and all reserved fields are zero, and
. `cs1` 's permissions could have been legally produced by <<ACPERM>>, and
. `cs1` is not sealed, and
. `cs2` 's permissions and bounds are equal to or a subset of `cs1` 's, and
. `cs2` 's bounds are not <<section_cap_malformed,malformed>>, and all reserved fields are zero, and
. `cs2` 's permissions could have been legally produced by <<ACPERM>>, and
. All reserved bits in `cs2` 's metadata are 0;

Otherwise, copy `cs2` to `cd` and clear `cd` 's tag.

<<CBLD>> is typically used alongside <<SCHI>> to build
capabilities from integer values.

NOTE: When `cs1` is `c0` this will copy `cs2` to `cd` and clear `cd.tag`.
However this may change in future extensions, and so software should not
assume `cs1==0` to be a pseudo instruction for tag clearing.

Exceptions::
include::require_cre.adoc[]

Prerequisites::
{cheri_base_ext_name}

Simplified Operation TODO #not debugged much easier to read than the existing SAIL# ::
[source,SAIL,subs="verbatim,quotes"]
--
let cs1_val = C(cs1);
let cs2_val = C(cs2) [with tag=1];
//isCapSubset includes derivability checks on both operands
let subset  = isCapSubset(cs1_val, cs2_val);
//Clear cd.tag if cs2 isn't a subset of cs1, or if
//cs1 is untagged or sealed, or if either is underivable
C(cd)       = clearTagIf(cs2_val, not(subset) |
                                  not(cs1_val.tag) |
                                  isCapSealed(cs1_val));
RETIRE_SUCCESS
--

Operation::
+
--
TODO: Original Sail looks at otype field, etc that don't exist
--
