<<<

[#CBUILDCAP,reftext="CBUILDCAP"]
==== CBUILDCAP

include::new_encoding_note.adoc[]

Synopsis::
Capability build

Mnemonic::
`cbuildcap cd, cs1, cs2`

Encoding::
include::wavedrom/cbuildcap.adoc[]

Description::
Copy `cs2` to `cd` and set the tag to 1 if `cs1.tag` is set, `cs1` is not
sealed, `cs1` 's permissions and bounds are equal or a superset of `cs2` 's,
`cs2` 's bounds are not malformed (see
xref:section_cap_malformed[xrefstyle=short]), and all reserved bits in `cs2` 's
metadata are 0. <<CBUILDCAP>> is typically used alongside <<CSETHIGH>> to build
capabilities from integer values.

Prerequisites::
{cheri_base_ext_name}

Simplified Operation TODO #not debugged much easier to read than the existing SAIL# ::
[source,SAIL,subs="verbatim,quotes"]
--
let cs1_val = if unsigned(cs1) == 0 then DDC else C(cs1);
let cs2_val = C(cs2) [with tag=1];
//isCapSubset includes derivability checks on both operands
let subset  = isCapSubset(cs1_val, cs2_val);
//Clear cd.tag if cs1 isn't a subset of cs1, or if
//cs1 is untagged or sealed, or if either is underivable
C(cd)       = clearTagIf(cs2_val, not(subset) |
                                  not(cs1_val.tag) |
                                  isCapSealed(cs1_val));
RETIRE_SUCCESS
--

Operation::
+
--
TODO: Original Sail looks at otype field, etc that don't exist
--

