<<<

[#CINCOFFSETIMM,reftext="CINCOFFSETIMM"]
==== CINCOFFSETIMM

See <<CINCOFFSET>>.

[#CINCOFFSET,reftext="CINCOFFSET"]
==== CINCOFFSET

include::new_encoding_note.adoc[]

ifdef::cheri_v9_annotations[]
NOTE: *CHERI v9 Note:* the immediate format has changed
endif::[]

Synopsis::
Capability pointer increment

Mnemonic::
`cincoffset cd, cs1, rs2` +
`cincoffsetimm cd, cs1, imm`

Encoding::
include::wavedrom/cincoffset.adoc[]

NOTE: <<CINCOFFSET>> with `rs2=x0` is decoded as <<CMOVE>> instead, the key
difference being that tagged and sealed capabilities do not have their tag
cleared by <<CMOVE>>.

Description::
Increment the address field of the capability `cs1`  and write the result to
`cd` . The tag bit of the output capability is 0 if `cs1`  did not have its tag
set to 1, the incremented address is outside `cs1` 's <<section_cap_representable_check>> or
`cs1`  is sealed. +
For <<CINCOFFSET>>, the address is incremented by the value in
`rs2` . +
For <<CINCOFFSETIMM>>, the address is incremented by the immediate value
`imm`.

Prerequisites::
{cheri_base_ext_name}

Operation (CINCOFFSET)::
+
--
TODO
--

Operation (CINCOFFSETIMM)::
+
--
TODO
--
