<<<

[#C_MV,reftext="C.MV"]
==== C.MV

Synopsis::
Capability move (C.MV), 16-bit encoding

pass:attributes,quotes[{cheri_cap_mode_name}] Mnemonic::
c.mv cd, cs2

pass:attributes,quotes[{cheri_cap_mode_name}] Expansion::
cmv cd, cs2

Suggested assembly syntax::
`mv rd, rs2` +
`mv cd, cs2`

NOTE: the suggested assembly syntax distinguishes from integer `mv` by operand type.

pass:attributes,quotes[{cheri_int_mode_name}] Mnemonic::
c.mv rd, rs2

pass:attributes,quotes[{cheri_int_mode_name}] Expansion::
add rd, x0, rs2

Encoding::
include::wavedrom/c_mv.adoc[]

pass:attributes,quotes[{cheri_cap_mode_name}] Description::
Capability register `cd` is replaced with the contents of `cs2`.

pass:attributes,quotes[{cheri_int_mode_name}] Description::
Standard RISC-V <<C_MV>> instruction.

include::malformed_no_check.adoc[]

Prerequisites for pass:attributes,quotes[{cheri_cap_mode_name}]::
{c_cheri_base_ext_names}

Prerequisites for pass:attributes,quotes[{cheri_int_mode_name}]::
{c_cheri_default_ext_names}

pass:attributes,quotes[{cheri_cap_mode_name}] Operation (after expansion to 32-bit encodings)::
 See <<CMV>>
