<<<

[#CSETBOUNDSIMM,reftext="CSETBOUNDSIMM"]
==== CSETBOUNDSIMM

See <<CSETBOUNDS>>.

[#CSETBOUNDS,reftext="CSETBOUNDS"]
==== CSETBOUNDS

ifdef::cheri_v9_annotations[]
NOTE: *CHERI v9 Note:* <<CSETBOUNDS>> was CSETBOUNDSEXACT,
<<CSETBOUNDSIMM>> would have been CSETBOUNDSEXACTIMM if it had existed.
endif::[]

include::new_encoding_note.adoc[]

ifdef::cheri_v9_annotations[]
NOTE: *CHERI v9 Note:* the immediate format has changed
endif::[]

Synopsis::
Capability set bounds

Mnemonic::
`csetbounds cd, cs1, rs2` +
`csetboundsimm cd, cs1, uimm`

Encoding::
include::wavedrom/csetbounds_32bit.adoc[]

Description::
Capability register `cd`  is set to capability register `cs1`  with the base
address of its bounds replaced with the value of `cs1.address` and
the length of its bounds set to `rs2`  (or `imm`). If the resulting capability
cannot be represented exactly then set `cd.tag` to 0.
In all cases, `cd.tag` is set to 0 if its bounds exceed `cs1` 's bounds, `cs1` 's
tag is 0  or `cs1` is sealed.
+
<<CSETBOUNDSIMM>> uses the `s` bit to scale the immediate by 4 places
+
`immediate = ZeroExtend(s ? uimm<<4 : uimm)`

Prerequisites::
{cheri_base_ext_name}

TODO: #this is the CSetBoundsExact() function which will be renamed#

Operation for CSETBOUNDS::
+
--
TODO
--

Operation for CSETBOUNDSIMM::
+
--
TODO
--
