<<<
//[#insns-csrr-32bit,reftext="CSR access (CSRRW[I], CSRRS[I], CSRRC[I]), 32-bit encoding"]

[#CSRRWI,reftext="CSRRWI"]
==== CSRRWI
See <<CSRRCI>>.

[#CSRRS,reftext="CSRRS"]
==== CSRRS
See <<CSRRCI>>.

[#CSRRSI,reftext="CSRRSI"]
==== CSRRSI
See <<CSRRCI>>.

[#CSRRC,reftext="CSRRC"]
==== CSRRC
See <<CSRRCI>>.

<<<

[#CSRRCI,reftext="CSRRCI"]
==== CSRRCI

ifdef::cheri_v9_annotations[]
NOTE: *CHERI v9 Note:* CSpecialRW is removed and this functionality replaces it
endif::[]


Synopsis::
CSR access (CSRRWI, CSRRS, CSRRSI, CSRRC, CSRRCI) 32-bit encodings

Mnemonics for accessing capability CSRs at CLEN-wide aliases::
`csrrs  cd, rs1, csr` +
`csrrc  cd, rs1, csr` +
`csrrwi cd, imm, csr` +
`csrrsi cd, imm, csr` +
`csrrci cd, imm, csr`

Mnemonics for accessing XLEN-wide CSRs or capability CSRs at XLEN-wide aliases::
`csrrs  rd, rs1, csr` +
`csrrc  rd, rs1, csr` +
`csrrwi rd, imm, csr` +
`csrrsi rd, imm, csr` +
`csrrci rd, imm, csr`

Encoding::
include::wavedrom/csr-instr.adoc[]

Description::
These are standard RISC-V CSR instructions with extended functionality for
accessing CLEN-wide CSRs, such as <<mtvec>>/<<mtvecc>>, which can be
accessed through either the RISC-V address or the capability address alias.
+
Unlike <<CSRRW>>, these instructions only update the address field when writing
capability CSRs regardless of the CSR's alias used. The final address to write
to the capability CSR is determined as defined by RISC-V for these
instructions. The metadata and tag are updated as defined in
xref:extended_CSR_writing[xrefstyle=short].
+
See xref:aliased_CSRs[xrefstyle=short] for a list of CLEN-wide CSRs and
xref:extended_CSR_writing[xrefstyle=short] for the action taken on writing an XLEN-wide value to each one.
+
If `cd` is `c0` (or `rd` is `x0`), then <<CSRRWI>> shall not read the CSR and
and shall not cause any of the side effects that might occur on a CSR read. If
`rs1` is `x0`, then <<CSRRS>>, <<CSRRC>>, <<CSRRSI>> and <<CSRRCI>> will not
write to the CSR at all, and so shall not cause any of the side effects that
might otherwise occur on a CSR write.
+
Access to XLEN-wide CSRs from other extensions is as specified by RISC-V.

NOTE: If `rs1` is `x0` and the CSR accessed is a capability, then <<CSRRS>>,
<<CSRRC>>, <<CSRRSI>> and <<CSRRCI>> do not write so no representability check
is needed in this case.

Permissions::
All non-user mode accessible CSRs require <<asr_perm>>, including existing RISC-V CSRs.

Prerequisites for capability address aliases::
{cheri_base_ext_name}

Prerequisites for legacy address aliases::
{cheri_legacy_ext_name}

Operation::
[source,SAIL,subs="verbatim,quotes"]
--
TBD
--
