<<<
//[#insns-csrr-32bit,reftext="CSR access (CSRRW[I], CSRRS[I], CSRRC[I]), 32-bit encoding"]

[#CSRRWI,reftext="CSRRWI"]
==== CSRRWI
See <<CSRRCI>>.

[#CSRRS,reftext="CSRRS"]
==== CSRRS
See <<CSRRCI>>.

[#CSRRSI,reftext="CSRRSI"]
==== CSRRSI
See <<CSRRCI>>.

[#CSRRC,reftext="CSRRC"]
==== CSRRC
See <<CSRRCI>>.

<<<

[#CSRRCI,reftext="CSRRCI"]
==== CSRRCI

ifdef::cheri_v9_annotations[]
NOTE: *CHERI v9 Note:* CSpecialRW is removed and this functionality replaces it
endif::[]


Synopsis::
CSR access (CSRRWI, CSRRS, CSRRSI, CSRRC, CSRRCI) 32-bit encodings

Register Source Mnemonics::
`csrr[s|c] rd, rs1, csr`

Immediate Source Mnemonics::
`csrr[w|s|c]i rd, imm, csr`

Encoding::
include::wavedrom/csr-instr.adoc[]

Description::
These are standard RISC-V CSR instructions with extended functionality for
accessing CLEN-wide CSRs, such as <<mtvec>>/<<mtvecc>> which can be
accessed through either the RISC-V address or the capability address alias.
+
Unlike <<CSRRW>> these instruction perform the same update to CLEN-wide CSRs
 to either the XLEN or CLEN-wide alias as they only every perform an XLEN-wide update.
 Where a CLEN-wide CSR is updated, through either alias, the final address is determined
 as defined by RISC-V for these instructions. The metadata and tag are updated
 as defined in xref:extended_CSR_writing[xrefstyle=short].
+
See xref:aliased_CSRs[xrefstyle=short] for a list of CLEN-wide CSRs and
xref:extended_CSR_writing[xrefstyle=short] for the action taken on writing an XLEN-wide value to each one.
+
Access to XLEN-wide CSRs from other extensions is as specified by RISC-V.

Permissions::
All non-user mode accessible CSRs require <<asr_perm>>, including existing RISC-V CSRs.

Prerequisites for capability address aliases::
{cheri_base_ext_name}

Prerequisites for legacy address aliases::
{cheri_legacy_ext_name}

Operation::
[source,SAIL,subs="verbatim,quotes"]
--
TBD
--
