<<<
//[#insns-csrr-32bit,reftext="CSR access (CSRRW[I], CSRRS[I], CSRRC[I]), 32-bit encoding"]

[#CSRRW,reftext="CSRRW"]
==== CSRRW

ifdef::cheri_v9_annotations[]
NOTE: *CHERI v9 Note:* CSpecialRW is removed and this functionality replaces it
endif::[]


Synopsis::
CSR access (CSRRW) 32-bit encodings

Mnemonic for accessing capability CSRs in Capability Mode::
`csrrw cd, csr, cs1`

Mnemonic for accessing XLEN-wide CSRs or extended CSRs in Legacy Mode::
`csrrw rd, csr, rs1`

Encoding::
include::wavedrom/csrw-instr.adoc[]

Description::
This is a standard RISC-V CSR instructions with extended functionality for
accessing CLEN-wide CSRs, such as <<mtvec>>/<<mtvecc>>.
+
See xref:aliased_CSRs[xrefstyle=short] for a list of CLEN-wide CSRs and
xref:extended_CSR_writing[xrefstyle=short] for the action taken on writing each one.
+
CSRRW writes `cs1` to extended CSRs in Capability Mode, and reads a full capability into `cd`.
+
CSRRW writes `rs1` to extended CSRs in Legacy Mode, and reads the address field into `rd`.
+
If `cd` is `c0` (or `rd` is `x0`), then the instruction shall not read the CSR
and shall not cause any of the side effects that might occur on a CSR read.
+
The assembler pseudoinstruction to write a capability CSR in Capability Mode,
`csrw csr, cs1`, is encoded as `csrrw c0, csr, cs1`.
+
Access to XLEN-wide CSRs from other extensions is as specified by RISC-V.


Permissions::
All non-user mode accessible CSRs require <<asr_perm>>, including existing RISC-V CSRs.

Prerequisites for Capability Mode::
{cheri_base_ext_name}

Prerequisites for Legacy Mode::
{cheri_legacy_ext_name}

Operation::
[source,SAIL,subs="verbatim,quotes"]
--
TBD
--
