<<<
//[#insns-csrr-32bit,reftext="CSR access (CSRRW[I], CSRRS[I], CSRRC[I]), 32-bit encoding"]

[#CSRRWI,reftext="CSRRWI"]
==== CSRRWI
See <<CSRRCI>>.

[#CSRRS,reftext="CSRRS"]
==== CSRRS
See <<CSRRCI>>.

[#CSRRSI,reftext="CSRRSI"]
==== CSRRSI
See <<CSRRCI>>.

[#CSRRC,reftext="CSRRC"]
==== CSRRC
See <<CSRRCI>>.

<<<

[#CSRRCI,reftext="CSRRCI"]
==== CSRRCI

ifdef::cheri_v9_annotations[]
NOTE: *CHERI v9 Note:* CSpecialRW is removed and this functionality replaces it
endif::[]


Synopsis::
CSR access (CSRRWI, CSRRS, CSRRSI, CSRRC, CSRRCI) 32-bit encodings

Mnemonics for accessing capability CSRs in pass:attributes,quotes[{cheri_cap_mode_name}]::
`csrrs  cd, csr, rs1` +
`csrrc  cd, csr, rs1` +
`csrrwi cd, csr, imm` +
`csrrsi cd, csr, imm` +
`csrrci cd, csr, imm`

Mnemonics for accessing XLEN-wide CSRs or extended CSRs in pass:attributes,quotes[{cheri_int_mode_name}]::
`csrrs  rd, csr, rs1` +
`csrrc  rd, csr, rs1` +
`csrrwi rd, csr, imm` +
`csrrsi rd, csr, imm` +
`csrrci rd, csr, imm`

Encoding::
include::wavedrom/csr-instr.adoc[]

Description::
These are standard RISC-V CSR instructions with extended functionality for
accessing capability CSRs, such as <<mtvec>>/<<mtvecc>>.
+
For capability CSRs, the full capability is read into `cd` in pass:attributes,quotes[{cheri_cap_mode_name}].
In pass:attributes,quotes[{cheri_int_mode_name}], the address field is instead read into `rd`.
+
Unlike <<CSRRW>>, these instructions only update the address field and the tag
as defined in xref:extended_CSR_writing[xrefstyle=short] when writing
capability CSRs regardless of the execution mode. The final address to
write to the capability CSR is determined as defined by RISC-V for these
instructions.
+
See xref:aliased_CSRs[xrefstyle=short] for a list of capability CSRs and
xref:extended_CSR_writing[xrefstyle=short] for the action taken on writing an XLEN-wide value to each one.
+
If `cd` is `c0` (or `rd` is `x0`), then <<CSRRWI>> shall not read the CSR and
and shall not cause any of the side effects that might occur on a CSR read. If
`rs1` is `x0` for <<CSRRS>> and <<CSRRC>>, or `imm` is 0 for <<CSRRSI>> and
<<CSRRCI>>, then the instruction will not write to the CSR at all, and so shall
not cause any of the side effects that might otherwise occur on a CSR write.
+
The assembler pseudoinstruction to read a capability CSR in Capability Mode,
`csrr cd, csr`, is encoded as `csrrs cd, csr, x0`.
+
Access to XLEN-wide CSRs is as specified by RISC-V.

NOTE: If the CSR accessed is a capability, and `rs1` is `x0` for <<CSRRS>> and
<<CSRRC>>, or `imm` is 0 for <<CSRRSI>> and <<CSRRCI>>, then the CSR is not
written so no representability check is needed in this case.

Permissions::
Accessing privileged CSRs requires <<asr_perm>>, including existing RISC-V
CSRs, as described in xref:zicsr-section-purecap[xrefstyle=short]. The list of
privileged and unprivileged CSRs is shown in cite:[riscv-priv-spec].

Prerequisites for pass:attributes,quotes[{cheri_cap_mode_name}]::
{cheri_base_ext_name}

Prerequisites for pass:attributes,quotes[{cheri_int_mode_name}]::
{cheri_default_ext_name}

Operation::
[source,SAIL,subs="verbatim,quotes"]
--
TBD
--
