<<<
//[#insns-csrr-32bit,reftext="CSR access (CSRRW[I], CSRRS[I], CSRRC[I]), 32-bit encoding"]

[#CSRRW,reftext="CSRRW"]
==== CSRRW

ifdef::cheri_v9_annotations[]
NOTE: *CHERI v9 Note:* CSpecialRW is removed and this functionality replaces it
endif::[]


Synopsis::
CSR access (CSRRW) 32-bit encodings

Mnemonic for accessing capability CSRs in pass:attributes,quotes[{cheri_cap_mode_name}]::
`csrrw cd, csr, cs1`

Mnemonic for accessing XLEN-wide CSRs or extended CSRs in pass:attributes,quotes[{cheri_int_mode_name}]::
`csrrw rd, csr, rs1`

Encoding::
include::wavedrom/csrw-instr.adoc[]

Description::
This is a standard RISC-V CSR instructions with extended functionality for
accessing CLEN-wide CSRs, such as <<mtvec>>/<<mtvecc>>.
+
See xref:aliased_CSRs[xrefstyle=short] for a list of CLEN-wide CSRs and
xref:extended_CSR_writing[xrefstyle=short] for the action taken on writing each one.
+
CSRRW writes `cs1` to extended CSRs in pass:attributes,quotes[{cheri_cap_mode_name}], and reads a full capability into `cd`.
+
CSRRW writes `rs1` to extended CSRs in pass:attributes,quotes[{cheri_int_mode_name}], and reads the address field into `rd`.
+
If `cd` is `c0` (or `rd` is `x0`), then the instruction shall not read the CSR
and shall not cause any of the side effects that might occur on a CSR read.
+
The assembler pseudo-instruction to write a capability CSR in pass:attributes,quotes[{cheri_cap_mode_name}],
`csrw csr, cs1`, is encoded as `csrrw c0, csr, cs1`.
+
Access to XLEN-wide CSRs from other extensions is as specified by RISC-V.

NOTE: When writing `cs1`, if the bounds are <<section_cap_malformed,malformed>>, any reserved bits are set
or the permission could not have been produced by <<ACPERM>> then clear the tag before writing to the CSR.

Permissions::
Accessing privileged CSRs require <<asr_perm>>, including existing RISC-V CSRs,
as described in xref:zicsr-section-purecap[xrefstyle=short]. The list of
privileged and unprivileged CSRs is shown in cite:[riscv-priv-spec].

Prerequisites for pass:attributes,quotes[{cheri_cap_mode_name}]::
{cheri_base_ext_name}

Prerequisites for pass:attributes,quotes[{cheri_int_mode_name}]::
{cheri_default_ext_name}

Operation::
[source,SAIL,subs="verbatim,quotes"]
--
TBD
--
