<<<
//[#insns-cvlce_ew,reftext="Vector load capability (CVLCE<EW>.V, VLCE<EW>.V)"]

[#CVLCE_EW_V,reftext="CVLCE<EW>.V"]
==== CVLCE<EW>.V

See <<VLCE<EW>.V>>.

[#VLCE_EW_V,reftext="VLCE<EW>.V"]
==== VLCE<EW>.V

Synopsis::
Vector load capability

pass:attributes,quotes[{cheri_cap_mode_name}] Mnemonics::
`cvlce<ew>.v vd, (cs1)`

pass:attributes,quotes[{cheri_int_mode_name}] Mnemonics::
`vlce<ew>.v vd, (rs1)`

Encoding::
include::wavedrom/cvlce_ew.adoc[]

Description::
Vector load, supporting CHERI capabilities.
+
The base address (`cs1`/`rs1`) is required to be `CLEN`-aligned, if it is a not, a load address misaligned exception occurs.
+
Other than the support for CHERI capabilities, these instructions operate in the same way as the corresponding
vector unit-stride load instruction. For each *complete* `CLEN`-bit subdivision of the destination that is
loaded, the associated tag bit is updated with the tag bit that is read from memory.
If (`vl` * `EEW`) is not a multiple of `CLEN` then the last `CLEN`-bit subdivision of
the destination that is updated with data from memory (which will be incomplete) has its associated tag bit
cleared.
+
Traps on these instructions will always be reported with a value of `vstart` that is a multiple of `CLEN` / `EEW`,
and will raise an illegal instruction exception if `vstart` does not meet this condition.
+
Implementations only provide the instructions dealing with the element widths they support. Instruction
encodings for unsupported element widths are reserved.

include::load_exceptions.adoc[]

Prerequisites for pass:attributes,quotes[{cheri_cap_mode_name}]::
{cheri_base_ext_name}, V, {cheri_vectorcap_ext_name}

Prerequisites for pass:attributes,quotes[{cheri_int_mode_name}]::
{cheri_base_ext_name}, V, {cheri_vectorcap_ext_name}

pass:attributes,quotes[{cheri_cap_mode_name}] Operation::
[source,SAIL,subs="verbatim,quotes"]
--
TBD
--

pass:attributes,quotes[{cheri_int_mode_name}] Operation::
--
TBD
--
