<<<
//[#insns-cvsce_ew,reftext="Vector store capability (CVLCE<EW>.V, VLCE<EW>.V)"]

[#CVSCE_EW_V,reftext="CVSCE<EW>.V"]
==== CVSCE<EW>.V

See <<VSCE<EW>.V>>.

[#VSCE_EW_V,reftext="VSCE<EW>.V"]
==== VSCE<EW>.V

Synopsis::
Vector store capability

pass:attributes,quotes[{cheri_cap_mode_name}] Mnemonics::
`...`

pass:attributes,quotes[{cheri_int_mode_name}] Mnemonics::
`...`

Encoding::
include::wavedrom/cvsce_ew.adoc[]

Description::
Vector store, supporting CHERI capabilities.
+
The base address (`cs1`/`rs1`) is required to be `CLEN`-aligned, if it is not, a store/AMO address misaligned exception occurs.
+
Other than the support for CHERI capabilities, these instructions operate in the same way as the corresponding
vector unit-stride load instruction. For each *complete* `CLEN`-bit subdivision of the source
that is stored, the associated tag bit is written to memory along with the data.
If (`vl` * `EEW`) is not a multiple of `CLEN` then the tag that is written to memory
along with the data from the last `CLEN`-bit subdivision of the source (which only partially be written)
has the value zero
(the tag bit associated with that `CLEN`-bit subdivision of the source vector
register group is ignored, but remains unmodified).
+
Traps on these instructions will always be reported with a value of `vstart` that is a multiple of `CLEN` / `EEW`,
and will raise an illegal instruction exception if `vstart` does not meet this condition.
+
Implementations only provide the instructions dealing with the element widths they support. Instruction
encodings for unsupported element widths are reserved.

include::store_exceptions.adoc[]

Prerequisites for pass:attributes,quotes[{cheri_cap_mode_name}]::
{cheri_base_ext_name}, V, {cheri_vectorcap_ext_name}

Prerequisites for pass:attributes,quotes[{cheri_int_mode_name}]::
{cheri_base_ext_name}, V, {cheri_vectorcap_ext_name}

pass:attributes,quotes[{cheri_cap_mode_name}] Operation::
[source,SAIL,subs="verbatim,quotes"]
--
TBD
--

pass:attributes,quotes[{cheri_int_mode_name}] Operation::
--
TBD
--
