<<<

[#HLVX_HU,reftext="HLVX.HU"]
==== HLVX.HU

See <<HLVX_WU>>.

<<<

[#HLVX_WU,reftext="HLVX.WU"]
==== HLVX.WU

Synopsis::
Hypervisor virtual machine load from executable memory

pass:attributes,quotes[{cheri_cap_mode_name}] Mnemonics::
`hlv.hu rd, cs1` +
`hlv.wu rd, cs1`

pass:attributes,quotes[{cheri_int_mode_name}] Mnemonics::
`hlv.hu rd, rs1` +
`hlv.wu rd, rs1`

Encoding::
include::wavedrom/hypv-virt-loadx.adoc[]

pass:attributes,quotes[{cheri_cap_mode_name}] Description::
Performs a load with the *execute* permission taking the place of *read*
permission during address translation and as though V=1; i.e., with the address
translation and protection, and endianness, that apply to memory access in
either VS-mode or VU-mode. The effective address is the address of `cs1`. The
authorising capability for the operation is `cs1`. A copy of the loaded value
is written to `rd`.

pass:attributes,quotes[{cheri_int_mode_name}] Description::
Performs a load with the *execute* permission taking the place of *read*
permission during address translation and as though V=1; i.e., with the address
translation and protection, and endianness, that apply to memory access in
either VS-mode or VU-mode. The effective address is `rs1`. The authorising
capability for the operation is <<ddc>>. A copy of the loaded value is written
to `rd`.

Exceptions::
CHERI fault exception when the authorising capability fails one of the checks
listed below; in this case, _CHERI data fault_ is reported in the <<mtval>> or
<<stval>> TYPE field and the corresponding code is written to CAUSE.
+
[%autowidth,options=header,align=center]
|==============================================================================
| CAUSE                      | Reason
| Tag violation              | Authority capability tag set to 0, or has any reserved bits set
| Seal violation             | Authority capability is sealed
| Permission violation       | Authority capability does not grant <<r_perm>> or <<x_perm>>, or the AP field could not have been produced by <<ACPERM>>
| Invalid address violation  | The effective address is invalid according to xref:section_invalid_addr_conv[xrefstyle=short]
| Length violation           | At least one byte accessed is outside the authority capability bounds, or the capability has <<section_cap_malformed,malformed>> bounds
|==============================================================================

Prerequisites for pass:attributes,quotes[{cheri_cap_mode_name}]::
{cheri_base_ext_name}, H

Prerequisites for pass:attributes,quotes[{cheri_int_mode_name}]::
{cheri_base_ext_name}, {cheri_default_ext_name}, H

pass:attributes,quotes[{cheri_cap_mode_name}] Operation::
+
--
TBD
--

pass:attributes,quotes[{cheri_int_mode_name}] Operation::
+
--
TBD
--
