<<<

[#HSV_B,reftext="HSV.B"]
==== HSV.B

See <<HSV_W>>.

[#HSV_H,reftext="HSV.H"]
==== HSV.H

See <<HSV_W>>.

[#HSV_D,reftext="HSV.D"]
==== HSV.D

See <<HSV_W>>.

<<<

[#HSV_W,reftext="HSV.W"]
==== HSV.W

Synopsis::
Hypervisor virtual-machine store

pass:attributes,quotes[{cheri_cap_mode_name}] Mnemonics (RV64)::
`hsv.b rs2, cs1` +
`hsv.h rs2, cs1` +
`hsv.w rs2, cs1` +
`hsv.d rs2, cs1`

pass:attributes,quotes[{cheri_int_mode_name}] Mnemonics (RV64)::
`hsv.b rs2, rs1` +
`hsv.h rs2, rs1` +
`hsv.w rs2, rs1` +
`hsv.d rs2, rs1`

pass:attributes,quotes[{cheri_cap_mode_name}] Mnemonics (RV32)::
`hsv.b rs2, cs1` +
`hsv.h rs2, cs1` +
`hsv.w rs2, cs1`

pass:attributes,quotes[{cheri_int_mode_name}] Mnemonics (RV32)::
`hsv.b rs2, rs1` +
`hsv.h rs2, rs1` +
`hsv.w rs2, rs1`

Encoding::
include::wavedrom/hypv-virt-store.adoc[]

pass:attributes,quotes[{cheri_cap_mode_name}] Description::
Performs a store as though V=1; i.e., with the address translation and
protection, and endianness, that apply to memory accesses in either VS-mode or
VU-mode. The effective address is the address of `cs1`. The authorising
capability for the operation is `cs1`. A copy of `rs2` is written to memory at
the location indicated by the effective address and the tag bit of each block
of memory naturally aligned to CLEN/8 is cleared.

pass:attributes,quotes[{cheri_int_mode_name}] Description::
Performs a store as though V=1; i.e., with address translation and protection,
and endianness, that apply to memory accesses in either VS-mode or VU-mode. The
effective address is `rs1`. The authorising capability for the operation is
<<ddc>>. A copy of `rs2` is written to memory at the location indicated by the
effective address and the tag bit of each block of memory naturally aligned to
CLEN/8 is cleared.

include::store_exceptions.adoc[]

Prerequisites for pass:attributes,quotes[{cheri_cap_mode_name}] HSV.B, HSV.H, HSV.W::
{cheri_base_ext_name}, H

Prerequisites for pass:attributes,quotes[{cheri_int_mode_name}] HSV.B, HSV.H, HSV.W::
{cheri_base_ext_name}, {cheri_default_ext_name} H

Prerequisites for pass:attributes,quotes[{cheri_cap_mode_name}] HSV.D::
RV64, {cheri_base_ext_name}, H

Prerequisites for pass:attributes,quotes[{cheri_int_mode_name}] HSV.D::
RV64, {cheri_base_ext_name}, {cheri_default_ext_name} H

pass:attributes,quotes[{cheri_cap_mode_name}] Operation::
+
--
TBD
--

pass:attributes,quotes[{cheri_int_mode_name}] Operation::
+
--
TBD
--
