<<<

[#HLV_C,reftext="HLV.C"]
==== HLV.C

Synopsis::
Hypervisor virtual-machine load capability

pass:attributes,quotes[{cheri_cap_mode_name}] Mnemonic::
`hlv.c cd, cs1`

pass:attributes,quotes[{cheri_int_mode_name}] Mnemonic::
`hlv.c cd, rs1`

Encoding::
include::wavedrom/hypv-virt-load-cap.adoc[]

pass:attributes,quotes[{cheri_cap_mode_name}] Description::
Load a CLEN+1 bit value from memory as though V=1; i.e., with the address
translation and protection, and endianness, that apply to memory accesses in
either VS-mode or VU-mode. The effective address is the address of `cs1`. The
authorising capability for the operation is `cs1`. A copy of the loaded value
is written to `cd`. The tag value written to `cd` is 0 if the tag of the memory
location loaded is 0 or `cs1` does not grant <<c_perm>>.

pass:attributes,quotes[{cheri_int_mode_name}] Description::
Load a CLEN+1 bit value from memory as though V=1; i.e., with the address
translation and protection, and endianness, that apply to memory accesses in
either VS-mode and VU-mode. The effective address is `rs1`. The authorising
capability for the operation is <<ddc>>. A copy of the loaded value is written
to `cd`. The tag value written to `cd` is 0 if the tag of the memory location
loaded is 0 or `cs1` does not grant <<c_perm>>.

include::malformed_no_check.adoc[]

:has_cap_data:
include::load_exceptions.adoc[]
+
include::require_cre.adoc[]

Prerequisites for pass:attributes,quotes[{cheri_cap_mode_name}]::
{cheri_base_ext_name}, H

Prerequisites for pass:attributes,quotes[{cheri_int_mode_name}]::
{cheri_base_ext_name}, {cheri_default_ext_name}, H

pass:attributes,quotes[{cheri_cap_mode_name}] Operation::
+
--
TBD
--

pass:attributes,quotes[{cheri_int_mode_name}] Operation::
+
--
TBD
--
