<<<

[#J,reftext="J"]
==== J

Expands to <<JAL>> following the expansion rule from cite:[riscv-unpriv-spec].

[#JAL,reftext="JAL"]
==== JAL

Synopsis::
Jump and link

pass:attributes,quotes[{cheri_cap_mode_name}] Mnemonic::
`jal cd, offset`

pass:attributes,quotes[{cheri_int_mode_name}] Mnemonic::
`jal rd, offset`

Encoding::
include::wavedrom/ct-unconditional.adoc[]

pass:attributes,quotes[{cheri_cap_mode_name}] Description::
JAL's immediate encodes a signed offset in multiple of 2 bytes. The <<pcc>> is
incremented by the sign-extended offset to form the jump target capability. The
target capability is written to <<pcc>>. The <<pcc>> of the next instruction
following the jump is sealed and written to `cd`.

pass:attributes,quotes[{cheri_int_mode_name}] Description::
JAL's immediate encodes a signed offset in multiple of 2 bytes. The
sign-extended offset is added to the <<pcc>>'s address to form the target
address which is written to the <<pcc>>'s address field. The address of the
instruction following the jump is written to `rd`.

Exceptions::
[%autowidth,options=header,align=center]
|==============================================================================
| CAUSE                      | pass:attributes,quotes[{cheri_int_mode_name}] | pass:attributes,quotes[{cheri_cap_mode_name}] | Reason
| Invalid address violation  | ✔    | ✔     | The target address is invalid according to xref:section_invalid_addr_conv[xrefstyle=short]
| Length violation           | ✔    | ✔     | Minimum length instruction is not within the target capability's bounds.
|==============================================================================

include::pcrel_debug_warning.adoc[]

Prerequisites for pass:attributes,quotes[{cheri_cap_mode_name}]::
{cheri_base_ext_name}

Prerequisites for pass:attributes,quotes[{cheri_int_mode_name}]::
{cheri_default_ext_name}

Operation::
+
--
TODO
--
