<<<

[#C_JAL,reftext="C.JAL"]
==== C.JAL

Synopsis::
Jump with link, 16-bit encodings

pass:attributes,quotes[{cheri_cap_mode_name}] Mnemonic (RV32)::
`c.jal c1, offset`

pass:attributes,quotes[{cheri_cap_mode_name}] Expansion (RV32)::
`jal c1, offset`

pass:attributes,quotes[{cheri_int_mode_name}] Mnemonic (RV32)::
`c.jal x1, offset`

pass:attributes,quotes[{cheri_int_mode_name}] Expansion (RV32)::
`jal x1, offset`

Encoding (RV32)::
include::wavedrom/c-jal-format-ls.adoc[]

pass:attributes,quotes[{cheri_cap_mode_name}] Description::
Link the next linear <<pcc>> to `cd` and seal. Jump to <<pcc>>.address+offset.

pass:attributes,quotes[{cheri_int_mode_name}] Description::
Set the next PC and link to `rd` according to the standard <<JAL>> definition.

Exceptions::
See <<JAL>>

include::pcrel_debug_warning.adoc[]

Prerequisites for pass:attributes,quotes[{cheri_cap_mode_name}]::
{c_cheri_base_ext_names}

Prerequisites for pass:attributes,quotes[{cheri_int_mode_name}]::
{c_cheri_default_ext_names}

Operation (after expansion to 32-bit encodings)::
 See <<JAL>>
