<<<

[#JALR_MODE,reftext="JALR.MODE"]
==== JALR.MODE

ifdef::cheri_v9_annotations[]
NOTE: *CHERI v9 Note:* This instruction used to have separate encodings in
CHERI v9 for each mode. The behaviour depends on the CHERI execution mode and now
only use a single *new* encoding.
endif::[]

Synopsis::
Indirect jump and link (via integer address or capability)

Capability Mode Mnemonic::
`jalr.mode rd, rs1`

Legacy Mode Mnemonic::
`jalr.mode cd, cs1`

Suggested assembly syntax::
`jalr rd, 0(rs1)` +
`jalr cd, 0(cs1)` +

NOTE: the suggested assembly syntax distinguishes from `jalr` by operand type.

Encoding::
include::wavedrom/ct-unconditional-jalr-cap.adoc[]

Capability Mode Description::
JALR.MODE allows unconditional jumps to a target integer address. The target
address in `rs1` is installed in the address field of the <<pcc>>. The address
of the instruction following the jump (<<pcc>> + 4) is written to `rd`.
This is identical to the legacy mode <<JALR>> instruction, but with zero offset.

Legacy Mode Description::
JALR.MODE allows unconditional jumps to a target capability. The capability in
`cs1` is installed in <<pcc>>. The <<pcc>> of the next instruction following
the jump (<<pcc>> + 4) is sealed and written to `cd`. This instruction can be
used to change the current CHERI execution mode and is identical to
<<JALR>> in capability mode but with zero offset.

Exception::
When these instructions cause CHERI exceptions, _CHERI jump or
branch_ fault is reported in the TYPE field and the following codes may be
reported in the CAUSE field of <<mtval>> or <<stval>>:

[%autowidth,options=header,align=center]
|==============================================================================
| CAUSE                 | Legacy Mode | Capability Mode| Reason
| Tag violation         |          | ✔       | `cs1` has tag set to 0
| Seal violation        |          | ✔       | `cs1` is sealed and the immediate is not 0
| Permission violation  |          | ✔       | `cs1` does not grant <<x_perm>>
| Length violation      | ✔        | ✔       | Minimum length instruction is not within the target capability's bounds
|==============================================================================

include::pcrel_debug_warning.adoc[]

Prerequisites for Capability Mode::
 {cheri_base_ext_name}

Prerequisites Legacy Mode::
 {cheri_legacy_ext_name}

Operation::
+
--
TODO
--
