<<<

[#JR,reftext="JR"]
==== JR

Expands to <<JALR>> following the expansion rule from cite:[riscv-unpriv-spec].

[#JALR,reftext="JALR"]
==== JALR

Synopsis::
Jump and link register

pass:attributes,quotes[{cheri_cap_mode_name}] Mnemonic::
`jalr cd, cs1, offset`

pass:attributes,quotes[{cheri_int_mode_name}] Mnemonic::
`jalr rd, rs1, offset`

Encoding::
include::wavedrom/ct-unconditional-2.adoc[]

pass:attributes,quotes[{cheri_cap_mode_name}] Description::
JALR allows unconditional, indirect jumps to a target capability. The
target capability is unsealed if the `offset` is zero.
The target address is obtained by adding the sign-extended 12-bit
`offset` to `cs1.address`, then setting the
least-significant bit of the result to zero.
The target capability may have
xref:section_invalid_addr_conv[xrefstyle=short]
performed and is then installed in <<pcc>>. The <<pcc>>
of the next instruction following the jump is sealed and written
to `cd`.

pass:attributes,quotes[{cheri_int_mode_name}] Description::
JALR allows unconditional, indirect jumps to a target address. The target
address is obtained by adding the sign-extended 12-bit immediate to `rs1`, then
setting the least-significant bit of the result to zero. The target address
is installed in the address field of the <<pcc>> which may require
xref:section_invalid_addr_conv[xrefstyle=short].
The address of the
instruction following the jump is written to `rd`.

Exceptions::
When these instructions cause CHERI exceptions, _CHERI jump or branch fault_
is reported in the TYPE field and the following codes may be
reported in the CAUSE field of <<mtval>> or <<stval>>:

[%autowidth,options=header,align=center]
|==============================================================================
| CAUSE                 | pass:attributes,quotes[{cheri_int_mode_name}] | pass:attributes,quotes[{cheri_cap_mode_name}] | Reason
| Tag violation         |      | ✔     | `cs1` has tag set to 0, or has any reserved bits set
| Seal violation        |      | ✔     | `cs1` is sealed and the immediate is not 0
| Permission violation  |      | ✔     | `cs1` does not grant <<x_perm>>, or the AP field could not have been produced by <<ACPERM>>
| Invalid address violation  | ✔    | ✔     | The target address is invalid according to xref:section_invalid_addr_conv[xrefstyle=short]
| Length violation      | ✔    | ✔     | Minimum length instruction is not within the target capability's bounds, which will fail
if `cs1` has <<section_cap_malformed,malformed>> bounds in pass:attributes,quotes[{cheri_cap_mode_name}].
|==============================================================================

include::pcrel_debug_warning.adoc[]

Prerequisites pass:attributes,quotes[{cheri_cap_mode_name}]::
{cheri_base_ext_name}

Prerequisites pass:attributes,quotes[{cheri_int_mode_name}]::
{cheri_default_ext_name}

Operation::
+
--
TBD
--
