<<<

[#C_JALR,reftext="C.JALR"]
==== C.JALR

Synopsis::
Jump register with link, 16-bit encodings

pass:attributes,quotes[{cheri_cap_mode_name}] Mnemonic::
`c.jalr c1, cs1`

pass:attributes,quotes[{cheri_cap_mode_name}] Expansion::
`jalr c1, 0(cs1)`

pass:attributes,quotes[{cheri_int_mode_name}] Mnemonic::
`c.jalr x1, rs1`

pass:attributes,quotes[{cheri_int_mode_name}] Expansion::
`jalr x1, 0(rs1)`

Encoding::
include::wavedrom/c-jalr-format-ls.adoc[]

pass:attributes,quotes[{cheri_cap_mode_name}] Description::
See <<JALR>> for execution of the expanded instruction as shown above.
Note that the `offset` is zero in the expansion.

pass:attributes,quotes[{cheri_int_mode_name}] Description::
See <<JALR>> for execution of the expanded instruction as shown above.
Note that the `offset` is zero in the expansion.

Exceptions::
See <<JALR>>

include::pcrel_debug_warning.adoc[]

Prerequisites for pass:attributes,quotes[{cheri_cap_mode_name}]::
{c_cheri_base_ext_names}

Prerequisites for pass:attributes,quotes[{cheri_int_mode_name}]::
{c_cheri_default_ext_names}

Operation (after expansion to 32-bit encodings)::
 See <<JALR>>
