<<<

[#C_JR,reftext="C.JR"]
==== C.JR

Synopsis::
Jump register without link, 16-bit encodings

pass:attributes,quotes[{cheri_cap_mode_name}] Mnemonic::
`c.jr cs1`

pass:attributes,quotes[{cheri_cap_mode_name}] Expansion::
`jalr c0, 0(cs1)`

pass:attributes,quotes[{cheri_int_mode_name}] Mnemonic::
`c.jr rs1`

pass:attributes,quotes[{cheri_int_mode_name}] Expansion::
`jalr x0, 0(rs1)`

Encoding::
include::wavedrom/c-cr-format-ls.adoc[]

pass:attributes,quotes[{cheri_cap_mode_name}] Description::
See <<JALR>> for execution of the expanded instruction as shown above.
Note that the `offset` is zero in the expansion.

pass:attributes,quotes[{cheri_int_mode_name}] Description::
See <<JALR>> for execution of the expanded instruction as shown above.
Note that the `offset` is zero in the expansion.

Exceptions::
See <<JALR>>

include::pcrel_debug_warning.adoc[]

Prerequisites for pass:attributes,quotes[{cheri_cap_mode_name}]::
{c_cheri_base_ext_names}

Prerequisites for pass:attributes,quotes[{cheri_int_mode_name}]::
{c_cheri_default_ext_names}

Operation (after expansion to 32-bit encodings)::
 See <<JALR>>
