<<<
//[#insns-load-res-cap-32bit,reftext="Load Reserved (CLR.C, LR.C), 32-bit encodings"]

[#LR_C,reftext="LR.C"]
==== LR.C

NOTE: The RV64 encoding is intended to also allocate the encoding for LR.Q for RV128.

Synopsis::
Load Reserved Capability (LR.C), 32-bit encodings

include::xlen_variable_warning.adoc[]

Capability Mode Mnemonics::
`lr.c cd, 0(cs1)`

Legacy Mode Mnemonics::
`lr.c cd, 0(rs1)`

Encoding::
include::wavedrom/load_res_cap.adoc[]

Capability Mode Description::
Load reserved instructions, authorised by the capability in `cs1`.
 All misaligned load reservations cause a load address misaligned exception to allow software emulation (Zam extension, see cite:[riscv-unpriv-spec]).

Legacy Mode Description::
Load reserved instructions, authorised by the capability in <<ddc>>.
 All misaligned load reservations cause a load address misaligned exception to allow software emulation (Zam extension, see cite:[riscv-unpriv-spec]).

:cap_load:

include::load_exceptions.adoc[]
+
include::require_cre.adoc[]

Prerequisites for Capability Mode::
{cheri_base_ext_name}, and A

Prerequisites for Legacy Mode::
{cheri_legacy_ext_name}, and A

Operation::
[source,SAIL,subs="verbatim,quotes"]
--
TBD
--
