<<<

[#LR_D,reftext="LR.D"]
==== LR.D
See <<LR.B>>.

[#LR_W,reftext="LR.W"]
==== LR.W
See <<LR.B>>.

[#LR_H,reftext="LR.H"]
==== LR.H
See <<LR.B>>.

<<<

[#LR_B,reftext="LR.B"]
==== LR.B

Synopsis::
Load Reserved (LR.D, LR.W, LR.H, LR.B), 32-bit encodings

Capability Mode Mnemonics (RV64)::
`lr.[d|w|h|b] rd, 0(cs1)`

Capability Mode Mnemonics (RV32)::
`lr.[w|h|b] rd, 0(cs1)`

Hybrid Mode Mnemonics (RV64)::
`lr.[d|w|h|b] rd, 0(rs1)`

Hybrid Mode Mnemonics (RV32)::
`lr.[w|h|b] rd, 0(rs1)`

Encoding::
include::wavedrom/load_res.adoc[]

Capability Mode Description::
Load reserved instructions, authorised by the capability in `cs1`.

Hybrid Mode Description::
Load reserved instructions, authorised by the capability in <<ddc>>.

:load_res:

include::load_exceptions.adoc[]

Prerequisites for Capability Mode LR.D::
RV64, {cheri_base_ext_name}, and A

Prerequisites for Capability Mode LR.W::
{cheri_base_ext_name}, and A

Prerequisites for Capability Mode LR.H, LR.B::
{lr_sc_bh_ext_name}, and {cheri_base_ext_name}

Prerequisites for LR.D::
RV64, {cheri_hybrid_ext_name}, and A

Prerequisites for LR.W::
{cheri_hybrid_ext_name}, and A

Prerequisites for LR.H, LR.B::
{lr_sc_bh_ext_name}, {cheri_hybrid_ext_name}


Operation::
[source,SAIL,subs="verbatim,quotes"]
--
TBD
--
