<<<

[#C_LWSP,reftext="C.LWSP"]
==== C.LWSP

See <<C_LDSP>>.

<<<

[#C_LDSP,reftext="C.LDSP"]
==== C.LDSP

Synopsis::
Load (C.LWSP, C.LDSP), 16-bit encodings

Capability Mode Mnemonics (RV64)::
`c.ld/c.lw rd, offset(csp)`

Capability Mode Expansions (RV64)::
`ld/lw rd, offset(csp)`

Legacy Mode Mnemonics (RV64)::
`c.ld/c.lw rd, offset(sp)`

Legacy Mode Expansions (RV64)::
`ld/lw rd, offset(sp)`

Capability Mode Mnemonics (RV32)::
`c.lw rd, offset(csp)`

Capability Mode Expansions (RV32)::
`lw rd, offset(csp)`

Legacy Mode Mnemonics (RV32)::
`c.lw rd, offset(sp)`

Legacy Mode Expansions (RV32)::
`lw rd, offset(sp)`

Encoding::
include::wavedrom/c-sp-load-store.adoc[]

Capability Mode Description::
Standard stack pointer relative load instructions, authorised by the capability in `csp`.

Legacy Mode Description::
Standard stack pointer relative load instructions, authorised by the capability in <<ddc>>.

include::load_exceptions.adoc[]

Prerequisites for Capability Mode C.LDSP::
RV64, and {c_cheri_base_ext_names}

Prerequisites for Legacy Mode C.LDSP::
RV64, and {c_cheri_legacy_ext_names}

Prerequisites for Capability Mode C.LWSP::
{c_cheri_base_ext_names}

Prerequisites for Legacy Mode C.LWSP::
{c_cheri_legacy_ext_names}

Operation (after expansion to 32-bit encodings)::
 See <<LW>>, <<LD>>
