<<<
[#C_FLD,reftext="C.FLD"]
==== C.FLD

[#C_FLDSP,reftext="C.FLDSP"]
==== C.FLDSP

Synopsis::
Double precision floating point loads (C.FLD, C.FLDSP), 16-bit encodings

Capability Mode Mnemonics (RV32)::
`c.fld frd', offset(cs1'/csp)`

Capability Mode Expansions (RV32)::
`fld frd', offset(csp)`

Default Mode Mnemonics::
`c.fld fs2, offset(rs1'/sp)`

Default Mode Expansions::
`fld fs2, offset(rs1'/sp)`

Encoding::
include::wavedrom/c-sp-load-css-dp.adoc[]
include::wavedrom/c-sp-load-css-dp-sprel.adoc[]

Default Mode Description::
Standard floating point stack pointer relative load instructions, authorised by the capability in <<ddc>>. Note that these instructions are not available in Capability Mode, as they have been remapped to <<C.LC>>, <<C.LCSP>>.

include::load_exceptions.adoc[]

Prerequisites for Capability Mode (RV32 only)::
{cheri_base_ext_name}, C and D; or +
{cheri_base_ext_name}, Zca and Zcd

Prerequisites for Default Mode::
{cheri_legacy_ext_name}, C and D; or +
{cheri_legacy_ext_name}, Zca and Zcd

Operation (after expansion to 32-bit encodings)::
 See <<FLD>>
