<<<

[#C_LWSP,reftext="C.LWSP"]
==== C.LWSP

See <<C_LDSP>>.

[#C_LDSP,reftext="C.LDSP"]
==== C.LDSP

Synopsis::
Load (C.LWSP, C.LDSP), 16-bit encodings

{cheri_cap_mode_name} Mnemonics::
`c.ld/c.lw rd, offset(csp)`

{cheri_cap_mode_name} Expansions::
`ld/lw rd, offset(csp)`

{cheri_int_mode_name} Mnemonics::
`c.ld/c.lw rd, offset(sp)`

{cheri_int_mode_name} Expansions::
`ld/lw rd, offset(sp)`

Encoding::
include::wavedrom/c-sp-load-store.adoc[]

{cheri_cap_mode_name} Description::
Standard stack pointer relative load instructions, authorized by the capability in `csp`.

{cheri_int_mode_name} Description::
Standard stack pointer relative load instructions, authorized by the capability in <<ddc>>.

include::load_exceptions.adoc[]

Prerequisites for {cheri_cap_mode_name} C.LDSP::
RV64 or RV32 and Zclsd, and {c_cheri_base_ext_names}

Prerequisites for {cheri_int_mode_name} C.LDSP::
RV64 or RV32 and Zclsd, and {c_cheri_default_ext_names}

Prerequisites for {cheri_cap_mode_name} C.LWSP::
{c_cheri_base_ext_names}

Prerequisites for {cheri_int_mode_name} C.LWSP::
{c_cheri_default_ext_names}

Operation (after expansion to 32-bit encodings)::
 See <<LW>>, <<LD>>
