<<<

[#LR_C,reftext="LR.C"]
==== LR.C

NOTE: The RV64 encoding is intended to also allocate the encoding for LR.Q for RV128.

Synopsis::
Load Reserved Capability (LR.C), 32-bit encodings

include::xlen_variable_warning.adoc[]

pass:attributes,quotes[{cheri_cap_mode_name}] Mnemonic::
`lr.c cd, 0(cs1)`

pass:attributes,quotes[{cheri_int_mode_name}] Mnemonic::
`lr.c cd, 0(rs1)`

Encoding::
include::wavedrom/load_res_cap.adoc[]

pass:attributes,quotes[{cheri_cap_mode_name}] Description::
Load reserved instructions, authorised by the capability in `cs1`.
 All misaligned load reservations cause a load address misaligned exception to allow software emulation (Zam extension, see cite:[riscv-unpriv-spec]).

pass:attributes,quotes[{cheri_int_mode_name}] Description::
Load reserved instructions, authorised by the capability in <<ddc>>.
 All misaligned load reservations cause a load address misaligned exception to allow software emulation (Zam extension, see cite:[riscv-unpriv-spec]).

:cap_load:

include::malformed_no_check.adoc[]

include::load_exceptions.adoc[]
+
include::require_cre.adoc[]

Prerequisites for pass:attributes,quotes[{cheri_cap_mode_name}]::
{cheri_base_ext_name}, and A

Prerequisites for pass:attributes,quotes[{cheri_int_mode_name}]::
{cheri_default_ext_name}, and A

Operation::
[source,SAIL,subs="verbatim,quotes"]
--
TBD
--
