<<<
[#C_FLD,reftext="C.FLD"]
==== C.FLD

See <<C.FLDSP>>

[#C_FLDSP,reftext="C.FLDSP"]
==== C.FLDSP

Synopsis::
Double precision floating point loads (C.FLD, C.FLDSP), 16-bit encodings

pass:attributes,quotes[{cheri_cap_mode_name}] Mnemonic (RV32)::
`c.fld frd', offset(cs1'/csp)`

pass:attributes,quotes[{cheri_cap_mode_name}] Expansion (RV32)::
`fld frd', offset(csp)`

pass:attributes,quotes[{cheri_int_mode_name}] Mnemonic::
`c.fld fs2, offset(rs1'/sp)`

pass:attributes,quotes[{cheri_int_mode_name}] Expansion::
`fld fs2, offset(rs1'/sp)`

Encoding::
include::wavedrom/c-sp-load-css-dp.adoc[]
include::wavedrom/c-sp-load-css-dp-sprel.adoc[]

pass:attributes,quotes[{cheri_int_mode_name}] Description::
Standard floating point stack pointer relative load instructions, authorised by the capability in <<ddc>>.

NOTE: These instructions are available in RV64 pass:attributes,quotes[{cheri_int_mode_name}] only.
In RV64 pass:attributes,quotes[{cheri_cap_mode_name}] they are remapped to <<C.LC>>/<<C.LCSP>>.

NOTE: These encodings may be remapped by future code-size Zcm standard extensions, similar to <<Zcmp>> and <<Zcmt>>.
The rule is that in RV64 pass:attributes,quotes[{cheri_cap_mode_name}]
they are *always* remapped to <<C.SC>>/<<C.SCSP>>.

include::load_exceptions.adoc[]

Prerequisites for pass:attributes,quotes[{cheri_cap_mode_name}] (RV32 only)::
{cheri_base_ext_name}, C and D; or +
{cheri_base_ext_name}, Zca and Zcd

Prerequisites for pass:attributes,quotes[{cheri_int_mode_name}]::
{cheri_default_ext_name}, C and D; or +
{cheri_default_ext_name}, Zca and Zcd

Operation (after expansion to 32-bit encodings)::
 See <<FLD>>
