<<<
//[#insns-load-res-cap-32bit,reftext="Load Reserved (CLR.C, LR.C), 32-bit encodings"]

[#LR_C,reftext="LR.C"]
==== LR.C

See <<CLR.C>>.

[#CLR_C,reftext="CLR.C"]
==== CLR.C

NOTE: The RV64 encoding is intended to also allocate the encoding for LR.Q for RV128.

Synopsis::
Load Reserved (CLR.C, LR.C), 32-bit encodings

include::xlen_variable_warning.adoc[]

Capability Mode Mnemonics (RV64)::
`clr.c cd, 0(cs1)`

Capability Mode Mnemonics (RV32)::
`clr.c cd, 0(cs1)`

Legacy Mode Mnemonics (RV64)::
`lr.c cd, 0(rs1)`

Legacy Mode Mnemonics (RV32)::
`lr.c cd, 0(rs1)`

Encoding::
include::wavedrom/load_res_cap.adoc[]

Capability Mode Description::
Load reserved instructions, authorised by the capability in `cs1`.
 All misaligned load reservations cause a load address misaligned exception to allow software emulation (Zam extension, see cite:[riscv-unpriv-spec]).

Legacy Mode Description::
Load reserved instructions, authorised by the capability in <<ddc>>.
 All misaligned load reservations cause a load address misaligned exception to allow software emulation (Zam extension, see cite:[riscv-unpriv-spec]).

:cap_load:

include::load_exceptions.adoc[]

Prerequisites for CLR::
{cheri_base_ext_name}

Prerequisites for LR::
{cheri_legacy_ext_name}

Operation::
[source,SAIL,subs="verbatim,quotes"]
--
TBD
--
