<<<

[#LD,reftext="LD"]
==== LD

See <<LB>>.

[#LWU,reftext="LWU"]
==== LWU

See <<LB>>.

[#LW,reftext="LW"]
==== LW

See <<LB>>.

[#LHU,reftext="LHU"]
==== LHU

See <<LB>>.

[#LH,reftext="LH"]
==== LH

See <<LB>>.

[#LBU,reftext="LBU"]
==== LBU

See <<LB>>.

<<<

[#LB,reftext="LB"]
==== LB

Synopsis::
Load (LD, LW[U], LH[U], LB[U])

Capability Mode Mnemonics (RV64)::
`ld    rd, offset(cs1)` +
`lw[u] rd, offset(cs1)` +
`lh[u] rd, offset(cs1)` +
`lb[u] rd, offset(cs1)`

Legacy Mode Mnemonics (RV64)::
`ld    rd, offset(rs1)` +
`lw[u] rd, offset(rs1)` +
`lh[u] rd, offset(rs1)` +
`lb[u] rd, offset(rs1)`

Capability Mode Mnemonics (RV32)::
`lw    rd, offset(cs1)` +
`lh[u] rd, offset(cs1)` +
`lb[u] rd, offset(cs1)`

Legacy Mode Mnemonics (RV32)::
`lw    rd, offset(rs1)` +
`lh[u] rd, offset(rs1)` +
`lb[u] rd, offset(rs1)`

Encoding::
include::wavedrom/load.adoc[]

Capability Mode Description::
Load integer data of the indicated size (byte, halfword, word, double-word)
from memory. The effective address of the load is obtained by adding the
sign-extended 12-bit offset to the address of `cs1`. The authorising capability
for the operation is `cs1`. A copy of the loaded value is written to `rd`.

Legacy Mode Description::
Load integer data of the indicated size (byte, halfword, word, double-word)
from memory. The effective address of the load is obtained by adding the
sign-extended 12-bit offset to `rs1`. The authorising capability for the
operation is <<ddc>>. A copy of the loaded value is written to `rd`.

include::load_exceptions.adoc[]

Prerequisites for Capability Mode LD::
RV64, {cheri_base_ext_name}

Prerequisites for Legacy Mode LD::
RV64, {cheri_legacy_ext_name}

Prerequisites for Capability Mode LW[U], LH[U], LB[U]::
{cheri_base_ext_name}, OR +
{cheri_legacy_ext_name}

Capability Mode Operation::
+
--
TBD
--

Legacy Mode Operation::
+
--
TODO
--
