<<<

[#C_LD,reftext="C.LD"]
==== C.LD
See <<C_LW>>.

<<<

[#C_LW,reftext="C.LW"]
==== C.LW

Synopsis::
Load (C.LD, C.LW), 16-bit encodings

Capability Mode Mnemonics (RV64)::
`c.ld/c.lw rd', offset(cs1')`

Capability Mode Expansions (RV64)::
`ld/lw rd', offset(cs1')`

Default Mode Mnemonics (RV64)::
`c.ld/c.lw rd', offset(rs1')`

Default Mode Expansions (RV64)::
`ld/lw rd', offset(rs1')`

Capability Mode Mnemonics (RV32)::
`c.lw rd', offset(cs1')`

Capability Mode Expansions (RV32)::
`lw rd', offset(cs1')`

Default Mode Mnemonics (RV32)::
`c.lw rd', offset(rs1')`

Default Mode Expansions (RV32)::
`lw rd', offset(rs1')`

Encoding::
include::wavedrom/reg-based-ldnstr.adoc[]

Capability Mode Description::
Standard load instructions, authorised by the capability in `cs1`.

Default Mode Description::
Standard load instructions, authorised by the capability in <<ddc>>.

include::load_exceptions.adoc[]

Prerequisites for Capability Mode C.LD::
RV64, and {c_cheri_base_ext_names}

Prerequisites for Default Mode C.LD::
RV64, {c_cheri_default_ext_names}

Prerequisites Capability Mode C.LW::
{c_cheri_base_ext_names}

Prerequisites Default Mode C.LW::
{c_cheri_default_ext_names}

Operation (after expansion to 32-bit encodings)::
 See <<LD>>, <<LW>>
