<<<

[#C_LH,reftext="C.LH"]
==== C.LH
See <<C.LBU>>.

[#C_LHU,reftext="C.LHU"]
==== C.LHU
See <<C.LBU>>.

<<<

[#C_LBU,reftext="C.LBU"]
==== C.LBU

Synopsis::
Load (C.LH, C.LHU, C.LBU), 16-bit encodings

pass:attributes,quotes[{cheri_cap_mode_name}] Mnemonics::
`c.lh  rd', offset(cs1')` +
`c.lhu rd', offset(cs1')` +
`c.lbu rd', offset(cs1')`

pass:attributes,quotes[{cheri_cap_mode_name}] Expansions::
`lh  rd, offset(cs1)` +
`lhu rd, offset(cs1)` +
`lbu rd, offset(cs1)`

pass:attributes,quotes[{cheri_int_mode_name}] Mnemonics::
`c.lh  rd', offset(rs1')` +
`c.lhu rd', offset(rs1')` +
`c.lbu rd', offset(rs1')`

pass:attributes,quotes[{cheri_int_mode_name}] Expansions::
`lh  rd, offset(rs1)` +
`lhu rd, offset(rs1)` +
`lbu rd, offset(rs1)`

Encoding::

include::wavedrom/reg-based-ldnstr-Zcb.adoc[]

pass:attributes,quotes[{cheri_cap_mode_name}] Description::
Subword load instructions, authorised by the capability in `cs1`.

pass:attributes,quotes[{cheri_int_mode_name}] Description::
Subword load instructions, authorised by the capability in <<ddc>>.

include::load_exceptions.adoc[]

Prerequisites for pass:attributes,quotes[{cheri_cap_mode_name}]::
{c_cheri_base_ext_names}, and Zcb

Prerequisites for pass:attributes,quotes[{cheri_int_mode_name}]::
{c_cheri_default_ext_names}, and Zcb

Operation (after expansion to 32-bit encodings)::
 See <<LHU>>, <<LH>>, <<LBU>>
