<<<

[#C_LWSP,reftext="C.LWSP"]
==== C.LWSP

See <<C_LDSP>>.

<<<

[#C_LDSP,reftext="C.LDSP"]
==== C.LDSP

Synopsis::
Load (C.LWSP, C.LDSP), 16-bit encodings

pass:attributes,quotes[{cheri_cap_mode_name}] Mnemonics (RV64)::
`c.ld/c.lw rd, offset(csp)`

pass:attributes,quotes[{cheri_cap_mode_name}] Expansions (RV64)::
`ld/lw rd, offset(csp)`

pass:attributes,quotes[{cheri_int_mode_name}] Mnemonics (RV64)::
`c.ld/c.lw rd, offset(sp)`

pass:attributes,quotes[{cheri_int_mode_name}] Expansions (RV64)::
`ld/lw rd, offset(sp)`

pass:attributes,quotes[{cheri_cap_mode_name}] Mnemonic (RV32)::
`c.lw rd, offset(csp)`

pass:attributes,quotes[{cheri_cap_mode_name}] Expansion (RV32)::
`lw rd, offset(csp)`

pass:attributes,quotes[{cheri_int_mode_name}] Mnemonic (RV32)::
`c.lw rd, offset(sp)`

pass:attributes,quotes[{cheri_int_mode_name}] Expansion (RV32)::
`lw rd, offset(sp)`

Encoding::
include::wavedrom/c-sp-load-store.adoc[]

pass:attributes,quotes[{cheri_cap_mode_name}] Description::
Standard stack pointer relative load instructions, authorised by the capability in `csp`.

pass:attributes,quotes[{cheri_int_mode_name}] Description::
Standard stack pointer relative load instructions, authorised by the capability in <<ddc>>.

include::load_exceptions.adoc[]

Prerequisites for pass:attributes,quotes[{cheri_cap_mode_name}] C.LDSP::
RV64, and {c_cheri_base_ext_names}

Prerequisites for pass:attributes,quotes[{cheri_int_mode_name}] C.LDSP::
RV64, and {c_cheri_default_ext_names}

Prerequisites for pass:attributes,quotes[{cheri_cap_mode_name}] C.LWSP::
{c_cheri_base_ext_names}

Prerequisites for pass:attributes,quotes[{cheri_int_mode_name}] C.LWSP::
{c_cheri_default_ext_names}

Operation (after expansion to 32-bit encodings)::
 See <<LW>>, <<LD>>
