<<<

[#C_LD,reftext="C.LD"]
==== C.LD
See <<C_LW>>.

<<<

[#C_LW,reftext="C.LW"]
==== C.LW

Synopsis::
Load (C.LD, C.LW), 16-bit encodings

pass:attributes,quotes[{cheri_cap_mode_name}] Mnemonics (RV64)::
`c.ld rd', offset(cs1')` +
`c.lw rd', offset(cs1')`

pass:attributes,quotes[{cheri_cap_mode_name}] Expansions (RV64)::
`ld rd', offset(cs1')` +
`lw rd', offset(cs1')`

pass:attributes,quotes[{cheri_int_mode_name}] Mnemonics (RV64)::
`c.ld rd', offset(rs1')` +
`c.lw rd', offset(rs1')`

pass:attributes,quotes[{cheri_int_mode_name}] Expansions (RV64)::
`ld rd', offset(rs1')` +
`lw rd', offset(rs1')`

pass:attributes,quotes[{cheri_cap_mode_name}] Mnemonic (RV32)::
`c.lw rd', offset(cs1')`

pass:attributes,quotes[{cheri_cap_mode_name}] Expansion (RV32)::
`lw rd', offset(cs1')`

pass:attributes,quotes[{cheri_int_mode_name}] Mnemonic (RV32)::
`c.lw rd', offset(rs1')`

pass:attributes,quotes[{cheri_int_mode_name}] Expansion (RV32)::
`lw rd', offset(rs1')`

Encoding::
include::wavedrom/reg-based-ldnstr.adoc[]

pass:attributes,quotes[{cheri_cap_mode_name}] Description::
Standard load instructions, authorised by the capability in `cs1`.

pass:attributes,quotes[{cheri_int_mode_name}] Description::
Standard load instructions, authorised by the capability in <<ddc>>.

include::load_exceptions.adoc[]

Prerequisites for pass:attributes,quotes[{cheri_cap_mode_name}] C.LD::
RV64, and {c_cheri_base_ext_names}

Prerequisites for pass:attributes,quotes[{cheri_int_mode_name}] C.LD::
RV64, {c_cheri_default_ext_names}

Prerequisites pass:attributes,quotes[{cheri_cap_mode_name}] C.LW::
{c_cheri_base_ext_names}

Prerequisites pass:attributes,quotes[{cheri_int_mode_name}] C.LW::
{c_cheri_default_ext_names}

Operation (after expansion to 32-bit encodings)::
 See <<LD>>, <<LW>>
