<<<
[#C_FLD,reftext="C.FLD"]
==== C.FLD

[#C_FLDSP,reftext="C.FLDSP"]
==== C.FLDSP

Synopsis::
Double precision floating point loads (C.FLD, C.FLDSP), 16-bit encodings

{cheri_cap_mode_name} Mnemonics (RV32)::
`c.fld frd', offset(cs1'/csp)`

{cheri_cap_mode_name} Expansions (RV32)::
`fld frd', offset(csp)`

{cheri_int_mode_name} Mnemonics::
`c.fld fs2, offset(rs1'/sp)`

{cheri_int_mode_name} Expansions::
`fld fs2, offset(rs1'/sp)`

Encoding::
include::wavedrom/c-sp-load-css-dp.adoc[]
include::wavedrom/c-sp-load-css-dp-sprel.adoc[]

{cheri_int_mode_name} Description::
Standard floating point stack pointer relative load instructions, authorised by the capability in <<ddc>>. Note that these instructions are not available in {cheri_cap_mode_name}, as they have been remapped to <<C.LC>>, <<C.LCSP>>.

include::load_exceptions.adoc[]

Prerequisites for {cheri_cap_mode_name} (RV32 only)::
{cheri_base_ext_name}, C and D; or +
{cheri_base_ext_name}, Zca and Zcd

Prerequisites for {cheri_int_mode_name}::
{cheri_default_ext_name}, C and D; or +
{cheri_default_ext_name}, Zca and Zcd

Operation (after expansion to 32-bit encodings)::
 See <<FLD>>
