<<<

[#C_LD,reftext="C.LD"]
==== C.LD
See <<C_LW>>.

<<<

[#C_LW,reftext="C.LW"]
==== C.LW

Synopsis::
Load (C.LD, C.LW), 16-bit encodings

{cheri_cap_mode_name} Mnemonics (RV64)::
`c.ld/c.lw rd', offset(cs1')`

{cheri_cap_mode_name} Expansions (RV64)::
`ld/lw rd', offset(cs1')`

{cheri_int_mode_name} Mnemonics (RV64)::
`c.ld/c.lw rd', offset(rs1')`

{cheri_int_mode_name} Expansions (RV64)::
`ld/lw rd', offset(rs1')`

{cheri_cap_mode_name} Mnemonics (RV32)::
`c.lw rd', offset(cs1')`

{cheri_cap_mode_name} Expansions (RV32)::
`lw rd', offset(cs1')`

{cheri_int_mode_name} Mnemonics (RV32)::
`c.lw rd', offset(rs1')`

{cheri_int_mode_name} Expansions (RV32)::
`lw rd', offset(rs1')`

Encoding::
include::wavedrom/reg-based-ldnstr.adoc[]

{cheri_cap_mode_name} Description::
Standard load instructions, authorised by the capability in `cs1`.

{cheri_int_mode_name} Description::
Standard load instructions, authorised by the capability in <<ddc>>.

include::load_exceptions.adoc[]

Prerequisites for {cheri_cap_mode_name} C.LD::
RV64, and {c_cheri_base_ext_names}

Prerequisites for {cheri_int_mode_name} C.LD::
RV64, {c_cheri_default_ext_names}

Prerequisites {cheri_cap_mode_name} C.LW::
{c_cheri_base_ext_names}

Prerequisites {cheri_int_mode_name} C.LW::
{c_cheri_default_ext_names}

Operation (after expansion to 32-bit encodings)::
 See <<LD>>, <<LW>>
