<<<

[#CLWU,reftext="CLWU"]
==== CLWU

See <<CLD>>.

[#CLW,reftext="CLW"]
==== CLW

See <<CLD>>.

[#CLHU,reftext="CLHU"]
==== CLHU

See <<CLD>>.

[#CLH,reftext="CLH"]
==== CLH

See <<CLD>>.

[#CLBU,reftext="CLBU"]
==== CLBU

See <<CLD>>.

[#CLB,reftext="CLB"]
==== CLB

See <<CLD>>.

[#LD,reftext="LD"]
==== LD

See <<CLD>>.

[#LWU,reftext="LWU"]
==== LWU

See <<CLD>>.

[#LW,reftext="LW"]
==== LW

See <<CLD>>.

[#LHU,reftext="LHU"]
==== LHU

See <<CLD>>.

[#LH,reftext="LH"]
==== LH

See <<CLD>>.

[#LBU,reftext="LBU"]
==== LBU

See <<CLD>>.

[#LB,reftext="LB"]
==== LB

See <<CLD>>.

<<<

[#CLD,reftext="CLD"]
==== CLD

Synopsis::
Load (CLD, CLW[U], CLH[U], CLB[U], LD, LW[U], LH[U], LB[U])

Capability Mode Mnemonics (RV64)::
`cld    rd, offset(cs1)` +
`clw[u] rd, offset(cs1)` +
`clh[u] rd, offset(cs1)` +
`clb[u] rd, offset(cs1)`

Legacy Mode Mnemonics (RV64)::
`ld    rd, offset(rs1)` +
`lw[u] rd, offset(rs1)` +
`lh[u] rd, offset(rs1)` +
`lb[u] rd, offset(rs1)`

Capability Mode Mnemonics (RV32)::
`clw    rd, offset(cs1)` +
`clh[u] rd, offset(cs1)` +
`clb[u] rd, offset(cs1)`

Legacy Mode Mnemonics (RV32)::
`lw    rd, offset(rs1)` +
`lh[u] rd, offset(rs1)` +
`lb[u] rd, offset(rs1)`

Encoding::
include::wavedrom/load.adoc[]

Capability Mode Description::
Load integer data of the indicated size (byte, halfword, word, double-word)
from memory. The effective address of the load is obtained by adding the
sign-extended 12-bit offset to the address of `cs1`. The authorising capability
for the operation is `cs1`. A copy of the loaded value is written to `rd`.

Legacy Mode Description::
Load integer data of the indicated size (byte, halfword, word, double-word)
from memory. The effective address of the load is obtained by adding the
sign-extended 12-bit offset to `rs1`. The authorising capability for the
operation is <<ddc>>. A copy of the loaded value is written to `rd`.

include::load_exceptions.adoc[]

Prerequisites for CLD::
RV64, {cheri_base_ext_name}

Prerequisites for CLW[U], CLH[U], CLB[U]::
{cheri_base_ext_name}

Prerequisites for LD::
RV64, {cheri_legacy_ext_name}

Prerequisites for LW[U], LH[U], LB[U]::
{cheri_legacy_ext_name}

Capability Mode Operation::
+
--
TBD
--

Legacy Mode Operation::
+
--
TODO
--
