<<<

[#LC,reftext="LC"]
==== LC

include::new_encoding_note.adoc[]

NOTE: The RV64 encoding is intended to also allocate the encoding for LQ for RV128.

Synopsis::
Load capability

Capability Mode Mnemonics::
`lc cd, offset(cs1)`

Default Mode Mnemonics::
`lc cd, offset(rs1)`

include::xlen_variable_warning.adoc[]

Encoding::
include::wavedrom/loadcap.adoc[]

Capability Mode Description::
Load a CLEN+1 bit value from memory and writes it to `cd`. The capability in `cs1` authorizes the operation. The effective address of the memory access is obtained by adding the address of `cs1` to the sign-extended 12-bit offset. The tag value written to `cd` is 0 if the tag of the memory location loaded is 0 or `cs1` does not grant <<c_perm>>.

Default Mode Description::
Loads a CLEN+1 bit value from memory and writes it to `cd`. The capability
authorising the operation is <<ddc>>. The effective address of the memory
access is obtained by adding `rs1` to the sign-extended 12-bit offset.
The tag value written to `cd` is 0 if the tag of the memory location loaded is
0 or <<ddc>> does not grant <<c_perm>>.

:has_cap_data:
include::load_exceptions.adoc[]
+
include::require_cre.adoc[]

Prerequisites for Capability Mode::
{cheri_base_ext_name}

Prerequisites for Default Mode::
{cheri_legacy_ext_name}

LC Operation::
+
--
TODO
--
