<<<

[#MODESW_INT,reftext="MODESW.INT"]
==== MODESW.INT
See <<MODESW_CAP>>.

[#MODESW_CAP,reftext="MODESW.CAP"]
==== MODESW.CAP

Synopsis::
Switch execution mode to {cheri_cap_mode_name} (MODESW.CAP), or {cheri_int_mode_name} (MODESW.INT), 32-bit encodings

Mnemonic::
`modesw.cap` +
`modesw.int`

Encoding::
include::wavedrom/modesw_32bit.adoc[]

Description::
Set the hart's current CHERI execution mode in <<pcc>>.
+
* MODESW.CAP: If the current mode in <<pcc>> is {cheri_int_mode_name} ({INT_MODE_VALUE}), then the <<m_bit>> in <<pcc>> is set to {cheri_cap_mode_name} ({CAP_MODE_VALUE}). Otherwise no effect.
* MODESW.INT: If the current mode in <<pcc>> is {cheri_cap_mode_name} ({CAP_MODE_VALUE}), then the <<m_bit>> in <<pcc>> is set to {cheri_int_mode_name} ({INT_MODE_VALUE}). Otherwise no effect.

NOTE: Implementations may optionally support executing <<MODESW_CAP>> and <<MODESW_INT>> from the
program buffer while in debug mode. If supported then the <<m_bit>> in
<<dinfc>> is set accordingly and used to control which mode to enter next time debug
mode is entered. The CHERI execution mode is only controlled by the <<m_bit>>
of <<dinfc>> in debug mode.

Exceptions::
include::require_cre.adoc[]

Prerequisites::
{cheri_default_ext_name}

Operation::
[source,SAIL,subs="verbatim,quotes"]
--
TODO
--
