<<<

[#SH1ADD,reftext="SH1ADD"]
==== SH1ADD
See <<SH3ADD>>.

[#SH2ADD,reftext="SH2ADD"]
==== SH2ADD
See <<SH3ADD>>.

<<<

[#SH3ADD,reftext="SH3ADD"]
==== SH3ADD

Synopsis::
Shift by _n_ and add for address generation (SH1ADD, SH2ADD, SH3ADD)

pass:attributes,quotes[{cheri_cap_mode_name}] Mnemonics::
`sh[1|2|3]add cd, rs1, cs2`

pass:attributes,quotes[{cheri_int_mode_name}] Mnemonics::
`sh[1|2|3]add rd, rs1, rs2`

Encoding::
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x33, attr: ['OP'] },
    { bits:  5, name: 'cd/rd' },
    { bits:  3, name: 0x2, attr: ['SH1ADD=010', 'SH2ADD=100', 'SH3ADD=110'] },
    { bits:  5, name: 'rs1' },
    { bits:  5, name: 'cs2/rs2' },
    { bits:  7, name: 0x10, attr: ['SH[1|2|3]ADD'] },
]}
....

pass:attributes,quotes[{cheri_cap_mode_name}] Description::
Increment the address field of `cs2` by `rs1` shifted left by _n_ bit positions. Clear the tag if the resulting capability is unrepresentable or `cs2` is sealed.

pass:attributes,quotes[{cheri_int_mode_name}] Description::
Increment `rs2` by `rs1` shifted left by _n_ bit positions.

Exceptions::
None

Prerequisites for pass:attributes,quotes[{cheri_cap_mode_name}]::
{cheri_base_ext_name}, Zba

Prerequisites for pass:attributes,quotes[{cheri_int_mode_name}]::
{cheri_default_ext_name}, Zba

pass:attributes,quotes[{cheri_cap_mode_name}] Operation::
[source,SAIL,subs="verbatim,quotes"]
--
TODO
--

pass:attributes,quotes[{cheri_int_mode_name}] Operation::
+
--
TODO
--
