<<<

[#SH4ADD,reftext="SH4ADD"]
==== SH4ADD

ifdef::cheri_v9_annotations[]
NOTE: *CHERI v9 Note:* This instruction is *new*.
endif::[]

Synopsis::
Shift by 4 and add for address generation (SH4ADD)

Capability Mode Mnemonics (RV64)::
`sh4add cd, rs1, cs2`

Legacy Mode Mnemonics (RV64)::
`sh4add rd, rs1, rs2`

Encoding::
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x33, attr: ['OP'] },
    { bits:  5, name: 'cd/rd' },
    { bits:  3, name: 0x7, attr: ['rv64: SH4ADD'] },
    { bits:  5, name: 'rs1' },
    { bits:  5, name: 'cs2/rs2' },
    { bits:  7, name: 16, attr: ['rv64: SH4ADD'] },
]}
....

Capability Mode Description::
Increment the address field of `cs2` by `rs1` shifted left by 4 bit positions. Clear the tag if the resulting capability is unrepresentable or `cs2` is sealed.

Legacy Mode Description::
Increment `rs2` by `rs1` shifted left by 4 bit positions.

Exceptions::
None

Prerequisites for Capability Mode::
RV64, {sh4add_ext_name}

Prerequisites for Legacy Mode::
RV64, {sh4add_ext_name}

Capability Mode Operation::
[source,SAIL,subs="verbatim,quotes"]
--
TBD
--

Legacy Mode Operation::
--
TBD
--
