<<<

[#SH4ADD_UW,reftext="SH4ADD.UW"]
==== SH4ADD.UW

Synopsis::
Shift by 4 and add unsigned words for address generation (SH4ADD.UW)

pass:attributes,quotes[{cheri_cap_mode_name}] Mnemonic (RV64)::
`sh4add.uw cd, rs1, cs2`

pass:attributes,quotes[{cheri_int_mode_name}] Mnemonic (RV64)::
`sh4add.uw rd, rs1, rs2`

Encoding::
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x3b, attr: ['OP'] },
    { bits:  5, name: 'cd/rd' },
    { bits:  3, name: 0x7, attr: ['rv64: SH4ADD.UW'] },
    { bits:  5, name: 'rs1' },
    { bits:  5, name: 'cs2/rs2' },
    { bits:  7, name: 16, attr: ['rv64: SH4ADD.UW'] },
]}
....

pass:attributes,quotes[{cheri_cap_mode_name}] Description::
Increment the address field of `cs2` by the unsigned word in `rs1` shifted left by 4 bit positions. Clear the tag if the resulting capability is unrepresentable or `cs2` is sealed.

pass:attributes,quotes[{cheri_int_mode_name}] Description::
Increment `rs2` by the unsigned word in `rs1` shifted left by 4 bit positions.

Exceptions::
None

Prerequisites for pass:attributes,quotes[{cheri_cap_mode_name}]::
RV64, {sh4add_ext_name}

Prerequisites for pass:attributes,quotes[{cheri_int_mode_name}]::
RV64, {sh4add_ext_name}

pass:attributes,quotes[{cheri_cap_mode_name}] Operation::
[source,SAIL,subs="verbatim,quotes"]
--
TBD
--

pass:attributes,quotes[{cheri_int_mode_name}] Operation::
--
TBD
--
