<<<

[#SH4ADD_UW,reftext="SH4ADD.UW"]
==== SH4ADD.UW

Synopsis::
Shift by 4 and add unsigned words for address generation (SH4ADD.UW)

Capability Mode Mnemonics (RV64)::
`sh4add.uw cd, rs1, cs2`

Legacy Mode Mnemonics (RV64)::
`sh4add.uw rd, rs1, rs2`

Encoding::
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x3b, attr: ['OP'] },
    { bits:  5, name: 'cd/rd' },
    { bits:  3, name: 0x7, attr: ['rv64: SH4ADD.UW'] },
    { bits:  5, name: 'rs1' },
    { bits:  5, name: 'cs2/rs2' },
    { bits:  7, name: 16, attr: ['rv64: SH4ADD.UW'] },
]}
....

Capability Mode Description::
Increment the address field of `cs2` by the unsigned word in `rs1` shifted left by 4 bit positions. Clear the tag if the resulting capability is unrepresentable or `cs2` is sealed.

Legacy Mode Description::
Increment `rs2` by the unsigned word in `rs1` shifted left by 4 bit positions.

Prerequisites for Capability Mode::
{cheri_base_ext_name}, Zba

Prerequisites for Legacy Mode::
{cheri_legacy_ext_name}, Zba

Capability Mode Operation::
[source,SAIL,subs="verbatim,quotes"]
--
TBD
--

Legacy Mode Operation::
--
TBD
--
