<<<

[#SD,reftext="SD"]
==== SD

See <<SB>>

[#SW,reftext="SW"]
==== SW

See <<SB>>

[#SH,reftext="SH"]
==== SH

See <<SB>>

<<<

[#SB,reftext="SB"]
==== SB

Synopsis::
Stores (SD, SW, SH, SB)

pass:attributes,quotes[{cheri_cap_mode_name}] Mnemonics (RV64)::
`sd rs2, offset(cs1)` +
`sw rs2, offset(cs1)` +
`sh rs2, offset(cs1)` +
`sb rs2, offset(cs1)`

pass:attributes,quotes[{cheri_int_mode_name}] Mnemonics (RV64)::
`sd rs2, offset(rs1)` +
`sw rs2, offset(rs1)` +
`sh rs2, offset(rs1)` +
`sb rs2, offset(rs1)`

pass:attributes,quotes[{cheri_cap_mode_name}] Mnemonics (RV32)::
`sw rs2, offset(cs1)` +
`sh rs2, offset(cs1)` +
`sb rs2, offset(cs1)`

pass:attributes,quotes[{cheri_int_mode_name}] Mnemonics (RV32)::
`sw rs2, offset(rs1)` +
`sh rs2, offset(rs1)` +
`sb rs2, offset(rs1)`

Encoding::
include::wavedrom/store.adoc[]

pass:attributes,quotes[{cheri_cap_mode_name}] Description::
Store integer data of the indicated size (byte, halfword, word, double-word) to
memory. The effective address of the store is obtained by adding the
sign-extended 12-bit offset to the address of `cs1`. The authorising capability
for the operation is `cs1`. A copy of `rs2` is written to memory at the
location indicated by the effective address and the tag bit of each block of
memory naturally aligned to CLEN/8 is cleared.

pass:attributes,quotes[{cheri_int_mode_name}] Description::
Store integer data of the indicated size (byte, halfword, word, double-word) to
memory. The effective address of the store is obtained by adding the
sign-extended 12-bit offset to `rs1`. The authorising capability for the
operation is <<ddc>>. A copy of `rs2` is written to memory at the location
indicated by the effective address and the tag bit of each block of memory
naturally aligned to CLEN/8 is cleared.

include::store_exceptions.adoc[]

Prerequisites for pass:attributes,quotes[{cheri_cap_mode_name}] SD::
RV64, {cheri_base_ext_name}

Prerequisites for pass:attributes,quotes[{cheri_int_mode_name}] SD::
RV64, {cheri_default_ext_name}

Prerequisites for pass:attributes,quotes[{cheri_cap_mode_name}] SW, SH, SB::
{cheri_base_ext_name}

Prerequisites for pass:attributes,quotes[{cheri_int_mode_name}] SW, SH, SB::
{cheri_default_ext_name}

Operation::
[source,SAIL,subs="verbatim,quotes"]
--
TBD
--
