<<<
//[#insns-store-cond-cap-32bit,reftext="store Conditional (CSC.C, SC.C), 32-bit encodings"]

[#SC_C,reftext="SC.C"]
==== SC.C

See <<CSC.C>>.

[#CSC_C,reftext="CSC.C"]
==== CSC.C

NOTE: The RV64 encoding is intended to also allocate the encoding for SC.Q for RV128.

Synopsis::
Store Conditional (CSC.C, SC.C), 32-bit encodings

include::xlen_variable_warning.adoc[]

Capability Mode Mnemonics::
`csc.c cd, cs2, 0(cs1)`

Legacy Mode Mnemonics::
`sc.c cd, cs2, 0(rs1)`

Encoding::
include::wavedrom/store_cond_cap.adoc[]

Capability Mode Description::
Store conditional instructions, authorised by the capability in `cs1`.
 All misaligned store conditionals cause a store/AMO address misaligned exception to allow software emulation (Zam extension, see cite:[riscv-unpriv-spec]).

Legacy Mode Description::
Store conditional instructions, authorised by the capability in <<ddc>>.
 All misaligned store conditionals cause a store/AMO address misaligned exception to allow software emulation (Zam extension, see cite:[riscv-unpriv-spec]).

:store_cond:

include::store_exceptions.adoc[]

Prerequisites for CSC.C::
{cheri_base_ext_name}

Prerequisites for SC.C::
{cheri_legacy_ext_name}

Operation::
[source,SAIL,subs="verbatim,quotes"]
--
TBD
--
