<<<

[#C_SWSP,reftext="C.SWSP"]
==== C.SWSP

See <<C_SDSP>>.

<<<

[#C_SDSP,reftext="C.SDSP"]
==== C.SDSP

Synopsis::
Stack pointer relative stores (C.SWSP, C.SDSP), 16-bit encodings

pass:attributes,quotes[{cheri_cap_mode_name}] Mnemonics (RV64)::
`c.sd rs2, offset(csp)` +
`c.sw rs2, offset(csp)`

pass:attributes,quotes[{cheri_cap_mode_name}] Expansions (RV64)::
`sd rs2, offset(csp)` +
`sw rs2, offset(csp)`

pass:attributes,quotes[{cheri_int_mode_name}] Mnemonics (RV64)::
`c.sd rs2, offset(sp)` +
`c.sw rs2, offset(sp)`

pass:attributes,quotes[{cheri_int_mode_name}] Expansions (RV64)::
`sd rs2, offset(sp)` +
`sw rs2, offset(sp)`

pass:attributes,quotes[{cheri_cap_mode_name}] Mnemonic (RV32)::
`c.sw rs2, offset(csp)`

pass:attributes,quotes[{cheri_cap_mode_name}] Expansion (RV32)::
`sw rs2, offset(csp)`

pass:attributes,quotes[{cheri_int_mode_name}] Mnemonic (RV32)::
`c.sw rs2, offset(sp)`

pass:attributes,quotes[{cheri_int_mode_name}] Expansion (RV32)::
`sw rs2, offset(sp)`

Encoding::
include::wavedrom/c-sp-load-store-css.adoc[]

pass:attributes,quotes[{cheri_cap_mode_name}] Description::
Standard stack pointer relative store instructions, authorised by the capability in `csp`.

pass:attributes,quotes[{cheri_int_mode_name}] Description::
Standard stack pointer relative store instructions, authorised by the capability in <<ddc>>.

include::store_exceptions.adoc[]

Prerequisites for pass:attributes,quotes[{cheri_cap_mode_name}] C.SDSP::
RV64, and {c_cheri_base_ext_names}

Prerequisites for pass:attributes,quotes[{cheri_int_mode_name}] C.SDSP::
RV64, and {c_cheri_default_ext_names}

Prerequisites for pass:attributes,quotes[{cheri_cap_mode_name}] C.SWSP::
{c_cheri_base_ext_names}

Prerequisites for pass:attributes,quotes[{cheri_int_mode_name}] C.SWSP::
{c_cheri_default_ext_names}

Operation (after expansion to 32-bit encodings)::
 See <<SD>>, <<SW>>
