<<<

[#SC_C,reftext="SC.C"]
==== SC.C

Synopsis::
Store Conditional (SC.C), 32-bit encoding

{cheri_cap_mode_name} Mnemonic::
`sc.c rd, cs2, 0(cs1)`

{cheri_int_mode_name} Mnemonic::
`sc.c rd, cs2, 0(rs1)`

Encoding::
include::wavedrom/store_cond_cap.adoc[]

{cheri_cap_mode_name} Description::
Store conditional instructions, authorized by the capability in `cs1`.
 All misaligned store conditionals cause a store/AMO address misaligned exception to allow software emulation (Zam extension, see cite:[riscv-unpriv-spec]).
+
include::load_store_c0.adoc[]

{cheri_int_mode_name} Description::
Store conditional instructions, authorized by the capability in <<ddc>>.
 All misaligned store conditionals cause a store/AMO address misaligned exception to allow software emulation (Zam extension, see cite:[riscv-unpriv-spec]).

:store_cond:

include::store_tag_perms.adoc[]

include::malformed_no_check.adoc[]

include::store_exceptions.adoc[]

Prerequisites for {cheri_cap_mode_name}::
{cheri_base_ext_name}, and A

Prerequisites for {cheri_int_mode_name}::
{cheri_default_ext_name}, and A

Operation::
[source,SAIL,subs="verbatim,quotes"]
--
TBD
--
