<<<

[#C_SWSP,reftext="C.SWSP"]
==== C.SWSP

See <<C_SDSP>>.

<<<

[#C_SDSP,reftext="C.SDSP"]
==== C.SDSP

Synopsis::
Stack pointer relative stores (C.SWSP, C.SDSP), 16-bit encodings

Capability Mode Mnemonics (RV64)::
`c.sw/c.sd rs2, offset(csp)`

Capability Mode Expansions (RV64)::
`sd/csw rs2, offset(csp)`

Legacy Mode Mnemonics (RV64)::
`c.sd/c.sw rs2, offset(sp)`

Legacy Mode Expansions (RV64)::
`sd/sw rs2, offset(sp)`

Capability Mode Mnemonics (RV32)::
`c.sw rs2, offset(csp)`

Capability Mode Expansion (RV32)::
`sw rs2, offset(csp)`

Legacy Mode Mnemonics (RV32)::
`c.sw rs2, offset(sp)`

Legacy Mode Expansion (RV32)::
`sw rs2, offset(sp)`

Encoding::
include::wavedrom/c-sp-load-store-css.adoc[]

Capability Mode Description::
Standard stack pointer relative store instructions, authorised by the capability in `csp`.

Legacy Mode Description::
Standard stack pointer relative store instructions, authorised by the capability in <<ddc>>.

include::store_exceptions.adoc[]

Prerequisites for C.SDSP::
RV64, and {c_cheri_base_ext_names}, or +
RV64, and {c_cheri_base_ext_names}

Prerequisites for C.SWSP::
{c_cheri_base_ext_names}, or +
{c_cheri_base_ext_names}

Operation (after expansion to 32-bit encodings)::
 See <<SD>>, <<SW>>
