<<<

[#FSD,reftext="FSD"]
==== FSD
See <<FSH>>.

[#FSW,reftext="FSW"]
==== FSW
See <<FSH>>.

<<<

[#FSH,reftext="FSH"]
==== FSH

Synopsis::
Floating point stores (FSD, FSW, FSH), 32-bit encodings

pass:attributes,quotes[{cheri_cap_mode_name}] Mnemonics::
`fsd fs2, offset(cs1)` +
`fsw fs2, offset(cs1)` +
`fsh fs2, offset(cs1)`

pass:attributes,quotes[{cheri_int_mode_name}] Mnemonics::
`fsd fs2, offset(rs1)` +
`fsw fs2, offset(rs1)` +
`fsh fs2, offset(rs1)`

Encoding::
include::wavedrom/fpstore.adoc[]

pass:attributes,quotes[{cheri_cap_mode_name}] Description::
Standard floating point store instructions, authorised by the capability in `cs1`.

pass:attributes,quotes[{cheri_int_mode_name}] Description::
Standard floating point store instructions, authorised by the capability in <<ddc>>.

include::store_exceptions.adoc[]

Prerequisites for pass:attributes,quotes[{cheri_cap_mode_name}] FSD::
{cheri_base_ext_name}, and D

Prerequisites for pass:attributes,quotes[{cheri_int_mode_name}] FSD::
{cheri_default_ext_name}, and D

Prerequisites for pass:attributes,quotes[{cheri_cap_mode_name}] FSW::
{cheri_base_ext_name}, and F

Prerequisites for pass:attributes,quotes[{cheri_int_mode_name}] FSW::
{cheri_default_ext_name}, and F

Prerequisites for pass:attributes,quotes[{cheri_cap_mode_name}] FSH::
{cheri_base_ext_name}, and Zfh or Zfhmin

Prerequisites for pass:attributes,quotes[{cheri_int_mode_name}] FSH::
{cheri_default_ext_name}, and Zfh or Zfhmin

Operation::
[source,SAIL,subs="verbatim,quotes"]
--
TBD
--
