<<<
//[#insns-store-16bit-fp-sp,reftext="Store (C.FSW, C.FSWSP), 16-bit encodings"]

[#C_FSW,reftext="C.FSW"]
==== C.FSW

See <<C.FSWSP>>.

[#C_FSWSP,reftext="C.FSWSP"]
==== C.FSWSP

Synopsis::
Floating point stores (C.FSW, C.FSWSP), 16-bit encodings

pass:attributes,quotes[{cheri_int_mode_name}] Mnemonics (RV32)::
`c.fsw rs2', offset(rs1')` +
`c.fsw rs2', offset(sp)`

pass:attributes,quotes[{cheri_int_mode_name}] Expansions (RV32)::
`fsw rs2', offset(rs1')` +
`fsw rs2', offset(sp)`

Encoding (RV32)::
include::wavedrom/c-sp-store-css-fp.adoc[]
include::wavedrom/c-sp-store-css-fp-sprel.adoc[]

pass:attributes,quotes[{cheri_int_mode_name}] Description::
Standard floating point store instructions, authorised by the capability in <<ddc>>.

NOTE: These instructions are available in RV32 pass:attributes,quotes[{cheri_int_mode_name}] only.
In pass:attributes,quotes[{cheri_cap_mode_name}] they are remapped to <<C.SC>>/<<C.SCSP>>.

NOTE: In pass:attributes,quotes[{cheri_int_mode_name}], these instructions may be remapped to
other encodings by future RV32 only extensions such as Zilsd.
If this is the case, then the Zilsd encodings will be valid in
pass:attributes,quotes[{cheri_int_mode_name}] only. In
pass:attributes,quotes[{cheri_cap_mode_name}] the instructions will still be <<C.SC>>/<<C.SCSP>>.

include::store_exceptions.adoc[]

Prerequisites::
{c_cheri_default_ext_names}, Zcf or F

Operation (after expansion to 32-bit encodings)::
 See <<FSW>>
