<<<

[#C_SD,reftext="C.SD"]
==== C.SD

See <<C.SW>>.

<<<

[#C_SW,reftext="C.SW"]
==== C.SW

Synopsis::
Stores (C.SD, C.SW), 16-bit encodings

Capability Mode Mnemonics (RV64)::
`c.sd/c.sw rs2', offset(cs1')`

Capability Mode Expansions (RV64)::
`sd/sw rs2', offset(cs1')`

Hybrid Mode Mnemonics (RV64)::
`c.sd/c.sw rs2', offset(rs1')`

Hybrid Mode Expansions (RV64)::
`sd/sw rs2', offset(rs1')`

Capability Mode Mnemonics (RV32)::
`c.sw rs2', offset(cs1')`

Capability Mode Expansion (RV32)::
`sw rs2', offset(cs1')`

Hybrid Mode Mnemonics (RV32)::
`c.sw rs2', offset(rs1')`

Hybrid Mode Expansion (RV32)::
`sw rs2', offset(rs1')`

Encoding::
include::wavedrom/c-cs-format-ls.adoc[]

Capability Mode Description::
Standard store instructions, authorised by the capability in `cs1`.

Hybrid Mode Description::
Standard store instructions, authorised by the capability in <<ddc>>.

include::store_exceptions.adoc[]

Prerequisites for Capability Mode C.SD::
RV64, and {c_cheri_base_ext_names}

Prerequisites for Hybrid Mode C.SD::
RV64, and {c_cheri_hybrid_ext_names}

Prerequisites for Capability Mode C.SW::
{c_cheri_base_ext_names}

Prerequisites for Hybrid Mode C.SW::
{c_cheri_hybrid_ext_names}

Operation (after expansion to 32-bit encodings)::
 See <<SD>>, <<SW>>
