<<<

[#SC,reftext="SC"]
==== SC

NOTE: The RV64 encoding is intended to also allocate the encoding for SQ for RV128.

Synopsis::
Store capability

Capability Mode Mnemonics::
`sc cs2, offset(cs1)`

Hybrid Mode Mnemonics::
`sc cs2, offset(rs1)`

include::xlen_variable_warning.adoc[]

Encoding::
include::wavedrom/storecap.adoc[]

Capability Mode Description::
Store the CLEN+1 bit value in `cs2` to memory. The capability in `cs1`
authorizes the operation. The effective address of the memory access is
obtained by adding the address of `cs1` to the sign-extended 12-bit offset. The
capability written to memory has the tag set to 0 if the tag of `cs2` is 0 or
`cs1` does not grant <<c_perm>>.

Hybrid Mode Description::
Store the CLEN+1 bit value in `cs2` to memory. The capability
authorising the operation is <<ddc>>. The effective address of the memory
access is obtained by adding `rs1` to the sign-extended 12-bit offset. The
capability written to memory has the tag set to 0 if `cs2` 's tag is 0 or
<<ddc>> does not grant <<c_perm>>.

:has_cap_data:
include::store_exceptions.adoc[]
+
include::require_cre.adoc[]

Prerequisites for Capability Mode::
{cheri_base_ext_name}

Prerequisites for Hybrid Mode::
{cheri_hybrid_ext_name}

SC Operation::
+
--
TODO
--
