<<<

[#SC_C,reftext="SC.C"]
==== SC.C

NOTE: The RV64 encoding is intended to also allocate the encoding for SC.Q for RV128.

Synopsis::
Store Conditional (SC.C), 32-bit encoding

include::xlen_variable_warning.adoc[]

pass:attributes,quotes[{cheri_cap_mode_name}] Mnemonic::
`sc.c rd, cs2, 0(cs1)`

pass:attributes,quotes[{cheri_int_mode_name}] Mnemonic::
`sc.c rd, cs2, 0(rs1)`

Encoding::
include::wavedrom/store_cond_cap.adoc[]

pass:attributes,quotes[{cheri_cap_mode_name}] Description::
Store conditional instructions, authorised by the capability in `cs1`.
 All misaligned store conditionals cause a store/AMO address misaligned exception to allow software emulation (Zam extension, see cite:[riscv-unpriv-spec]).

pass:attributes,quotes[{cheri_int_mode_name}] Description::
Store conditional instructions, authorised by the capability in <<ddc>>.
 All misaligned store conditionals cause a store/AMO address misaligned exception to allow software emulation (Zam extension, see cite:[riscv-unpriv-spec]).

:store_cond:

include::malformed_no_check.adoc[]

include::store_exceptions.adoc[]
+
include::require_cre.adoc[]

Prerequisites for pass:attributes,quotes[{cheri_cap_mode_name}]::
{cheri_base_ext_name}, and A

Prerequisites for pass:attributes,quotes[{cheri_int_mode_name}]::
{cheri_default_ext_name}, and A

Operation::
[source,SAIL,subs="verbatim,quotes"]
--
TBD
--
