<<<

[#C_SH,reftext="C.SH"]
==== C.SH
See <<C.SB>>.

<<<

[#C_SB,reftext="C.SB"]
==== C.SB

Synopsis::
Stores (C.SH, C.SB), 16-bit encodings

pass:attributes,quotes[{cheri_cap_mode_name}] Mnemonics::
`c.sh/c.sb rs2', offset(cs1')`

pass:attributes,quotes[{cheri_cap_mode_name}] Expansions::
`sh/sb rs2', offset(cs1')`

pass:attributes,quotes[{cheri_int_mode_name}] Mnemonics::
`c.sh/c.sb rs2', offset(rs1')`

pass:attributes,quotes[{cheri_int_mode_name}] Expansions::
`sh/sb rs2', offset(rs1')`

Encoding::
include::wavedrom/reg-based-str-Zcb.adoc[]

pass:attributes,quotes[{cheri_cap_mode_name}] Description::
Subword store instructions, authorised by the capability in `cs1`.

pass:attributes,quotes[{cheri_int_mode_name}] Description::
Subword store instructions, authorised by the capability in <<ddc>>.

include::store_exceptions.adoc[]

Prerequisites for pass:attributes,quotes[{cheri_cap_mode_name}]::
{c_cheri_base_ext_names}, and Zcb

Prerequisites for pass:attributes,quotes[{cheri_int_mode_name}]::
{c_cheri_default_ext_names}, and Zcb

Operation (after expansion to 32-bit encodings)::
 See <<SH>>, <<SB>>
