<<<

[#SC_C,reftext="SC.C"]
==== SC.C

NOTE: The RV64 encoding is intended to also allocate the encoding for SC.Q for RV128.

Synopsis::
Store Conditional (SC.C), 32-bit encoding

include::xlen_variable_warning.adoc[]

Capability Mode Mnemonics::
`sc.c rd, cs2, 0(cs1)`

Default Mode Mnemonics::
`sc.c rd, cs2, 0(rs1)`

Encoding::
include::wavedrom/store_cond_cap.adoc[]

Capability Mode Description::
Store conditional instructions, authorised by the capability in `cs1`.
 All misaligned store conditionals cause a store/AMO address misaligned exception to allow software emulation (Zam extension, see cite:[riscv-unpriv-spec]).

Default Mode Description::
Store conditional instructions, authorised by the capability in <<ddc>>.
 All misaligned store conditionals cause a store/AMO address misaligned exception to allow software emulation (Zam extension, see cite:[riscv-unpriv-spec]).

:store_cond:

include::store_exceptions.adoc[]
+
include::require_cre.adoc[]

Prerequisites for Capability Mode::
{cheri_base_ext_name}, and A

Prerequisites for Default Mode::
{cheri_legacy_ext_name}, and A

Operation::
[source,SAIL,subs="verbatim,quotes"]
--
TBD
--
