<<<

[#C_SD,reftext="C.SD"]
==== C.SD

See <<C.SW>>.

<<<

[#C_SW,reftext="C.SW"]
==== C.SW

Synopsis::
Stores (C.SD, C.SW), 16-bit encodings

pass:attributes,quotes[{cheri_cap_mode_name}] Mnemonics (RV64)::
`c.sd rs2', offset(cs1')` +
`c.sw rs2', offset(cs1')`

pass:attributes,quotes[{cheri_cap_mode_name}] Expansions (RV64)::
`sd rs2', offset(cs1')` +
`sw rs2', offset(cs1')`

pass:attributes,quotes[{cheri_int_mode_name}] Mnemonics (RV64)::
`c.sd rs2', offset(rs1')` +
`c.sw rs2', offset(rs1')`

pass:attributes,quotes[{cheri_int_mode_name}] Expansions (RV64)::
`sd rs2', offset(rs1')` +
`sw rs2', offset(rs1')`

pass:attributes,quotes[{cheri_cap_mode_name}] Mnemonic (RV32)::
`c.sw rs2', offset(cs1')`

pass:attributes,quotes[{cheri_cap_mode_name}] Expansion (RV32)::
`sw rs2', offset(cs1')`

pass:attributes,quotes[{cheri_int_mode_name}] Mnemonic (RV32)::
`c.sw rs2', offset(rs1')`

pass:attributes,quotes[{cheri_int_mode_name}] Expansion (RV32)::
`sw rs2', offset(rs1')`

Encoding::
include::wavedrom/c-cs-format-ls.adoc[]

pass:attributes,quotes[{cheri_cap_mode_name}] Description::
Standard store instructions, authorised by the capability in `cs1`.

pass:attributes,quotes[{cheri_int_mode_name}] Description::
Standard store instructions, authorised by the capability in <<ddc>>.

include::store_exceptions.adoc[]

Prerequisites for pass:attributes,quotes[{cheri_cap_mode_name}] C.SD::
RV64, and {c_cheri_base_ext_names}

Prerequisites for pass:attributes,quotes[{cheri_int_mode_name}] C.SD::
RV64, and {c_cheri_default_ext_names}

Prerequisites for pass:attributes,quotes[{cheri_cap_mode_name}] C.SW::
{c_cheri_base_ext_names}

Prerequisites for pass:attributes,quotes[{cheri_int_mode_name}] C.SW::
{c_cheri_default_ext_names}

Operation (after expansion to 32-bit encodings)::
 See <<SD>>, <<SW>>
