<<<

[#SC_D,reftext="SC.D"]
==== SC.D
See <<SC.B>>.

[#SC_W,reftext="SC.W"]
==== SC.W
See <<SC.B>>.

[#SC_H,reftext="SC.H"]
==== SC.H
See <<SC.B>>.

<<<

[#SC_B,reftext="SC.B"]
==== SC.B

Synopsis::
Store Conditional (SC.D, SC.W, SC.H, SC.B), 32-bit encodings

pass:attributes,quotes[{cheri_cap_mode_name}] Mnemonics (RV64)::
`sc.[d|w|h|b] rd, rs2, 0(cs1)`

pass:attributes,quotes[{cheri_cap_mode_name}] Mnemonics (RV32)::
`sc.[w|h|b] rd, rs2, 0(cs1)`

pass:attributes,quotes[{cheri_int_mode_name}] Mnemonics (RV64)::
`sc.[d|w|h|b] rd, rs2, 0(rs1)`

pass:attributes,quotes[{cheri_int_mode_name}] Mnemonics (RV32)::
`sc.[w|h|b] rd, rs2, 0(rs1)`

Encoding::
include::wavedrom/store_cond.adoc[]

pass:attributes,quotes[{cheri_cap_mode_name}] Description::
Store conditional instructions, authorised by the capability in `cs1`.

pass:attributes,quotes[{cheri_int_mode_name}] Description::
Store conditional instructions, authorised by the capability in <<ddc>>.

:store_cond:

include::store_exceptions.adoc[]

Prerequisites for pass:attributes,quotes[{cheri_cap_mode_name}] SC.D::
RV64, and {cheri_base_ext_name}, and A

Prerequisites for pass:attributes,quotes[{cheri_int_mode_name}] SC.D::
RV64, and {cheri_default_ext_name}, and A

Prerequisites for pass:attributes,quotes[{cheri_cap_mode_name}] SC.W::
{cheri_base_ext_name}, and A

Prerequisites for pass:attributes,quotes[{cheri_int_mode_name}] SC.W::
{cheri_default_ext_name}, and A

Prerequisites for pass:attributes,quotes[{cheri_cap_mode_name}] SC.H, SC.B::
{cheri_base_ext_name}, and {lr_sc_bh_ext_name}

Prerequisites for pass:attributes,quotes[{cheri_int_mode_name}] SC.H, SC.B::
{cheri_default_ext_name}, and {lr_sc_bh_ext_name}

Operation::
[source,SAIL,subs="verbatim,quotes"]
--
TBD
--
