<<<
//[#insns-store-16bit,reftext="Store (C.CSD, C.CSW, C.SD, C.SW), 16-bit encodings"]

[#C_CSD,reftext="C.CSD"]
==== C.CSD

See <<C.SW>>.

[#C_CSW,reftext="C.CSW"]
==== C.CSW

See <<C.SW>>.

[#C_SD,reftext="C.SD"]
==== C.SD

See <<C.SW>>.

<<<

[#C_SW,reftext="C.SW"]
==== C.SW

Synopsis::
Stores (C.CSD, C.CSW, C.SD, C.SW), 16-bit encodings

Capability Mode Mnemonics (RV64)::
`c.csd/c.csw rs2', offset(cs1')`

Capability Mode Expansions (RV64)::
`csd/csw rs2', offset(cs1')`

Legacy Mode Mnemonics (RV64)::
`c.sd/c.sw rs2', offset(rs1')`

Legacy Mode Expansions (RV64)::
`sd/sw rs2', offset(rs1')`

Capability Mode Mnemonics (RV32)::
`c.csw rs2', offset(cs1')`

Capability Mode Expansion (RV32)::
`csw rs2', offset(cs1')`

Legacy Mode Mnemonics (RV32)::
`c.sw rs2', offset(rs1')`

Legacy Mode Expansion (RV32)::
`sw rs2', offset(rs1')`

Encoding::
include::wavedrom/c-cs-format-ls.adoc[]

Capability Mode Description::
Standard store instructions, authorised by the capability in `cs1`.

Legacy Mode Description::
Standard store instructions, authorised by the capability in <<ddc>>.

include::store_exceptions.adoc[]

Prerequisites for C.CSD::
RV64, and {c_cheri_base_ext_names}

Prerequisites for C.CSW::
{c_cheri_base_ext_names}

Prerequisites for C.SD::
RV64, and {c_cheri_legacy_ext_names}

Prerequisites for C.SW::
{c_cheri_legacy_ext_names}

Operation (after expansion to 32-bit encodings)::
 See <<CSD>>, <<CSW>>, <<SD>>, <<SW>>
