<<<
[#C_FSD,reftext="C.FSD"]
==== C.FSD
See <<C.FSDSP>>.

[#C_FSDSP,reftext="C.FSDSP"]
==== C.FSDSP

Synopsis::
Double precision floating point stores (C.FSD, C.FSDSP), 16-bit encodings

Capability Mode Mnemonics (RV32CD/RV32D_Zca)::
`c.fsd fs2, offset(cs1'/csp)`

Capability Mode Expansions (RV32)::
`fsd fs2, offset(csp)`

Hybrid Mode Mnemonics (RV32CD/RV32D_Zca)::
`c.fsd fs2, offset(rs1'/sp)`

Hybrid Mode Expansions (RV32)::
`fsd fs2, offset(rs1'/sp)`

Hybrid Mode Mnemonics (RV64CD/RV64D_Zca)::
`c.fsd fs2, offset(rs1'/sp)`

Hybrid Mode Expansion (RV64)::
`fsd fs2, offset(rs1'/sp)`

Encoding::
include::wavedrom/c-sp-store-css-fp-dp.adoc[]
include::wavedrom/c-sp-store-css-fp-dp-sprel.adoc[]

Capability Mode Description::
Standard floating point stack pointer relative store instructions, authorised by the capability in `cs1` or `csp`.

Hybrid Mode Description::
Standard floating point stack pointer relative store instructions, authorised by the capability in <<ddc>>.

include::store_exceptions.adoc[]

Prerequisites for Capability Mode C.FSD, C.FSDSP (RV32 only)::
{cheri_base_ext_name}, C and D; or +
{cheri_base_ext_name}, Zca and Zcd

Prerequisites for Hybrid Mode C.FSD, C.FSDSP::
{cheri_hybrid_ext_name}, C and D; or +
{cheri_hybrid_ext_name}, Zca and Zcd

Operation (after expansion to 32-bit encodings)::
 See <<FSD>>
