<<<
//[#insns-store-16bit-fp-dp,reftext="Store (C.CFSD, C.FSD, C.CFSDSP, C.FSDSP), 16-bit encodings"]

[#C_CFSD,reftext="C.CFSD"]
==== C.CFSD
See <<C.FSDSP>>.

[#C_CFSDSP,reftext="C.CFSDSP"]
==== C.CFSDSP
See <<C.FSDSP>>.

[#C_FSD,reftext="C.FSD"]
==== C.FSD
See <<C.FSDSP>>.

<<<

[#C_FSDSP,reftext="C.FSDSP"]
==== C.FSDSP

Synopsis::
Double precision floating point stores (C.CFSD, C.FSD, C.CFSDSP, C.FSDSP), 16-bit encodings

Capability Mode Mnemonics (RV32CD/RV32D_Zca)::
`c.cfsd fs2, offset(cs1'/csp)`

Capability Mode Expansions (RV32)::
`cfsd fs2, offset(csp)`

Legacy Mode Mnemonics (RV32CD/RV32D_Zca)::
`c.fsd fs2, offset(rs1'/sp)`

Legacy Mode Expansions (RV32)::
`fsd fs2, offset(rs1'/sp)`

Legacy Mode Mnemonics (RV64CD/RV64D_Zca)::
`c.fsd fs2, offset(rs1'/sp)`

Legacy Mode Expansion (RV64)::
`fsd fs2, offset(rs1'/sp)`

Encoding::
include::wavedrom/c-sp-store-css-fp-dp.adoc[]
include::wavedrom/c-sp-store-css-fp-dp-sprel.adoc[]

Capability Mode Description::
Standard floating point stack pointer relative store instructions, authorised by the capability in `cs1` or `csp`.

Legacy Mode Description::
Standard floating point stack pointer relative store instructions, authorised by the capability in <<ddc>>.

include::store_exceptions.adoc[]

Prerequisites for C.CFSD, C.CFSDSP (RV32 only)::
{c_cheri_base_ext_names}, and Zcd or D

Prerequisites for C.FSD, C.FSDSP::
{c_cheri_legacy_ext_names}, and Zcd or D

Operation (after expansion to 32-bit encodings)::
 See <<CFSD>>, <<FSD>>

