<<<

[#CM_POPRET,reftext="CM.POPRET"]
==== CM.POPRET

Synopsis::
Destroy stack frame (CM.POPRET): load the return address register and 0 to 12 saved registers from the stack frame, deallocate the stack frame. Return through the return address register. 16-bit encodings.

Capability Mode Mnemonic::
`cm.popret \{creg_list\}, -stack_adj`

Default Mode Mnemonics::
`cm.popret \{reg_list\}, -stack_adj`

Encoding::
[wavedrom, , svg]
....
{reg:[
    { bits:  2, name: 0x2,             attr: ['C2'] },
    { bits:  2, name: 'spimm\[5:4\]',  attr: [] },
    { bits:  4, name: 'rlist',         attr: [] },
    { bits:  5, name: 0x1e,            attr: [] },
    { bits:  3, name: 0x5,             attr: ['FUNCT3'] },
],config:{bits:16}}
....

[NOTE]

_rlist_ values 0 to 3 are reserved for a future EABI variant

Capability Mode Description::
Load capability registers as specified in _creg_list_. Deallocate stack frame. Return by calling <<JALR>> to `cra`. All data accesses are checked against `csp`. The return destination is checked against `cra`.

Default Mode Description::
Load integer registers as specified in _reg_list_. Deallocate stack frame. Return by calling <<JALR>> to `ra`. All data accesses are checked against <<ddc>>. The return destination is checked against <<pcc>>.

Permissions::
Loads are checked as for <<LC>> in both Capability and Default Modes.
+
The return is checked as for <<JALR>> in both Capability and Default Modes.

Exceptions::
When these instructions cause CHERI exceptions, _CHERI data fault_
is reported in the TYPE field if a load causes an exception, or
_CHERI instruction access fault_ if the return causes an exception.
The following codes may be
reported in the CAUSE field of <<mtval>> or <<stval>>:

[width="50%",options=header,cols="2,^1",align=center]
|==============================================================================
| CAUSE                 |
| Tag violation         |  ✔
| Seal violation        |  ✔
| Permission violation  |  ✔
| Length violation      |  ✔
|==============================================================================

:!cap_load:

include::pcrel_debug_warning.adoc[]

Prerequisites for Capability Mode::
{c_cheri_base_ext_names}, Zcmp

Prerequisites for Default Mode::
{c_cheri_default_ext_names}, Zcmp

Operation::
[source,SAIL,subs="verbatim,quotes"]
--
TBD
--
