<<<

[#CM_MVSA01,reftext="CM.MVSA01"]
==== CM.MVSA01

See <<CM.CMVSA01>> and cite:[riscv-code-size-spec].

[#CM_CMVSA01,reftext="CM.CMVSA01"]
==== CM.CMVSA01

Synopsis::
CM.CMVSA01, CM.MVSA01: Move argument registers 0 and 1 into two saved registers.

Capability Mode Mnemonic::
`cm.cmvsa01 cr1s', cr2s'`

Legacy Mode Mnemonics::
`cm.mvsa01 r1s', r2s'`

Encoding::
[wavedrom, , svg]
....
{reg:[
    { bits:  2, name: 0x2,      attr: ['C2'] },
    { bits:  3, name: 'r2s\'',  attr: [] },
    { bits:  2, name: 0x1,      attr: [] },
    { bits:  3, name: 'r1s\'',  attr: [] },
    { bits:  3, name: 0x3,      attr: [] },
    { bits:  3, name: 0x5,      attr: ['FUNCT3'] },
],config:{bits:16}}
....

NOTE: The encoding uses sreg number specifiers instead of xreg number specifiers to save encoding space. The saved register encoding is shown in xref:saved_register_mapping[xrefstyle=short].

Capability Mode Description::
Atomically move two saved capability registers `cs0-cs7` into `ca0` and `ca1`.

Legacy Mode Description::
Atomically move two saved integer registers `s0-s7` into `a0` and `a1`.

Prerequisites for CM.CMVSA01::
{c_cheri_base_ext_names}, Zcmp

Prerequisites for CM.MVSA01::
{c_cheri_legacy_ext_names}, Zcmp

Operation::
[source,SAIL,subs="verbatim,quotes"]
--
TBD
--
