<<<

[#CM_PUSH,reftext="CM.PUSH"]
==== CM.PUSH

Synopsis::
Create stack frame (CM.PUSH): store the return address register and 0 to 12 saved registers to the stack frame, optionally allocate additional stack space. 16-bit encodings.

pass:attributes,quotes[{cheri_cap_mode_name}] Mnemonic (RV32)::
`cm.push \{creg_list\}, -stack_adj`

pass:attributes,quotes[{cheri_int_mode_name}] Mnemonic::
`cm.push \{reg_list\}, -stack_adj`

Encoding::
[wavedrom, , svg]
....
{reg:[
    { bits:  2, name: 0x2,             attr: ['C2'] },
    { bits:  2, name: 'spimm\[5:4\]',  attr: [] },
    { bits:  4, name: 'rlist',         attr: [] },
    { bits:  5, name: 0x18,            attr: [] },
    { bits:  3, name: 0x5,             attr: ['FUNCT3'] },
],config:{bits:16}}
....

[NOTE]

_rlist_ values 0 to 3 are reserved for a future EABI variant

pass:attributes,quotes[{cheri_cap_mode_name}] Description::
Create stack frame, store capability registers as specified in _creg_list_. Optionally allocate additional multiples of 16-byte stack space. All accesses are checked against `csp`.

pass:attributes,quotes[{cheri_int_mode_name}] Description::
Create stack frame, store integer registers as specified in _reg_list_. Optionally allocate additional multiples of 16-byte stack space. All accesses are checked against <<ddc>>.

include::zcm_common.adoc[]

include::store_exceptions.adoc[]

Prerequisites for pass:attributes,quotes[{cheri_cap_mode_name}]::
{c_cheri_base_ext_names}, Zcmp

Prerequisites for pass:attributes,quotes[{cheri_int_mode_name}]::
{c_cheri_default_ext_names}, Zcmp

Operation::
[source,SAIL,subs="verbatim,quotes"]
--
TBD
--
