<<<

[#CM_MVA01S,reftext="CM.MVA01S"]
==== CM.MVA01S

Synopsis::
Move two saved registers into argument registers 0 and 1.

Capability Mode Mnemonic::
`cm.mva01s cr1s', cr2s'`

Hybrid Mode Mnemonics::
`cm.mva01s r1s', r2s'`

Encoding::
[wavedrom, , svg]
....
{reg:[
    { bits:  2, name: 0x2,      attr: ['C2'] },
    { bits:  3, name: 'r2s\'',  attr: [] },
    { bits:  2, name: 0x3,      attr: [] },
    { bits:  3, name: 'r1s\'',  attr: [] },
    { bits:  3, name: 0x3,      attr: [] },
    { bits:  3, name: 0x5,      attr: ['FUNCT3'] },
],config:{bits:16}}
....

NOTE: The encoding uses sreg number specifiers instead of xreg number specifiers to save encoding space. The saved register encoding is shown in xref:saved_register_mapping[xrefstyle=short].

Capability Mode Description::
Atomically move two capability registers `ca0` and `ca1` into `cs0-cs7`.

Hybrid Mode Description::
Atomically move two integer registers  `a0` and `a1` into `s0-s7`.

Prerequisites for Capability Mode::
{c_cheri_base_ext_names}, Zcmp

Prerequisites for Hybrid Mode::
{c_cheri_hybrid_ext_names}, Zcmp

Operation::
[source,SAIL,subs="verbatim,quotes"]
--
TBD
--
