<<<

[#CM_POPRETZ,reftext="CM.POPRETZ"]
==== CM.POPRETZ

Synopsis::
Destroy stack frame (CM.POPRETZ): load the return address register and register 0 to 12 saved registers from the stack frame, deallocate the stack frame. Move zero into argument register zero. Return through the return address register. 16-bit encodings.

pass:attributes,quotes[{cheri_cap_mode_name}] Mnemonic (RV32)::
`cm.popretz \{creg_list\}, -stack_adj`

pass:attributes,quotes[{cheri_int_mode_name}] Mnemonic::
`cm.popretz \{reg_list\}, -stack_adj`

Encoding::
[wavedrom, , svg]
....
{reg:[
    { bits:  2, name: 0x2,             attr: ['C2'] },
    { bits:  2, name: 'spimm\[5:4\]',  attr: [] },
    { bits:  4, name: 'rlist',         attr: [] },
    { bits:  5, name: 0x1c,            attr: [] },
    { bits:  3, name: 0x5,             attr: ['FUNCT3'] },
],config:{bits:16}}
....

[NOTE]

_rlist_ values 0 to 3 are reserved for a future EABI variant

pass:attributes,quotes[{cheri_cap_mode_name}] Description::
Load capability registers as specified in _creg_list_. Deallocate stack frame. Move zero into `ca0`. Return by calling <<JALR>> to `cra`. All data accesses are checked against `csp`. The return destination is checked against `cra`.

pass:attributes,quotes[{cheri_int_mode_name}] Description::
Load integer registers as specified in _reg_list_. Deallocate stack frame. Move zero into `a0`. Return by calling <<JALR>> to `ra`. All data accesses are checked against <<ddc>>. The return destination is checked against <<pcc>>.

Permissions::
Loads are checked as for <<LC>> in both pass:attributes,quotes[{cheri_int_mode_name}] and
pass:attributes,quotes[{cheri_cap_mode_name}].
+
The return is checked as for <<JALR>> in both pass:attributes,quotes[{cheri_int_mode_name}] and
pass:attributes,quotes[{cheri_cap_mode_name}].

include::zcm_common.adoc[]

include::load_exceptions.adoc[]

include::pcrel_debug_warning.adoc[]

Prerequisites for pass:attributes,quotes[{cheri_cap_mode_name}]::
{c_cheri_base_ext_names}, Zcmp

Prerequisites for pass:attributes,quotes[{cheri_int_mode_name}]::
{c_cheri_default_ext_names}, Zcmp

Operation::
[source,SAIL,subs="verbatim,quotes"]
--
TBD
--
