<<<

[#CM_MVSA01,reftext="CM.MVSA01"]
==== CM.MVSA01

Synopsis::
CM.MVSA01: Move argument registers 0 and 1 into two saved registers.

pass:attributes,quotes[{cheri_cap_mode_name}] Mnemonic (RV32)::
`cm.mvsa01 cr1s', cr2s'`

pass:attributes,quotes[{cheri_int_mode_name}] Mnemonic::
`cm.mvsa01 r1s', r2s'`

Encoding::
[wavedrom, , svg]
....
{reg:[
    { bits:  2, name: 0x2,      attr: ['C2'] },
    { bits:  3, name: 'r2s\'',  attr: [] },
    { bits:  2, name: 0x1,      attr: [] },
    { bits:  3, name: 'r1s\'',  attr: [] },
    { bits:  3, name: 0x3,      attr: [] },
    { bits:  3, name: 0x5,      attr: ['FUNCT3'] },
],config:{bits:16}}
....

NOTE: The encoding uses sreg number specifiers instead of xreg number specifiers to save encoding space. The saved register encoding is shown in xref:saved_register_mapping[xrefstyle=short].

pass:attributes,quotes[{cheri_cap_mode_name}] Description::
Atomically move two saved capability registers `cs0-cs7` into `ca0` and `ca1`.

pass:attributes,quotes[{cheri_int_mode_name}] Description::
Atomically move two saved integer registers `s0-s7` into `a0` and `a1`.

include::zcm_common.adoc[]

Prerequisites for pass:attributes,quotes[{cheri_cap_mode_name}]::
{c_cheri_base_ext_names}, Zcmp

Prerequisites for pass:attributes,quotes[{cheri_int_mode_name}]::
{c_cheri_default_ext_names}, Zcmp

Operation::
[source,SAIL,subs="verbatim,quotes"]
--
TBD
--
