---
name: DCO Check

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - converted_to_draft

jobs:
  dco_check:
    uses: riscv/riscv-isa-manual/.github/workflows/dco_check.yml@main
    permissions:
      pull-requests: write
      contents: read
      issues: write
